scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1464309157673331
          y: -0.25159769721674635
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.2931683234772148
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01469229182059416
            roll: 0.0
            pitch: 0.0
            yaw: 0.11129971856840776
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006773992140780208
            roll: 0.0
            pitch: 0.0
            yaw: -0.07325141405832082
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.016517542023262617
            roll: 0.0
            pitch: 0.0
            yaw: -0.12090118967366012
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01690910088575126
            roll: 0.0
            pitch: 0.0
            yaw: 0.04083418519172158
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.004756498136762852
            roll: 0.0
            pitch: 0.0
            yaw: -0.050715682209565585
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04108510266058109
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.046863136709993244
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06635536975235516
            roll: 0.0
            pitch: 0.0
            yaw: -0.6715837876471705
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08689655924832973
            roll: 0.0
            pitch: 0.0
            yaw: -0.4851443078446064
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08070917959326687
            roll: 0.0
            pitch: 0.0
            yaw: 0.24999476783528451
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05292938305687309
            roll: 0.0
            pitch: 0.0
            yaw: 0.34318809459588717
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.020157419994369985
            roll: 0.0
            pitch: 0.0
            yaw: -0.7690199668544543
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09592262906418396
            roll: 0.0
            pitch: 0.0
            yaw: 0.7637954990253915
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0010888283792457537
              y: 0.01693758445630905
              z: 0.04402062379094211
              roll: 0.4614262405961598
              pitch: -0.49544317326278015
              yaw: 1.3304236159282559
            roll: 0.4760272540801035
            pitch: -0.48986468087574364
            yaw: 1.3228059419719056
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1888374751938881
          y: -0.25620356441046555
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.42846466429323615
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.02091980035617844
            roll: 0.0
            pitch: 0.0
            yaw: -0.14234238147282446
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.015321497257440116
            roll: 0.0
            pitch: 0.0
            yaw: -0.13839096440737964
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.009278651227281259
            roll: 0.0
            pitch: 0.0
            yaw: -0.09915728171524447
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.005099073236230132
            roll: 0.0
            pitch: 0.0
            yaw: -0.054465926429791284
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01811443032297523
            roll: 0.0
            pitch: 0.0
            yaw: -0.11816635841801637
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02420838030176943
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.007228457295916632
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07049064392522358
            roll: 0.0
            pitch: 0.0
            yaw: -0.8062897171501755
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.005856934579447123
            roll: 0.0
            pitch: 0.0
            yaw: 0.13241870067081374
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05400761845693697
            roll: 0.0
            pitch: 0.0
            yaw: 0.26985026032889814
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0003046718216147132
            roll: 0.0
            pitch: 0.0
            yaw: 0.1195953958889675
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.007021427397863322
            roll: 0.0
            pitch: 0.0
            yaw: 0.03268085452843805
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04979917706074406
            roll: 0.0
            pitch: 0.0
            yaw: -0.36803333650663517
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0007041751160495285
              y: 0.015312960786837826
              z: 0.043956125856996035
              roll: 0.4149514433680356
              pitch: -0.5178609914008432
              yaw: 1.3121036939397968
            roll: 0.46577964255542925
            pitch: -0.465494648960165
            yaw: 1.3611512915365014
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.20943966666110622
          y: -0.2758219041143258
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.2572260383207281
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.021127537026596428
            roll: 0.0
            pitch: 0.0
            yaw: 0.1387607889052887
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.013019001080574862
            roll: 0.0
            pitch: 0.0
            yaw: 0.16805571281339254
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.011696506355718332
            roll: 0.0
            pitch: 0.0
            yaw: 0.027955067819132984
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.014175635709925083
            roll: 0.0
            pitch: 0.0
            yaw: 0.08606956592890175
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0033647627113427628
            roll: 0.0
            pitch: 0.0
            yaw: 0.06962550762611483
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.035437384429913024
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.027083982359686523
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.015865988355419344
            roll: 0.0
            pitch: 0.0
            yaw: 0.07237425780201057
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.024689787243483058
            roll: 0.0
            pitch: 0.0
            yaw: -0.18612428626612787
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.09200283692469238
            roll: 0.0
            pitch: 0.0
            yaw: -0.45196134626647555
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06766971748679107
            roll: 0.0
            pitch: 0.0
            yaw: 0.13599690787100638
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.09466040367720702
            roll: 0.0
            pitch: 0.0
            yaw: -0.2863195206336734
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08134696170442894
            roll: 0.0
            pitch: 0.0
            yaw: 0.26132679583007934
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0008550901747728724
              y: 0.017147098623605868
              z: 0.04288933012192935
              roll: 0.45015975315426593
              pitch: -0.5076250382303854
              yaw: 1.3597980850945102
            roll: 0.45607536588450637
            pitch: -0.4902304278297401
            yaw: 1.3133939766251752
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
