scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.29484636006937404
          y: -0.21402936661332722
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.09535458077369852
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.009366059140846168
            roll: 0.0
            pitch: 0.0
            yaw: -0.005480187307615791
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0036811906303294284
            roll: 0.0
            pitch: 0.0
            yaw: -0.14339755400109097
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.020488039910936874
            roll: 0.0
            pitch: 0.0
            yaw: -0.05139628673612362
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.006911310423264851
            roll: 0.0
            pitch: 0.0
            yaw: -0.021030968034353337
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02195037212459299
            roll: 0.0
            pitch: 0.0
            yaw: -0.06715732610131518
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.029683798322678607
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04380136559231504
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.004396436749888585
            roll: 0.0
            pitch: 0.0
            yaw: -0.3955523043173037
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.025259478706770547
            roll: 0.0
            pitch: 0.0
            yaw: -0.8981192470969158
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03631522247859383
            roll: 0.0
            pitch: 0.0
            yaw: -0.9633366368263315
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07966463720132919
            roll: 0.0
            pitch: 0.0
            yaw: 0.37845071109553485
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05857522420449816
            roll: 0.0
            pitch: 0.0
            yaw: -0.7430520332918721
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07761961757441366
            roll: 0.0
            pitch: 0.0
            yaw: 0.22977287452322437
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0003288846516132978
              y: 0.014570237444157459
              z: 0.04417662534543052
              roll: 0.4489995587158906
              pitch: -0.49588861928202704
              yaw: 1.3605453507603238
            roll: 0.4348304830530528
            pitch: -0.4886332989239756
            yaw: 1.321501608414797
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.16625464267341722
          y: -0.22037864328256923
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.185861117205826
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.014967722763595787
            roll: 0.0
            pitch: 0.0
            yaw: 0.13077295993826643
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01215479167143066
            roll: 0.0
            pitch: 0.0
            yaw: 0.14717200331589908
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0016783102420419235
            roll: 0.0
            pitch: 0.0
            yaw: -0.005772231164925118
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.007489201110354015
            roll: 0.0
            pitch: 0.0
            yaw: -0.12300158126754028
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0035863636551797876
            roll: 0.0
            pitch: 0.0
            yaw: 0.11494479066100305
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.017825707269985502
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.017557115940452887
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0711938224595037
            roll: 0.0
            pitch: 0.0
            yaw: 0.5992831524614914
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0016273623506511264
            roll: 0.0
            pitch: 0.0
            yaw: -0.3167658461552608
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05936259699466288
            roll: 0.0
            pitch: 0.0
            yaw: 0.2860749912675744
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07961716879694827
            roll: 0.0
            pitch: 0.0
            yaw: 0.5738030251763515
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.071020034393178
            roll: 0.0
            pitch: 0.0
            yaw: 0.5654893688689471
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03842193046258021
            roll: 0.0
            pitch: 0.0
            yaw: 0.5650234170657222
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0015807774457181898
              y: 0.015565688683801468
              z: 0.04057396287817821
              roll: 0.45837745015967984
              pitch: -0.5236557674515802
              yaw: 1.3064409518394298
            roll: 0.43543403938853886
            pitch: -0.4878393315620018
            yaw: 1.3609007074540542
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.22493892714671498
          y: -0.1321370164898346
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.42429309139686433
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.02036953416109815
            roll: 0.0
            pitch: 0.0
            yaw: -0.1730666867015514
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.00942686203448112
            roll: 0.0
            pitch: 0.0
            yaw: 0.07662192108225135
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.006707153686050429
            roll: 0.0
            pitch: 0.0
            yaw: 0.16579555304571492
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0071696734433754315
            roll: 0.0
            pitch: 0.0
            yaw: 0.03357738756475073
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.012476306533006846
            roll: 0.0
            pitch: 0.0
            yaw: -0.15634575224393402
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04515857012638143
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05342786809103084
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.051632069507194026
            roll: 0.0
            pitch: 0.0
            yaw: 0.6434345920411411
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.053531869246096014
            roll: 0.0
            pitch: 0.0
            yaw: -0.25152451027265965
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01446909846966006
            roll: 0.0
            pitch: 0.0
            yaw: -0.41626356431167966
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.02619645785056761
            roll: 0.0
            pitch: 0.0
            yaw: 0.16491932508279028
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07417880392527382
            roll: 0.0
            pitch: 0.0
            yaw: -0.7212482417092537
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.01536449138730843
            roll: 0.0
            pitch: 0.0
            yaw: -0.34409287319821125
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0012132437356288368
              y: 0.016741781384354077
              z: 0.04396333088258462
              roll: 0.4351929774998045
              pitch: -0.5053717603810094
              yaw: 1.3416262914080683
            roll: 0.47479323013903674
            pitch: -0.5013241250075207
            yaw: 1.3040811557994478
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
