scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.15280657361409294
          y: -0.20905038049466315
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.07115089471858527
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.005812687230312891
            roll: 0.0
            pitch: 0.0
            yaw: 0.024908352658441435
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.013430494830942032
            roll: 0.0
            pitch: 0.0
            yaw: -0.095961771507314
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.00775382595494202
            roll: 0.0
            pitch: 0.0
            yaw: 0.14953155585048072
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.004357376298064382
            roll: 0.0
            pitch: 0.0
            yaw: 0.041074153302863264
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.013144697694236335
            roll: 0.0
            pitch: 0.0
            yaw: 0.04093791855082282
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.019426340094257713
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02142582147301858
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.01566130707669809
            roll: 0.0
            pitch: 0.0
            yaw: 0.43953281016447976
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.004745859250589277
            roll: 0.0
            pitch: 0.0
            yaw: 0.01221273645073806
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.052707805198407676
            roll: 0.0
            pitch: 0.0
            yaw: -0.9094956837134534
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04997192878969184
            roll: 0.0
            pitch: 0.0
            yaw: -0.8432299547388521
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07015824535472034
            roll: 0.0
            pitch: 0.0
            yaw: -0.6929483805322887
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.014819657310453468
            roll: 0.0
            pitch: 0.0
            yaw: -0.355516537421541
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0008168994042145098
              y: 0.016811526480338002
              z: 0.04252214332889519
              roll: 0.44725809280557544
              pitch: -0.47308134040682465
              yaw: 1.3044772768428468
            roll: 0.448923151580801
            pitch: -0.49222503858965444
            yaw: 1.300970667769438
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.11232096569951536
          y: -0.2677198377074015
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.3672136271642137
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01826866776656797
            roll: 0.0
            pitch: 0.0
            yaw: -0.12883629535513633
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.022580118368510434
            roll: 0.0
            pitch: 0.0
            yaw: 0.07193780561909863
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0018333154061670569
            roll: 0.0
            pitch: 0.0
            yaw: 0.1546229847708952
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0029312580658572805
            roll: 0.0
            pitch: 0.0
            yaw: 0.007596883536661825
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.005368329512902791
            roll: 0.0
            pitch: 0.0
            yaw: 0.04973313954463529
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.014456453369521713
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05264483717760142
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07458149673379884
            roll: 0.0
            pitch: 0.0
            yaw: -1.0038948795595912
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.055713418313518365
            roll: 0.0
            pitch: 0.0
            yaw: -0.8959916851851131
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0023790647974298307
            roll: 0.0
            pitch: 0.0
            yaw: 0.033239704973763384
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05121082451048132
            roll: 0.0
            pitch: 0.0
            yaw: -0.6354643465397598
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.02522667084115529
            roll: 0.0
            pitch: 0.0
            yaw: -0.03331193602426574
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09265855965381778
            roll: 0.0
            pitch: 0.0
            yaw: -0.3023556438441162
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0011162563471918338
              y: 0.01672586373115741
              z: 0.041355791180075666
              roll: 0.44620809043375204
              pitch: -0.44766643132839634
              yaw: 1.298311887809731
            roll: 0.44748886436560237
            pitch: -0.489848135856077
            yaw: 1.3137821753204242
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.17621550906693015
          y: -0.29567835751199845
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4575752959230538
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.013694290307514453
            roll: 0.0
            pitch: 0.0
            yaw: -0.12296502412452653
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.012957962196065508
            roll: 0.0
            pitch: 0.0
            yaw: 0.06460314839051554
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0016482066453992993
            roll: 0.0
            pitch: 0.0
            yaw: 0.08439724259307452
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01595060516108937
            roll: 0.0
            pitch: 0.0
            yaw: -0.06657199050248196
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.022183666383407942
            roll: 0.0
            pitch: 0.0
            yaw: 0.09519635217526001
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.038872368171583904
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.016286031093122516
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.010172861989766482
            roll: 0.0
            pitch: 0.0
            yaw: -1.0266548397000574
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.03284734215268992
            roll: 0.0
            pitch: 0.0
            yaw: 0.7648707347028634
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05938107667601897
            roll: 0.0
            pitch: 0.0
            yaw: -0.45719545655423777
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.012914001642924292
            roll: 0.0
            pitch: 0.0
            yaw: -0.1413885501349459
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08570300867849578
            roll: 0.0
            pitch: 0.0
            yaw: 0.9998501321707105
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06995588132842609
            roll: 0.0
            pitch: 0.0
            yaw: 0.35658851564114435
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0016262661818938103
              y: 0.015494047243493424
              z: 0.0427663612024252
              roll: 0.448620502238747
              pitch: -0.4962928884561383
              yaw: 1.2977463575287669
            roll: 0.46541269470749924
            pitch: -0.48820442156105087
            yaw: 1.3251235282863396
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
