scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.16625464267341722
          y: -0.22037864328256923
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.185861117205826
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.014967722763595787
            roll: 0.0
            pitch: 0.0
            yaw: 0.13077295993826643
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01215479167143066
            roll: 0.0
            pitch: 0.0
            yaw: 0.14717200331589908
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0016783102420419235
            roll: 0.0
            pitch: 0.0
            yaw: -0.005772231164925118
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.007489201110354015
            roll: 0.0
            pitch: 0.0
            yaw: -0.12300158126754028
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0035863636551797876
            roll: 0.0
            pitch: 0.0
            yaw: 0.11494479066100305
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.017825707269985502
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.017557115940452887
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0711938224595037
            roll: 0.0
            pitch: 0.0
            yaw: 0.5992831524614914
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0016273623506511264
            roll: 0.0
            pitch: 0.0
            yaw: -0.3167658461552608
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05936259699466288
            roll: 0.0
            pitch: 0.0
            yaw: 0.2860749912675744
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07961716879694827
            roll: 0.0
            pitch: 0.0
            yaw: 0.5738030251763515
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.071020034393178
            roll: 0.0
            pitch: 0.0
            yaw: 0.5654893688689471
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03842193046258021
            roll: 0.0
            pitch: 0.0
            yaw: 0.5650234170657222
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00010256990398506633
              y: 0.016101737580214732
              z: 0.04179812036352862
              roll: 0.4283790311239511
              pitch: -0.4803167651672722
              yaw: 1.290325107664156
            roll: 0.43543403938853886
            pitch: -0.4878393315620018
            yaw: 1.3609007074540542
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.22172510426679312
          y: -0.15455662109632734
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.1875374686663065
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01853668411515498
            roll: 0.0
            pitch: 0.0
            yaw: -0.11225836623784147
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.015224703279658209
            roll: 0.0
            pitch: 0.0
            yaw: -0.15428619096965684
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.00975952235751159
            roll: 0.0
            pitch: 0.0
            yaw: -0.14511803503121348
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0020082460368145948
            roll: 0.0
            pitch: 0.0
            yaw: 0.048765428356054547
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.011753875665399566
            roll: 0.0
            pitch: 0.0
            yaw: -0.13398253682017097
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.017273022217988945
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.018908178973863668
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.008923888608820749
            roll: 0.0
            pitch: 0.0
            yaw: -0.23823137969980968
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.010665194901613342
            roll: 0.0
            pitch: 0.0
            yaw: 0.34120269460128605
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05788859518111232
            roll: 0.0
            pitch: 0.0
            yaw: -0.8069523719435939
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06237483177208246
            roll: 0.0
            pitch: 0.0
            yaw: -0.9678097716472932
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06216109350797311
            roll: 0.0
            pitch: 0.0
            yaw: -0.6698001576661721
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04427625119191814
            roll: 0.0
            pitch: 0.0
            yaw: -0.6412084468637798
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0012097600844970513
              y: 0.014642084064915952
              z: 0.04050788264412442
              roll: 0.47032765786539277
              pitch: -0.45306984919946885
              yaw: 1.3625811476481786
            roll: 0.4530702275940748
            pitch: -0.48699796670763495
            yaw: 1.3567838683118367
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.26522401363391623
          y: -0.18898434031718644
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.02546578203500849
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.00744837806742487
            roll: 0.0
            pitch: 0.0
            yaw: -0.14166141778919744
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01060364716849197
            roll: 0.0
            pitch: 0.0
            yaw: -0.08787598950955651
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.014070182380550994
            roll: 0.0
            pitch: 0.0
            yaw: 0.002753854667300798
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.021344556813834802
            roll: 0.0
            pitch: 0.0
            yaw: 0.12596859287444845
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0035570737635626758
            roll: 0.0
            pitch: 0.0
            yaw: 0.010729956741235891
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04021254299905365
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.025082056963631916
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.005704151349325448
            roll: 0.0
            pitch: 0.0
            yaw: 0.5556285353207093
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05331106635382973
            roll: 0.0
            pitch: 0.0
            yaw: -0.8007150477112842
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.029195925325243982
            roll: 0.0
            pitch: 0.0
            yaw: 0.5660344642636619
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09432640586124577
            roll: 0.0
            pitch: 0.0
            yaw: 1.0468493682903042
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0004997816308567604
            roll: 0.0
            pitch: 0.0
            yaw: -0.5802394365465462
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.008773030595395026
            roll: 0.0
            pitch: 0.0
            yaw: 0.8897313139667908
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0007770181834084607
              y: 0.015562161773461577
              z: 0.040920024161238584
              roll: 0.4581818248422919
              pitch: -0.47816594841265103
              yaw: 1.323068352014432
            roll: 0.4290341208821937
            pitch: -0.46186655534315574
            yaw: 1.3553456228646317
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
