scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2754208233592208
          y: -0.14592284840591804
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.0940520464113207
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.019491356898341188
            roll: 0.0
            pitch: 0.0
            yaw: 0.09174463057550647
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.013635017166118021
            roll: 0.0
            pitch: 0.0
            yaw: 0.16453576325483232
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.012759795539432704
            roll: 0.0
            pitch: 0.0
            yaw: 0.09822778037010343
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.011193281788981227
            roll: 0.0
            pitch: 0.0
            yaw: 0.0366803520904381
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0058979581155818445
            roll: 0.0
            pitch: 0.0
            yaw: 0.04658583427952076
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0013979346935648201
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.021728292589989547
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.017380583352979637
            roll: 0.0
            pitch: 0.0
            yaw: -0.5878510905916751
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.03139731520459593
            roll: 0.0
            pitch: 0.0
            yaw: 0.04339389679091088
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.059300128747104705
            roll: 0.0
            pitch: 0.0
            yaw: -0.978508103619667
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05820570275425766
            roll: 0.0
            pitch: 0.0
            yaw: -0.1908989006961216
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06073968991827364
            roll: 0.0
            pitch: 0.0
            yaw: 0.24661878331768672
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.007315900065865147
            roll: 0.0
            pitch: 0.0
            yaw: -0.3800922464861377
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001492516664647375
              y: 0.016499110766343892
              z: 0.04430340977605374
              roll: 0.42992104665477476
              pitch: -0.5219500631810738
              yaw: 1.3533229476671058
            roll: 0.4091981994499076
            pitch: -0.4461047223854617
            yaw: 1.324587632378286
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1583290040349497
          y: -0.2865774197736563
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4058892926928256
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.012211176015192733
            roll: 0.0
            pitch: 0.0
            yaw: 0.15608368877458112
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.010771991992133993
            roll: 0.0
            pitch: 0.0
            yaw: -0.05170232100433425
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01501650059369206
            roll: 0.0
            pitch: 0.0
            yaw: 0.15773223431824385
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.016350198547970627
            roll: 0.0
            pitch: 0.0
            yaw: -0.06003744022058995
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0005970198123548646
            roll: 0.0
            pitch: 0.0
            yaw: 0.09151566431707908
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.054318973698452774
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.005898982114969337
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.025903752969838365
            roll: 0.0
            pitch: 0.0
            yaw: 0.7030857517252898
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04932319832742279
            roll: 0.0
            pitch: 0.0
            yaw: -0.8187664082607353
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.034369461601927186
            roll: 0.0
            pitch: 0.0
            yaw: -0.8311712339399824
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04764225890887855
            roll: 0.0
            pitch: 0.0
            yaw: 0.3481892850920887
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0253692776406306
            roll: 0.0
            pitch: 0.0
            yaw: 0.5261566538319402
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06985909100783469
            roll: 0.0
            pitch: 0.0
            yaw: 0.10037318370345827
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0010529512083868582
              y: 0.016994248988208886
              z: 0.0435266614676168
              roll: 0.48296022154062535
              pitch: -0.48715350220342163
              yaw: 1.3584169119378011
            roll: 0.46320647964102596
            pitch: -0.47197494280217633
            yaw: 1.3432331967645381
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.23574694677261493
          y: -0.112965632782947
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.06676775402449053
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.017829391895359988
            roll: 0.0
            pitch: 0.0
            yaw: 0.08487356226887888
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01031213716703893
            roll: 0.0
            pitch: 0.0
            yaw: -0.11099132124055172
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.019754552566959238
            roll: 0.0
            pitch: 0.0
            yaw: 0.007160939609654193
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.007654933675617976
            roll: 0.0
            pitch: 0.0
            yaw: 0.13836423060628888
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.007485948851631535
            roll: 0.0
            pitch: 0.0
            yaw: 0.01974519164218677
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03593174017168872
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.007007649805949381
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.03879024922978813
            roll: 0.0
            pitch: 0.0
            yaw: -0.3362632702345014
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.015301877279657095
            roll: 0.0
            pitch: 0.0
            yaw: 0.6504957597286065
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07643033889773054
            roll: 0.0
            pitch: 0.0
            yaw: -0.14945537733130987
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.019079362043024392
            roll: 0.0
            pitch: 0.0
            yaw: -0.5213393522521614
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06210724003080187
            roll: 0.0
            pitch: 0.0
            yaw: 0.9335964787617743
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08149137550912189
            roll: 0.0
            pitch: 0.0
            yaw: 0.3152649111558259
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.001565146486900276
              y: 0.013921592396793489
              z: 0.042749212069162296
              roll: 0.41805417794242483
              pitch: -0.4913442749157615
              yaw: 1.3172209607220375
            roll: 0.45199984934546406
            pitch: -0.5134908561575756
            yaw: 1.2971961480595524
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
