scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.24925927589161312
          y: -0.17107228744652084
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4294154020195313
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.010185869876759839
            roll: 0.0
            pitch: 0.0
            yaw: -0.11125918602415849
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01591492296245855
            roll: 0.0
            pitch: 0.0
            yaw: 0.14552770904756074
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.009540337620463293
            roll: 0.0
            pitch: 0.0
            yaw: -0.05660119356981773
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.015731879577376387
            roll: 0.0
            pitch: 0.0
            yaw: 0.008290322758892466
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0017871467836058537
            roll: 0.0
            pitch: 0.0
            yaw: -0.042449081568020186
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02956541608502833
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.014894836004355476
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.086891425643214
            roll: 0.0
            pitch: 0.0
            yaw: 0.07592056883637577
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.011936704150452379
            roll: 0.0
            pitch: 0.0
            yaw: -0.7203229440934635
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0435927539351976
            roll: 0.0
            pitch: 0.0
            yaw: -0.6833656817506732
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.02377317409690105
            roll: 0.0
            pitch: 0.0
            yaw: -0.1318690438585034
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.01712932155954934
            roll: 0.0
            pitch: 0.0
            yaw: -0.1326414207026949
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06068271908101747
            roll: 0.0
            pitch: 0.0
            yaw: 0.1581549739242165
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0019029168151336027
              y: 0.01374056812768309
              z: 0.042444659031362936
              roll: 0.4280014030789778
              pitch: -0.5158943243827788
              yaw: 1.3136868797697447
            roll: 0.4058830427312191
            pitch: -0.5118052762896884
            yaw: 1.3186773303014463
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.16769526666107365
          y: -0.2921444594400922
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.09751747194232119
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.003768753610363093
            roll: 0.0
            pitch: 0.0
            yaw: -0.15737434902270456
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.008493658379818057
            roll: 0.0
            pitch: 0.0
            yaw: 0.15428972892367315
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.005420410839098673
            roll: 0.0
            pitch: 0.0
            yaw: -0.12699967588652628
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013749831301881288
            roll: 0.0
            pitch: 0.0
            yaw: 0.044473801790473805
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -5.5816616860080576e-05
            roll: 0.0
            pitch: 0.0
            yaw: -0.15455304560720784
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04001033378769737
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.023004064911621824
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0207450017087486
            roll: 0.0
            pitch: 0.0
            yaw: 0.6730318872495724
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09132929460475038
            roll: 0.0
            pitch: 0.0
            yaw: -0.7139045067035843
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.049586353060623756
            roll: 0.0
            pitch: 0.0
            yaw: 0.50811392540806
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.011671530432781407
            roll: 0.0
            pitch: 0.0
            yaw: -0.36805407795479483
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.059817647793752475
            roll: 0.0
            pitch: 0.0
            yaw: -0.5431627364706777
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.018529594093490726
            roll: 0.0
            pitch: 0.0
            yaw: 0.6565565894044771
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0012405050037032103
              y: 0.01512366523630929
              z: 0.04306482484343495
              roll: 0.4760173822271469
              pitch: -0.4685510072795286
              yaw: 1.3345526896110742
            roll: 0.4611619023079606
            pitch: -0.442497964540845
            yaw: 1.3662070531227526
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.11909403912950248
          y: -0.28743179132988705
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.20352503632551422
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.005797114895150751
            roll: 0.0
            pitch: 0.0
            yaw: -0.1708286997659108
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01649505012388367
            roll: 0.0
            pitch: 0.0
            yaw: 0.09721542446581921
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0020555156089777475
            roll: 0.0
            pitch: 0.0
            yaw: 0.02110068627837347
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0028950896696023527
            roll: 0.0
            pitch: 0.0
            yaw: 0.06104904589898896
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 7.108173332207729e-05
            roll: 0.0
            pitch: 0.0
            yaw: 0.08057503383907605
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.001592668489914989
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02903149513545472
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07448962550159824
            roll: 0.0
            pitch: 0.0
            yaw: 1.014234573370245
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.042494536134730136
            roll: 0.0
            pitch: 0.0
            yaw: 0.011435472012566006
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.053146607584484
            roll: 0.0
            pitch: 0.0
            yaw: -0.9340408132307795
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.07385447243145007
            roll: 0.0
            pitch: 0.0
            yaw: -0.9625736157149996
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.043863523822414846
            roll: 0.0
            pitch: 0.0
            yaw: 0.002267262617097643
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06667845338163456
            roll: 0.0
            pitch: 0.0
            yaw: -0.1593707868339166
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0012066836909052558
              y: 0.01454710896778138
              z: 0.04220977449836153
              roll: 0.40942002970012487
              pitch: -0.46282128598465844
              yaw: 1.367512397590167
            roll: 0.475276324766271
            pitch: -0.45135308151779796
            yaw: 1.334054827276815
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
