scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.22926536626360708
          y: -0.2033557354822939
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.36453881990872705
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01834858963039214
            roll: 0.0
            pitch: 0.0
            yaw: -0.12769179042015447
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.00517938985944337
            roll: 0.0
            pitch: 0.0
            yaw: -0.16694902573921244
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.016469511838248567
            roll: 0.0
            pitch: 0.0
            yaw: -0.10978160309694576
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0192430938330699
            roll: 0.0
            pitch: 0.0
            yaw: 0.07836155515572996
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.004664098234618299
            roll: 0.0
            pitch: 0.0
            yaw: -0.05493188897920549
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0019647667554055018
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03831422144049018
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.005931910454839873
            roll: 0.0
            pitch: 0.0
            yaw: -0.9002939949337265
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.028751802433903614
            roll: 0.0
            pitch: 0.0
            yaw: 0.07329873973956191
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02025252042329756
            roll: 0.0
            pitch: 0.0
            yaw: -0.2542501392255757
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0731988940535902
            roll: 0.0
            pitch: 0.0
            yaw: -0.9974624326088661
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.047391212203076474
            roll: 0.0
            pitch: 0.0
            yaw: 0.9864605984903643
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04044073072002555
            roll: 0.0
            pitch: 0.0
            yaw: -0.8245242663636707
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0019843796199643425
              y: 0.013800036082369536
              z: 0.04388600912546802
              roll: 0.4184964970114981
              pitch: -0.4744317293641163
              yaw: 1.355032477533163
            roll: 0.47752049540024577
            pitch: -0.4881979878119182
            yaw: 1.359520940098283
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1325551859962312
          y: -0.23241947147859032
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4000015032048717
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01470293156822846
            roll: 0.0
            pitch: 0.0
            yaw: -0.04877549551189164
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010062234417789293
            roll: 0.0
            pitch: 0.0
            yaw: 0.07057331797515357
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.011134433534849605
            roll: 0.0
            pitch: 0.0
            yaw: -0.06862311711982015
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.004259656611455814
            roll: 0.0
            pitch: 0.0
            yaw: -0.04451593846376145
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.005736264623005107
            roll: 0.0
            pitch: 0.0
            yaw: -0.15223592179450116
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0559048383410548
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.016528221624662345
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05079268054426704
            roll: 0.0
            pitch: 0.0
            yaw: 0.029041377101123533
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07140860760225232
            roll: 0.0
            pitch: 0.0
            yaw: 0.49499362400638525
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.006186741726012163
            roll: 0.0
            pitch: 0.0
            yaw: 0.8634031109951381
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09271611358033494
            roll: 0.0
            pitch: 0.0
            yaw: -0.7229647011127724
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.047700569948796456
            roll: 0.0
            pitch: 0.0
            yaw: -0.5868193950083518
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07560203322110248
            roll: 0.0
            pitch: 0.0
            yaw: 0.32161674415475683
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.000512503058071019
              y: 0.01709561772867635
              z: 0.04373660004980036
              roll: 0.4193478124339787
              pitch: -0.506079879250971
              yaw: 1.3592683508188368
            roll: 0.45731492645506605
            pitch: -0.44676324332759104
            yaw: 1.3136288831661644
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.27008406816844566
          y: -0.17046638688416516
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.40249221152584624
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01620040686299984
            roll: 0.0
            pitch: 0.0
            yaw: 0.09110533854577496
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.012014554474660004
            roll: 0.0
            pitch: 0.0
            yaw: 0.1382326609170217
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0012726782700597794
            roll: 0.0
            pitch: 0.0
            yaw: -0.11862786404839912
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.021182747791728067
            roll: 0.0
            pitch: 0.0
            yaw: 0.03152207159673395
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0027870148877609073
            roll: 0.0
            pitch: 0.0
            yaw: 0.09614516908386939
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.036046978282305825
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0027609076138329497
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07377177792007478
            roll: 0.0
            pitch: 0.0
            yaw: 0.24246771400900635
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.03264732139543994
            roll: 0.0
            pitch: 0.0
            yaw: 0.7465570773440333
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03265916419947529
            roll: 0.0
            pitch: 0.0
            yaw: 0.8508328176108404
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05478841098077855
            roll: 0.0
            pitch: 0.0
            yaw: -0.36291012787423405
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.015613795357022148
            roll: 0.0
            pitch: 0.0
            yaw: -0.3486651254858294
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08128238587620372
            roll: 0.0
            pitch: 0.0
            yaw: 0.3075046216176982
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.00034628215643625225
              y: 0.013641761157904274
              z: 0.04435804076998786
              roll: 0.42709967475466426
              pitch: -0.4636241061531071
              yaw: 1.3525886992392566
            roll: 0.4515603054762699
            pitch: -0.4539041143604494
            yaw: 1.3303180402779746
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
