scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.10374027698022868
          y: -0.1419643688663697
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.016211907004683668
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.011648101662174452
            roll: 0.0
            pitch: 0.0
            yaw: -0.1316870462955215
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0024061838055115525
            roll: 0.0
            pitch: 0.0
            yaw: -0.14111462281357662
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.015670728754652127
            roll: 0.0
            pitch: 0.0
            yaw: -0.03107863909069647
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.004073564384104975
            roll: 0.0
            pitch: 0.0
            yaw: 0.0022823216951316228
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.00733661816660912
            roll: 0.0
            pitch: 0.0
            yaw: -0.018117096569200103
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03684838344213856
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.009396873394800526
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.00920661208862128
            roll: 0.0
            pitch: 0.0
            yaw: -0.2754297660005772
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.005668840284634186
            roll: 0.0
            pitch: 0.0
            yaw: 0.46551840465530514
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.046807520471642466
            roll: 0.0
            pitch: 0.0
            yaw: -0.2544489208055011
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.02498430432903445
            roll: 0.0
            pitch: 0.0
            yaw: 0.10951729271824173
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.002946909789689464
            roll: 0.0
            pitch: 0.0
            yaw: 0.42182263174915224
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.029083945506526848
            roll: 0.0
            pitch: 0.0
            yaw: -0.27926992562444763
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00041314097864129625
              y: 0.013880370408360694
              z: 0.04132233787547868
              roll: 0.4297377083202605
              pitch: -0.4777872913905749
              yaw: 1.3392167877644254
            roll: 0.40963673075052365
            pitch: -0.471266005508077
            yaw: 1.3101738001780092
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.27658917138839717
          y: -0.21201838632166092
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.03316673251255764
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.010530026712777536
            roll: 0.0
            pitch: 0.0
            yaw: -0.0569038976590481
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01735715947260981
            roll: 0.0
            pitch: 0.0
            yaw: -0.15110387340879544
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.00546803082555939
            roll: 0.0
            pitch: 0.0
            yaw: -0.04641781610966153
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02211712222055079
            roll: 0.0
            pitch: 0.0
            yaw: 0.14177281573732303
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.008821146714403677
            roll: 0.0
            pitch: 0.0
            yaw: 0.1004124047341039
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04550018735203937
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03027282512301864
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0551997531841944
            roll: 0.0
            pitch: 0.0
            yaw: 0.36568525305087296
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08590436715461112
            roll: 0.0
            pitch: 0.0
            yaw: -0.9742861964618789
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.041765111669370525
            roll: 0.0
            pitch: 0.0
            yaw: 0.6153141354342602
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.094069790035605
            roll: 0.0
            pitch: 0.0
            yaw: -0.7219726236092037
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.09212076495125147
            roll: 0.0
            pitch: 0.0
            yaw: -0.8372314505022003
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08312415843105422
            roll: 0.0
            pitch: 0.0
            yaw: 0.7761496341401635
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0014100309832188228
              y: 0.015457877609375555
              z: 0.04111572048260803
              roll: 0.42006849048474726
              pitch: -0.4647115762227734
              yaw: 1.3354491967008717
            roll: 0.40762717244010765
            pitch: -0.5096656439686621
            yaw: 1.3005515108915462
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.1550692585866309
          y: -0.16656463268363203
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.0687545470397053
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.018528729289472235
            roll: 0.0
            pitch: 0.0
            yaw: -0.17107314423734316
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0016248357848022213
            roll: 0.0
            pitch: 0.0
            yaw: 0.15866316127624164
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.001819437095029769
            roll: 0.0
            pitch: 0.0
            yaw: 0.09823573634761984
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.001272093919235405
            roll: 0.0
            pitch: 0.0
            yaw: 0.03629493403855355
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0038599653068670907
            roll: 0.0
            pitch: 0.0
            yaw: 0.0914516703759291
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0006562889138231401
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.026066857566408586
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.013855829536577602
            roll: 0.0
            pitch: 0.0
            yaw: 0.1327065114906647
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07346759956551571
            roll: 0.0
            pitch: 0.0
            yaw: -0.7533834025074932
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0018315332417463137
            roll: 0.0
            pitch: 0.0
            yaw: 0.2909613219522247
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.043188165995603434
            roll: 0.0
            pitch: 0.0
            yaw: -0.04425805229154922
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.011227887824601851
            roll: 0.0
            pitch: 0.0
            yaw: -0.4137293159765444
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0940989437283843
            roll: 0.0
            pitch: 0.0
            yaw: -0.8405200895319046
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0007747297146379836
              y: 0.015703344446351755
              z: 0.0427411998328493
              roll: 0.43258466009907426
              pitch: -0.4871539687595776
              yaw: 1.3175293193079811
            roll: 0.46023768851762104
            pitch: -0.5174889416335587
            yaw: 1.3037938999047047
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
