scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1356835947567495
          y: -0.1707441112341015
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.25291350309577476
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.016736468359829313
            roll: 0.0
            pitch: 0.0
            yaw: -0.13918519668793553
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0015518137551803896
            roll: 0.0
            pitch: 0.0
            yaw: 0.15405258847682013
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.006587577363624805
            roll: 0.0
            pitch: 0.0
            yaw: -0.0378985292267873
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0025819842268770647
            roll: 0.0
            pitch: 0.0
            yaw: 0.02200412102625829
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.016973204477938875
            roll: 0.0
            pitch: 0.0
            yaw: 0.13834000572678995
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03607386354833304
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.029420475696969508
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08365254479852305
            roll: 0.0
            pitch: 0.0
            yaw: -0.22702742121669717
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0615501106416223
            roll: 0.0
            pitch: 0.0
            yaw: -0.465165479465819
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.025962553689245618
            roll: 0.0
            pitch: 0.0
            yaw: 0.8483860015862759
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05966255141624115
            roll: 0.0
            pitch: 0.0
            yaw: 0.8069293942401037
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0842042415187361
            roll: 0.0
            pitch: 0.0
            yaw: -0.1003808290225946
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.020937658120576394
            roll: 0.0
            pitch: 0.0
            yaw: -0.5666063905939664
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0016264337228268579
              y: 0.016751347582856818
              z: 0.04266267185078471
              roll: 0.4137593001647483
              pitch: -0.47601907438458674
              yaw: 1.325751929655833
            roll: 0.46171338430282083
            pitch: -0.4710853702637217
            yaw: 1.3153507599404275
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.12020806870426062
          y: -0.16916644472830714
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.43322553319751467
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.004183814168385175
            roll: 0.0
            pitch: 0.0
            yaw: 0.011306678297323458
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.004470264253668307
            roll: 0.0
            pitch: 0.0
            yaw: -0.17091173822276912
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.005944346525067139
            roll: 0.0
            pitch: 0.0
            yaw: 0.00880931359102341
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02331259477050785
            roll: 0.0
            pitch: 0.0
            yaw: 0.07152021294488628
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.006823061615365254
            roll: 0.0
            pitch: 0.0
            yaw: -0.0468533546471242
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02804807172014618
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.014416925820823878
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.009015043505838566
            roll: 0.0
            pitch: 0.0
            yaw: -0.5859324822269882
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.060491381146258724
            roll: 0.0
            pitch: 0.0
            yaw: 0.21517950163743138
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.026791760423110073
            roll: 0.0
            pitch: 0.0
            yaw: 0.1277487928699288
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08464848601173455
            roll: 0.0
            pitch: 0.0
            yaw: 0.5943193779863545
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0011357046581563918
            roll: 0.0
            pitch: 0.0
            yaw: 0.4158593672002562
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08753157990060584
            roll: 0.0
            pitch: 0.0
            yaw: -0.7147070243415523
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0013469497528237437
              y: 0.01628112945784909
              z: 0.040664880631146316
              roll: 0.45248983129285103
              pitch: -0.4856326460837381
              yaw: 1.3305141165933636
            roll: 0.46253507152907775
            pitch: -0.4735243555912278
            yaw: 1.3006708725436782
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.289448945830154
          y: -0.2530953079241474
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.06350774219638666
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.001790989962120234
            roll: 0.0
            pitch: 0.0
            yaw: -0.10048925314747324
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006678116727533007
            roll: 0.0
            pitch: 0.0
            yaw: -0.08881797725849215
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.007057043220097859
            roll: 0.0
            pitch: 0.0
            yaw: 0.16359263488229248
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.010421381479515724
            roll: 0.0
            pitch: 0.0
            yaw: 0.09578475427142957
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.012640027682303705
            roll: 0.0
            pitch: 0.0
            yaw: -0.03860507467251159
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.005945792941353306
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03843171313630095
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08756132743696068
            roll: 0.0
            pitch: 0.0
            yaw: 0.7494432558508055
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09053642187069016
            roll: 0.0
            pitch: 0.0
            yaw: -0.7683766811593262
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.038532791774930936
            roll: 0.0
            pitch: 0.0
            yaw: -0.1270781059905206
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.040198135072753244
            roll: 0.0
            pitch: 0.0
            yaw: -0.9867018338033364
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03468982118664418
            roll: 0.0
            pitch: 0.0
            yaw: -0.4081565495002526
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.024357326711197794
            roll: 0.0
            pitch: 0.0
            yaw: -0.724321452875714
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0005586398712778759
              y: 0.016115346008971874
              z: 0.042705974621800896
              roll: 0.4746553482274922
              pitch: -0.4823448071723825
              yaw: 1.3153534855736142
            roll: 0.45476898621689316
            pitch: -0.492400968075981
            yaw: 1.3085741413206895
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
