scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.19314743974141488
          y: -0.13632350223070427
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.29756863541361445
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.008431704180744092
            roll: 0.0
            pitch: 0.0
            yaw: 0.11569973038876141
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01929928499561928
            roll: 0.0
            pitch: 0.0
            yaw: 0.15005446584713727
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.012119605970587598
            roll: 0.0
            pitch: 0.0
            yaw: 0.08678824044848454
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.02067585421485944
            roll: 0.0
            pitch: 0.0
            yaw: 0.0985653358765759
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.022387075782158615
            roll: 0.0
            pitch: 0.0
            yaw: -0.02890687568458114
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02193285277676707
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.033863818641559185
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.022193096747494687
            roll: 0.0
            pitch: 0.0
            yaw: 0.6808226997062408
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.015925238348605375
            roll: 0.0
            pitch: 0.0
            yaw: 0.563751230049405
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06086303904394566
            roll: 0.0
            pitch: 0.0
            yaw: -0.9163980511042265
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.06482370612304028
            roll: 0.0
            pitch: 0.0
            yaw: -0.12652589146332616
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0015658122000258706
            roll: 0.0
            pitch: 0.0
            yaw: -0.1673621314643986
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.018048811034938675
            roll: 0.0
            pitch: 0.0
            yaw: -0.2650754483883738
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0010541935442502553
              y: 0.015426990583773392
              z: 0.04061025829116301
              roll: 0.43577973492876276
              pitch: -0.5042260300249226
              yaw: 1.3417345270880074
            roll: 0.4502569944188629
            pitch: -0.4507591590543373
            yaw: 1.3364599509628845
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.10770351698462986
          y: -0.2319122965633143
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3550503439019208
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0013559989152054051
            roll: 0.0
            pitch: 0.0
            yaw: 0.1605241955075895
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.011515844973759903
            roll: 0.0
            pitch: 0.0
            yaw: -0.09132129640686551
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01688634047826501
            roll: 0.0
            pitch: 0.0
            yaw: -0.10827243241612533
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.004053077576988275
            roll: 0.0
            pitch: 0.0
            yaw: 0.08815429424308302
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.006684751891223509
            roll: 0.0
            pitch: 0.0
            yaw: -0.06374272479943631
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.040234422629982176
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.00814331213128934
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.014592488035659254
            roll: 0.0
            pitch: 0.0
            yaw: 0.5088764698088863
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.06387441376841102
            roll: 0.0
            pitch: 0.0
            yaw: -0.8460719479570104
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.030082608679505435
            roll: 0.0
            pitch: 0.0
            yaw: -0.1460585574329487
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08405606124868337
            roll: 0.0
            pitch: 0.0
            yaw: 0.4527054381534321
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0026594182798314325
            roll: 0.0
            pitch: 0.0
            yaw: -0.9011351870549934
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04479633958754317
            roll: 0.0
            pitch: 0.0
            yaw: 0.4243371719557816
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0017428575998739908
              y: 0.015879444086294207
              z: 0.0435297268132548
              roll: 0.41285825131940407
              pitch: -0.46924641443301013
              yaw: 1.3401134654886575
            roll: 0.42231651987755053
            pitch: -0.4413989462640334
            yaw: 1.3574207915368512
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.12508165108081354
          y: -0.15324685917050718
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.26026172659227
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.007685274253158536
            roll: 0.0
            pitch: 0.0
            yaw: -0.03905630109926522
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.014236466050877382
            roll: 0.0
            pitch: 0.0
            yaw: -0.1451175399709027
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.010826244019152158
            roll: 0.0
            pitch: 0.0
            yaw: 0.0334994292720765
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.005202714555502794
            roll: 0.0
            pitch: 0.0
            yaw: -0.17236527196272428
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01456573512818508
            roll: 0.0
            pitch: 0.0
            yaw: 0.08457575949718549
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.033267408368969284
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.02410886060421065
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.014265667323778847
            roll: 0.0
            pitch: 0.0
            yaw: 0.7379264916613801
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.022625522029444275
            roll: 0.0
            pitch: 0.0
            yaw: -0.6373814054384497
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06443733261535134
            roll: 0.0
            pitch: 0.0
            yaw: 0.8607895564910149
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03729541012643732
            roll: 0.0
            pitch: 0.0
            yaw: -0.5620704923407739
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07866917934132447
            roll: 0.0
            pitch: 0.0
            yaw: -0.7345349232841896
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.003813222172739536
            roll: 0.0
            pitch: 0.0
            yaw: 0.38701329053210465
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.001102264710909468
              y: 0.01534628796880361
              z: 0.04124461985503783
              roll: 0.4314385297197857
              pitch: -0.48275037763467415
              yaw: 1.3049862989581542
            roll: 0.4693617609755195
            pitch: -0.46895023282384307
            yaw: 1.303161215553823
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
