scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2563454092265237
          y: -0.22135104896101698
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.33474016226011705
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0038159065464011856
            roll: 0.0
            pitch: 0.0
            yaw: -0.08158349079333119
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01771863490466832
            roll: 0.0
            pitch: 0.0
            yaw: 0.0759096519204755
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.001520863293573562
            roll: 0.0
            pitch: 0.0
            yaw: -0.10893165583469416
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.006368143262840922
            roll: 0.0
            pitch: 0.0
            yaw: 0.13666401428251518
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0028514526046008216
            roll: 0.0
            pitch: 0.0
            yaw: 0.13909936638290588
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05448676259112058
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0394097227094523
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07994983114538776
            roll: 0.0
            pitch: 0.0
            yaw: 0.8691223592437953
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.010623812106704378
            roll: 0.0
            pitch: 0.0
            yaw: -0.38629778802861503
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03754385060598343
            roll: 0.0
            pitch: 0.0
            yaw: 0.2036627689068553
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05258416380197849
            roll: 0.0
            pitch: 0.0
            yaw: -1.0177346685215864
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05379439840799576
            roll: 0.0
            pitch: 0.0
            yaw: 0.755877003082126
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.028718875758361198
            roll: 0.0
            pitch: 0.0
            yaw: -0.11119980411280184
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0008079697456030632
              y: 0.013780786607715204
              z: 0.04212922706712763
              roll: 0.43288448813374597
              pitch: -0.5223037965280477
              yaw: 1.3011472357174025
            roll: 0.46639979471059034
            pitch: -0.501738986665936
            yaw: 1.3442342828733587
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2004786326688188
          y: -0.19602544490639434
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3552431192308605
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.006657971809651192
            roll: 0.0
            pitch: 0.0
            yaw: -0.10182316728726179
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.020032348290543973
            roll: 0.0
            pitch: 0.0
            yaw: 0.0428464574928111
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.007945845530240435
            roll: 0.0
            pitch: 0.0
            yaw: -0.10564558742322863
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01636237355336574
            roll: 0.0
            pitch: 0.0
            yaw: 0.11715671693559448
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.010655337566264467
            roll: 0.0
            pitch: 0.0
            yaw: -0.018001119515472425
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.00855060888338869
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.004408793067228897
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07963567339578881
            roll: 0.0
            pitch: 0.0
            yaw: 0.6419658304486466
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.023089237009931332
            roll: 0.0
            pitch: 0.0
            yaw: -0.682125004321825
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.007112706652676007
            roll: 0.0
            pitch: 0.0
            yaw: 0.765369614346666
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.09564377489026038
            roll: 0.0
            pitch: 0.0
            yaw: -0.012383424391878783
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.009988105124306104
            roll: 0.0
            pitch: 0.0
            yaw: -0.9013219753512826
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06425050216633155
            roll: 0.0
            pitch: 0.0
            yaw: 0.2914205302804238
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -3.3596786855369376e-05
              y: 0.016121642360564584
              z: 0.044281180836453424
              roll: 0.4665611145278684
              pitch: -0.5017267159248583
              yaw: 1.36845972039327
            roll: 0.4698575101167534
            pitch: -0.49143744763284053
            yaw: 1.3512015794452195
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.26913835229644145
          y: -0.1992746184351981
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.058208630097735914
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.007719445973699031
            roll: 0.0
            pitch: 0.0
            yaw: -0.11193406353204623
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01617157662198551
            roll: 0.0
            pitch: 0.0
            yaw: 0.10836253240737653
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.018579039245281877
            roll: 0.0
            pitch: 0.0
            yaw: 0.07957002924321949
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.013558757672812505
            roll: 0.0
            pitch: 0.0
            yaw: -0.06315985529856011
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.019172570997353845
            roll: 0.0
            pitch: 0.0
            yaw: -0.050890183579437503
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.051164907103066815
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05021851142081846
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.007233413015541201
            roll: 0.0
            pitch: 0.0
            yaw: 0.34974803044739744
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.022853612420375174
            roll: 0.0
            pitch: 0.0
            yaw: -0.5659530006594718
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07871994055034248
            roll: 0.0
            pitch: 0.0
            yaw: -0.22876224813736545
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.045111311063279064
            roll: 0.0
            pitch: 0.0
            yaw: -0.6375413955083999
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06229829566230696
            roll: 0.0
            pitch: 0.0
            yaw: 0.8840134652499034
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.001765461155733547
            roll: 0.0
            pitch: 0.0
            yaw: 0.8628424693061545
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0009592109774017236
              y: 0.016984138454513673
              z: 0.04418899378765329
              roll: 0.44807371202725177
              pitch: -0.48515048161317953
              yaw: 1.3408875143900358
            roll: 0.4829225367888594
            pitch: -0.5176269266253509
            yaw: 1.354074695467676
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
