scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.27658917138839717
          y: -0.21201838632166092
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.03316673251255764
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.010530026712777536
            roll: 0.0
            pitch: 0.0
            yaw: -0.0569038976590481
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01735715947260981
            roll: 0.0
            pitch: 0.0
            yaw: -0.15110387340879544
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.00546803082555939
            roll: 0.0
            pitch: 0.0
            yaw: -0.04641781610966153
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02211712222055079
            roll: 0.0
            pitch: 0.0
            yaw: 0.14177281573732303
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.008821146714403677
            roll: 0.0
            pitch: 0.0
            yaw: 0.1004124047341039
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04550018735203937
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03027282512301864
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0551997531841944
            roll: 0.0
            pitch: 0.0
            yaw: 0.36568525305087296
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08590436715461112
            roll: 0.0
            pitch: 0.0
            yaw: -0.9742861964618789
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.041765111669370525
            roll: 0.0
            pitch: 0.0
            yaw: 0.6153141354342602
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.094069790035605
            roll: 0.0
            pitch: 0.0
            yaw: -0.7219726236092037
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.09212076495125147
            roll: 0.0
            pitch: 0.0
            yaw: -0.8372314505022003
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08312415843105422
            roll: 0.0
            pitch: 0.0
            yaw: 0.7761496341401635
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0016140353053225305
              y: 0.016227532723852623
              z: 0.04384712918214214
              roll: 0.47527831806233517
              pitch: -0.5041987591346438
              yaw: 1.3397728904755477
            roll: 0.40762717244010765
            pitch: -0.5096656439686621
            yaw: 1.3005515108915462
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1356835947567495
          y: -0.1707441112341015
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.25291350309577476
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.016736468359829313
            roll: 0.0
            pitch: 0.0
            yaw: -0.13918519668793553
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0015518137551803896
            roll: 0.0
            pitch: 0.0
            yaw: 0.15405258847682013
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.006587577363624805
            roll: 0.0
            pitch: 0.0
            yaw: -0.0378985292267873
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0025819842268770647
            roll: 0.0
            pitch: 0.0
            yaw: 0.02200412102625829
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.016973204477938875
            roll: 0.0
            pitch: 0.0
            yaw: 0.13834000572678995
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03607386354833304
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.029420475696969508
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08365254479852305
            roll: 0.0
            pitch: 0.0
            yaw: -0.22702742121669717
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0615501106416223
            roll: 0.0
            pitch: 0.0
            yaw: -0.465165479465819
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.025962553689245618
            roll: 0.0
            pitch: 0.0
            yaw: 0.8483860015862759
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05966255141624115
            roll: 0.0
            pitch: 0.0
            yaw: 0.8069293942401037
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0842042415187361
            roll: 0.0
            pitch: 0.0
            yaw: -0.1003808290225946
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.020937658120576394
            roll: 0.0
            pitch: 0.0
            yaw: -0.5666063905939664
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0016495544821583507
              y: 0.013996607185435914
              z: 0.042531134697294186
              roll: 0.45290829486490713
              pitch: -0.4633911094115608
              yaw: 1.3164833925730108
            roll: 0.46171338430282083
            pitch: -0.4710853702637217
            yaw: 1.3153507599404275
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.1550692585866309
          y: -0.16656463268363203
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.0687545470397053
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.018528729289472235
            roll: 0.0
            pitch: 0.0
            yaw: -0.17107314423734316
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0016248357848022213
            roll: 0.0
            pitch: 0.0
            yaw: 0.15866316127624164
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.001819437095029769
            roll: 0.0
            pitch: 0.0
            yaw: 0.09823573634761984
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.001272093919235405
            roll: 0.0
            pitch: 0.0
            yaw: 0.03629493403855355
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0038599653068670907
            roll: 0.0
            pitch: 0.0
            yaw: 0.0914516703759291
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0006562889138231401
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.026066857566408586
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.013855829536577602
            roll: 0.0
            pitch: 0.0
            yaw: 0.1327065114906647
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07346759956551571
            roll: 0.0
            pitch: 0.0
            yaw: -0.7533834025074932
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0018315332417463137
            roll: 0.0
            pitch: 0.0
            yaw: 0.2909613219522247
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.043188165995603434
            roll: 0.0
            pitch: 0.0
            yaw: -0.04425805229154922
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.011227887824601851
            roll: 0.0
            pitch: 0.0
            yaw: -0.4137293159765444
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0940989437283843
            roll: 0.0
            pitch: 0.0
            yaw: -0.8405200895319046
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0010916113030549329
              y: 0.016851258046993067
              z: 0.04390373014745231
              roll: 0.47014908886493567
              pitch: -0.5073368496559937
              yaw: 1.3116742500225225
            roll: 0.46023768851762104
            pitch: -0.5174889416335587
            yaw: 1.3037938999047047
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
