scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2522098101406217
          y: -0.2370601712925292
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.0015155026347830614
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0017847529412168342
            roll: 0.0
            pitch: 0.0
            yaw: 0.12396186172602419
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.02086277230692754
            roll: 0.0
            pitch: 0.0
            yaw: 0.04181588011314538
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.02260592962725918
            roll: 0.0
            pitch: 0.0
            yaw: 0.1748399788919825
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.008602968176676657
            roll: 0.0
            pitch: 0.0
            yaw: 0.0397796330200898
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.002297601948105743
            roll: 0.0
            pitch: 0.0
            yaw: 0.17243528540306924
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.018719036598028656
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04446034766519448
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06977316852750384
            roll: 0.0
            pitch: 0.0
            yaw: 0.49392530418816416
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0929283791730322
            roll: 0.0
            pitch: 0.0
            yaw: 0.9137435050148643
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05069834507760487
            roll: 0.0
            pitch: 0.0
            yaw: -0.040600897600913344
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.035166552334156324
            roll: 0.0
            pitch: 0.0
            yaw: 0.6461832095780118
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06222023658475044
            roll: 0.0
            pitch: 0.0
            yaw: -0.6985330093498056
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06824053465771318
            roll: 0.0
            pitch: 0.0
            yaw: 0.5433189086917398
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00180472472589048
              y: 0.015191484948258522
              z: 0.04296439240757862
              roll: 0.4111090319906745
              pitch: -0.49047178644219325
              yaw: 1.2972811550390495
            roll: 0.41297027908405726
            pitch: -0.4409456031281078
            yaw: 1.3207600909344832
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.18536117515204908
          y: -0.1868799191378085
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.057189346640181715
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.020118525609382615
            roll: 0.0
            pitch: 0.0
            yaw: -0.04729512555810245
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.012346450640099236
            roll: 0.0
            pitch: 0.0
            yaw: -0.08538224014751707
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01716299260775863
            roll: 0.0
            pitch: 0.0
            yaw: -0.06359481268781617
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013089439677680705
            roll: 0.0
            pitch: 0.0
            yaw: 0.09772456565642051
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.009983531008951954
            roll: 0.0
            pitch: 0.0
            yaw: -0.043250795490757415
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.008513807867356442
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.013946579916624978
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0859704514289445
            roll: 0.0
            pitch: 0.0
            yaw: 0.36778142828021987
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.015473980115676078
            roll: 0.0
            pitch: 0.0
            yaw: -0.7601458459845469
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.009305933931733498
            roll: 0.0
            pitch: 0.0
            yaw: 0.11628935935164564
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03914645100238173
            roll: 0.0
            pitch: 0.0
            yaw: -0.5813948590777709
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.000596891883954509
            roll: 0.0
            pitch: 0.0
            yaw: 0.18632853160807739
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08715103611589584
            roll: 0.0
            pitch: 0.0
            yaw: 0.9412400855693159
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0018806937817218232
              y: 0.017004107807250632
              z: 0.041849549623278345
              roll: 0.4360050450690131
              pitch: -0.501370679916523
              yaw: 1.2909543784515831
            roll: 0.47480793140166483
            pitch: -0.502151113856379
            yaw: 1.3371109566498283
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.23663201195611044
          y: -0.2457134677338099
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4448655128456631
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.013786715432745185
            roll: 0.0
            pitch: 0.0
            yaw: 0.0007690095633560434
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.013691233603490808
            roll: 0.0
            pitch: 0.0
            yaw: 0.11401756334134117
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.002637726932395959
            roll: 0.0
            pitch: 0.0
            yaw: -0.05948929235321984
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01284550807945524
            roll: 0.0
            pitch: 0.0
            yaw: 0.12012761188753746
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01622229591132684
            roll: 0.0
            pitch: 0.0
            yaw: 0.03296749831911461
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.026181600357938303
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.029924457997444472
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0756899171909126
            roll: 0.0
            pitch: 0.0
            yaw: 0.5161383926563579
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09502330310756035
            roll: 0.0
            pitch: 0.0
            yaw: 0.8053914767662556
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.009596366811280288
            roll: 0.0
            pitch: 0.0
            yaw: -0.9344976227606796
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.033839352794427596
            roll: 0.0
            pitch: 0.0
            yaw: -0.3898177102549124
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.02855131067029676
            roll: 0.0
            pitch: 0.0
            yaw: -0.6414998280062685
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08222243397467388
            roll: 0.0
            pitch: 0.0
            yaw: -0.9431981055228146
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0015973119775097543
              y: 0.015223793396743259
              z: 0.042975182238492345
              roll: 0.4166718322577327
              pitch: -0.4494231910031933
              yaw: 1.317784103770925
            roll: 0.41712921974137646
            pitch: -0.46912711921511135
            yaw: 1.3174280893493742
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
