scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2506295544199886
          y: -0.27154650270410147
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.26936412021147416
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.019794701775065017
            roll: 0.0
            pitch: 0.0
            yaw: -0.1584240677652384
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008794137661974354
            roll: 0.0
            pitch: 0.0
            yaw: -0.1677358462488943
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0003216070799759545
            roll: 0.0
            pitch: 0.0
            yaw: -0.01578725344907475
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01906792430880065
            roll: 0.0
            pitch: 0.0
            yaw: -0.04445946607978396
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.02049397828327402
            roll: 0.0
            pitch: 0.0
            yaw: 0.14366706123150785
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04196530400501448
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.010181846889640148
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05645153995774349
            roll: 0.0
            pitch: 0.0
            yaw: 0.41547926785719547
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04697524466002331
            roll: 0.0
            pitch: 0.0
            yaw: -0.6342963581228709
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02623981795707507
            roll: 0.0
            pitch: 0.0
            yaw: -0.27016223745327417
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08347227206741406
            roll: 0.0
            pitch: 0.0
            yaw: 0.4015508856537786
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.018313463575273553
            roll: 0.0
            pitch: 0.0
            yaw: 0.19442794477853442
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04185711944926922
            roll: 0.0
            pitch: 0.0
            yaw: -0.0955899861715035
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0018294981151690836
              y: 0.01440976529715704
              z: 0.040730461840442565
              roll: 0.4356445717124037
              pitch: -0.4696013085768611
              yaw: 1.309196201301102
            roll: 0.4224470503462527
            pitch: -0.4565949952980612
            yaw: 1.3175649448956717
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.10770351698462986
          y: -0.2319122965633143
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3550503439019208
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0013559989152054051
            roll: 0.0
            pitch: 0.0
            yaw: 0.1605241955075895
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.011515844973759903
            roll: 0.0
            pitch: 0.0
            yaw: -0.09132129640686551
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01688634047826501
            roll: 0.0
            pitch: 0.0
            yaw: -0.10827243241612533
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.004053077576988275
            roll: 0.0
            pitch: 0.0
            yaw: 0.08815429424308302
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.006684751891223509
            roll: 0.0
            pitch: 0.0
            yaw: -0.06374272479943631
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.040234422629982176
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.00814331213128934
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.014592488035659254
            roll: 0.0
            pitch: 0.0
            yaw: 0.5088764698088863
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.06387441376841102
            roll: 0.0
            pitch: 0.0
            yaw: -0.8460719479570104
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.030082608679505435
            roll: 0.0
            pitch: 0.0
            yaw: -0.1460585574329487
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08405606124868337
            roll: 0.0
            pitch: 0.0
            yaw: 0.4527054381534321
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0026594182798314325
            roll: 0.0
            pitch: 0.0
            yaw: -0.9011351870549934
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04479633958754317
            roll: 0.0
            pitch: 0.0
            yaw: 0.4243371719557816
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001595266062059621
              y: 0.016350127509403935
              z: 0.042040159778792455
              roll: 0.44220943434090604
              pitch: -0.5036755878369666
              yaw: 1.348568473171526
            roll: 0.42231651987755053
            pitch: -0.4413989462640334
            yaw: 1.3574207915368512
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.13521756182136857
          y: -0.20444478057428347
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.13495348707747923
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.02121466725881043
            roll: 0.0
            pitch: 0.0
            yaw: -0.05306065634358724
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.005433591566248494
            roll: 0.0
            pitch: 0.0
            yaw: 0.16616853342972387
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.003443168793411753
            roll: 0.0
            pitch: 0.0
            yaw: 0.1644260876250357
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01133348651051122
            roll: 0.0
            pitch: 0.0
            yaw: -0.03431051461994719
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.014947361314173457
            roll: 0.0
            pitch: 0.0
            yaw: 0.10880659571280482
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02560003078596893
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0435435224467392
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.008874055410006604
            roll: 0.0
            pitch: 0.0
            yaw: -0.0639107784660049
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05214769411297024
            roll: 0.0
            pitch: 0.0
            yaw: -0.245420272996268
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.024670785694487607
            roll: 0.0
            pitch: 0.0
            yaw: -0.3347397623711641
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08937465476459786
            roll: 0.0
            pitch: 0.0
            yaw: -0.14405494384670592
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.061702431794336945
            roll: 0.0
            pitch: 0.0
            yaw: 0.9048278808538506
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07544411452157755
            roll: 0.0
            pitch: 0.0
            yaw: 1.0379384919735883
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0003629550433990958
              y: 0.016669473185771687
              z: 0.04163618341111158
              roll: 0.45361600798224966
              pitch: -0.4849774345540715
              yaw: 1.3456893577896858
            roll: 0.4558084998010032
            pitch: -0.4945129733150547
            yaw: 1.2984868888889853
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
