scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.15714078844798154
          y: -0.2757572721579994
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.3415374993808318
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.00016430967589621884
            roll: 0.0
            pitch: 0.0
            yaw: 0.14748106839236047
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0064053887191649565
            roll: 0.0
            pitch: 0.0
            yaw: -0.10979524955535515
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.008055642488450924
            roll: 0.0
            pitch: 0.0
            yaw: 0.1745722287980372
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.014584921819472407
            roll: 0.0
            pitch: 0.0
            yaw: 0.1726596366143806
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.013542422880832395
            roll: 0.0
            pitch: 0.0
            yaw: 0.061434413915448155
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.016701932235916067
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03140320332792618
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0022927344572569175
            roll: 0.0
            pitch: 0.0
            yaw: -0.18630801074240622
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08716133209578425
            roll: 0.0
            pitch: 0.0
            yaw: 0.29400616296388504
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09582797552717484
            roll: 0.0
            pitch: 0.0
            yaw: -0.8121344205705959
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.046113139086328914
            roll: 0.0
            pitch: 0.0
            yaw: 0.16879867697074458
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05054165308216707
            roll: 0.0
            pitch: 0.0
            yaw: -0.22459372583068926
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.00469196805674732
            roll: 0.0
            pitch: 0.0
            yaw: 1.031846017572631
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0014305209437424802
              y: 0.01703367244171599
              z: 0.04262324318213034
              roll: 0.46311381450769945
              pitch: -0.5204619630795494
              yaw: 1.3236902686302263
            roll: 0.4307535802451856
            pitch: -0.5152163185512629
            yaw: 1.3380375060244039
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.13861507221879116
          y: -0.20478892506106533
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.425523167231461
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.007153033148778579
            roll: 0.0
            pitch: 0.0
            yaw: -0.03992859510792501
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.013735098652662585
            roll: 0.0
            pitch: 0.0
            yaw: 0.09405623804763674
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01755378089285217
            roll: 0.0
            pitch: 0.0
            yaw: 0.009108981902246266
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.006941219229449194
            roll: 0.0
            pitch: 0.0
            yaw: -0.02220320664069475
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.008638698539081679
            roll: 0.0
            pitch: 0.0
            yaw: -0.10367525930670236
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.025154721801332637
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.00895628217758522
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.03135531688511142
            roll: 0.0
            pitch: 0.0
            yaw: 0.4813875650736106
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.032292384717075795
            roll: 0.0
            pitch: 0.0
            yaw: -0.4599669467045492
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08998933065282541
            roll: 0.0
            pitch: 0.0
            yaw: 0.595854599111997
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04582547517147631
            roll: 0.0
            pitch: 0.0
            yaw: 0.038417985628596885
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.00868316130040872
            roll: 0.0
            pitch: 0.0
            yaw: -0.1740439307503162
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05278290281286234
            roll: 0.0
            pitch: 0.0
            yaw: 0.9727201323713939
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0007219919017433531
              y: 0.016998601600696626
              z: 0.04051860324322009
              roll: 0.4465177286163823
              pitch: -0.5197897544275644
              yaw: 1.3327862273609032
            roll: 0.429471216776905
            pitch: -0.44310328866540033
            yaw: 1.3279035460568838
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.289448945830154
          y: -0.2530953079241474
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.06350774219638666
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.001790989962120234
            roll: 0.0
            pitch: 0.0
            yaw: -0.10048925314747324
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006678116727533007
            roll: 0.0
            pitch: 0.0
            yaw: -0.08881797725849215
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.007057043220097859
            roll: 0.0
            pitch: 0.0
            yaw: 0.16359263488229248
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.010421381479515724
            roll: 0.0
            pitch: 0.0
            yaw: 0.09578475427142957
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.012640027682303705
            roll: 0.0
            pitch: 0.0
            yaw: -0.03860507467251159
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.005945792941353306
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03843171313630095
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08756132743696068
            roll: 0.0
            pitch: 0.0
            yaw: 0.7494432558508055
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09053642187069016
            roll: 0.0
            pitch: 0.0
            yaw: -0.7683766811593262
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.038532791774930936
            roll: 0.0
            pitch: 0.0
            yaw: -0.1270781059905206
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.040198135072753244
            roll: 0.0
            pitch: 0.0
            yaw: -0.9867018338033364
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03468982118664418
            roll: 0.0
            pitch: 0.0
            yaw: -0.4081565495002526
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.024357326711197794
            roll: 0.0
            pitch: 0.0
            yaw: -0.724321452875714
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0006006511832313765
              y: 0.014110907887636212
              z: 0.04415556860099246
              roll: 0.4824830589201173
              pitch: -0.44801363570079894
              yaw: 1.3150301447375166
            roll: 0.45476898621689316
            pitch: -0.492400968075981
            yaw: 1.3085741413206895
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
