scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.19184116125644435
          y: -0.1946807622850606
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.10889417670153811
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.011516981242908744
            roll: 0.0
            pitch: 0.0
            yaw: -0.160181239729457
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010332934130112298
            roll: 0.0
            pitch: 0.0
            yaw: -0.03569016235378061
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0006627418236519814
            roll: 0.0
            pitch: 0.0
            yaw: -0.06854349980214071
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0011293873065401847
            roll: 0.0
            pitch: 0.0
            yaw: -0.03229073725861578
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01377927436027733
            roll: 0.0
            pitch: 0.0
            yaw: 0.061877776968566695
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.026939587772281795
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.00884301864420154
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.02495767803715339
            roll: 0.0
            pitch: 0.0
            yaw: -0.31487199308330194
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08989584226973633
            roll: 0.0
            pitch: 0.0
            yaw: 0.8662772162239167
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.037479144076528165
            roll: 0.0
            pitch: 0.0
            yaw: -0.4154730042710052
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08019321977184932
            roll: 0.0
            pitch: 0.0
            yaw: -0.8796897368538431
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07492455709238055
            roll: 0.0
            pitch: 0.0
            yaw: -0.9493189138420248
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08346862641841996
            roll: 0.0
            pitch: 0.0
            yaw: 0.6296246862606587
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0008327251986405691
              y: 0.01357638769157645
              z: 0.04275322921824774
              roll: 0.4661937129305651
              pitch: -0.47145238407532114
              yaw: 1.3357191004531652
            roll: 0.4789347461679028
            pitch: -0.49704267136347297
            yaw: 1.2949085754295615
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2004786326688188
          y: -0.19602544490639434
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3552431192308605
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.006657971809651192
            roll: 0.0
            pitch: 0.0
            yaw: -0.10182316728726179
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.020032348290543973
            roll: 0.0
            pitch: 0.0
            yaw: 0.0428464574928111
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.007945845530240435
            roll: 0.0
            pitch: 0.0
            yaw: -0.10564558742322863
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01636237355336574
            roll: 0.0
            pitch: 0.0
            yaw: 0.11715671693559448
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.010655337566264467
            roll: 0.0
            pitch: 0.0
            yaw: -0.018001119515472425
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.00855060888338869
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.004408793067228897
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07963567339578881
            roll: 0.0
            pitch: 0.0
            yaw: 0.6419658304486466
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.023089237009931332
            roll: 0.0
            pitch: 0.0
            yaw: -0.682125004321825
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.007112706652676007
            roll: 0.0
            pitch: 0.0
            yaw: 0.765369614346666
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.09564377489026038
            roll: 0.0
            pitch: 0.0
            yaw: -0.012383424391878783
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.009988105124306104
            roll: 0.0
            pitch: 0.0
            yaw: -0.9013219753512826
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06425050216633155
            roll: 0.0
            pitch: 0.0
            yaw: 0.2914205302804238
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0013192961861329335
              y: 0.01649827970438529
              z: 0.04269743518784017
              roll: 0.41358711864644104
              pitch: -0.5122549745389501
              yaw: 1.3289625918351813
            roll: 0.4698575101167534
            pitch: -0.49143744763284053
            yaw: 1.3512015794452195
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.26138443329693933
          y: -0.23807359847065596
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4583476545067132
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.022131221804168717
            roll: 0.0
            pitch: 0.0
            yaw: 0.022280824002612942
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010051627604680702
            roll: 0.0
            pitch: 0.0
            yaw: 0.10363644443124165
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.018967347117238145
            roll: 0.0
            pitch: 0.0
            yaw: -0.12644845959569087
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.015065770285993058
            roll: 0.0
            pitch: 0.0
            yaw: 0.10673006667637097
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01967815613090946
            roll: 0.0
            pitch: 0.0
            yaw: -0.12937225002924907
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04554389320262864
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.004548542194749983
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0762857312474848
            roll: 0.0
            pitch: 0.0
            yaw: 0.5137990618970509
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0035346621678055273
            roll: 0.0
            pitch: 0.0
            yaw: -0.7210821269049398
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02704278159066148
            roll: 0.0
            pitch: 0.0
            yaw: 0.8408935707953393
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05091428659473462
            roll: 0.0
            pitch: 0.0
            yaw: -0.7757998061362799
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08946228501596254
            roll: 0.0
            pitch: 0.0
            yaw: -0.3280069348374848
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06846711178876133
            roll: 0.0
            pitch: 0.0
            yaw: 0.8785811193272592
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0017268442083306628
              y: 0.013878922224094885
              z: 0.04329817447613561
              roll: 0.4297222738766319
              pitch: -0.45782952221285195
              yaw: 1.3494561374955125
            roll: 0.44508280866062144
            pitch: -0.5134097583476765
            yaw: 1.320069827938851
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
