scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2920330326886891
          y: -0.2877842847999565
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.21951542457064244
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.004693095888448063
            roll: 0.0
            pitch: 0.0
            yaw: -0.10464662564214382
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.021864624251769466
            roll: 0.0
            pitch: 0.0
            yaw: -0.017448930520035183
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0052538264561688315
            roll: 0.0
            pitch: 0.0
            yaw: -0.14057967252246958
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.020741358560270207
            roll: 0.0
            pitch: 0.0
            yaw: 0.12790081115268698
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.016148001245704688
            roll: 0.0
            pitch: 0.0
            yaw: 0.027357336231904866
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.007848358444674589
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04307793669065636
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.058096418014310675
            roll: 0.0
            pitch: 0.0
            yaw: -0.7825476859752074
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05478385063134053
            roll: 0.0
            pitch: 0.0
            yaw: 0.5748805099694678
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06012432936221372
            roll: 0.0
            pitch: 0.0
            yaw: -1.019029512226852
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.023947124063305777
            roll: 0.0
            pitch: 0.0
            yaw: 0.7362868225621253
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07268806601786891
            roll: 0.0
            pitch: 0.0
            yaw: -0.6851369338517252
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06982599788485608
            roll: 0.0
            pitch: 0.0
            yaw: 0.4502184866662915
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0019684289217817806
              y: 0.01722859074282305
              z: 0.042318148362052416
              roll: 0.47415722163249546
              pitch: -0.4488891259449496
              yaw: 1.3288395624350593
            roll: 0.4214805041734122
            pitch: -0.5074089204241781
            yaw: 1.3372990283066732
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.22458664133997946
          y: -0.1254561560411114
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.043057572628061314
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01339951615204951
            roll: 0.0
            pitch: 0.0
            yaw: -0.03549892363822249
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.004751893094178592
            roll: 0.0
            pitch: 0.0
            yaw: -0.06891832482355496
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0009777481415691007
            roll: 0.0
            pitch: 0.0
            yaw: 0.0932142522844705
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.009959483829923427
            roll: 0.0
            pitch: 0.0
            yaw: -0.14435158158256414
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.021774017171195335
            roll: 0.0
            pitch: 0.0
            yaw: 0.029122377276845135
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.018506222402040813
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04888843770737823
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.09126251376445887
            roll: 0.0
            pitch: 0.0
            yaw: 0.5574379532629521
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0806848461350784
            roll: 0.0
            pitch: 0.0
            yaw: -0.042139113408615314
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0671635923250915
            roll: 0.0
            pitch: 0.0
            yaw: -0.8497922949161246
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.038968496008112335
            roll: 0.0
            pitch: 0.0
            yaw: -0.9016444677918398
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.010456939317798952
            roll: 0.0
            pitch: 0.0
            yaw: -0.22527374701270508
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08628072927056236
            roll: 0.0
            pitch: 0.0
            yaw: -0.11415812942654191
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0012345789580491934
              y: 0.013448195785757568
              z: 0.04278397486511204
              roll: 0.4164373685690784
              pitch: -0.48927839292063124
              yaw: 1.2923387863074047
            roll: 0.4698327498934649
            pitch: -0.46681106836942854
            yaw: 1.3460351816938176
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.19194346272777962
          y: -0.12201044067566283
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.07914852042042886
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.00886536925192711
            roll: 0.0
            pitch: 0.0
            yaw: -0.11647757169462197
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0007858310530939987
            roll: 0.0
            pitch: 0.0
            yaw: 0.14700534661759268
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.020244047950885906
            roll: 0.0
            pitch: 0.0
            yaw: -0.06620101902009252
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0018293427965886677
            roll: 0.0
            pitch: 0.0
            yaw: 0.06335839322498199
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.001215871477278238
            roll: 0.0
            pitch: 0.0
            yaw: -0.12911860344018852
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02084936025970842
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0541664597820099
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08400202650792701
            roll: 0.0
            pitch: 0.0
            yaw: 0.897677843199461
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08834649947798551
            roll: 0.0
            pitch: 0.0
            yaw: 0.2746921748535647
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.034239979521857256
            roll: 0.0
            pitch: 0.0
            yaw: 0.3622780508177612
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.029932065698001914
            roll: 0.0
            pitch: 0.0
            yaw: 0.6849439770603021
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.03550997088197514
            roll: 0.0
            pitch: 0.0
            yaw: -0.6040370803653488
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06383570614790501
            roll: 0.0
            pitch: 0.0
            yaw: 0.024915495310144697
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0012456822306073177
              y: 0.01629284381389113
              z: 0.04271027667124185
              roll: 0.4032803501181796
              pitch: -0.4591797625939669
              yaw: 1.3210161115467745
            roll: 0.4726312294830334
            pitch: -0.47978523268346607
            yaw: 1.3443287729817293
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
