scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1440870875475187
          y: -0.1411587144896569
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.2108847378376586
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.010373197566707116
            roll: 0.0
            pitch: 0.0
            yaw: 0.08033541271633987
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.013793680776811597
            roll: 0.0
            pitch: 0.0
            yaw: 0.0343561649086957
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.012924564782527737
            roll: 0.0
            pitch: 0.0
            yaw: 0.048701633761458446
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.006818355046298035
            roll: 0.0
            pitch: 0.0
            yaw: 0.1596775989164193
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.002828672792963994
            roll: 0.0
            pitch: 0.0
            yaw: 0.15248917690347286
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.046319393640777806
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0417802983077772
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.007995111849959893
            roll: 0.0
            pitch: 0.0
            yaw: -0.8626029720947216
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07936743078513098
            roll: 0.0
            pitch: 0.0
            yaw: -0.804479589952548
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05395923248676133
            roll: 0.0
            pitch: 0.0
            yaw: -0.0013172008106758781
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.09130864177621996
            roll: 0.0
            pitch: 0.0
            yaw: -0.5610787812050211
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05859275212262875
            roll: 0.0
            pitch: 0.0
            yaw: 0.40825899434250634
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.029068769865248784
            roll: 0.0
            pitch: 0.0
            yaw: 0.9398989008106262
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00139170436150469
              y: 0.013987019703261347
              z: 0.041373614075301685
              roll: 0.45445566904429874
              pitch: -0.49296729319554977
              yaw: 1.3544364865898024
            roll: 0.42063662873710234
            pitch: -0.45270703983589167
            yaw: 1.303037912622271
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1453119915103248
          y: -0.2631313274415514
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.44179075601541784
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.008745081270920649
            roll: 0.0
            pitch: 0.0
            yaw: -0.05568114398057865
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006216404142537303
            roll: 0.0
            pitch: 0.0
            yaw: -0.11013235754140448
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.008135818936268408
            roll: 0.0
            pitch: 0.0
            yaw: -0.15098888268835794
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.003954357070395716
            roll: 0.0
            pitch: 0.0
            yaw: 0.08416338479805663
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.009535775765736193
            roll: 0.0
            pitch: 0.0
            yaw: 0.06756742844407848
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.010534283587183349
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.011787738556064659
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.03405109081539964
            roll: 0.0
            pitch: 0.0
            yaw: -0.21462683226131296
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.043724351202451495
            roll: 0.0
            pitch: 0.0
            yaw: 0.14996911375999566
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.027280879231864716
            roll: 0.0
            pitch: 0.0
            yaw: -0.7417632707468125
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05184735994941522
            roll: 0.0
            pitch: 0.0
            yaw: -0.3006128904309856
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.042491849660714016
            roll: 0.0
            pitch: 0.0
            yaw: 0.016396886887439344
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.025932666118873335
            roll: 0.0
            pitch: 0.0
            yaw: 0.06311087211540745
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0011764985208255964
              y: 0.015073857951239673
              z: 0.04058824838144599
              roll: 0.4431100052267586
              pitch: -0.4719954252255788
              yaw: 1.3322145790803666
            roll: 0.4508087966662215
            pitch: -0.4846567826644636
            yaw: 1.3637214611469186
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2214091394481399
          y: -0.25375265402376757
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.18137660838695124
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0067653244198787495
            roll: 0.0
            pitch: 0.0
            yaw: 0.05520296027636598
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.004800314006862087
            roll: 0.0
            pitch: 0.0
            yaw: 0.01888220307381369
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.013837113755035439
            roll: 0.0
            pitch: 0.0
            yaw: 0.03515511514532685
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.005280272040102143
            roll: 0.0
            pitch: 0.0
            yaw: 0.10653305590493983
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.005450016817681265
            roll: 0.0
            pitch: 0.0
            yaw: -0.1384098401393829
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03358318708855364
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.043426554383324364
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08254220174555318
            roll: 0.0
            pitch: 0.0
            yaw: -0.7707808197156923
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.040540838600528706
            roll: 0.0
            pitch: 0.0
            yaw: -0.758295036227511
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05432572956006418
            roll: 0.0
            pitch: 0.0
            yaw: 0.5152340681923293
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.040838128377931195
            roll: 0.0
            pitch: 0.0
            yaw: 0.06765627593577173
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.04494051196937632
            roll: 0.0
            pitch: 0.0
            yaw: -0.862140679561985
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.024793740029998637
            roll: 0.0
            pitch: 0.0
            yaw: 0.8401704821549967
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.00020439834967339587
              y: 0.016062505387560932
              z: 0.04134839244914528
              roll: 0.4416268632246051
              pitch: -0.4713575976564031
              yaw: 1.3531599493027031
            roll: 0.42326812781566914
            pitch: -0.5079202326825435
            yaw: 1.3206127457792098
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
