scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.24037078799264383
          y: -0.19030562565840636
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.29676836072859336
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015644554304537622
            roll: 0.0
            pitch: 0.0
            yaw: 0.0769271019611551
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.004743100622207404
            roll: 0.0
            pitch: 0.0
            yaw: -0.15295726862614364
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0046502771931374
            roll: 0.0
            pitch: 0.0
            yaw: 0.09165239206173337
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.016269695713165812
            roll: 0.0
            pitch: 0.0
            yaw: -0.013647960018484229
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.006393662530264941
            roll: 0.0
            pitch: 0.0
            yaw: 0.12275798883903588
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.059708370670848804
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.019933935714722975
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08002298822190498
            roll: 0.0
            pitch: 0.0
            yaw: -0.46533949175800904
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09268354030526293
            roll: 0.0
            pitch: 0.0
            yaw: -0.8376369392660032
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03974397700450891
            roll: 0.0
            pitch: 0.0
            yaw: 0.5502653132438924
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.050500909412006356
            roll: 0.0
            pitch: 0.0
            yaw: 0.7348192494802532
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.02933068154601312
            roll: 0.0
            pitch: 0.0
            yaw: 0.4564274600062499
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09280995049524048
            roll: 0.0
            pitch: 0.0
            yaw: 0.19763941261673046
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0015614921962131727
              y: 0.014002166795475765
              z: 0.043103531177830466
              roll: 0.4245660949397931
              pitch: -0.5184301389835021
              yaw: 1.3682357035943467
            roll: 0.47855968392745285
            pitch: -0.44011816631717016
            yaw: 1.2968926246967318
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.22926536626360708
          y: -0.2033557354822939
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.36453881990872705
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01834858963039214
            roll: 0.0
            pitch: 0.0
            yaw: -0.12769179042015447
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.00517938985944337
            roll: 0.0
            pitch: 0.0
            yaw: -0.16694902573921244
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.016469511838248567
            roll: 0.0
            pitch: 0.0
            yaw: -0.10978160309694576
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0192430938330699
            roll: 0.0
            pitch: 0.0
            yaw: 0.07836155515572996
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.004664098234618299
            roll: 0.0
            pitch: 0.0
            yaw: -0.05493188897920549
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0019647667554055018
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03831422144049018
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.005931910454839873
            roll: 0.0
            pitch: 0.0
            yaw: -0.9002939949337265
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.028751802433903614
            roll: 0.0
            pitch: 0.0
            yaw: 0.07329873973956191
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02025252042329756
            roll: 0.0
            pitch: 0.0
            yaw: -0.2542501392255757
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0731988940535902
            roll: 0.0
            pitch: 0.0
            yaw: -0.9974624326088661
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.047391212203076474
            roll: 0.0
            pitch: 0.0
            yaw: 0.9864605984903643
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04044073072002555
            roll: 0.0
            pitch: 0.0
            yaw: -0.8245242663636707
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0018417063902913442
              y: 0.015772451548075286
              z: 0.043871700414631065
              roll: 0.4657620526461134
              pitch: -0.4614033856642599
              yaw: 1.3084282008909431
            roll: 0.47752049540024577
            pitch: -0.4881979878119182
            yaw: 1.359520940098283
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.1719432686311931
          y: -0.29261296751913374
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.07147315855055492
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0012842467410902406
            roll: 0.0
            pitch: 0.0
            yaw: 4.5276470371835575e-05
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01759606531093979
            roll: 0.0
            pitch: 0.0
            yaw: 0.0013225893844476533
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0020344939308724434
            roll: 0.0
            pitch: 0.0
            yaw: -0.10321217922313693
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.011335557812419433
            roll: 0.0
            pitch: 0.0
            yaw: -0.0017537453262905511
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.015026951836988992
            roll: 0.0
            pitch: 0.0
            yaw: 0.03870155200785988
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03885174906132498
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0007497357642781352
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08424338690010366
            roll: 0.0
            pitch: 0.0
            yaw: -0.42038847829239356
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.019841143115548382
            roll: 0.0
            pitch: 0.0
            yaw: -0.8300633006931735
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07234736330397179
            roll: 0.0
            pitch: 0.0
            yaw: -0.7012471395307405
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03128191686208012
            roll: 0.0
            pitch: 0.0
            yaw: 0.31380825394144995
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.024654998793798594
            roll: 0.0
            pitch: 0.0
            yaw: -0.3025366919830891
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04343921524719014
            roll: 0.0
            pitch: 0.0
            yaw: -0.9029827008852251
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0015613618077071245
              y: 0.014317175854858234
              z: 0.04422124606700026
              roll: 0.4187401041122649
              pitch: -0.5078508195183608
              yaw: 1.3227582311973647
            roll: 0.4358015397966057
            pitch: -0.48518043548912587
            yaw: 1.344017815264529
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
