scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.29187227591504217
          y: -0.15989336978380403
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.10371826044774068
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0035930504518560252
            roll: 0.0
            pitch: 0.0
            yaw: 0.08477728721976507
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.023020442084116584
            roll: 0.0
            pitch: 0.0
            yaw: 0.1004920206551908
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.00454101647773698
            roll: 0.0
            pitch: 0.0
            yaw: 0.1016934346398814
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.00801298168409775
            roll: 0.0
            pitch: 0.0
            yaw: -0.02946716709466135
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01395908292522248
            roll: 0.0
            pitch: 0.0
            yaw: 0.10346515631885916
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.010695117631495457
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03939858927917292
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06559558420446165
            roll: 0.0
            pitch: 0.0
            yaw: 0.34546389082983
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05919938613680849
            roll: 0.0
            pitch: 0.0
            yaw: -0.15916473323643032
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09301287004450065
            roll: 0.0
            pitch: 0.0
            yaw: 0.6124112459046365
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.026870107162604018
            roll: 0.0
            pitch: 0.0
            yaw: -0.005197527482297515
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.019779428515490832
            roll: 0.0
            pitch: 0.0
            yaw: 0.04063882650283546
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.020574657830582363
            roll: 0.0
            pitch: 0.0
            yaw: 0.9582558144511768
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0015620850165979018
              y: 0.013962569228381568
              z: 0.041131770213876685
              roll: 0.42217050652550103
              pitch: -0.5212468749222059
              yaw: 1.2959165275529347
            roll: 0.4086352074943644
            pitch: -0.4544625549416192
            yaw: 1.315716959814825
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.10661735377828925
          y: -0.15028697097577098
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4443818548222864
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.017114272855927183
            roll: 0.0
            pitch: 0.0
            yaw: 0.019247820868534105
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006316137318455317
            roll: 0.0
            pitch: 0.0
            yaw: 0.06075108018011402
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.006264513684005008
            roll: 0.0
            pitch: 0.0
            yaw: 0.07352102083570386
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.007695738437505432
            roll: 0.0
            pitch: 0.0
            yaw: 0.023833387689580543
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.010798873029597152
            roll: 0.0
            pitch: 0.0
            yaw: -0.06297939441557042
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02269885800580168
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03908342634944301
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04054803978958741
            roll: 0.0
            pitch: 0.0
            yaw: 0.9862143518660569
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08957934203810548
            roll: 0.0
            pitch: 0.0
            yaw: 0.5851783802088533
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07462459870389498
            roll: 0.0
            pitch: 0.0
            yaw: 1.0460814966823195
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03962970137437967
            roll: 0.0
            pitch: 0.0
            yaw: -0.41314961172381814
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07574361853546593
            roll: 0.0
            pitch: 0.0
            yaw: 1.0099593123562796
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.027816201045407926
            roll: 0.0
            pitch: 0.0
            yaw: 0.6103345352395961
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00010099769783794219
              y: 0.017000637894519315
              z: 0.04169702145476856
              roll: 0.4072598285798193
              pitch: -0.47258027856411505
              yaw: 1.3067665975408658
            roll: 0.4423974416406185
            pitch: -0.47738937269330506
            yaw: 1.3154227464444366
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.19086888253481177
          y: -0.12901679085520162
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.42446173168460677
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0008718434915379603
            roll: 0.0
            pitch: 0.0
            yaw: -0.0025998948543182188
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0005327466867745996
            roll: 0.0
            pitch: 0.0
            yaw: -0.16762684068899383
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.013351721351064341
            roll: 0.0
            pitch: 0.0
            yaw: -0.09561493310904225
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.004550802572051045
            roll: 0.0
            pitch: 0.0
            yaw: -0.001618282694123785
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.020379185050906502
            roll: 0.0
            pitch: 0.0
            yaw: -0.10836667472558374
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.012249029175037743
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.057436963210984245
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07338967177035874
            roll: 0.0
            pitch: 0.0
            yaw: 0.7237433535294857
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.03331145313876108
            roll: 0.0
            pitch: 0.0
            yaw: 1.0063295548583022
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.025152307463146076
            roll: 0.0
            pitch: 0.0
            yaw: -0.3333840680092516
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.011508073668733979
            roll: 0.0
            pitch: 0.0
            yaw: 0.03259984789619397
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.046862123842850795
            roll: 0.0
            pitch: 0.0
            yaw: -0.1421719606580938
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0015716401925442713
            roll: 0.0
            pitch: 0.0
            yaw: 0.15860851646651208
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0010513822777173444
              y: 0.016243333758722753
              z: 0.04147414646662946
              roll: 0.4332457496723359
              pitch: -0.511152460881357
              yaw: 1.3667981798429631
            roll: 0.4217738238541378
            pitch: -0.5145449542922147
            yaw: 1.3440567749301198
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
