scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.14503459890020418
          y: -0.2340995312408951
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.1338115497630209
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0010062703651833385
            roll: 0.0
            pitch: 0.0
            yaw: -0.1380497183763496
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.018691904404321197
            roll: 0.0
            pitch: 0.0
            yaw: 0.09462913545172091
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.010555913684877467
            roll: 0.0
            pitch: 0.0
            yaw: -0.15624051899929509
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.005418897612427611
            roll: 0.0
            pitch: 0.0
            yaw: -0.16550767902651958
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.019544737141613797
            roll: 0.0
            pitch: 0.0
            yaw: 0.13932974706289203
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.004819300787905767
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03858087552854375
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.018904811234883384
            roll: 0.0
            pitch: 0.0
            yaw: -1.0239916130822417
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.01768304317709181
            roll: 0.0
            pitch: 0.0
            yaw: -0.5218802655735776
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06686407355895768
            roll: 0.0
            pitch: 0.0
            yaw: 0.2369218197660663
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07284709118226212
            roll: 0.0
            pitch: 0.0
            yaw: -0.7885446424053472
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0015592935571923372
            roll: 0.0
            pitch: 0.0
            yaw: -0.1808383424108161
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07215136315866735
            roll: 0.0
            pitch: 0.0
            yaw: -0.5393858456936935
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0011565676780288846
              y: 0.0136330237059382
              z: 0.04057920926019279
              roll: 0.42838693160086716
              pitch: -0.4628494350482265
              yaw: 1.3525411995998948
            roll: 0.47112415154644627
            pitch: -0.5194172471150733
            yaw: 1.363327503623205
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2316141670108276
          y: -0.2807730279010134
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3928857780964309
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0222734454033996
            roll: 0.0
            pitch: 0.0
            yaw: 0.17493001498517208
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01744679257102851
            roll: 0.0
            pitch: 0.0
            yaw: -0.0020327419363335986
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.015970477139217246
            roll: 0.0
            pitch: 0.0
            yaw: -0.1551528612507443
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013674449574879788
            roll: 0.0
            pitch: 0.0
            yaw: 0.08468316523530794
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.002147166373896916
            roll: 0.0
            pitch: 0.0
            yaw: 0.15463262831411012
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.025710794454462595
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03748729191651225
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07616048636765091
            roll: 0.0
            pitch: 0.0
            yaw: 0.5988909452279427
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.009940230512860318
            roll: 0.0
            pitch: 0.0
            yaw: -0.24264279857346094
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.028207907667966478
            roll: 0.0
            pitch: 0.0
            yaw: -0.7735126464635597
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.020292793692824176
            roll: 0.0
            pitch: 0.0
            yaw: -0.7313362956237015
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06344393701228995
            roll: 0.0
            pitch: 0.0
            yaw: -0.273172267384011
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07690489925277738
            roll: 0.0
            pitch: 0.0
            yaw: 0.4370652541217528
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0017492561842003362
              y: 0.017175033061333604
              z: 0.04405979333447658
              roll: 0.47918786200030183
              pitch: -0.4439780791304538
              yaw: 1.3055446445462546
            roll: 0.4088650372390145
            pitch: -0.47878947174203446
            yaw: 1.327408612962014
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2684888600226152
          y: -0.2507164609556605
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.47290205691829634
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.020864031600110772
            roll: 0.0
            pitch: 0.0
            yaw: 0.029968602911372988
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01646299421908181
            roll: 0.0
            pitch: 0.0
            yaw: 0.16345992608212612
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0133516706877009
            roll: 0.0
            pitch: 0.0
            yaw: -0.06442115213499003
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.011823556836935926
            roll: 0.0
            pitch: 0.0
            yaw: 0.1272479658802539
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01285357657006407
            roll: 0.0
            pitch: 0.0
            yaw: 0.14307742614875435
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.053693460058318536
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04567798877278591
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05036168746381847
            roll: 0.0
            pitch: 0.0
            yaw: -0.4539912328188239
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.032376223225854525
            roll: 0.0
            pitch: 0.0
            yaw: 0.1544039869756919
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06907686033590472
            roll: 0.0
            pitch: 0.0
            yaw: -0.6686712273781408
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0806207703887817
            roll: 0.0
            pitch: 0.0
            yaw: 0.9335051544361772
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.002420064837630534
            roll: 0.0
            pitch: 0.0
            yaw: -0.5371286830862413
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05193363559162398
            roll: 0.0
            pitch: 0.0
            yaw: 1.0206038810709084
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0013017524944770728
              y: 0.014501996931707327
              z: 0.04310324868666453
              roll: 0.4122666827050168
              pitch: -0.4835165230078751
              yaw: 1.357048922163934
            roll: 0.44304614268277764
            pitch: -0.44377136481268015
            yaw: 1.3611336126948832
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
