scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1464309157673331
          y: -0.25159769721674635
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.2931683234772148
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01469229182059416
            roll: 0.0
            pitch: 0.0
            yaw: 0.11129971856840776
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006773992140780208
            roll: 0.0
            pitch: 0.0
            yaw: -0.07325141405832082
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.016517542023262617
            roll: 0.0
            pitch: 0.0
            yaw: -0.12090118967366012
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01690910088575126
            roll: 0.0
            pitch: 0.0
            yaw: 0.04083418519172158
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.004756498136762852
            roll: 0.0
            pitch: 0.0
            yaw: -0.050715682209565585
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04108510266058109
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.046863136709993244
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06635536975235516
            roll: 0.0
            pitch: 0.0
            yaw: -0.6715837876471705
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08689655924832973
            roll: 0.0
            pitch: 0.0
            yaw: -0.4851443078446064
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08070917959326687
            roll: 0.0
            pitch: 0.0
            yaw: 0.24999476783528451
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05292938305687309
            roll: 0.0
            pitch: 0.0
            yaw: 0.34318809459588717
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.020157419994369985
            roll: 0.0
            pitch: 0.0
            yaw: -0.7690199668544543
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09592262906418396
            roll: 0.0
            pitch: 0.0
            yaw: 0.7637954990253915
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0015220993063294642
              y: 0.016258928152274615
              z: 0.04189582036733068
              roll: 0.4508717587017371
              pitch: -0.5003009196400983
              yaw: 1.32465148216545
            roll: 0.4760272540801035
            pitch: -0.48986468087574364
            yaw: 1.3228059419719056
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.10374027698022868
          y: -0.1419643688663697
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.016211907004683668
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.011648101662174452
            roll: 0.0
            pitch: 0.0
            yaw: -0.1316870462955215
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0024061838055115525
            roll: 0.0
            pitch: 0.0
            yaw: -0.14111462281357662
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.015670728754652127
            roll: 0.0
            pitch: 0.0
            yaw: -0.03107863909069647
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.004073564384104975
            roll: 0.0
            pitch: 0.0
            yaw: 0.0022823216951316228
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.00733661816660912
            roll: 0.0
            pitch: 0.0
            yaw: -0.018117096569200103
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03684838344213856
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.009396873394800526
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.00920661208862128
            roll: 0.0
            pitch: 0.0
            yaw: -0.2754297660005772
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.005668840284634186
            roll: 0.0
            pitch: 0.0
            yaw: 0.46551840465530514
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.046807520471642466
            roll: 0.0
            pitch: 0.0
            yaw: -0.2544489208055011
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.02498430432903445
            roll: 0.0
            pitch: 0.0
            yaw: 0.10951729271824173
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.002946909789689464
            roll: 0.0
            pitch: 0.0
            yaw: 0.42182263174915224
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.029083945506526848
            roll: 0.0
            pitch: 0.0
            yaw: -0.27926992562444763
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0006911669074119667
              y: 0.01615975473502174
              z: 0.044427786217574095
              roll: 0.42467348558721885
              pitch: -0.496056655085116
              yaw: 1.3521371139312692
            roll: 0.40963673075052365
            pitch: -0.471266005508077
            yaw: 1.3101738001780092
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.289448945830154
          y: -0.2530953079241474
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.06350774219638666
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.001790989962120234
            roll: 0.0
            pitch: 0.0
            yaw: -0.10048925314747324
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006678116727533007
            roll: 0.0
            pitch: 0.0
            yaw: -0.08881797725849215
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.007057043220097859
            roll: 0.0
            pitch: 0.0
            yaw: 0.16359263488229248
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.010421381479515724
            roll: 0.0
            pitch: 0.0
            yaw: 0.09578475427142957
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.012640027682303705
            roll: 0.0
            pitch: 0.0
            yaw: -0.03860507467251159
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.005945792941353306
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03843171313630095
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08756132743696068
            roll: 0.0
            pitch: 0.0
            yaw: 0.7494432558508055
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09053642187069016
            roll: 0.0
            pitch: 0.0
            yaw: -0.7683766811593262
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.038532791774930936
            roll: 0.0
            pitch: 0.0
            yaw: -0.1270781059905206
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.040198135072753244
            roll: 0.0
            pitch: 0.0
            yaw: -0.9867018338033364
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03468982118664418
            roll: 0.0
            pitch: 0.0
            yaw: -0.4081565495002526
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.024357326711197794
            roll: 0.0
            pitch: 0.0
            yaw: -0.724321452875714
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0012445700290174958
              y: 0.016866525235817803
              z: 0.04307009527806408
              roll: 0.45319823860325686
              pitch: -0.4552213422542023
              yaw: 1.2930869814060888
            roll: 0.45476898621689316
            pitch: -0.492400968075981
            yaw: 1.3085741413206895
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
