scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.22172510426679312
          y: -0.15455662109632734
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.1875374686663065
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01853668411515498
            roll: 0.0
            pitch: 0.0
            yaw: -0.11225836623784147
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.015224703279658209
            roll: 0.0
            pitch: 0.0
            yaw: -0.15428619096965684
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.00975952235751159
            roll: 0.0
            pitch: 0.0
            yaw: -0.14511803503121348
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0020082460368145948
            roll: 0.0
            pitch: 0.0
            yaw: 0.048765428356054547
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.011753875665399566
            roll: 0.0
            pitch: 0.0
            yaw: -0.13398253682017097
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.017273022217988945
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.018908178973863668
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.008923888608820749
            roll: 0.0
            pitch: 0.0
            yaw: -0.23823137969980968
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.010665194901613342
            roll: 0.0
            pitch: 0.0
            yaw: 0.34120269460128605
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05788859518111232
            roll: 0.0
            pitch: 0.0
            yaw: -0.8069523719435939
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06237483177208246
            roll: 0.0
            pitch: 0.0
            yaw: -0.9678097716472932
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06216109350797311
            roll: 0.0
            pitch: 0.0
            yaw: -0.6698001576661721
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04427625119191814
            roll: 0.0
            pitch: 0.0
            yaw: -0.6412084468637798
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0014243302883984925
              y: 0.016007379477809277
              z: 0.04247146337260483
              roll: 0.41922686612867477
              pitch: -0.45722947142081205
              yaw: 1.3482826939307404
            roll: 0.4530702275940748
            pitch: -0.48699796670763495
            yaw: 1.3567838683118367
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2506295544199886
          y: -0.27154650270410147
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.26936412021147416
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.019794701775065017
            roll: 0.0
            pitch: 0.0
            yaw: -0.1584240677652384
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008794137661974354
            roll: 0.0
            pitch: 0.0
            yaw: -0.1677358462488943
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0003216070799759545
            roll: 0.0
            pitch: 0.0
            yaw: -0.01578725344907475
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01906792430880065
            roll: 0.0
            pitch: 0.0
            yaw: -0.04445946607978396
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.02049397828327402
            roll: 0.0
            pitch: 0.0
            yaw: 0.14366706123150785
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04196530400501448
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.010181846889640148
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05645153995774349
            roll: 0.0
            pitch: 0.0
            yaw: 0.41547926785719547
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04697524466002331
            roll: 0.0
            pitch: 0.0
            yaw: -0.6342963581228709
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02623981795707507
            roll: 0.0
            pitch: 0.0
            yaw: -0.27016223745327417
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08347227206741406
            roll: 0.0
            pitch: 0.0
            yaw: 0.4015508856537786
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.018313463575273553
            roll: 0.0
            pitch: 0.0
            yaw: 0.19442794477853442
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04185711944926922
            roll: 0.0
            pitch: 0.0
            yaw: -0.0955899861715035
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00024598908810749163
              y: 0.014911855073700735
              z: 0.043895061236710234
              roll: 0.43814831628677625
              pitch: -0.5046229463584744
              yaw: 1.3338331538344015
            roll: 0.4224470503462527
            pitch: -0.4565949952980612
            yaw: 1.3175649448956717
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.16807934932732427
          y: -0.21962657880138178
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.1758383291893333
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.022170405068982872
            roll: 0.0
            pitch: 0.0
            yaw: 0.08434861824623935
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.009601178393651771
            roll: 0.0
            pitch: 0.0
            yaw: 0.02386637095631075
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01749086218623149
            roll: 0.0
            pitch: 0.0
            yaw: 0.15283646146432733
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.020801097163423172
            roll: 0.0
            pitch: 0.0
            yaw: -0.15941992459206938
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0029890812210471712
            roll: 0.0
            pitch: 0.0
            yaw: 0.16333285344362725
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05124064522499296
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05356890407004908
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.030774247122128118
            roll: 0.0
            pitch: 0.0
            yaw: -0.6120490473710569
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05281556377099547
            roll: 0.0
            pitch: 0.0
            yaw: 1.0416973235853526
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.00985253042577991
            roll: 0.0
            pitch: 0.0
            yaw: 0.5952147035903601
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.018037521657669517
            roll: 0.0
            pitch: 0.0
            yaw: -0.3707798597408398
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03140607069410731
            roll: 0.0
            pitch: 0.0
            yaw: 0.6483925929112544
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03899842037192394
            roll: 0.0
            pitch: 0.0
            yaw: -0.42184130722340873
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0018204006467183848
              y: 0.0167277933902482
              z: 0.04230164125802247
              roll: 0.47388093934066733
              pitch: -0.4576756589339806
              yaw: 1.3267181970443351
            roll: 0.46225267721325947
            pitch: -0.4763238691167737
            yaw: 1.2907199727074075
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
