scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1888374751938881
          y: -0.25620356441046555
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.42846466429323615
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.02091980035617844
            roll: 0.0
            pitch: 0.0
            yaw: -0.14234238147282446
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.015321497257440116
            roll: 0.0
            pitch: 0.0
            yaw: -0.13839096440737964
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.009278651227281259
            roll: 0.0
            pitch: 0.0
            yaw: -0.09915728171524447
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.005099073236230132
            roll: 0.0
            pitch: 0.0
            yaw: -0.054465926429791284
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01811443032297523
            roll: 0.0
            pitch: 0.0
            yaw: -0.11816635841801637
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02420838030176943
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.007228457295916632
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07049064392522358
            roll: 0.0
            pitch: 0.0
            yaw: -0.8062897171501755
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.005856934579447123
            roll: 0.0
            pitch: 0.0
            yaw: 0.13241870067081374
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05400761845693697
            roll: 0.0
            pitch: 0.0
            yaw: 0.26985026032889814
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0003046718216147132
            roll: 0.0
            pitch: 0.0
            yaw: 0.1195953958889675
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.007021427397863322
            roll: 0.0
            pitch: 0.0
            yaw: 0.03268085452843805
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04979917706074406
            roll: 0.0
            pitch: 0.0
            yaw: -0.36803333650663517
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0015223006608556951
              y: 0.014305995494150727
              z: 0.04286257155818929
              roll: 0.41763911443119117
              pitch: -0.4902452929620765
              yaw: 1.3687750322970067
            roll: 0.46577964255542925
            pitch: -0.465494648960165
            yaw: 1.3611512915365014
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.14843533544561763
          y: -0.11627377919726437
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.282510219830551
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015690856002599368
            roll: 0.0
            pitch: 0.0
            yaw: 0.09376475812200752
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.014851847660396282
            roll: 0.0
            pitch: 0.0
            yaw: 0.12601096846999638
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.014785590489793672
            roll: 0.0
            pitch: 0.0
            yaw: 0.15497633046528475
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 2.0718029126287618e-05
            roll: 0.0
            pitch: 0.0
            yaw: -0.06633621052460163
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0162339507073496
            roll: 0.0
            pitch: 0.0
            yaw: 0.0027227065824520225
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.026461205396537055
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.013304705343907791
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.04012812302579272
            roll: 0.0
            pitch: 0.0
            yaw: 0.5108218708720083
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0865944587833789
            roll: 0.0
            pitch: 0.0
            yaw: -0.3998447656850628
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07978555076105663
            roll: 0.0
            pitch: 0.0
            yaw: 0.504438601638949
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06012827228016398
            roll: 0.0
            pitch: 0.0
            yaw: 0.24172194807172342
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05021761950686842
            roll: 0.0
            pitch: 0.0
            yaw: -0.2708991774089121
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08042716788614394
            roll: 0.0
            pitch: 0.0
            yaw: -0.7710949037894982
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0011339210585726463
              y: 0.01600101270619874
              z: 0.040987111679056845
              roll: 0.4419480700270057
              pitch: -0.47316080470449634
              yaw: 1.3437223079480376
            roll: 0.41032785350855533
            pitch: -0.49527151823152593
            yaw: 1.294572628081229
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.11909403912950248
          y: -0.28743179132988705
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.20352503632551422
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.005797114895150751
            roll: 0.0
            pitch: 0.0
            yaw: -0.1708286997659108
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01649505012388367
            roll: 0.0
            pitch: 0.0
            yaw: 0.09721542446581921
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0020555156089777475
            roll: 0.0
            pitch: 0.0
            yaw: 0.02110068627837347
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0028950896696023527
            roll: 0.0
            pitch: 0.0
            yaw: 0.06104904589898896
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 7.108173332207729e-05
            roll: 0.0
            pitch: 0.0
            yaw: 0.08057503383907605
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.001592668489914989
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02903149513545472
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07448962550159824
            roll: 0.0
            pitch: 0.0
            yaw: 1.014234573370245
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.042494536134730136
            roll: 0.0
            pitch: 0.0
            yaw: 0.011435472012566006
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.053146607584484
            roll: 0.0
            pitch: 0.0
            yaw: -0.9340408132307795
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.07385447243145007
            roll: 0.0
            pitch: 0.0
            yaw: -0.9625736157149996
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.043863523822414846
            roll: 0.0
            pitch: 0.0
            yaw: 0.002267262617097643
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06667845338163456
            roll: 0.0
            pitch: 0.0
            yaw: -0.1593707868339166
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0011055176712169656
              y: 0.01460727624428182
              z: 0.04197344382306515
              roll: 0.4813432959410877
              pitch: -0.5091612286324192
              yaw: 1.357563863740063
            roll: 0.475276324766271
            pitch: -0.45135308151779796
            yaw: 1.334054827276815
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
