scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.20037708128767479
          y: -0.24965719885442936
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.10247609659596246
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015447423965341621
            roll: 0.0
            pitch: 0.0
            yaw: 0.11797329623748287
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01830144900603637
            roll: 0.0
            pitch: 0.0
            yaw: 0.09539687730809865
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.002548770855645449
            roll: 0.0
            pitch: 0.0
            yaw: 0.155051031774257
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0008688200483665288
            roll: 0.0
            pitch: 0.0
            yaw: -0.1450946436282303
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.020346636210446127
            roll: 0.0
            pitch: 0.0
            yaw: 0.08366225535501792
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03731274056379237
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.017276760024805014
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07768971589328297
            roll: 0.0
            pitch: 0.0
            yaw: -0.5349270479979382
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0778650027053896
            roll: 0.0
            pitch: 0.0
            yaw: -0.6955271823427109
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04036136243118249
            roll: 0.0
            pitch: 0.0
            yaw: -0.595435416475327
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.06693057826840179
            roll: 0.0
            pitch: 0.0
            yaw: -0.7190207382557972
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.047066264098463484
            roll: 0.0
            pitch: 0.0
            yaw: 0.9966919371968468
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07747923200674064
            roll: 0.0
            pitch: 0.0
            yaw: -0.7621596551679306
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0019910310512452575
              y: 0.014141022776997737
              z: 0.044073745226845054
              roll: 0.40989624458034163
              pitch: -0.4439884288988951
              yaw: 1.3498657175938091
            roll: 0.42334317185280046
            pitch: -0.5053950402714644
            yaw: 1.2965691933493526
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1325551859962312
          y: -0.23241947147859032
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4000015032048717
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01470293156822846
            roll: 0.0
            pitch: 0.0
            yaw: -0.04877549551189164
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010062234417789293
            roll: 0.0
            pitch: 0.0
            yaw: 0.07057331797515357
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.011134433534849605
            roll: 0.0
            pitch: 0.0
            yaw: -0.06862311711982015
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.004259656611455814
            roll: 0.0
            pitch: 0.0
            yaw: -0.04451593846376145
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.005736264623005107
            roll: 0.0
            pitch: 0.0
            yaw: -0.15223592179450116
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0559048383410548
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.016528221624662345
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05079268054426704
            roll: 0.0
            pitch: 0.0
            yaw: 0.029041377101123533
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07140860760225232
            roll: 0.0
            pitch: 0.0
            yaw: 0.49499362400638525
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.006186741726012163
            roll: 0.0
            pitch: 0.0
            yaw: 0.8634031109951381
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09271611358033494
            roll: 0.0
            pitch: 0.0
            yaw: -0.7229647011127724
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.047700569948796456
            roll: 0.0
            pitch: 0.0
            yaw: -0.5868193950083518
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07560203322110248
            roll: 0.0
            pitch: 0.0
            yaw: 0.32161674415475683
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0013562675113676418
              y: 0.015526075922608254
              z: 0.043567636685740464
              roll: 0.446987752574833
              pitch: -0.48407114264225376
              yaw: 1.2928449621621159
            roll: 0.45731492645506605
            pitch: -0.44676324332759104
            yaw: 1.3136288831661644
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.292543361846261
          y: -0.21162912247729
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4661083576978605
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01678823147169184
            roll: 0.0
            pitch: 0.0
            yaw: -0.015178996739714984
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.005678765427555389
            roll: 0.0
            pitch: 0.0
            yaw: 0.08598053960662683
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0043762402514648975
            roll: 0.0
            pitch: 0.0
            yaw: -0.09410069625449123
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.02071919404690425
            roll: 0.0
            pitch: 0.0
            yaw: -0.0722633035864916
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.007612783418313989
            roll: 0.0
            pitch: 0.0
            yaw: 0.008166540461832184
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.013621052233140064
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.02863350700479577
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07426990795817151
            roll: 0.0
            pitch: 0.0
            yaw: 0.7423984366085055
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09220247831925692
            roll: 0.0
            pitch: 0.0
            yaw: -0.5415287006420862
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07817776136431574
            roll: 0.0
            pitch: 0.0
            yaw: 1.0129176649417746
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.026752579041312938
            roll: 0.0
            pitch: 0.0
            yaw: -0.6791159284784289
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.04033218737576131
            roll: 0.0
            pitch: 0.0
            yaw: -0.47072598120051545
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.02362630146824375
            roll: 0.0
            pitch: 0.0
            yaw: -0.16113722343730963
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.001582178747948935
              y: 0.015647648378881385
              z: 0.041638769124903004
              roll: 0.40446518708118145
              pitch: -0.45355350649717885
              yaw: 1.336831293070087
            roll: 0.43545537730376493
            pitch: -0.49103398667538084
            yaw: 1.3156050521243352
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
