scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.14859960677802042
          y: -0.19392706707967633
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.22956691091165682
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0053298133181899805
            roll: 0.0
            pitch: 0.0
            yaw: -0.07996267549036465
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.009112062366350135
            roll: 0.0
            pitch: 0.0
            yaw: 0.17063076654157955
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.009367054325409482
            roll: 0.0
            pitch: 0.0
            yaw: 0.1693545602365068
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.019171636934378296
            roll: 0.0
            pitch: 0.0
            yaw: -0.1027469224630301
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.010570057770538224
            roll: 0.0
            pitch: 0.0
            yaw: 0.022816641522903025
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.037496625915266014
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04215620313533376
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.002152647985723302
            roll: 0.0
            pitch: 0.0
            yaw: -0.5403916259997633
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0024696561198284395
            roll: 0.0
            pitch: 0.0
            yaw: -0.6456270367952959
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0009140460822013169
            roll: 0.0
            pitch: 0.0
            yaw: 1.0419967815659603
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.07176679435597054
            roll: 0.0
            pitch: 0.0
            yaw: 0.6833392578732429
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.011135423871062936
            roll: 0.0
            pitch: 0.0
            yaw: -0.47704808362081863
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.02952504318454728
            roll: 0.0
            pitch: 0.0
            yaw: -0.47128880839788845
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00024208557049373034
              y: 0.01709307473731306
              z: 0.042708123615173475
              roll: 0.43519055940495
              pitch: -0.4930507518944615
              yaw: 1.331610641736968
            roll: 0.42221433247378864
            pitch: -0.510495206784058
            yaw: 1.365541697794111
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.14503459890020418
          y: -0.2340995312408951
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.1338115497630209
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0010062703651833385
            roll: 0.0
            pitch: 0.0
            yaw: -0.1380497183763496
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.018691904404321197
            roll: 0.0
            pitch: 0.0
            yaw: 0.09462913545172091
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.010555913684877467
            roll: 0.0
            pitch: 0.0
            yaw: -0.15624051899929509
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.005418897612427611
            roll: 0.0
            pitch: 0.0
            yaw: -0.16550767902651958
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.019544737141613797
            roll: 0.0
            pitch: 0.0
            yaw: 0.13932974706289203
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.004819300787905767
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03858087552854375
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.018904811234883384
            roll: 0.0
            pitch: 0.0
            yaw: -1.0239916130822417
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.01768304317709181
            roll: 0.0
            pitch: 0.0
            yaw: -0.5218802655735776
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06686407355895768
            roll: 0.0
            pitch: 0.0
            yaw: 0.2369218197660663
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07284709118226212
            roll: 0.0
            pitch: 0.0
            yaw: -0.7885446424053472
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0015592935571923372
            roll: 0.0
            pitch: 0.0
            yaw: -0.1808383424108161
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07215136315866735
            roll: 0.0
            pitch: 0.0
            yaw: -0.5393858456936935
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00034509464641827676
              y: 0.01710637200609733
              z: 0.04417031697327948
              roll: 0.4803165512881967
              pitch: -0.5208108903716452
              yaw: 1.3694440553488243
            roll: 0.47112415154644627
            pitch: -0.5194172471150733
            yaw: 1.363327503623205
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.21993290758151096
          y: -0.2954958176066606
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.29655449072818973
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0198258510734773
            roll: 0.0
            pitch: 0.0
            yaw: 0.13141942601131112
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0003255111957897669
            roll: 0.0
            pitch: 0.0
            yaw: -0.025087720464930796
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.015960101839620898
            roll: 0.0
            pitch: 0.0
            yaw: 0.022663107871804672
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.015262128896435856
            roll: 0.0
            pitch: 0.0
            yaw: 0.10839542040936023
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.018038948850566873
            roll: 0.0
            pitch: 0.0
            yaw: -0.14220007507287263
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.016905964180504204
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.019738012366152108
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08251804730602157
            roll: 0.0
            pitch: 0.0
            yaw: 0.3014125971092887
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04980339836075656
            roll: 0.0
            pitch: 0.0
            yaw: -0.5001841123243357
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.006118481326196232
            roll: 0.0
            pitch: 0.0
            yaw: 0.5736792024013022
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.004670001437475035
            roll: 0.0
            pitch: 0.0
            yaw: -0.8588304968682364
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.022221096656377004
            roll: 0.0
            pitch: 0.0
            yaw: -0.6735723136092495
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.005471209705202276
            roll: 0.0
            pitch: 0.0
            yaw: -0.9673092554344828
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0009013600556852038
              y: 0.01448238716915889
              z: 0.041819939026050766
              roll: 0.41015634022426056
              pitch: -0.5022148859907559
              yaw: 1.3099659535463957
            roll: 0.4195938020441776
            pitch: -0.49986550550759007
            yaw: 1.3152828324382557
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
