scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.16769526666107365
          y: -0.2921444594400922
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.09751747194232119
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.003768753610363093
            roll: 0.0
            pitch: 0.0
            yaw: -0.15737434902270456
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.008493658379818057
            roll: 0.0
            pitch: 0.0
            yaw: 0.15428972892367315
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.005420410839098673
            roll: 0.0
            pitch: 0.0
            yaw: -0.12699967588652628
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013749831301881288
            roll: 0.0
            pitch: 0.0
            yaw: 0.044473801790473805
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -5.5816616860080576e-05
            roll: 0.0
            pitch: 0.0
            yaw: -0.15455304560720784
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04001033378769737
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.023004064911621824
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0207450017087486
            roll: 0.0
            pitch: 0.0
            yaw: 0.6730318872495724
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09132929460475038
            roll: 0.0
            pitch: 0.0
            yaw: -0.7139045067035843
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.049586353060623756
            roll: 0.0
            pitch: 0.0
            yaw: 0.50811392540806
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.011671530432781407
            roll: 0.0
            pitch: 0.0
            yaw: -0.36805407795479483
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.059817647793752475
            roll: 0.0
            pitch: 0.0
            yaw: -0.5431627364706777
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.018529594093490726
            roll: 0.0
            pitch: 0.0
            yaw: 0.6565565894044771
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0008584018319959109
              y: 0.015514734756363398
              z: 0.043956144551395106
              roll: 0.4635572739457009
              pitch: -0.4897678254197
              yaw: 1.290307142996122
            roll: 0.4611619023079606
            pitch: -0.442497964540845
            yaw: 1.3662070531227526
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2004786326688188
          y: -0.19602544490639434
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3552431192308605
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.006657971809651192
            roll: 0.0
            pitch: 0.0
            yaw: -0.10182316728726179
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.020032348290543973
            roll: 0.0
            pitch: 0.0
            yaw: 0.0428464574928111
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.007945845530240435
            roll: 0.0
            pitch: 0.0
            yaw: -0.10564558742322863
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01636237355336574
            roll: 0.0
            pitch: 0.0
            yaw: 0.11715671693559448
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.010655337566264467
            roll: 0.0
            pitch: 0.0
            yaw: -0.018001119515472425
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.00855060888338869
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.004408793067228897
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07963567339578881
            roll: 0.0
            pitch: 0.0
            yaw: 0.6419658304486466
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.023089237009931332
            roll: 0.0
            pitch: 0.0
            yaw: -0.682125004321825
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.007112706652676007
            roll: 0.0
            pitch: 0.0
            yaw: 0.765369614346666
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.09564377489026038
            roll: 0.0
            pitch: 0.0
            yaw: -0.012383424391878783
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.009988105124306104
            roll: 0.0
            pitch: 0.0
            yaw: -0.9013219753512826
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06425050216633155
            roll: 0.0
            pitch: 0.0
            yaw: 0.2914205302804238
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0012815827965741186
              y: 0.013998948950996907
              z: 0.04277224251730381
              roll: 0.45569331186390544
              pitch: -0.4721586446356956
              yaw: 1.3498898559255232
            roll: 0.4698575101167534
            pitch: -0.49143744763284053
            yaw: 1.3512015794452195
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.16807934932732427
          y: -0.21962657880138178
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.1758383291893333
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.022170405068982872
            roll: 0.0
            pitch: 0.0
            yaw: 0.08434861824623935
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.009601178393651771
            roll: 0.0
            pitch: 0.0
            yaw: 0.02386637095631075
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01749086218623149
            roll: 0.0
            pitch: 0.0
            yaw: 0.15283646146432733
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.020801097163423172
            roll: 0.0
            pitch: 0.0
            yaw: -0.15941992459206938
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0029890812210471712
            roll: 0.0
            pitch: 0.0
            yaw: 0.16333285344362725
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05124064522499296
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05356890407004908
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.030774247122128118
            roll: 0.0
            pitch: 0.0
            yaw: -0.6120490473710569
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05281556377099547
            roll: 0.0
            pitch: 0.0
            yaw: 1.0416973235853526
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.00985253042577991
            roll: 0.0
            pitch: 0.0
            yaw: 0.5952147035903601
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.018037521657669517
            roll: 0.0
            pitch: 0.0
            yaw: -0.3707798597408398
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03140607069410731
            roll: 0.0
            pitch: 0.0
            yaw: 0.6483925929112544
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03899842037192394
            roll: 0.0
            pitch: 0.0
            yaw: -0.42184130722340873
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0006417815524590246
              y: 0.014320143973881752
              z: 0.041237963219868785
              roll: 0.4200990960620999
              pitch: -0.5004734543443884
              yaw: 1.3377726442722406
            roll: 0.46225267721325947
            pitch: -0.4763238691167737
            yaw: 1.2907199727074075
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
