scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1557013025653577
          y: -0.2623848273089251
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.19217364751023347
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015090988383310001
            roll: 0.0
            pitch: 0.0
            yaw: -0.1469983958995358
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.010108666046782094
            roll: 0.0
            pitch: 0.0
            yaw: -0.05414053342824593
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.018548580054026258
            roll: 0.0
            pitch: 0.0
            yaw: 0.09853332499217843
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.013134272905794185
            roll: 0.0
            pitch: 0.0
            yaw: -0.17143317828754934
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.016413656101232653
            roll: 0.0
            pitch: 0.0
            yaw: 0.08713119756825644
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.045391629448458475
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.017644661149656585
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05131396517768823
            roll: 0.0
            pitch: 0.0
            yaw: 0.2562614219727364
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.00696614793078916
            roll: 0.0
            pitch: 0.0
            yaw: -0.22810284605906095
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.036814525551069434
            roll: 0.0
            pitch: 0.0
            yaw: -0.23608643280886643
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0332908440362428
            roll: 0.0
            pitch: 0.0
            yaw: -0.1373307870355649
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03940083823699997
            roll: 0.0
            pitch: 0.0
            yaw: 0.6093973068128737
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09409954195691549
            roll: 0.0
            pitch: 0.0
            yaw: -0.3062705514192098
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0016073101739299905
              y: 0.016969168982591876
              z: 0.04291202054803357
              roll: 0.4243353746124512
              pitch: -0.4497348034607515
              yaw: 1.3398991280923356
            roll: 0.4340842163034785
            pitch: -0.48528615806117814
            yaw: 1.3323511287327057
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1464309157673331
          y: -0.25159769721674635
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.2931683234772148
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01469229182059416
            roll: 0.0
            pitch: 0.0
            yaw: 0.11129971856840776
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006773992140780208
            roll: 0.0
            pitch: 0.0
            yaw: -0.07325141405832082
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.016517542023262617
            roll: 0.0
            pitch: 0.0
            yaw: -0.12090118967366012
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01690910088575126
            roll: 0.0
            pitch: 0.0
            yaw: 0.04083418519172158
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.004756498136762852
            roll: 0.0
            pitch: 0.0
            yaw: -0.050715682209565585
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04108510266058109
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.046863136709993244
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06635536975235516
            roll: 0.0
            pitch: 0.0
            yaw: -0.6715837876471705
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08689655924832973
            roll: 0.0
            pitch: 0.0
            yaw: -0.4851443078446064
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08070917959326687
            roll: 0.0
            pitch: 0.0
            yaw: 0.24999476783528451
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05292938305687309
            roll: 0.0
            pitch: 0.0
            yaw: 0.34318809459588717
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.020157419994369985
            roll: 0.0
            pitch: 0.0
            yaw: -0.7690199668544543
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09592262906418396
            roll: 0.0
            pitch: 0.0
            yaw: 0.7637954990253915
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001206287464600127
              y: 0.014346559954392983
              z: 0.04313580603672997
              roll: 0.42857143877639425
              pitch: -0.4736713053110371
              yaw: 1.303027838286608
            roll: 0.4760272540801035
            pitch: -0.48986468087574364
            yaw: 1.3228059419719056
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.11073650577155603
          y: -0.12771596886814188
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.20648762153510858
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0162986853435808
            roll: 0.0
            pitch: 0.0
            yaw: -0.13268218316000568
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.017306884065462803
            roll: 0.0
            pitch: 0.0
            yaw: 0.004106284458281317
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0011998031606879102
            roll: 0.0
            pitch: 0.0
            yaw: 0.15453403357124668
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.016110834512605997
            roll: 0.0
            pitch: 0.0
            yaw: -0.15685499343468287
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02301689978745334
            roll: 0.0
            pitch: 0.0
            yaw: -0.000483887678017908
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.00960536886900059
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0427324360977067
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07787977469735852
            roll: 0.0
            pitch: 0.0
            yaw: -0.2589312746136655
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05108765854466976
            roll: 0.0
            pitch: 0.0
            yaw: -0.5688855313713241
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.008347740284369257
            roll: 0.0
            pitch: 0.0
            yaw: 0.7530825999714774
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05011210197368626
            roll: 0.0
            pitch: 0.0
            yaw: -0.9801391991267946
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.09576022833328446
            roll: 0.0
            pitch: 0.0
            yaw: 0.3242315546593719
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03853096843004375
            roll: 0.0
            pitch: 0.0
            yaw: -0.6722153416044082
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.00017497113434851962
              y: 0.015181481926279832
              z: 0.043812221195652146
              roll: 0.40928051007014915
              pitch: -0.47912027286117187
              yaw: 1.3676872377178864
            roll: 0.42935564680308014
            pitch: -0.4965558489281133
            yaw: 1.3040221727286425
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
