scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1356835947567495
          y: -0.1707441112341015
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.25291350309577476
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.016736468359829313
            roll: 0.0
            pitch: 0.0
            yaw: -0.13918519668793553
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0015518137551803896
            roll: 0.0
            pitch: 0.0
            yaw: 0.15405258847682013
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.006587577363624805
            roll: 0.0
            pitch: 0.0
            yaw: -0.0378985292267873
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0025819842268770647
            roll: 0.0
            pitch: 0.0
            yaw: 0.02200412102625829
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.016973204477938875
            roll: 0.0
            pitch: 0.0
            yaw: 0.13834000572678995
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03607386354833304
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.029420475696969508
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08365254479852305
            roll: 0.0
            pitch: 0.0
            yaw: -0.22702742121669717
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0615501106416223
            roll: 0.0
            pitch: 0.0
            yaw: -0.465165479465819
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.025962553689245618
            roll: 0.0
            pitch: 0.0
            yaw: 0.8483860015862759
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05966255141624115
            roll: 0.0
            pitch: 0.0
            yaw: 0.8069293942401037
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0842042415187361
            roll: 0.0
            pitch: 0.0
            yaw: -0.1003808290225946
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.020937658120576394
            roll: 0.0
            pitch: 0.0
            yaw: -0.5666063905939664
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0002277403258102626
              y: 0.015104932925233036
              z: 0.044127686259133776
              roll: 0.4311754519151984
              pitch: -0.45048941190765585
              yaw: 1.346366180737146
            roll: 0.46171338430282083
            pitch: -0.4710853702637217
            yaw: 1.3153507599404275
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1325551859962312
          y: -0.23241947147859032
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4000015032048717
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01470293156822846
            roll: 0.0
            pitch: 0.0
            yaw: -0.04877549551189164
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010062234417789293
            roll: 0.0
            pitch: 0.0
            yaw: 0.07057331797515357
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.011134433534849605
            roll: 0.0
            pitch: 0.0
            yaw: -0.06862311711982015
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.004259656611455814
            roll: 0.0
            pitch: 0.0
            yaw: -0.04451593846376145
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.005736264623005107
            roll: 0.0
            pitch: 0.0
            yaw: -0.15223592179450116
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0559048383410548
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.016528221624662345
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05079268054426704
            roll: 0.0
            pitch: 0.0
            yaw: 0.029041377101123533
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07140860760225232
            roll: 0.0
            pitch: 0.0
            yaw: 0.49499362400638525
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.006186741726012163
            roll: 0.0
            pitch: 0.0
            yaw: 0.8634031109951381
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09271611358033494
            roll: 0.0
            pitch: 0.0
            yaw: -0.7229647011127724
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.047700569948796456
            roll: 0.0
            pitch: 0.0
            yaw: -0.5868193950083518
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07560203322110248
            roll: 0.0
            pitch: 0.0
            yaw: 0.32161674415475683
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0012995999093340723
              y: 0.014306405978038103
              z: 0.04055780776623678
              roll: 0.41790287049895836
              pitch: -0.4682601681386398
              yaw: 1.3501780874111964
            roll: 0.45731492645506605
            pitch: -0.44676324332759104
            yaw: 1.3136288831661644
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.13628496814691532
          y: -0.12811767850322245
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.41599249498989344
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.016633837803483188
            roll: 0.0
            pitch: 0.0
            yaw: 0.1728789897971879
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.011147539440221357
            roll: 0.0
            pitch: 0.0
            yaw: -0.03565767671650258
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01614977273023222
            roll: 0.0
            pitch: 0.0
            yaw: -0.1529968046691943
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.018242767707140405
            roll: 0.0
            pitch: 0.0
            yaw: -0.09335080093974622
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.020679698218062745
            roll: 0.0
            pitch: 0.0
            yaw: 0.1368337748064063
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0431749539878808
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04110848729908405
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.06471086100384787
            roll: 0.0
            pitch: 0.0
            yaw: -1.0313040366003954
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.018483622065963573
            roll: 0.0
            pitch: 0.0
            yaw: -0.35794115045238173
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.09445690955575285
            roll: 0.0
            pitch: 0.0
            yaw: 0.20734882771787655
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0782999645876486
            roll: 0.0
            pitch: 0.0
            yaw: -0.7786046471496524
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03349676872982865
            roll: 0.0
            pitch: 0.0
            yaw: 0.18343425153529203
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05190589283482499
            roll: 0.0
            pitch: 0.0
            yaw: 0.9752879106226506
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.001001942692047102
              y: 0.014365231648967185
              z: 0.0425042790554817
              roll: 0.4284904742695303
              pitch: -0.5001124083611469
              yaw: 1.3250476750910543
            roll: 0.470032194424458
            pitch: -0.47415397504545526
            yaw: 1.322642857346973
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
