scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1557013025653577
          y: -0.2623848273089251
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.19217364751023347
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015090988383310001
            roll: 0.0
            pitch: 0.0
            yaw: -0.1469983958995358
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.010108666046782094
            roll: 0.0
            pitch: 0.0
            yaw: -0.05414053342824593
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.018548580054026258
            roll: 0.0
            pitch: 0.0
            yaw: 0.09853332499217843
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.013134272905794185
            roll: 0.0
            pitch: 0.0
            yaw: -0.17143317828754934
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.016413656101232653
            roll: 0.0
            pitch: 0.0
            yaw: 0.08713119756825644
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.045391629448458475
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.017644661149656585
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05131396517768823
            roll: 0.0
            pitch: 0.0
            yaw: 0.2562614219727364
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.00696614793078916
            roll: 0.0
            pitch: 0.0
            yaw: -0.22810284605906095
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.036814525551069434
            roll: 0.0
            pitch: 0.0
            yaw: -0.23608643280886643
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0332908440362428
            roll: 0.0
            pitch: 0.0
            yaw: -0.1373307870355649
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03940083823699997
            roll: 0.0
            pitch: 0.0
            yaw: 0.6093973068128737
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09409954195691549
            roll: 0.0
            pitch: 0.0
            yaw: -0.3062705514192098
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0019684767452311435
              y: 0.016014481632419805
              z: 0.043765388794018145
              roll: 0.4330431390346963
              pitch: -0.4453694176272228
              yaw: 1.3349137831004292
            roll: 0.4340842163034785
            pitch: -0.48528615806117814
            yaw: 1.3323511287327057
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1375931404404463
          y: -0.18069444778469984
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.1820304695338798
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015878548860276603
            roll: 0.0
            pitch: 0.0
            yaw: 0.17179665647212738
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.013876483017961003
            roll: 0.0
            pitch: 0.0
            yaw: 0.015464950838446762
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.013815314661963
            roll: 0.0
            pitch: 0.0
            yaw: -0.11587589733313441
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.004830516472131934
            roll: 0.0
            pitch: 0.0
            yaw: -0.17044921295244828
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.00426896595901129
            roll: 0.0
            pitch: 0.0
            yaw: -0.07066230982472022
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05189646899784317
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.016020300309655858
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04067032502954694
            roll: 0.0
            pitch: 0.0
            yaw: -0.6055960524578612
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.024993771353001182
            roll: 0.0
            pitch: 0.0
            yaw: -0.04371231959236854
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09593649051391542
            roll: 0.0
            pitch: 0.0
            yaw: 0.8607144672802174
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06942885887198746
            roll: 0.0
            pitch: 0.0
            yaw: -0.8570811686246677
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.017326651964215067
            roll: 0.0
            pitch: 0.0
            yaw: 0.42875913207467686
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.064285872773935
            roll: 0.0
            pitch: 0.0
            yaw: 0.09750864898864098
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0005828209716853996
              y: 0.015148959301660407
              z: 0.04132521799314562
              roll: 0.41045949447018737
              pitch: -0.4575010032324925
              yaw: 1.3209851802963408
            roll: 0.43804573431868654
            pitch: -0.5169717323470893
            yaw: 1.3282465138151305
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.11909403912950248
          y: -0.28743179132988705
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.20352503632551422
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.005797114895150751
            roll: 0.0
            pitch: 0.0
            yaw: -0.1708286997659108
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01649505012388367
            roll: 0.0
            pitch: 0.0
            yaw: 0.09721542446581921
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0020555156089777475
            roll: 0.0
            pitch: 0.0
            yaw: 0.02110068627837347
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0028950896696023527
            roll: 0.0
            pitch: 0.0
            yaw: 0.06104904589898896
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 7.108173332207729e-05
            roll: 0.0
            pitch: 0.0
            yaw: 0.08057503383907605
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.001592668489914989
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02903149513545472
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07448962550159824
            roll: 0.0
            pitch: 0.0
            yaw: 1.014234573370245
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.042494536134730136
            roll: 0.0
            pitch: 0.0
            yaw: 0.011435472012566006
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.053146607584484
            roll: 0.0
            pitch: 0.0
            yaw: -0.9340408132307795
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.07385447243145007
            roll: 0.0
            pitch: 0.0
            yaw: -0.9625736157149996
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.043863523822414846
            roll: 0.0
            pitch: 0.0
            yaw: 0.002267262617097643
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06667845338163456
            roll: 0.0
            pitch: 0.0
            yaw: -0.1593707868339166
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0018232192679359471
              y: 0.014089569133278253
              z: 0.04444519053124313
              roll: 0.4533287743876342
              pitch: -0.4912005401949605
              yaw: 1.2951644043031973
            roll: 0.475276324766271
            pitch: -0.45135308151779796
            yaw: 1.334054827276815
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
