scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.19184116125644435
          y: -0.1946807622850606
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.10889417670153811
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.011516981242908744
            roll: 0.0
            pitch: 0.0
            yaw: -0.160181239729457
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010332934130112298
            roll: 0.0
            pitch: 0.0
            yaw: -0.03569016235378061
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0006627418236519814
            roll: 0.0
            pitch: 0.0
            yaw: -0.06854349980214071
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0011293873065401847
            roll: 0.0
            pitch: 0.0
            yaw: -0.03229073725861578
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01377927436027733
            roll: 0.0
            pitch: 0.0
            yaw: 0.061877776968566695
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.026939587772281795
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.00884301864420154
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.02495767803715339
            roll: 0.0
            pitch: 0.0
            yaw: -0.31487199308330194
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08989584226973633
            roll: 0.0
            pitch: 0.0
            yaw: 0.8662772162239167
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.037479144076528165
            roll: 0.0
            pitch: 0.0
            yaw: -0.4154730042710052
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08019321977184932
            roll: 0.0
            pitch: 0.0
            yaw: -0.8796897368538431
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07492455709238055
            roll: 0.0
            pitch: 0.0
            yaw: -0.9493189138420248
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08346862641841996
            roll: 0.0
            pitch: 0.0
            yaw: 0.6296246862606587
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0011369615388353478
              y: 0.014632556437435289
              z: 0.042343504019910605
              roll: 0.46480774769787314
              pitch: -0.489599359453489
              yaw: 1.35305621089515
            roll: 0.4789347461679028
            pitch: -0.49704267136347297
            yaw: 1.2949085754295615
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1325551859962312
          y: -0.23241947147859032
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4000015032048717
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01470293156822846
            roll: 0.0
            pitch: 0.0
            yaw: -0.04877549551189164
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010062234417789293
            roll: 0.0
            pitch: 0.0
            yaw: 0.07057331797515357
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.011134433534849605
            roll: 0.0
            pitch: 0.0
            yaw: -0.06862311711982015
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.004259656611455814
            roll: 0.0
            pitch: 0.0
            yaw: -0.04451593846376145
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.005736264623005107
            roll: 0.0
            pitch: 0.0
            yaw: -0.15223592179450116
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0559048383410548
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.016528221624662345
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05079268054426704
            roll: 0.0
            pitch: 0.0
            yaw: 0.029041377101123533
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07140860760225232
            roll: 0.0
            pitch: 0.0
            yaw: 0.49499362400638525
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.006186741726012163
            roll: 0.0
            pitch: 0.0
            yaw: 0.8634031109951381
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09271611358033494
            roll: 0.0
            pitch: 0.0
            yaw: -0.7229647011127724
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.047700569948796456
            roll: 0.0
            pitch: 0.0
            yaw: -0.5868193950083518
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07560203322110248
            roll: 0.0
            pitch: 0.0
            yaw: 0.32161674415475683
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0010291419100448636
              y: 0.013850422841006777
              z: 0.04186136332562057
              roll: 0.4292953021010865
              pitch: -0.5101892207226446
              yaw: 1.3534552860575466
            roll: 0.45731492645506605
            pitch: -0.44676324332759104
            yaw: 1.3136288831661644
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.1544496517066687
          y: -0.1681280034071396
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.0914781647605949
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01068519174579214
            roll: 0.0
            pitch: 0.0
            yaw: 0.1546455249414383
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007859941774509563
            roll: 0.0
            pitch: 0.0
            yaw: 0.008132923148561899
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0153944419233355
            roll: 0.0
            pitch: 0.0
            yaw: 0.08115642159299302
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.014730655329820416
            roll: 0.0
            pitch: 0.0
            yaw: 0.07175622643113824
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.018928199514279292
            roll: 0.0
            pitch: 0.0
            yaw: -0.05140577984959954
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.035766571206530845
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.006396402763283945
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04062688178227298
            roll: 0.0
            pitch: 0.0
            yaw: 0.4658624616351583
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08498966473485305
            roll: 0.0
            pitch: 0.0
            yaw: -0.09394258768211561
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.027539569087204882
            roll: 0.0
            pitch: 0.0
            yaw: 0.9227358065405393
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07906794325721506
            roll: 0.0
            pitch: 0.0
            yaw: -0.3936627135659284
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03828162257829096
            roll: 0.0
            pitch: 0.0
            yaw: 0.41768402848610164
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.038171347331087326
            roll: 0.0
            pitch: 0.0
            yaw: -0.9801454394527843
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.001986620447845319
              y: 0.01698537168687035
              z: 0.042352767239028345
              roll: 0.40540558572705926
              pitch: -0.5030016389038047
              yaw: 1.3571496404884298
            roll: 0.41645593015981036
            pitch: -0.4728738637544354
            yaw: 1.3646657587064859
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
