scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.14843533544561763
          y: -0.11627377919726437
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.282510219830551
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015690856002599368
            roll: 0.0
            pitch: 0.0
            yaw: 0.09376475812200752
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.014851847660396282
            roll: 0.0
            pitch: 0.0
            yaw: 0.12601096846999638
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.014785590489793672
            roll: 0.0
            pitch: 0.0
            yaw: 0.15497633046528475
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 2.0718029126287618e-05
            roll: 0.0
            pitch: 0.0
            yaw: -0.06633621052460163
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0162339507073496
            roll: 0.0
            pitch: 0.0
            yaw: 0.0027227065824520225
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.026461205396537055
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.013304705343907791
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.04012812302579272
            roll: 0.0
            pitch: 0.0
            yaw: 0.5108218708720083
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0865944587833789
            roll: 0.0
            pitch: 0.0
            yaw: -0.3998447656850628
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07978555076105663
            roll: 0.0
            pitch: 0.0
            yaw: 0.504438601638949
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06012827228016398
            roll: 0.0
            pitch: 0.0
            yaw: 0.24172194807172342
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05021761950686842
            roll: 0.0
            pitch: 0.0
            yaw: -0.2708991774089121
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08042716788614394
            roll: 0.0
            pitch: 0.0
            yaw: -0.7710949037894982
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0004225509027389368
              y: 0.015430562916522115
              z: 0.04142209986650865
              roll: 0.443685047766229
              pitch: -0.502038250502643
              yaw: 1.3090286611346806
            roll: 0.41032785350855533
            pitch: -0.49527151823152593
            yaw: 1.294572628081229
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2507722636612417
          y: -0.12388441522998109
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4681005843151017
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.003486486045312112
            roll: 0.0
            pitch: 0.0
            yaw: 0.035555846655542095
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01180306203112691
            roll: 0.0
            pitch: 0.0
            yaw: 0.03440426167145666
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0023228499851325433
            roll: 0.0
            pitch: 0.0
            yaw: 0.16090559014515238
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.004536839686631641
            roll: 0.0
            pitch: 0.0
            yaw: 0.061173276454884795
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.002012831206906606
            roll: 0.0
            pitch: 0.0
            yaw: 0.16818607554498055
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05083775446100007
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04446792836090735
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08400735692997299
            roll: 0.0
            pitch: 0.0
            yaw: -0.7081973193766709
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.06348997840525045
            roll: 0.0
            pitch: 0.0
            yaw: -0.9494464873905564
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03796770646353076
            roll: 0.0
            pitch: 0.0
            yaw: -0.3084068268076362
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03809333010803029
            roll: 0.0
            pitch: 0.0
            yaw: -0.0880451049451969
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08363291661165106
            roll: 0.0
            pitch: 0.0
            yaw: -0.4616164665493535
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0784004443168024
            roll: 0.0
            pitch: 0.0
            yaw: 0.670679299360277
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0006275194087843948
              y: 0.015219679579574923
              z: 0.04146052056561814
              roll: 0.4740094372421546
              pitch: -0.44555091102844635
              yaw: 1.3051051408698287
            roll: 0.4390952935473614
            pitch: -0.4776412438199628
            yaw: 1.3554192431218193
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.1369711815558095
          y: -0.17608884838598723
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4169681813762097
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01478728305562278
            roll: 0.0
            pitch: 0.0
            yaw: -0.12223065217277455
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.009022494314396896
            roll: 0.0
            pitch: 0.0
            yaw: -0.14321447050252775
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0005780605960879134
            roll: 0.0
            pitch: 0.0
            yaw: -0.06783955177448917
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.016305537716830132
            roll: 0.0
            pitch: 0.0
            yaw: -0.056821588013000704
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.011579644325755378
            roll: 0.0
            pitch: 0.0
            yaw: -0.09551570239514323
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.047094240269040605
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.029884260855832467
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.01575474679671303
            roll: 0.0
            pitch: 0.0
            yaw: 0.8398153742062233
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0005159057881061191
            roll: 0.0
            pitch: 0.0
            yaw: 0.3819951042285583
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07651224376999544
            roll: 0.0
            pitch: 0.0
            yaw: -0.31628193941022287
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05122656040336876
            roll: 0.0
            pitch: 0.0
            yaw: -0.9423124499490875
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03181703926383603
            roll: 0.0
            pitch: 0.0
            yaw: 0.24786270155247636
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08317049373265689
            roll: 0.0
            pitch: 0.0
            yaw: 0.09086912259731195
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0015331250965187216
              y: 0.015183742426743814
              z: 0.043660494239052966
              roll: 0.41708689548296507
              pitch: -0.5052877160080457
              yaw: 1.3640327343450223
            roll: 0.4279416463458987
            pitch: -0.44745335578436274
            yaw: 1.33266978442865
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
