scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1557013025653577
          y: -0.2623848273089251
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.19217364751023347
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015090988383310001
            roll: 0.0
            pitch: 0.0
            yaw: -0.1469983958995358
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.010108666046782094
            roll: 0.0
            pitch: 0.0
            yaw: -0.05414053342824593
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.018548580054026258
            roll: 0.0
            pitch: 0.0
            yaw: 0.09853332499217843
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.013134272905794185
            roll: 0.0
            pitch: 0.0
            yaw: -0.17143317828754934
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.016413656101232653
            roll: 0.0
            pitch: 0.0
            yaw: 0.08713119756825644
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.045391629448458475
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.017644661149656585
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05131396517768823
            roll: 0.0
            pitch: 0.0
            yaw: 0.2562614219727364
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.00696614793078916
            roll: 0.0
            pitch: 0.0
            yaw: -0.22810284605906095
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.036814525551069434
            roll: 0.0
            pitch: 0.0
            yaw: -0.23608643280886643
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0332908440362428
            roll: 0.0
            pitch: 0.0
            yaw: -0.1373307870355649
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03940083823699997
            roll: 0.0
            pitch: 0.0
            yaw: 0.6093973068128737
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09409954195691549
            roll: 0.0
            pitch: 0.0
            yaw: -0.3062705514192098
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00030332210074160036
              y: 0.014675522645390624
              z: 0.04356112249648516
              roll: 0.47744316282990806
              pitch: -0.5125058827887397
              yaw: 1.3012299339865159
            roll: 0.4340842163034785
            pitch: -0.48528615806117814
            yaw: 1.3323511287327057
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.15480464607848132
          y: -0.265209508004293
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.07981186982859445
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.009331755915621173
            roll: 0.0
            pitch: 0.0
            yaw: -0.13047625457723735
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0035837514136704655
            roll: 0.0
            pitch: 0.0
            yaw: -0.014496495808442589
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.008975305066689197
            roll: 0.0
            pitch: 0.0
            yaw: -0.08679725141587781
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.005785746500319409
            roll: 0.0
            pitch: 0.0
            yaw: -0.08606743326627618
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0030124114088543735
            roll: 0.0
            pitch: 0.0
            yaw: -0.1514449463088094
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0027798302900294974
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.016923124428128544
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.04169875145673907
            roll: 0.0
            pitch: 0.0
            yaw: 0.4556616175065249
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.059679430478929374
            roll: 0.0
            pitch: 0.0
            yaw: 0.4439534854444671
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08778162302866738
            roll: 0.0
            pitch: 0.0
            yaw: 0.1613403057388052
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03514065969378977
            roll: 0.0
            pitch: 0.0
            yaw: 0.14467756433928747
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07632322305612001
            roll: 0.0
            pitch: 0.0
            yaw: 0.39998916060402867
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05956644238598223
            roll: 0.0
            pitch: 0.0
            yaw: -0.7392635332570965
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 1.098745248511758e-05
              y: 0.01576565016944108
              z: 0.04092705460439918
              roll: 0.4635397879748636
              pitch: -0.4688869081603788
              yaw: 1.3621447669284588
            roll: 0.48037276076991575
            pitch: -0.5034208593183888
            yaw: 1.301664916462058
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.13140610876838546
          y: -0.28498255010270396
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.3134900187702334
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.02130591501715271
            roll: 0.0
            pitch: 0.0
            yaw: -0.10184634870686109
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.015855698618656884
            roll: 0.0
            pitch: 0.0
            yaw: -0.10862852212017426
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01476816244375755
            roll: 0.0
            pitch: 0.0
            yaw: -0.06589104690330286
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.012980817651406823
            roll: 0.0
            pitch: 0.0
            yaw: -0.0653584970795092
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.00888867116930725
            roll: 0.0
            pitch: 0.0
            yaw: 0.05851078460115344
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.039403843291966376
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02056765697562267
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.05919560443694405
            roll: 0.0
            pitch: 0.0
            yaw: -0.43067905714384935
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09055028361481048
            roll: 0.0
            pitch: 0.0
            yaw: -0.8267340482777773
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03928448542850804
            roll: 0.0
            pitch: 0.0
            yaw: -0.9648165154666394
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09313289853424964
            roll: 0.0
            pitch: 0.0
            yaw: 0.8697558036743085
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03797870710088472
            roll: 0.0
            pitch: 0.0
            yaw: 0.414140339648418
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07603819052371008
            roll: 0.0
            pitch: 0.0
            yaw: -0.3694633464158966
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.001923333225343693
              y: 0.014601919770419622
              z: 0.043243831258514824
              roll: 0.4727960387731577
              pitch: -0.49046211916242377
              yaw: 1.2965842406638344
            roll: 0.4234730238422235
            pitch: -0.4936444022139942
            yaw: 1.3397967685337278
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
