scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2920330326886891
          y: -0.2877842847999565
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.21951542457064244
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.004693095888448063
            roll: 0.0
            pitch: 0.0
            yaw: -0.10464662564214382
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.021864624251769466
            roll: 0.0
            pitch: 0.0
            yaw: -0.017448930520035183
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0052538264561688315
            roll: 0.0
            pitch: 0.0
            yaw: -0.14057967252246958
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.020741358560270207
            roll: 0.0
            pitch: 0.0
            yaw: 0.12790081115268698
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.016148001245704688
            roll: 0.0
            pitch: 0.0
            yaw: 0.027357336231904866
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.007848358444674589
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04307793669065636
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.058096418014310675
            roll: 0.0
            pitch: 0.0
            yaw: -0.7825476859752074
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05478385063134053
            roll: 0.0
            pitch: 0.0
            yaw: 0.5748805099694678
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06012432936221372
            roll: 0.0
            pitch: 0.0
            yaw: -1.019029512226852
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.023947124063305777
            roll: 0.0
            pitch: 0.0
            yaw: 0.7362868225621253
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07268806601786891
            roll: 0.0
            pitch: 0.0
            yaw: -0.6851369338517252
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06982599788485608
            roll: 0.0
            pitch: 0.0
            yaw: 0.4502184866662915
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0016936613488537878
              y: 0.014981275080948857
              z: 0.04046404230726411
              roll: 0.4059208643569993
              pitch: -0.5013255690101156
              yaw: 1.3232335534083934
            roll: 0.4214805041734122
            pitch: -0.5074089204241781
            yaw: 1.3372990283066732
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2754208233592208
          y: -0.14592284840591804
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.0940520464113207
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.019491356898341188
            roll: 0.0
            pitch: 0.0
            yaw: 0.09174463057550647
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.013635017166118021
            roll: 0.0
            pitch: 0.0
            yaw: 0.16453576325483232
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.012759795539432704
            roll: 0.0
            pitch: 0.0
            yaw: 0.09822778037010343
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.011193281788981227
            roll: 0.0
            pitch: 0.0
            yaw: 0.0366803520904381
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0058979581155818445
            roll: 0.0
            pitch: 0.0
            yaw: 0.04658583427952076
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0013979346935648201
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.021728292589989547
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.017380583352979637
            roll: 0.0
            pitch: 0.0
            yaw: -0.5878510905916751
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.03139731520459593
            roll: 0.0
            pitch: 0.0
            yaw: 0.04339389679091088
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.059300128747104705
            roll: 0.0
            pitch: 0.0
            yaw: -0.978508103619667
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05820570275425766
            roll: 0.0
            pitch: 0.0
            yaw: -0.1908989006961216
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06073968991827364
            roll: 0.0
            pitch: 0.0
            yaw: 0.24661878331768672
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.007315900065865147
            roll: 0.0
            pitch: 0.0
            yaw: -0.3800922464861377
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0012728622356106838
              y: 0.014345299885430271
              z: 0.0409935903841103
              roll: 0.43272528687802647
              pitch: -0.5152023724466069
              yaw: 1.3379914807314077
            roll: 0.4091981994499076
            pitch: -0.4461047223854617
            yaw: 1.324587632378286
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2357079336196524
          y: -0.2219997605102082
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.48799731351747555
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.019147264085388478
            roll: 0.0
            pitch: 0.0
            yaw: -0.03874384214979412
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01983311865301022
            roll: 0.0
            pitch: 0.0
            yaw: -0.10920418562703764
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0017168909666070362
            roll: 0.0
            pitch: 0.0
            yaw: -0.06243800776213637
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.010151603883274005
            roll: 0.0
            pitch: 0.0
            yaw: -0.00894307344090628
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.016274433567387194
            roll: 0.0
            pitch: 0.0
            yaw: -0.03663461132146609
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03556336779396754
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.050398615503290986
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0781186047053617
            roll: 0.0
            pitch: 0.0
            yaw: -0.992333008676672
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09607345126154113
            roll: 0.0
            pitch: 0.0
            yaw: 0.42097019140073
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04186113889975409
            roll: 0.0
            pitch: 0.0
            yaw: 0.613273235416822
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.06840643681100547
            roll: 0.0
            pitch: 0.0
            yaw: -0.26526193353104643
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.030608536761032132
            roll: 0.0
            pitch: 0.0
            yaw: -0.33309110838730194
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04905444882022193
            roll: 0.0
            pitch: 0.0
            yaw: -0.580057626715744
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.00020902428287686856
              y: 0.014674332041930452
              z: 0.04326947551657416
              roll: 0.4647004848241816
              pitch: -0.5199350294133688
              yaw: 1.3150920655208285
            roll: 0.44104042669793375
            pitch: -0.4419800917939514
            yaw: 1.3371284134736205
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
