scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2754208233592208
          y: -0.14592284840591804
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.0940520464113207
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.019491356898341188
            roll: 0.0
            pitch: 0.0
            yaw: 0.09174463057550647
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.013635017166118021
            roll: 0.0
            pitch: 0.0
            yaw: 0.16453576325483232
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.012759795539432704
            roll: 0.0
            pitch: 0.0
            yaw: 0.09822778037010343
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.011193281788981227
            roll: 0.0
            pitch: 0.0
            yaw: 0.0366803520904381
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0058979581155818445
            roll: 0.0
            pitch: 0.0
            yaw: 0.04658583427952076
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0013979346935648201
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.021728292589989547
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.017380583352979637
            roll: 0.0
            pitch: 0.0
            yaw: -0.5878510905916751
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.03139731520459593
            roll: 0.0
            pitch: 0.0
            yaw: 0.04339389679091088
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.059300128747104705
            roll: 0.0
            pitch: 0.0
            yaw: -0.978508103619667
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05820570275425766
            roll: 0.0
            pitch: 0.0
            yaw: -0.1908989006961216
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06073968991827364
            roll: 0.0
            pitch: 0.0
            yaw: 0.24661878331768672
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.007315900065865147
            roll: 0.0
            pitch: 0.0
            yaw: -0.3800922464861377
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0003678004360938697
              y: 0.01431340127541405
              z: 0.04248534620829358
              roll: 0.4692611494997765
              pitch: -0.5147084785930792
              yaw: 1.327405232524063
            roll: 0.4091981994499076
            pitch: -0.4461047223854617
            yaw: 1.324587632378286
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2973247705162446
          y: -0.1275011590614676
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.25337316070806504
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.009666605284206571
            roll: 0.0
            pitch: 0.0
            yaw: -0.007637408247304245
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01580574581402118
            roll: 0.0
            pitch: 0.0
            yaw: 0.0334376901696945
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.020433815507553552
            roll: 0.0
            pitch: 0.0
            yaw: -0.02440002855243978
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0037115409640883466
            roll: 0.0
            pitch: 0.0
            yaw: -0.03351718307509577
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.016645824947565134
            roll: 0.0
            pitch: 0.0
            yaw: 0.14767314875164972
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.007588227885692821
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.011471942600032009
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.011466131677059122
            roll: 0.0
            pitch: 0.0
            yaw: -0.4784847546641936
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.03607016233282728
            roll: 0.0
            pitch: 0.0
            yaw: -0.7946320032021832
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 4.4384461749813475e-06
            roll: 0.0
            pitch: 0.0
            yaw: 0.250238966433191
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03609046235599668
            roll: 0.0
            pitch: 0.0
            yaw: 0.7727271648939213
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08140386264112565
            roll: 0.0
            pitch: 0.0
            yaw: 0.026505612345670393
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.09203775621367319
            roll: 0.0
            pitch: 0.0
            yaw: 0.920333578347664
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00021215451485193495
              y: 0.013661847217556646
              z: 0.04316888465771085
              roll: 0.4221871243917259
              pitch: -0.46209198149865116
              yaw: 1.3676350678919327
            roll: 0.45001862573841184
            pitch: -0.481493446578358
            yaw: 1.294792809772055
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.22870842529554194
          y: -0.24292458135085007
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4574669161801157
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.006578786869799872
            roll: 0.0
            pitch: 0.0
            yaw: -0.11418255784315584
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.009263093553471175
            roll: 0.0
            pitch: 0.0
            yaw: 0.12878817297102124
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.008103558857174571
            roll: 0.0
            pitch: 0.0
            yaw: 0.051124365285991596
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.006147485062480822
            roll: 0.0
            pitch: 0.0
            yaw: 0.0027577705808393416
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02117900073762774
            roll: 0.0
            pitch: 0.0
            yaw: 0.13579820909118234
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.005288693582265386
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.007199370716658944
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07107361928221695
            roll: 0.0
            pitch: 0.0
            yaw: -0.18735310212804013
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.005930597627263487
            roll: 0.0
            pitch: 0.0
            yaw: 0.047735750242460906
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.030396268684551808
            roll: 0.0
            pitch: 0.0
            yaw: -0.1454329645678396
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08874621549008935
            roll: 0.0
            pitch: 0.0
            yaw: -1.0290284617395788
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0007558347451568775
            roll: 0.0
            pitch: 0.0
            yaw: 0.978608168033489
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.09227781288846248
            roll: 0.0
            pitch: 0.0
            yaw: -0.9930215376347563
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 2.377493907437583e-05
              y: 0.016398012208362664
              z: 0.04140821022460035
              roll: 0.41697783527002547
              pitch: -0.5056447556068147
              yaw: 1.3278143681344792
            roll: 0.4626954798140938
            pitch: -0.5136971440488222
            yaw: 1.3562847900148944
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
