scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.29187227591504217
          y: -0.15989336978380403
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.10371826044774068
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0035930504518560252
            roll: 0.0
            pitch: 0.0
            yaw: 0.08477728721976507
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.023020442084116584
            roll: 0.0
            pitch: 0.0
            yaw: 0.1004920206551908
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.00454101647773698
            roll: 0.0
            pitch: 0.0
            yaw: 0.1016934346398814
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.00801298168409775
            roll: 0.0
            pitch: 0.0
            yaw: -0.02946716709466135
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01395908292522248
            roll: 0.0
            pitch: 0.0
            yaw: 0.10346515631885916
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.010695117631495457
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03939858927917292
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06559558420446165
            roll: 0.0
            pitch: 0.0
            yaw: 0.34546389082983
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05919938613680849
            roll: 0.0
            pitch: 0.0
            yaw: -0.15916473323643032
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09301287004450065
            roll: 0.0
            pitch: 0.0
            yaw: 0.6124112459046365
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.026870107162604018
            roll: 0.0
            pitch: 0.0
            yaw: -0.005197527482297515
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.019779428515490832
            roll: 0.0
            pitch: 0.0
            yaw: 0.04063882650283546
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.020574657830582363
            roll: 0.0
            pitch: 0.0
            yaw: 0.9582558144511768
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.001402936971190648
              y: 0.016685016326338356
              z: 0.04131541432857659
              roll: 0.4724268108501676
              pitch: -0.4854872115854999
              yaw: 1.2944453322348832
            roll: 0.4086352074943644
            pitch: -0.4544625549416192
            yaw: 1.315716959814825
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2550360382814444
          y: -0.12409767890923362
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.3176958931187367
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.009685234737220823
            roll: 0.0
            pitch: 0.0
            yaw: -0.05370474385135736
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0076292529672233565
            roll: 0.0
            pitch: 0.0
            yaw: -0.13593022718779268
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.016527157478207086
            roll: 0.0
            pitch: 0.0
            yaw: 0.11561210293016594
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.014476652242693134
            roll: 0.0
            pitch: 0.0
            yaw: -0.06559971017597137
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01887416232102556
            roll: 0.0
            pitch: 0.0
            yaw: -0.07005318714180192
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.016132598606812765
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05402411652598359
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.053922835250172774
            roll: 0.0
            pitch: 0.0
            yaw: -0.8936016532627316
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.014166086505226272
            roll: 0.0
            pitch: 0.0
            yaw: 0.5485844177725303
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04813208506731931
            roll: 0.0
            pitch: 0.0
            yaw: 0.49871720317212165
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.00601605115753584
            roll: 0.0
            pitch: 0.0
            yaw: 0.9965845324863427
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.09241637383392654
            roll: 0.0
            pitch: 0.0
            yaw: 0.7329847447016422
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.020693991737368342
            roll: 0.0
            pitch: 0.0
            yaw: -0.14004169565142144
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001088276737936828
              y: 0.013464469005036962
              z: 0.04196551303227709
              roll: 0.4108723097833193
              pitch: -0.46024995418352743
              yaw: 1.3613821135011963
            roll: 0.42641859563536605
            pitch: -0.4607860054997125
            yaw: 1.3180283613212465
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.1550692585866309
          y: -0.16656463268363203
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.0687545470397053
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.018528729289472235
            roll: 0.0
            pitch: 0.0
            yaw: -0.17107314423734316
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0016248357848022213
            roll: 0.0
            pitch: 0.0
            yaw: 0.15866316127624164
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.001819437095029769
            roll: 0.0
            pitch: 0.0
            yaw: 0.09823573634761984
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.001272093919235405
            roll: 0.0
            pitch: 0.0
            yaw: 0.03629493403855355
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0038599653068670907
            roll: 0.0
            pitch: 0.0
            yaw: 0.0914516703759291
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0006562889138231401
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.026066857566408586
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.013855829536577602
            roll: 0.0
            pitch: 0.0
            yaw: 0.1327065114906647
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07346759956551571
            roll: 0.0
            pitch: 0.0
            yaw: -0.7533834025074932
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0018315332417463137
            roll: 0.0
            pitch: 0.0
            yaw: 0.2909613219522247
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.043188165995603434
            roll: 0.0
            pitch: 0.0
            yaw: -0.04425805229154922
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.011227887824601851
            roll: 0.0
            pitch: 0.0
            yaw: -0.4137293159765444
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0940989437283843
            roll: 0.0
            pitch: 0.0
            yaw: -0.8405200895319046
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.00076829665729433
              y: 0.01690394673975766
              z: 0.040481959436956864
              roll: 0.4238897677077839
              pitch: -0.5212802729602982
              yaw: 1.3399313796386312
            roll: 0.46023768851762104
            pitch: -0.5174889416335587
            yaw: 1.3037938999047047
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
