scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.18536117515204908
          y: -0.1868799191378085
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.057189346640181715
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.020118525609382615
            roll: 0.0
            pitch: 0.0
            yaw: -0.04729512555810245
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.012346450640099236
            roll: 0.0
            pitch: 0.0
            yaw: -0.08538224014751707
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01716299260775863
            roll: 0.0
            pitch: 0.0
            yaw: -0.06359481268781617
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013089439677680705
            roll: 0.0
            pitch: 0.0
            yaw: 0.09772456565642051
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.009983531008951954
            roll: 0.0
            pitch: 0.0
            yaw: -0.043250795490757415
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.008513807867356442
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.013946579916624978
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0859704514289445
            roll: 0.0
            pitch: 0.0
            yaw: 0.36778142828021987
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.015473980115676078
            roll: 0.0
            pitch: 0.0
            yaw: -0.7601458459845469
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.009305933931733498
            roll: 0.0
            pitch: 0.0
            yaw: 0.11628935935164564
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03914645100238173
            roll: 0.0
            pitch: 0.0
            yaw: -0.5813948590777709
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.000596891883954509
            roll: 0.0
            pitch: 0.0
            yaw: 0.18632853160807739
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08715103611589584
            roll: 0.0
            pitch: 0.0
            yaw: 0.9412400855693159
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0007263250575912953
              y: 0.013606181866014403
              z: 0.042645561559115724
              roll: 0.43283175519731065
              pitch: -0.4935361108366993
              yaw: 1.3032157590967737
            roll: 0.47480793140166483
            pitch: -0.502151113856379
            yaw: 1.3371109566498283
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1090957760273934
          y: -0.1216354782511079
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.16503923123386754
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015569162114772031
            roll: 0.0
            pitch: 0.0
            yaw: -0.1598902585769904
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.009226624451424015
            roll: 0.0
            pitch: 0.0
            yaw: 0.17459828863726606
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.018648750937036808
            roll: 0.0
            pitch: 0.0
            yaw: -0.10532482297732271
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.010664954620305818
            roll: 0.0
            pitch: 0.0
            yaw: 0.16697222179992033
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01774796124861249
            roll: 0.0
            pitch: 0.0
            yaw: -0.12249743814789107
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0426276618706055
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04278848231484657
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.03762682900496661
            roll: 0.0
            pitch: 0.0
            yaw: -0.7337013135039687
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05406005344303841
            roll: 0.0
            pitch: 0.0
            yaw: -0.5261355923040475
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06058360248097097
            roll: 0.0
            pitch: 0.0
            yaw: 0.19797001357063126
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0955501371571151
            roll: 0.0
            pitch: 0.0
            yaw: 0.02629947570231206
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03201365595268116
            roll: 0.0
            pitch: 0.0
            yaw: -0.3976887637630181
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04325401668697906
            roll: 0.0
            pitch: 0.0
            yaw: -0.18489101239068984
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0007129497894051069
              y: 0.016099185564475364
              z: 0.04204750589382752
              roll: 0.47373930786367013
              pitch: -0.4608698499459243
              yaw: 1.3230366300974206
            roll: 0.42404819385690085
            pitch: -0.48915534011640294
            yaw: 1.3434329392519064
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.23663201195611044
          y: -0.2457134677338099
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4448655128456631
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.013786715432745185
            roll: 0.0
            pitch: 0.0
            yaw: 0.0007690095633560434
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.013691233603490808
            roll: 0.0
            pitch: 0.0
            yaw: 0.11401756334134117
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.002637726932395959
            roll: 0.0
            pitch: 0.0
            yaw: -0.05948929235321984
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01284550807945524
            roll: 0.0
            pitch: 0.0
            yaw: 0.12012761188753746
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01622229591132684
            roll: 0.0
            pitch: 0.0
            yaw: 0.03296749831911461
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.026181600357938303
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.029924457997444472
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0756899171909126
            roll: 0.0
            pitch: 0.0
            yaw: 0.5161383926563579
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09502330310756035
            roll: 0.0
            pitch: 0.0
            yaw: 0.8053914767662556
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.009596366811280288
            roll: 0.0
            pitch: 0.0
            yaw: -0.9344976227606796
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.033839352794427596
            roll: 0.0
            pitch: 0.0
            yaw: -0.3898177102549124
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.02855131067029676
            roll: 0.0
            pitch: 0.0
            yaw: -0.6414998280062685
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08222243397467388
            roll: 0.0
            pitch: 0.0
            yaw: -0.9431981055228146
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0018853795946530913
              y: 0.017348019654146514
              z: 0.044402453814175305
              roll: 0.4198925072013304
              pitch: -0.46290195104601106
              yaw: 1.3195494437519213
            roll: 0.41712921974137646
            pitch: -0.46912711921511135
            yaw: 1.3174280893493742
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
