scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.15280657361409294
          y: -0.20905038049466315
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.07115089471858527
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.005812687230312891
            roll: 0.0
            pitch: 0.0
            yaw: 0.024908352658441435
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.013430494830942032
            roll: 0.0
            pitch: 0.0
            yaw: -0.095961771507314
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.00775382595494202
            roll: 0.0
            pitch: 0.0
            yaw: 0.14953155585048072
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.004357376298064382
            roll: 0.0
            pitch: 0.0
            yaw: 0.041074153302863264
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.013144697694236335
            roll: 0.0
            pitch: 0.0
            yaw: 0.04093791855082282
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.019426340094257713
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02142582147301858
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.01566130707669809
            roll: 0.0
            pitch: 0.0
            yaw: 0.43953281016447976
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.004745859250589277
            roll: 0.0
            pitch: 0.0
            yaw: 0.01221273645073806
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.052707805198407676
            roll: 0.0
            pitch: 0.0
            yaw: -0.9094956837134534
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04997192878969184
            roll: 0.0
            pitch: 0.0
            yaw: -0.8432299547388521
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07015824535472034
            roll: 0.0
            pitch: 0.0
            yaw: -0.6929483805322887
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.014819657310453468
            roll: 0.0
            pitch: 0.0
            yaw: -0.355516537421541
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00011455387353566772
              y: 0.014978643729734939
              z: 0.041025352797265345
              roll: 0.48097397877711334
              pitch: -0.520125144500193
              yaw: 1.3145280796880758
            roll: 0.448923151580801
            pitch: -0.49222503858965444
            yaw: 1.300970667769438
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.15284430462221063
          y: -0.17601648933337546
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.021485419460036792
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0013508718320396525
            roll: 0.0
            pitch: 0.0
            yaw: 0.06939350532066801
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.001108068336984576
            roll: 0.0
            pitch: 0.0
            yaw: 0.12533707944994044
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0090369654837299
            roll: 0.0
            pitch: 0.0
            yaw: 0.17296262960089642
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.021313484792276304
            roll: 0.0
            pitch: 0.0
            yaw: 0.12993430500711628
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.00638988722458359
            roll: 0.0
            pitch: 0.0
            yaw: 0.17187413859969347
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04271681104514009
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.052495693264824936
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.000627303690289932
            roll: 0.0
            pitch: 0.0
            yaw: -0.40525095771287334
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.01804080028831355
            roll: 0.0
            pitch: 0.0
            yaw: 0.6118241465089926
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.036917622854739346
            roll: 0.0
            pitch: 0.0
            yaw: 1.0391654282611025
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0437009859486068
            roll: 0.0
            pitch: 0.0
            yaw: -0.5860357374992138
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07131128448382906
            roll: 0.0
            pitch: 0.0
            yaw: 0.8246779639776705
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05525996807039546
            roll: 0.0
            pitch: 0.0
            yaw: -0.04895208460667633
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0009410369637120916
              y: 0.016603912369041157
              z: 0.04258195014213434
              roll: 0.470222195312774
              pitch: -0.4562619123575045
              yaw: 1.3130080439779308
            roll: 0.4615821303334478
            pitch: -0.4685803199647943
            yaw: 1.3360791910957288
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.13521756182136857
          y: -0.20444478057428347
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.13495348707747923
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.02121466725881043
            roll: 0.0
            pitch: 0.0
            yaw: -0.05306065634358724
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.005433591566248494
            roll: 0.0
            pitch: 0.0
            yaw: 0.16616853342972387
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.003443168793411753
            roll: 0.0
            pitch: 0.0
            yaw: 0.1644260876250357
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01133348651051122
            roll: 0.0
            pitch: 0.0
            yaw: -0.03431051461994719
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.014947361314173457
            roll: 0.0
            pitch: 0.0
            yaw: 0.10880659571280482
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02560003078596893
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0435435224467392
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.008874055410006604
            roll: 0.0
            pitch: 0.0
            yaw: -0.0639107784660049
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05214769411297024
            roll: 0.0
            pitch: 0.0
            yaw: -0.245420272996268
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.024670785694487607
            roll: 0.0
            pitch: 0.0
            yaw: -0.3347397623711641
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08937465476459786
            roll: 0.0
            pitch: 0.0
            yaw: -0.14405494384670592
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.061702431794336945
            roll: 0.0
            pitch: 0.0
            yaw: 0.9048278808538506
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07544411452157755
            roll: 0.0
            pitch: 0.0
            yaw: 1.0379384919735883
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0014281437022133697
              y: 0.01545399368987258
              z: 0.044185549216464434
              roll: 0.44642538861420705
              pitch: -0.5170460215960547
              yaw: 1.35412143621872
            roll: 0.4558084998010032
            pitch: -0.4945129733150547
            yaw: 1.2984868888889853
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
