scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2920330326886891
          y: -0.2877842847999565
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.21951542457064244
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.004693095888448063
            roll: 0.0
            pitch: 0.0
            yaw: -0.10464662564214382
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.021864624251769466
            roll: 0.0
            pitch: 0.0
            yaw: -0.017448930520035183
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0052538264561688315
            roll: 0.0
            pitch: 0.0
            yaw: -0.14057967252246958
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.020741358560270207
            roll: 0.0
            pitch: 0.0
            yaw: 0.12790081115268698
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.016148001245704688
            roll: 0.0
            pitch: 0.0
            yaw: 0.027357336231904866
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.007848358444674589
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04307793669065636
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.058096418014310675
            roll: 0.0
            pitch: 0.0
            yaw: -0.7825476859752074
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05478385063134053
            roll: 0.0
            pitch: 0.0
            yaw: 0.5748805099694678
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06012432936221372
            roll: 0.0
            pitch: 0.0
            yaw: -1.019029512226852
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.023947124063305777
            roll: 0.0
            pitch: 0.0
            yaw: 0.7362868225621253
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07268806601786891
            roll: 0.0
            pitch: 0.0
            yaw: -0.6851369338517252
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06982599788485608
            roll: 0.0
            pitch: 0.0
            yaw: 0.4502184866662915
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0017314088263586042
              y: 0.016826939818598233
              z: 0.042774755189972424
              roll: 0.45502101811828066
              pitch: -0.4635557834982336
              yaw: 1.3218268546788348
            roll: 0.4214805041734122
            pitch: -0.5074089204241781
            yaw: 1.3372990283066732
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2563454092265237
          y: -0.22135104896101698
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.33474016226011705
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0038159065464011856
            roll: 0.0
            pitch: 0.0
            yaw: -0.08158349079333119
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01771863490466832
            roll: 0.0
            pitch: 0.0
            yaw: 0.0759096519204755
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.001520863293573562
            roll: 0.0
            pitch: 0.0
            yaw: -0.10893165583469416
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.006368143262840922
            roll: 0.0
            pitch: 0.0
            yaw: 0.13666401428251518
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0028514526046008216
            roll: 0.0
            pitch: 0.0
            yaw: 0.13909936638290588
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05448676259112058
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0394097227094523
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07994983114538776
            roll: 0.0
            pitch: 0.0
            yaw: 0.8691223592437953
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.010623812106704378
            roll: 0.0
            pitch: 0.0
            yaw: -0.38629778802861503
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03754385060598343
            roll: 0.0
            pitch: 0.0
            yaw: 0.2036627689068553
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05258416380197849
            roll: 0.0
            pitch: 0.0
            yaw: -1.0177346685215864
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05379439840799576
            roll: 0.0
            pitch: 0.0
            yaw: 0.755877003082126
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.028718875758361198
            roll: 0.0
            pitch: 0.0
            yaw: -0.11119980411280184
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00036784550565592414
              y: 0.01685619294863532
              z: 0.04266381473461564
              roll: 0.4326854319971712
              pitch: -0.47678369891871575
              yaw: 1.363276623563238
            roll: 0.46639979471059034
            pitch: -0.501738986665936
            yaw: 1.3442342828733587
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.23474360594511365
          y: -0.16801585394025387
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.11974018440348588
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.018939409449017116
            roll: 0.0
            pitch: 0.0
            yaw: -0.07985618578728781
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0023251290981492444
            roll: 0.0
            pitch: 0.0
            yaw: -0.12718771242650834
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.004255513657892278
            roll: 0.0
            pitch: 0.0
            yaw: 0.15007126759397676
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.017263058379976895
            roll: 0.0
            pitch: 0.0
            yaw: -0.05119088081481893
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.020524641644901274
            roll: 0.0
            pitch: 0.0
            yaw: -0.06910512804331216
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0053727976858955195
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0010864111340000149
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.018692209625832013
            roll: 0.0
            pitch: 0.0
            yaw: -0.06540374843773544
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.004906397806453508
            roll: 0.0
            pitch: 0.0
            yaw: -0.5199084474349764
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.011888028004131232
            roll: 0.0
            pitch: 0.0
            yaw: -0.47550717132274334
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05919265741507172
            roll: 0.0
            pitch: 0.0
            yaw: -0.18436256569568088
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08400537454208845
            roll: 0.0
            pitch: 0.0
            yaw: 0.6805545473023653
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.01672521933556302
            roll: 0.0
            pitch: 0.0
            yaw: 0.7190978168622564
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.000390230844189991
              y: 0.014055217382772588
              z: 0.042505925872556145
              roll: 0.46081830688924985
              pitch: -0.47814389243987343
              yaw: 1.3188135986660332
            roll: 0.43990912404812726
            pitch: -0.4486415620356785
            yaw: 1.3041762440625637
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
