scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2920330326886891
          y: -0.2877842847999565
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.21951542457064244
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.004693095888448063
            roll: 0.0
            pitch: 0.0
            yaw: -0.10464662564214382
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.021864624251769466
            roll: 0.0
            pitch: 0.0
            yaw: -0.017448930520035183
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0052538264561688315
            roll: 0.0
            pitch: 0.0
            yaw: -0.14057967252246958
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.020741358560270207
            roll: 0.0
            pitch: 0.0
            yaw: 0.12790081115268698
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.016148001245704688
            roll: 0.0
            pitch: 0.0
            yaw: 0.027357336231904866
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.007848358444674589
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04307793669065636
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.058096418014310675
            roll: 0.0
            pitch: 0.0
            yaw: -0.7825476859752074
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05478385063134053
            roll: 0.0
            pitch: 0.0
            yaw: 0.5748805099694678
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06012432936221372
            roll: 0.0
            pitch: 0.0
            yaw: -1.019029512226852
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.023947124063305777
            roll: 0.0
            pitch: 0.0
            yaw: 0.7362868225621253
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07268806601786891
            roll: 0.0
            pitch: 0.0
            yaw: -0.6851369338517252
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06982599788485608
            roll: 0.0
            pitch: 0.0
            yaw: 0.4502184866662915
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0015104321313135355
              y: 0.01399695498208136
              z: 0.04385989119608726
              roll: 0.4266946006897269
              pitch: -0.5162231913542339
              yaw: 1.2904135030513617
            roll: 0.4214805041734122
            pitch: -0.5074089204241781
            yaw: 1.3372990283066732
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1325551859962312
          y: -0.23241947147859032
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4000015032048717
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01470293156822846
            roll: 0.0
            pitch: 0.0
            yaw: -0.04877549551189164
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010062234417789293
            roll: 0.0
            pitch: 0.0
            yaw: 0.07057331797515357
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.011134433534849605
            roll: 0.0
            pitch: 0.0
            yaw: -0.06862311711982015
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.004259656611455814
            roll: 0.0
            pitch: 0.0
            yaw: -0.04451593846376145
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.005736264623005107
            roll: 0.0
            pitch: 0.0
            yaw: -0.15223592179450116
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0559048383410548
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.016528221624662345
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05079268054426704
            roll: 0.0
            pitch: 0.0
            yaw: 0.029041377101123533
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07140860760225232
            roll: 0.0
            pitch: 0.0
            yaw: 0.49499362400638525
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.006186741726012163
            roll: 0.0
            pitch: 0.0
            yaw: 0.8634031109951381
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09271611358033494
            roll: 0.0
            pitch: 0.0
            yaw: -0.7229647011127724
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.047700569948796456
            roll: 0.0
            pitch: 0.0
            yaw: -0.5868193950083518
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07560203322110248
            roll: 0.0
            pitch: 0.0
            yaw: 0.32161674415475683
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0005891804526564938
              y: 0.014307300155287672
              z: 0.04160969849527992
              roll: 0.4734595590875876
              pitch: -0.4663544241338404
              yaw: 1.3323795280057793
            roll: 0.45731492645506605
            pitch: -0.44676324332759104
            yaw: 1.3136288831661644
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.20938161815175832
          y: -0.22754066246153964
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.45172848419080247
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0022473997869664336
            roll: 0.0
            pitch: 0.0
            yaw: 0.11252731748199296
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.012705024822654624
            roll: 0.0
            pitch: 0.0
            yaw: 0.13202040471340648
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.016109639741354972
            roll: 0.0
            pitch: 0.0
            yaw: -0.07224864809754417
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.012728723984388499
            roll: 0.0
            pitch: 0.0
            yaw: 0.07872316586831818
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0023968140300502858
            roll: 0.0
            pitch: 0.0
            yaw: 0.14747552279630416
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05704830339192006
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05798604410334047
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05350237732012441
            roll: 0.0
            pitch: 0.0
            yaw: 1.0185987247412898
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.02566450229806931
            roll: 0.0
            pitch: 0.0
            yaw: 0.46877047977694075
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07494528085627361
            roll: 0.0
            pitch: 0.0
            yaw: 0.43718650168444895
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0012706191941142392
            roll: 0.0
            pitch: 0.0
            yaw: 0.8668181652191009
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0016855376225582974
            roll: 0.0
            pitch: 0.0
            yaw: -0.74087890487767
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03699215098102135
            roll: 0.0
            pitch: 0.0
            yaw: -0.7042618058750807
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0005860841395519813
              y: 0.015774157027654452
              z: 0.040538242933299114
              roll: 0.47050709912772315
              pitch: -0.5074680455140593
              yaw: 1.342194707053051
            roll: 0.4344129017197082
            pitch: -0.5119148417595784
            yaw: 1.351659978320673
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
