scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2507722636612417
          y: -0.12388441522998109
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4681005843151017
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.003486486045312112
            roll: 0.0
            pitch: 0.0
            yaw: 0.035555846655542095
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01180306203112691
            roll: 0.0
            pitch: 0.0
            yaw: 0.03440426167145666
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0023228499851325433
            roll: 0.0
            pitch: 0.0
            yaw: 0.16090559014515238
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.004536839686631641
            roll: 0.0
            pitch: 0.0
            yaw: 0.061173276454884795
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.002012831206906606
            roll: 0.0
            pitch: 0.0
            yaw: 0.16818607554498055
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05083775446100007
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04446792836090735
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08400735692997299
            roll: 0.0
            pitch: 0.0
            yaw: -0.7081973193766709
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.06348997840525045
            roll: 0.0
            pitch: 0.0
            yaw: -0.9494464873905564
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03796770646353076
            roll: 0.0
            pitch: 0.0
            yaw: -0.3084068268076362
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03809333010803029
            roll: 0.0
            pitch: 0.0
            yaw: -0.0880451049451969
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08363291661165106
            roll: 0.0
            pitch: 0.0
            yaw: -0.4616164665493535
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0784004443168024
            roll: 0.0
            pitch: 0.0
            yaw: 0.670679299360277
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.000762293417844741
              y: 0.015273576203462955
              z: 0.04224516931504166
              roll: 0.4309531203923958
              pitch: -0.48483942788524037
              yaw: 1.3559875798340122
            roll: 0.4390952935473614
            pitch: -0.4776412438199628
            yaw: 1.3554192431218193
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.15280657361409294
          y: -0.20905038049466315
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.07115089471858527
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.005812687230312891
            roll: 0.0
            pitch: 0.0
            yaw: 0.024908352658441435
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.013430494830942032
            roll: 0.0
            pitch: 0.0
            yaw: -0.095961771507314
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.00775382595494202
            roll: 0.0
            pitch: 0.0
            yaw: 0.14953155585048072
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.004357376298064382
            roll: 0.0
            pitch: 0.0
            yaw: 0.041074153302863264
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.013144697694236335
            roll: 0.0
            pitch: 0.0
            yaw: 0.04093791855082282
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.019426340094257713
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02142582147301858
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.01566130707669809
            roll: 0.0
            pitch: 0.0
            yaw: 0.43953281016447976
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.004745859250589277
            roll: 0.0
            pitch: 0.0
            yaw: 0.01221273645073806
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.052707805198407676
            roll: 0.0
            pitch: 0.0
            yaw: -0.9094956837134534
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04997192878969184
            roll: 0.0
            pitch: 0.0
            yaw: -0.8432299547388521
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07015824535472034
            roll: 0.0
            pitch: 0.0
            yaw: -0.6929483805322887
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.014819657310453468
            roll: 0.0
            pitch: 0.0
            yaw: -0.355516537421541
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0015829725513057343
              y: 0.014005769188963456
              z: 0.041731722056111864
              roll: 0.42167101584415884
              pitch: -0.4539606215862651
              yaw: 1.2991500095648443
            roll: 0.448923151580801
            pitch: -0.49222503858965444
            yaw: 1.300970667769438
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.14581943489180033
          y: -0.23972387044043264
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.28915620929343755
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.017301729226769043
            roll: 0.0
            pitch: 0.0
            yaw: 0.02546278515975292
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0074139854509397245
            roll: 0.0
            pitch: 0.0
            yaw: -0.023018047679072118
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0046103816703007665
            roll: 0.0
            pitch: 0.0
            yaw: 0.15772599930781644
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.011722918976636939
            roll: 0.0
            pitch: 0.0
            yaw: -0.06647086910188077
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.002056724229674123
            roll: 0.0
            pitch: 0.0
            yaw: -0.09514701622614694
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.050824559477992304
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.02154127668885806
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0022383612645630047
            roll: 0.0
            pitch: 0.0
            yaw: 0.8249694880262302
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.005874925419951868
            roll: 0.0
            pitch: 0.0
            yaw: 0.9526505172567887
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.045866892641694794
            roll: 0.0
            pitch: 0.0
            yaw: 0.7965244407702219
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.09367529867178856
            roll: 0.0
            pitch: 0.0
            yaw: -0.2328822285167057
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08901183110934743
            roll: 0.0
            pitch: 0.0
            yaw: -0.8117882525260456
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06769021618307455
            roll: 0.0
            pitch: 0.0
            yaw: 0.5247462966978871
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0005574121462301684
              y: 0.01685708792330469
              z: 0.04368027015546965
              roll: 0.4358038154369861
              pitch: -0.4648616405889716
              yaw: 1.3191048346014251
            roll: 0.418020303384083
            pitch: -0.5051420433508663
            yaw: 1.3538867408183657
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
