scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.19184116125644435
          y: -0.1946807622850606
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.10889417670153811
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.011516981242908744
            roll: 0.0
            pitch: 0.0
            yaw: -0.160181239729457
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010332934130112298
            roll: 0.0
            pitch: 0.0
            yaw: -0.03569016235378061
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0006627418236519814
            roll: 0.0
            pitch: 0.0
            yaw: -0.06854349980214071
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0011293873065401847
            roll: 0.0
            pitch: 0.0
            yaw: -0.03229073725861578
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01377927436027733
            roll: 0.0
            pitch: 0.0
            yaw: 0.061877776968566695
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.026939587772281795
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.00884301864420154
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.02495767803715339
            roll: 0.0
            pitch: 0.0
            yaw: -0.31487199308330194
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08989584226973633
            roll: 0.0
            pitch: 0.0
            yaw: 0.8662772162239167
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.037479144076528165
            roll: 0.0
            pitch: 0.0
            yaw: -0.4154730042710052
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08019321977184932
            roll: 0.0
            pitch: 0.0
            yaw: -0.8796897368538431
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07492455709238055
            roll: 0.0
            pitch: 0.0
            yaw: -0.9493189138420248
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08346862641841996
            roll: 0.0
            pitch: 0.0
            yaw: 0.6296246862606587
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0017892996706281592
              y: 0.01468637667045716
              z: 0.04133302981214243
              roll: 0.4827605482279411
              pitch: -0.4524744046024116
              yaw: 1.3549676344292647
            roll: 0.4789347461679028
            pitch: -0.49704267136347297
            yaw: 1.2949085754295615
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1464309157673331
          y: -0.25159769721674635
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.2931683234772148
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01469229182059416
            roll: 0.0
            pitch: 0.0
            yaw: 0.11129971856840776
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006773992140780208
            roll: 0.0
            pitch: 0.0
            yaw: -0.07325141405832082
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.016517542023262617
            roll: 0.0
            pitch: 0.0
            yaw: -0.12090118967366012
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01690910088575126
            roll: 0.0
            pitch: 0.0
            yaw: 0.04083418519172158
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.004756498136762852
            roll: 0.0
            pitch: 0.0
            yaw: -0.050715682209565585
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04108510266058109
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.046863136709993244
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06635536975235516
            roll: 0.0
            pitch: 0.0
            yaw: -0.6715837876471705
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08689655924832973
            roll: 0.0
            pitch: 0.0
            yaw: -0.4851443078446064
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08070917959326687
            roll: 0.0
            pitch: 0.0
            yaw: 0.24999476783528451
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05292938305687309
            roll: 0.0
            pitch: 0.0
            yaw: 0.34318809459588717
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.020157419994369985
            roll: 0.0
            pitch: 0.0
            yaw: -0.7690199668544543
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09592262906418396
            roll: 0.0
            pitch: 0.0
            yaw: 0.7637954990253915
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0007847922530151057
              y: 0.013731797939122733
              z: 0.043485952690042885
              roll: 0.40487848668408244
              pitch: -0.44550781065040745
              yaw: 1.300131184823743
            roll: 0.4760272540801035
            pitch: -0.48986468087574364
            yaw: 1.3228059419719056
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.19318401382377987
          y: -0.1026213554195552
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.011869354079894978
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.00788035644158849
            roll: 0.0
            pitch: 0.0
            yaw: 0.055643344807708356
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.02281243027646309
            roll: 0.0
            pitch: 0.0
            yaw: -0.15464449550962747
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0004961226928569713
            roll: 0.0
            pitch: 0.0
            yaw: -0.15791078364368422
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012991431610585509
            roll: 0.0
            pitch: 0.0
            yaw: -0.061849858179758646
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.00415730411451521
            roll: 0.0
            pitch: 0.0
            yaw: -0.11411687053929614
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03826207654766077
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05898808187738001
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.037315405699460576
            roll: 0.0
            pitch: 0.0
            yaw: 0.846124533308678
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04454595589798588
            roll: 0.0
            pitch: 0.0
            yaw: -1.0097905832531975
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.00023413335853179895
            roll: 0.0
            pitch: 0.0
            yaw: 1.027057861656006
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06962642380882886
            roll: 0.0
            pitch: 0.0
            yaw: -1.0378879356657715
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03289930341700609
            roll: 0.0
            pitch: 0.0
            yaw: -0.7182277664621748
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04298933232854821
            roll: 0.0
            pitch: 0.0
            yaw: -0.48432589502661094
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0011024265590921915
              y: 0.015969914047787883
              z: 0.04106122931180223
              roll: 0.45893856251444254
              pitch: -0.4979624276904117
              yaw: 1.3477337416122697
            roll: 0.4579939973646355
            pitch: -0.451877324068329
            yaw: 1.3152095064615998
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
