scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2072777650216031
          y: -0.2704075892535939
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.05514818434136115
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.021342009747556415
            roll: 0.0
            pitch: 0.0
            yaw: -0.09631665443444698
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006159704724032149
            roll: 0.0
            pitch: 0.0
            yaw: -0.14001959884652743
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.009372663584564005
            roll: 0.0
            pitch: 0.0
            yaw: -0.17024984968501
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.006493486087098665
            roll: 0.0
            pitch: 0.0
            yaw: 0.02064415869157238
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.006630977830737968
            roll: 0.0
            pitch: 0.0
            yaw: -0.1295697965714274
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02007998550431732
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.035833282661330665
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0629956975360523
            roll: 0.0
            pitch: 0.0
            yaw: 0.141967616249012
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07481990908238051
            roll: 0.0
            pitch: 0.0
            yaw: 0.9747378542739
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.037392009513389834
            roll: 0.0
            pitch: 0.0
            yaw: -0.4453557036081017
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.002931757250289671
            roll: 0.0
            pitch: 0.0
            yaw: -0.48019673060303325
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.040248520348319106
            roll: 0.0
            pitch: 0.0
            yaw: 0.8498050344419363
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.004021562150060165
            roll: 0.0
            pitch: 0.0
            yaw: -0.2745947268525508
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0008513461110921682
              y: 0.016502360700778866
              z: 0.0413759382498043
              roll: 0.4603771639329478
              pitch: -0.5173732918681471
              yaw: 1.3389172940278442
            roll: 0.41089588473203836
            pitch: -0.4715979485801589
            yaw: 1.3574145028046931
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.15714078844798154
          y: -0.2757572721579994
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.3415374993808318
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.00016430967589621884
            roll: 0.0
            pitch: 0.0
            yaw: 0.14748106839236047
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0064053887191649565
            roll: 0.0
            pitch: 0.0
            yaw: -0.10979524955535515
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.008055642488450924
            roll: 0.0
            pitch: 0.0
            yaw: 0.1745722287980372
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.014584921819472407
            roll: 0.0
            pitch: 0.0
            yaw: 0.1726596366143806
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.013542422880832395
            roll: 0.0
            pitch: 0.0
            yaw: 0.061434413915448155
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.016701932235916067
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03140320332792618
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0022927344572569175
            roll: 0.0
            pitch: 0.0
            yaw: -0.18630801074240622
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08716133209578425
            roll: 0.0
            pitch: 0.0
            yaw: 0.29400616296388504
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09582797552717484
            roll: 0.0
            pitch: 0.0
            yaw: -0.8121344205705959
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.046113139086328914
            roll: 0.0
            pitch: 0.0
            yaw: 0.16879867697074458
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05054165308216707
            roll: 0.0
            pitch: 0.0
            yaw: -0.22459372583068926
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.00469196805674732
            roll: 0.0
            pitch: 0.0
            yaw: 1.031846017572631
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0008291479554535137
              y: 0.01506065091321291
              z: 0.04274069886671597
              roll: 0.4634605980338966
              pitch: -0.5103712004421671
              yaw: 1.307217901397444
            roll: 0.4307535802451856
            pitch: -0.5152163185512629
            yaw: 1.3380375060244039
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2214091394481399
          y: -0.25375265402376757
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.18137660838695124
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0067653244198787495
            roll: 0.0
            pitch: 0.0
            yaw: 0.05520296027636598
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.004800314006862087
            roll: 0.0
            pitch: 0.0
            yaw: 0.01888220307381369
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.013837113755035439
            roll: 0.0
            pitch: 0.0
            yaw: 0.03515511514532685
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.005280272040102143
            roll: 0.0
            pitch: 0.0
            yaw: 0.10653305590493983
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.005450016817681265
            roll: 0.0
            pitch: 0.0
            yaw: -0.1384098401393829
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03358318708855364
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.043426554383324364
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08254220174555318
            roll: 0.0
            pitch: 0.0
            yaw: -0.7707808197156923
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.040540838600528706
            roll: 0.0
            pitch: 0.0
            yaw: -0.758295036227511
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05432572956006418
            roll: 0.0
            pitch: 0.0
            yaw: 0.5152340681923293
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.040838128377931195
            roll: 0.0
            pitch: 0.0
            yaw: 0.06765627593577173
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.04494051196937632
            roll: 0.0
            pitch: 0.0
            yaw: -0.862140679561985
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.024793740029998637
            roll: 0.0
            pitch: 0.0
            yaw: 0.8401704821549967
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.00014329221004149087
              y: 0.01532462679825818
              z: 0.04297447687759201
              roll: 0.42842137659132185
              pitch: -0.4559125820342636
              yaw: 1.342972066566389
            roll: 0.42326812781566914
            pitch: -0.5079202326825435
            yaw: 1.3206127457792098
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
