scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.22522648450401142
          y: -0.13371869041364526
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.0698502249502383
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.013336944896524969
            roll: 0.0
            pitch: 0.0
            yaw: -0.12683389705774695
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.00506249992170138
            roll: 0.0
            pitch: 0.0
            yaw: -0.10214931159883464
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0028682179423665417
            roll: 0.0
            pitch: 0.0
            yaw: -0.020352819887291346
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.021413342639660958
            roll: 0.0
            pitch: 0.0
            yaw: -0.11320308053238508
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.010803242831178944
            roll: 0.0
            pitch: 0.0
            yaw: 0.10382759873776526
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.007738903985525056
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0037738969178314347
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.025778959740063515
            roll: 0.0
            pitch: 0.0
            yaw: -0.09419761171828722
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.02585597364512819
            roll: 0.0
            pitch: 0.0
            yaw: 0.1229147208737491
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04584435730398903
            roll: 0.0
            pitch: 0.0
            yaw: -0.3410106878629747
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07836888670226683
            roll: 0.0
            pitch: 0.0
            yaw: -0.2948834780807762
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05600913974572012
            roll: 0.0
            pitch: 0.0
            yaw: -0.6723699598636732
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07500212040542176
            roll: 0.0
            pitch: 0.0
            yaw: -0.9920917542617668
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0014605336446063362
              y: 0.013984258355079387
              z: 0.04045431959769136
              roll: 0.4050497907608833
              pitch: -0.46958698177822134
              yaw: 1.2975681009066444
            roll: 0.46117427017455037
            pitch: -0.5155849284821725
            yaw: 1.357672611796368
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.12325115584290476
          y: -0.11627062967318355
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4544989760544341
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0016337090766443997
            roll: 0.0
            pitch: 0.0
            yaw: 0.14100717767221116
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.007912905761936234
            roll: 0.0
            pitch: 0.0
            yaw: 0.10939094868297522
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0010178440331425447
            roll: 0.0
            pitch: 0.0
            yaw: 0.04473801711706954
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013723385898949073
            roll: 0.0
            pitch: 0.0
            yaw: 0.14056935858571518
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0004665728578620888
            roll: 0.0
            pitch: 0.0
            yaw: -0.029946469984591717
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04299052956058172
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03698490633719757
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.039320356227740404
            roll: 0.0
            pitch: 0.0
            yaw: 0.046597816511709134
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.042512885920704
            roll: 0.0
            pitch: 0.0
            yaw: 0.763531900907974
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02448421828158076
            roll: 0.0
            pitch: 0.0
            yaw: 0.3067467441169416
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08309117340090474
            roll: 0.0
            pitch: 0.0
            yaw: -0.6893653742199921
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.005027811791921535
            roll: 0.0
            pitch: 0.0
            yaw: 0.18460080699954284
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07900990176063592
            roll: 0.0
            pitch: 0.0
            yaw: 0.6984197034570085
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0016921746316359851
              y: 0.013742062337107203
              z: 0.04328803920034245
              roll: 0.4810627067077538
              pitch: -0.44846360638496774
              yaw: 1.3262185782253963
            roll: 0.4830611493696284
            pitch: -0.4818190748001026
            yaw: 1.2961420467675144
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2513684900915637
          y: -0.2675215008328601
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.48155045330534607
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.022638079972189605
            roll: 0.0
            pitch: 0.0
            yaw: 0.019813634221715393
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.02171671489970705
            roll: 0.0
            pitch: 0.0
            yaw: -0.1628211205115538
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.017269422722365875
            roll: 0.0
            pitch: 0.0
            yaw: 0.11174284208936741
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0013495288169171858
            roll: 0.0
            pitch: 0.0
            yaw: -0.02499426907232244
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.003976305900310947
            roll: 0.0
            pitch: 0.0
            yaw: -0.04014622992505393
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.005222360470833201
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05431346546248507
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.023478002631755368
            roll: 0.0
            pitch: 0.0
            yaw: 0.8726128601133134
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05942507182115961
            roll: 0.0
            pitch: 0.0
            yaw: -0.6864082672596621
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08131822768232802
            roll: 0.0
            pitch: 0.0
            yaw: -1.0419412243611357
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.07842054133364364
            roll: 0.0
            pitch: 0.0
            yaw: 0.63348470498294
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.018673410345559943
            roll: 0.0
            pitch: 0.0
            yaw: 0.8283872786573865
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.007253537943269592
            roll: 0.0
            pitch: 0.0
            yaw: -0.8675522773664701
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0017360651982021938
              y: 0.017096650935997545
              z: 0.044115249788170795
              roll: 0.4310890676845223
              pitch: -0.5153586009107631
              yaw: 1.3077962497707647
            roll: 0.4150234942498122
            pitch: -0.46021368033704885
            yaw: 1.3497705299853158
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
