scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2222883920405858
          y: -0.15164633341921457
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.42639572539886095
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.019361327156571042
            roll: 0.0
            pitch: 0.0
            yaw: -0.09382781045864833
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0044882634520894485
            roll: 0.0
            pitch: 0.0
            yaw: 0.0632560661599374
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.009620750946531073
            roll: 0.0
            pitch: 0.0
            yaw: 0.016484152934208407
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01800054517448583
            roll: 0.0
            pitch: 0.0
            yaw: 0.11856672832920251
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.007946607808747935
            roll: 0.0
            pitch: 0.0
            yaw: -0.1640329160299016
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05378971005362018
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.01908944135248336
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08735900853318725
            roll: 0.0
            pitch: 0.0
            yaw: 0.47892807084696987
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.046391356471351376
            roll: 0.0
            pitch: 0.0
            yaw: 0.04599731122019768
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08237525557546731
            roll: 0.0
            pitch: 0.0
            yaw: 0.6281229828003665
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.029106473407057354
            roll: 0.0
            pitch: 0.0
            yaw: -1.0335373720190266
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.02338788304918865
            roll: 0.0
            pitch: 0.0
            yaw: 0.923754816086694
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07134377861424104
            roll: 0.0
            pitch: 0.0
            yaw: -0.8611113701199496
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0009926284039179284
              y: 0.015456747187788653
              z: 0.04200243647665562
              roll: 0.46216212679263624
              pitch: -0.5201648768757822
              yaw: 1.3303666438735648
            roll: 0.4644539608733409
            pitch: -0.4651246118825987
            yaw: 1.3015086636652016
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2989836953733769
          y: -0.16461664619476982
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.22036960782072956
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.004620272543456903
            roll: 0.0
            pitch: 0.0
            yaw: 0.13687774480715542
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007163855134003333
            roll: 0.0
            pitch: 0.0
            yaw: 0.10403180802489886
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.004221844479258299
            roll: 0.0
            pitch: 0.0
            yaw: -0.11206851057569628
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.019739306388024264
            roll: 0.0
            pitch: 0.0
            yaw: 0.12743721526203217
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0010437468015675848
            roll: 0.0
            pitch: 0.0
            yaw: -0.11011319469288518
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.013038459608306928
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.035386047915432914
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0780384109919523
            roll: 0.0
            pitch: 0.0
            yaw: 0.8802273516592938
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04234969119299417
            roll: 0.0
            pitch: 0.0
            yaw: 0.5030794702778498
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.006911593052162421
            roll: 0.0
            pitch: 0.0
            yaw: -0.7478524273970416
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.025639377860025556
            roll: 0.0
            pitch: 0.0
            yaw: -0.40636980558361
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08882999982784766
            roll: 0.0
            pitch: 0.0
            yaw: 0.5003638258035563
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.09290878289775048
            roll: 0.0
            pitch: 0.0
            yaw: -0.8565804882156184
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0009127778330733315
              y: 0.014084795583291527
              z: 0.041101405152555476
              roll: 0.4066383588296816
              pitch: -0.46578135138056054
              yaw: 1.3052415825838828
            roll: 0.4419625306049697
            pitch: -0.4990156251679515
            yaw: 1.3143439303061137
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.24869804207427118
          y: -0.24438231677665037
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.15405422949986247
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01127004892719128
            roll: 0.0
            pitch: 0.0
            yaw: -0.057526851715708135
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006987702253698557
            roll: 0.0
            pitch: 0.0
            yaw: 0.15705308987407351
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.010214410709317938
            roll: 0.0
            pitch: 0.0
            yaw: -0.10039605990405658
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013306360095326422
            roll: 0.0
            pitch: 0.0
            yaw: 0.1163128044815358
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.00784679209758913
            roll: 0.0
            pitch: 0.0
            yaw: 0.11711826248860635
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.01949974755109228
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.009405633646382597
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.025528771203634226
            roll: 0.0
            pitch: 0.0
            yaw: 0.6851409266061212
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04178157125109105
            roll: 0.0
            pitch: 0.0
            yaw: -0.5547609066954104
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07470241666735827
            roll: 0.0
            pitch: 0.0
            yaw: -0.1331072975865698
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.010059398070174336
            roll: 0.0
            pitch: 0.0
            yaw: 0.5679001440316074
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0605718056177017
            roll: 0.0
            pitch: 0.0
            yaw: 0.10189289728111417
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03865437477167195
            roll: 0.0
            pitch: 0.0
            yaw: -0.47637366143936233
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0007188978095434924
              y: 0.013612925385244943
              z: 0.043458638726483007
              roll: 0.42235552533742377
              pitch: -0.45697421388108905
              yaw: 1.3634139805767538
            roll: 0.4789108515243963
            pitch: -0.47332754319431497
            yaw: 1.3637268237951248
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
