scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.10089753562493811
          y: -0.21925821671686324
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.0018952221425639904
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0063680813110305375
            roll: 0.0
            pitch: 0.0
            yaw: -0.12993297117008645
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01712020899357708
            roll: 0.0
            pitch: 0.0
            yaw: -0.05064010271525511
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.015058392078668078
            roll: 0.0
            pitch: 0.0
            yaw: -0.07997000084197448
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02339447158551764
            roll: 0.0
            pitch: 0.0
            yaw: -0.04883562375017203
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.006591747959459906
            roll: 0.0
            pitch: 0.0
            yaw: -0.027368025122216283
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.024437486734218174
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.009801048074581792
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.04081032948713892
            roll: 0.0
            pitch: 0.0
            yaw: -0.5534605578442109
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07548636718956868
            roll: 0.0
            pitch: 0.0
            yaw: -0.6535577040839967
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07811038538088522
            roll: 0.0
            pitch: 0.0
            yaw: 0.26755045801588073
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05563192222288687
            roll: 0.0
            pitch: 0.0
            yaw: 0.4895499614582026
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08380053748342406
            roll: 0.0
            pitch: 0.0
            yaw: 0.5337183927540714
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08892413708890876
            roll: 0.0
            pitch: 0.0
            yaw: -0.3920991157877247
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00042436881501004605
              y: 0.015311666925946262
              z: 0.04225371409768046
              roll: 0.46557222173033036
              pitch: -0.5050812592938179
              yaw: 1.3009351482379126
            roll: 0.4173996169275483
            pitch: -0.4808599173764917
            yaw: 1.2961609215020666
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2924727096513759
          y: -0.27815623148725604
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.40594876908874156
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01645352069901093
            roll: 0.0
            pitch: 0.0
            yaw: -0.09389194191889216
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.010600984646763251
            roll: 0.0
            pitch: 0.0
            yaw: -0.12496947306633446
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.013132069910139703
            roll: 0.0
            pitch: 0.0
            yaw: 0.05039622885376005
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012752334697257277
            roll: 0.0
            pitch: 0.0
            yaw: 0.04502145365792856
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.022140350241238956
            roll: 0.0
            pitch: 0.0
            yaw: 0.11450232964028789
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.014191393651612982
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.02752008908487822
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.050620474734889676
            roll: 0.0
            pitch: 0.0
            yaw: 0.3740216495655251
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.010890633743314004
            roll: 0.0
            pitch: 0.0
            yaw: 1.038326087192537
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02790127747527303
            roll: 0.0
            pitch: 0.0
            yaw: 0.8025368260589791
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04097650754445817
            roll: 0.0
            pitch: 0.0
            yaw: 0.4684186738284313
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.013448051100646077
            roll: 0.0
            pitch: 0.0
            yaw: 0.5697579167700877
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06194203080921776
            roll: 0.0
            pitch: 0.0
            yaw: -0.6047725326147193
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0005534347181475523
              y: 0.014230961145432996
              z: 0.04099834139150152
              roll: 0.412217676853046
              pitch: -0.4518366760170529
              yaw: 1.339511538550812
            roll: 0.47834139766632977
            pitch: -0.48820344088455425
            yaw: 1.3136885896720407
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.25618256421404695
          y: -0.12700355068229982
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.17462396582934447
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0019527811604195013
            roll: 0.0
            pitch: 0.0
            yaw: 0.13721800680376495
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0012760764905766428
            roll: 0.0
            pitch: 0.0
            yaw: -0.07693337931197552
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.007778570713891599
            roll: 0.0
            pitch: 0.0
            yaw: -0.052733340193013886
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01348911129144547
            roll: 0.0
            pitch: 0.0
            yaw: 0.12745827811409333
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.015816771596560683
            roll: 0.0
            pitch: 0.0
            yaw: -0.13468952956955024
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.059721650403783445
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03112710081946561
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.04014908105447737
            roll: 0.0
            pitch: 0.0
            yaw: 0.26638365893245397
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.01068930505745222
            roll: 0.0
            pitch: 0.0
            yaw: -0.3910670341069489
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.054405302627906604
            roll: 0.0
            pitch: 0.0
            yaw: -0.5927438154609522
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.059143041130368806
            roll: 0.0
            pitch: 0.0
            yaw: 0.9628896758509244
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.001516072863556317
            roll: 0.0
            pitch: 0.0
            yaw: 0.5071833678515287
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.02949935655453105
            roll: 0.0
            pitch: 0.0
            yaw: -0.49013532637906376
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0017569206552552994
              y: 0.014104702882797653
              z: 0.04365444448930008
              roll: 0.42310421123581715
              pitch: -0.4970465836157755
              yaw: 1.3136012758843207
            roll: 0.4550337845385265
            pitch: -0.45739852448439755
            yaw: 1.3126548075809945
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
