scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.16568512666075225
          y: -0.29327002307692773
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4497230039609721
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.018243050995114148
            roll: 0.0
            pitch: 0.0
            yaw: 0.05264869056924429
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006143342642824526
            roll: 0.0
            pitch: 0.0
            yaw: -0.1098317129153402
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.017129620700619744
            roll: 0.0
            pitch: 0.0
            yaw: -0.1607461083347918
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.004897503170180353
            roll: 0.0
            pitch: 0.0
            yaw: 0.06483410337516085
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01806301252056159
            roll: 0.0
            pitch: 0.0
            yaw: 0.08369299876686997
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.025512945413437127
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02448904783524375
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04348650325354547
            roll: 0.0
            pitch: 0.0
            yaw: -0.630406920460659
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04417729159375958
            roll: 0.0
            pitch: 0.0
            yaw: -0.7599980818497616
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.033290309705944016
            roll: 0.0
            pitch: 0.0
            yaw: 0.9728572428095157
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.051129726601897046
            roll: 0.0
            pitch: 0.0
            yaw: 0.44110491563321075
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.09510378877725996
            roll: 0.0
            pitch: 0.0
            yaw: 0.20218811447775442
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.005899726014184731
            roll: 0.0
            pitch: 0.0
            yaw: -0.2139077492291681
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0007389234112195374
              y: 0.015143672059325167
              z: 0.042500436531074964
              roll: 0.42127791960819777
              pitch: -0.5018968112638778
              yaw: 1.2972172293309474
            roll: 0.4102786314225317
            pitch: -0.5015190239079893
            yaw: 1.3666748602685463
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.14804497804304814
          y: -0.25488609643871674
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.29450649631689785
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.020980202322762806
            roll: 0.0
            pitch: 0.0
            yaw: -0.12749576542961324
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.017327190917738988
            roll: 0.0
            pitch: 0.0
            yaw: 0.13639059629298672
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.006994331399579539
            roll: 0.0
            pitch: 0.0
            yaw: -0.004897938944303293
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.021029491521705232
            roll: 0.0
            pitch: 0.0
            yaw: -0.11314434655815797
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01696544762999095
            roll: 0.0
            pitch: 0.0
            yaw: -0.05241834323608745
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05246907287136021
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.018554416877632686
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.057620520750747965
            roll: 0.0
            pitch: 0.0
            yaw: -0.8361287240736506
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.005415494466515347
            roll: 0.0
            pitch: 0.0
            yaw: 0.8887190337190232
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07870722630131305
            roll: 0.0
            pitch: 0.0
            yaw: -0.5484639591433182
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08960547065379748
            roll: 0.0
            pitch: 0.0
            yaw: -0.6823970810676641
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05841666531346809
            roll: 0.0
            pitch: 0.0
            yaw: 0.9088656888447162
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05108053774528476
            roll: 0.0
            pitch: 0.0
            yaw: -0.633953736247823
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0011753972104668398
              y: 0.014117394743220192
              z: 0.04121504999533931
              roll: 0.4204308807346197
              pitch: -0.45207591974686046
              yaw: 1.296559472360835
            roll: 0.45285414735713525
            pitch: -0.4868360542404803
            yaw: 1.3322652523315115
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.29179701066311375
          y: -0.15393257545186423
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.19571719551790057
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0004814408098295468
            roll: 0.0
            pitch: 0.0
            yaw: 0.1584805419110028
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0033247008342727827
            roll: 0.0
            pitch: 0.0
            yaw: -0.1654253426451025
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0015221902186400953
            roll: 0.0
            pitch: 0.0
            yaw: 0.005108903607679488
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.016640259972258577
            roll: 0.0
            pitch: 0.0
            yaw: -0.01085038984528025
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01601650898613638
            roll: 0.0
            pitch: 0.0
            yaw: -0.06302803603469957
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.045962531234005566
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02932225947069038
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0011928642774681891
            roll: 0.0
            pitch: 0.0
            yaw: 0.3202061949162047
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0524573409051905
            roll: 0.0
            pitch: 0.0
            yaw: -0.9995308306071131
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04067173486759627
            roll: 0.0
            pitch: 0.0
            yaw: -0.7779411994911347
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08842544015534434
            roll: 0.0
            pitch: 0.0
            yaw: -0.803387690407098
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08487011174969464
            roll: 0.0
            pitch: 0.0
            yaw: -0.35700620934157834
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07155847444023938
            roll: 0.0
            pitch: 0.0
            yaw: 0.7164824512332173
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0012483223021966627
              y: 0.016688132156564006
              z: 0.04440779021564583
              roll: 0.403676797223506
              pitch: -0.4470523943644595
              yaw: 1.3277117718427982
            roll: 0.4348968948203434
            pitch: -0.4904050683646016
            yaw: 1.348788651295395
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
