scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.15195385123762056
          y: -0.18507911556074857
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.07275171893318555
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.013125247582529035
            roll: 0.0
            pitch: 0.0
            yaw: -0.07326169175394688
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008620351021704881
            roll: 0.0
            pitch: 0.0
            yaw: 0.12448185661000921
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01633330914100655
            roll: 0.0
            pitch: 0.0
            yaw: 0.07417542813274447
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.011259365781887916
            roll: 0.0
            pitch: 0.0
            yaw: 0.08097812886989675
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.019674578157159537
            roll: 0.0
            pitch: 0.0
            yaw: -0.0839167649838591
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.053667097807297004
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04441330637890075
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.04726353503896799
            roll: 0.0
            pitch: 0.0
            yaw: 0.070618284542596
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.013123679132636332
            roll: 0.0
            pitch: 0.0
            yaw: 0.2557510386741897
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08241936817694179
            roll: 0.0
            pitch: 0.0
            yaw: 0.058400795035897124
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.023653434627960726
            roll: 0.0
            pitch: 0.0
            yaw: -1.023297067550952
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.009948504477790623
            roll: 0.0
            pitch: 0.0
            yaw: 0.13012575496883017
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.026206148731717796
            roll: 0.0
            pitch: 0.0
            yaw: -0.0591009813239064
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0007377926354612731
              y: 0.015035723545231793
              z: 0.04175410682432294
              roll: 0.4153136187770516
              pitch: -0.4571160770538689
              yaw: 1.3475993260712116
            roll: 0.4267857096889318
            pitch: -0.5087860626488795
            yaw: 1.3233060740299498
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.28040354507764786
          y: -0.17824964690742068
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.03851624827296041
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.017231388027146292
            roll: 0.0
            pitch: 0.0
            yaw: -0.03607000126491802
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.016641421046907856
            roll: 0.0
            pitch: 0.0
            yaw: -0.0645473133905652
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.00011027647244968991
            roll: 0.0
            pitch: 0.0
            yaw: 0.14587207978136024
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0038995435076032703
            roll: 0.0
            pitch: 0.0
            yaw: 0.007610938275512208
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.00844186484886425
            roll: 0.0
            pitch: 0.0
            yaw: 0.09177508299170883
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.003105573956580683
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0022212044017376545
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0929533352667431
            roll: 0.0
            pitch: 0.0
            yaw: 0.7198850426327517
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04377098566836457
            roll: 0.0
            pitch: 0.0
            yaw: -0.6582576813599115
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09151275342263354
            roll: 0.0
            pitch: 0.0
            yaw: 0.8051286104382498
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08238673127247281
            roll: 0.0
            pitch: 0.0
            yaw: -0.5861051299109448
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.09104694458545534
            roll: 0.0
            pitch: 0.0
            yaw: 0.9605146442502324
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.027320559546215803
            roll: 0.0
            pitch: 0.0
            yaw: 0.5702356605025496
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0007435969332468106
              y: 0.016991353686143306
              z: 0.04355125578986696
              roll: 0.42441820677356695
              pitch: -0.44901851704574813
              yaw: 1.3321812671906639
            roll: 0.4584512673729186
            pitch: -0.44898613089639094
            yaw: 1.3634616225866258
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.1939271192620417
          y: -0.1849198937581012
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.33132453736072376
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.011541033344461035
            roll: 0.0
            pitch: 0.0
            yaw: -0.05240723960273705
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0022689462221573142
            roll: 0.0
            pitch: 0.0
            yaw: 0.1015865445830405
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.012361036277484078
            roll: 0.0
            pitch: 0.0
            yaw: 0.1003562672033213
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.017471508131371914
            roll: 0.0
            pitch: 0.0
            yaw: -0.0759165001853343
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.012690956694555854
            roll: 0.0
            pitch: 0.0
            yaw: -0.01247820038061509
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.002875633530713753
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.018479309634013202
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.09077339172507129
            roll: 0.0
            pitch: 0.0
            yaw: -0.8330609842751188
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.048786667346735646
            roll: 0.0
            pitch: 0.0
            yaw: 0.2729350742201295
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0067617749868593285
            roll: 0.0
            pitch: 0.0
            yaw: -0.9561859286220529
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.06340575600233195
            roll: 0.0
            pitch: 0.0
            yaw: 0.9641132217231518
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.005373636558264658
            roll: 0.0
            pitch: 0.0
            yaw: 0.5503210460480761
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07271708538544533
            roll: 0.0
            pitch: 0.0
            yaw: -0.4907769888184449
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0018696348022582022
              y: 0.014832562601442063
              z: 0.04046528582432535
              roll: 0.44093265012222627
              pitch: -0.48608791822842873
              yaw: 1.2943087092329795
            roll: 0.42396599004064034
            pitch: -0.4515310515709821
            yaw: 1.3105501177011663
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
