scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1962209721309411
          y: -0.21064399546641738
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.361659866838847
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.011698834489581901
            roll: 0.0
            pitch: 0.0
            yaw: -0.08507011305645022
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.00011676168205662987
            roll: 0.0
            pitch: 0.0
            yaw: -0.07886417879977357
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.016187210162016123
            roll: 0.0
            pitch: 0.0
            yaw: -0.09195134019111009
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0134395143546348
            roll: 0.0
            pitch: 0.0
            yaw: 0.0639714696114275
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.004379905573102815
            roll: 0.0
            pitch: 0.0
            yaw: 0.08409639885177972
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.015181717149190622
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.036524766438348885
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.053306937284033025
            roll: 0.0
            pitch: 0.0
            yaw: -0.5803381961400987
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.029727127570860434
            roll: 0.0
            pitch: 0.0
            yaw: 0.4958481479635688
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07417077393112897
            roll: 0.0
            pitch: 0.0
            yaw: -0.7964474156965162
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03578965853016025
            roll: 0.0
            pitch: 0.0
            yaw: -0.7366162798946129
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.048856027296142954
            roll: 0.0
            pitch: 0.0
            yaw: -0.03107887569394041
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05524317014014293
            roll: 0.0
            pitch: 0.0
            yaw: -1.0328368976899296
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0005538993822369824
              y: 0.01720693022409742
              z: 0.04413955634944988
              roll: 0.4339601569202506
              pitch: -0.48155169731681435
              yaw: 1.3324854196848628
            roll: 0.4185710498363193
            pitch: -0.5065574283038983
            yaw: 1.3156469798838109
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.21219459946931402
          y: -0.18207843441941068
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.08585352638900257
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01957603484210984
            roll: 0.0
            pitch: 0.0
            yaw: 0.04366449663176719
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0038472845199020965
            roll: 0.0
            pitch: 0.0
            yaw: 0.04375897263013129
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.009956695584443079
            roll: 0.0
            pitch: 0.0
            yaw: -0.024872098819753607
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.019257972240522045
            roll: 0.0
            pitch: 0.0
            yaw: -0.08143560016349252
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.013835550115885338
            roll: 0.0
            pitch: 0.0
            yaw: -0.04748305957598528
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04898784547344494
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.007012562543627275
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07275169293030646
            roll: 0.0
            pitch: 0.0
            yaw: 0.7690915565954153
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.02664162011854583
            roll: 0.0
            pitch: 0.0
            yaw: 0.4972614742971646
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02687187154111026
            roll: 0.0
            pitch: 0.0
            yaw: -0.7658846086454523
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04458826536176838
            roll: 0.0
            pitch: 0.0
            yaw: 0.005834496643377873
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08302824901970918
            roll: 0.0
            pitch: 0.0
            yaw: 0.34727058030584423
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03037508241467582
            roll: 0.0
            pitch: 0.0
            yaw: 0.59515853036578
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0007914271573149509
              y: 0.014443432578809976
              z: 0.04193189910872236
              roll: 0.41848289770104136
              pitch: -0.4684717027031336
              yaw: 1.3457625599958185
            roll: 0.4773976211377834
            pitch: -0.5142310206138118
            yaw: 1.364567016624542
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.22076183228503105
          y: -0.15744447583856494
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.0722718639991411
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01793372216640643
            roll: 0.0
            pitch: 0.0
            yaw: -0.08901218481913557
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.015332773885165255
            roll: 0.0
            pitch: 0.0
            yaw: 0.17160336996054876
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.021313312188650416
            roll: 0.0
            pitch: 0.0
            yaw: 0.04838485939277998
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013307446180371737
            roll: 0.0
            pitch: 0.0
            yaw: 0.1270705976058049
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.008626496751277177
            roll: 0.0
            pitch: 0.0
            yaw: -0.06528123748653165
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.029524216275295376
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0479200394439583
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0430456780507871
            roll: 0.0
            pitch: 0.0
            yaw: -0.7297332032242094
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0810449847766305
            roll: 0.0
            pitch: 0.0
            yaw: -0.7949715287737866
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05634685503191156
            roll: 0.0
            pitch: 0.0
            yaw: -0.9942163081275882
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.053551685790807574
            roll: 0.0
            pitch: 0.0
            yaw: -0.022497605730894765
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.012170370209616477
            roll: 0.0
            pitch: 0.0
            yaw: -0.04351567891892594
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.039079412753438604
            roll: 0.0
            pitch: 0.0
            yaw: -0.296818275327152
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0010596192590639373
              y: 0.0171205200157487
              z: 0.0439392793752715
              roll: 0.46202329470276277
              pitch: -0.487793078266761
              yaw: 1.2970061392619816
            roll: 0.46494658579017256
            pitch: -0.5161126471862357
            yaw: 1.3033235409750545
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
