scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.26707598911290914
          y: -0.2746721727122146
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.3933403037382862
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0010383911381935916
            roll: 0.0
            pitch: 0.0
            yaw: -0.01906732414532311
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006768431353569571
            roll: 0.0
            pitch: 0.0
            yaw: -0.0585900148509154
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.020253576887263355
            roll: 0.0
            pitch: 0.0
            yaw: 0.0679775436784947
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.011575297265685743
            roll: 0.0
            pitch: 0.0
            yaw: -0.13199057559789631
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01564747914885122
            roll: 0.0
            pitch: 0.0
            yaw: -0.013047954362870262
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.001031807651219463
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.030915413109955762
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08519303735630938
            roll: 0.0
            pitch: 0.0
            yaw: 0.05161241619969981
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04590800147226727
            roll: 0.0
            pitch: 0.0
            yaw: -0.6915427906505499
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.024918921992626922
            roll: 0.0
            pitch: 0.0
            yaw: -0.14322049168225215
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0367522369422528
            roll: 0.0
            pitch: 0.0
            yaw: 0.3039837879175884
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.008501068281019486
            roll: 0.0
            pitch: 0.0
            yaw: 0.9669115838468725
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04396156143256579
            roll: 0.0
            pitch: 0.0
            yaw: -0.6354116798295529
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0014683312237438696
              y: 0.016023814107900096
              z: 0.04207008774802972
              roll: 0.4087806281299647
              pitch: -0.5194638074183432
              yaw: 1.3279492286024408
            roll: 0.4156587538733596
            pitch: -0.47909791110035677
            yaw: 1.3581141973393704
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2336102320540111
          y: -0.2114856651253742
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.0335214916106491
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.009380357200819416
            roll: 0.0
            pitch: 0.0
            yaw: -0.1583149122010573
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.013071999720391483
            roll: 0.0
            pitch: 0.0
            yaw: 0.140144885401414
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0030394562959313344
            roll: 0.0
            pitch: 0.0
            yaw: 0.1580087581184842
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.020317187558392458
            roll: 0.0
            pitch: 0.0
            yaw: -0.057484277194884165
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01940767379558172
            roll: 0.0
            pitch: 0.0
            yaw: 0.002872337059695085
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05039445465382021
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.018792062821555953
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.09307287482753734
            roll: 0.0
            pitch: 0.0
            yaw: 0.49293678434483623
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.021521035348360654
            roll: 0.0
            pitch: 0.0
            yaw: -0.8983540064220517
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08460204741762699
            roll: 0.0
            pitch: 0.0
            yaw: 0.6498536613263299
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04716903059198019
            roll: 0.0
            pitch: 0.0
            yaw: -0.7048159494711095
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.00866889081285653
            roll: 0.0
            pitch: 0.0
            yaw: -0.04106894842365416
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.051124427002790906
            roll: 0.0
            pitch: 0.0
            yaw: -0.5545855611797816
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0010996485990164531
              y: 0.015359713941522673
              z: 0.04403888945528197
              roll: 0.423308175108312
              pitch: -0.49343457064510843
              yaw: 1.294748640193654
            roll: 0.40619125155504704
            pitch: -0.506513480345034
            yaw: 1.3270942926336289
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.23121815035299223
          y: -0.24132953568957594
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.2967392569593609
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.021882577439493116
            roll: 0.0
            pitch: 0.0
            yaw: 0.04737084726578006
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01828661210748391
            roll: 0.0
            pitch: 0.0
            yaw: 0.051161475178731625
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.018320310707632622
            roll: 0.0
            pitch: 0.0
            yaw: 0.034648434959102276
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0180172568718108
            roll: 0.0
            pitch: 0.0
            yaw: 0.16509929321132294
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01782758715416543
            roll: 0.0
            pitch: 0.0
            yaw: 0.0988991573841776
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04946549155668645
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04770620598229304
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05567377461833214
            roll: 0.0
            pitch: 0.0
            yaw: 0.4007409713583847
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.014881904372365362
            roll: 0.0
            pitch: 0.0
            yaw: 0.17224847055857406
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.09130801872207477
            roll: 0.0
            pitch: 0.0
            yaw: -0.6084181768130563
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03461401910332801
            roll: 0.0
            pitch: 0.0
            yaw: 0.3729060869943672
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06271326807568807
            roll: 0.0
            pitch: 0.0
            yaw: -0.016160151768481068
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0029797850442701
            roll: 0.0
            pitch: 0.0
            yaw: -0.9867700932324126
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0006288686646036745
              y: 0.01658495808911391
              z: 0.042196955998002106
              roll: 0.47423089924662376
              pitch: -0.47975968438764344
              yaw: 1.343453583860013
            roll: 0.4272143539476358
            pitch: -0.4832903024864092
            yaw: 1.3446573604356973
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
