scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.28664738700885406
          y: -0.2737011207294607
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.08543137155821068
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.018654390671466355
            roll: 0.0
            pitch: 0.0
            yaw: 0.15800386753457457
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.018800913025206062
            roll: 0.0
            pitch: 0.0
            yaw: 0.029171566851257796
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.015728474511657826
            roll: 0.0
            pitch: 0.0
            yaw: -0.1602847950836905
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.008996637459576299
            roll: 0.0
            pitch: 0.0
            yaw: -0.14787953272384863
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.010773927523141727
            roll: 0.0
            pitch: 0.0
            yaw: -0.09780212220853603
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01640026917983653
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05694316687224498
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.03914455667343579
            roll: 0.0
            pitch: 0.0
            yaw: -0.8787379092450825
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.06348807292856917
            roll: 0.0
            pitch: 0.0
            yaw: -0.0827786224902416
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05287024798916056
            roll: 0.0
            pitch: 0.0
            yaw: 0.8716793531979807
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.06884225989805356
            roll: 0.0
            pitch: 0.0
            yaw: -0.977664250392255
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.030905169809170394
            roll: 0.0
            pitch: 0.0
            yaw: -0.5633483180800705
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0006603127798438246
            roll: 0.0
            pitch: 0.0
            yaw: 0.5404926614299781
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0005819808404018132
              y: 0.015218676269234604
              z: 0.04232802055429877
              roll: 0.4658102131311923
              pitch: -0.46627320179433973
              yaw: 1.348849459621997
            roll: 0.4260492233988383
            pitch: -0.4719666832326244
            yaw: 1.3626232706380919
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.196189916422215
          y: -0.2387032310085902
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.14353382408727022
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.010950873664807799
            roll: 0.0
            pitch: 0.0
            yaw: -0.08667025651328392
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.004981798397138776
            roll: 0.0
            pitch: 0.0
            yaw: 0.023602696842465326
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.004275907659337115
            roll: 0.0
            pitch: 0.0
            yaw: -0.14088994260292476
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0011329566228372029
            roll: 0.0
            pitch: 0.0
            yaw: 0.13790201454440754
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.013044516245753946
            roll: 0.0
            pitch: 0.0
            yaw: 0.11472038432437981
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04015576999702902
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05352043421539998
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.02960266611585738
            roll: 0.0
            pitch: 0.0
            yaw: 0.9178992162522397
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.06686665814511401
            roll: 0.0
            pitch: 0.0
            yaw: 0.6509158421320775
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08970687494447363
            roll: 0.0
            pitch: 0.0
            yaw: -0.9956035469418827
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.040884460015424055
            roll: 0.0
            pitch: 0.0
            yaw: -0.441826927891966
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.011604597215970472
            roll: 0.0
            pitch: 0.0
            yaw: 0.9295718086140843
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09450681754609559
            roll: 0.0
            pitch: 0.0
            yaw: 0.4409724961841901
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 6.212214533140312e-05
              y: 0.016741848817920128
              z: 0.043267222331276785
              roll: 0.41228529850896745
              pitch: -0.4730314477206867
              yaw: 1.3443454557185752
            roll: 0.4331181673372443
            pitch: -0.4552520984869145
            yaw: 1.2944118209812243
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.23354903664324805
          y: -0.15268905778327424
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.05399386949500151
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0024945426140612695
            roll: 0.0
            pitch: 0.0
            yaw: 0.03223294754155348
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.016566925345236697
            roll: 0.0
            pitch: 0.0
            yaw: 0.08269098625895327
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.015756089045641467
            roll: 0.0
            pitch: 0.0
            yaw: -0.05868357837176756
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0028211700538341884
            roll: 0.0
            pitch: 0.0
            yaw: 0.07164758405416913
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0158363880040613
            roll: 0.0
            pitch: 0.0
            yaw: -0.1736781364411514
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.00478382526414204
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0061928212649126485
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.008550385690999543
            roll: 0.0
            pitch: 0.0
            yaw: -0.4754139870051657
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.016328748005260088
            roll: 0.0
            pitch: 0.0
            yaw: -0.6161929865575635
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08455001002331458
            roll: 0.0
            pitch: 0.0
            yaw: 0.025230169556536453
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05709577589415811
            roll: 0.0
            pitch: 0.0
            yaw: 0.013357702924370773
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06247178733737729
            roll: 0.0
            pitch: 0.0
            yaw: 0.6121097209232564
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.019641100333297065
            roll: 0.0
            pitch: 0.0
            yaw: 0.5000211486073309
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0014610120226223257
              y: 0.017316882412131234
              z: 0.04296565800263655
              roll: 0.43927680721605883
              pitch: -0.48382458407848
              yaw: 1.3101859523856347
            roll: 0.4375484704106079
            pitch: -0.5030944165828426
            yaw: 1.3079075855135114
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
