scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2820430007915558
          y: -0.12018453632894252
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.05672812649557335
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0017278036955947484
            roll: 0.0
            pitch: 0.0
            yaw: 0.03230951601479967
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.008312239492298128
            roll: 0.0
            pitch: 0.0
            yaw: 0.11545405741426362
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01505759435886728
            roll: 0.0
            pitch: 0.0
            yaw: -0.14945927179973184
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.019263738011989016
            roll: 0.0
            pitch: 0.0
            yaw: -0.11440715657820286
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.017456868643509517
            roll: 0.0
            pitch: 0.0
            yaw: 0.1134320400588747
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04004027496882839
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.047982143763559235
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08565398192266804
            roll: 0.0
            pitch: 0.0
            yaw: 0.179577706375168
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0516743786925048
            roll: 0.0
            pitch: 0.0
            yaw: -0.23799466221956322
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05878882495532789
            roll: 0.0
            pitch: 0.0
            yaw: -0.7408867350647457
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05633054017531476
            roll: 0.0
            pitch: 0.0
            yaw: 0.6578728161228293
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0013748088187846563
            roll: 0.0
            pitch: 0.0
            yaw: -0.1857003055143902
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.046710441925663294
            roll: 0.0
            pitch: 0.0
            yaw: -0.9218113700287123
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001836119703792852
              y: 0.017121164559931196
              z: 0.04405932332912332
              roll: 0.4418504758285393
              pitch: -0.4536944061097271
              yaw: 1.292151415780475
            roll: 0.44331680621882996
            pitch: -0.49729402458867983
            yaw: 1.3240188505649741
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1051554964001451
          y: -0.12592364631484504
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.01754626566159656
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.008947828705018557
            roll: 0.0
            pitch: 0.0
            yaw: 0.03531016885917446
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.020500080436822485
            roll: 0.0
            pitch: 0.0
            yaw: -0.09298306957444842
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.02308436155085044
            roll: 0.0
            pitch: 0.0
            yaw: -0.12737989479085143
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01693115551380437
            roll: 0.0
            pitch: 0.0
            yaw: 0.031419542185412264
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.010629968730844631
            roll: 0.0
            pitch: 0.0
            yaw: -0.009830600924703586
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.057063100462117794
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.01868096421264394
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06460020754155812
            roll: 0.0
            pitch: 0.0
            yaw: -0.06363923283112749
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.034405913079086525
            roll: 0.0
            pitch: 0.0
            yaw: -0.3703263592523123
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.025682710267513675
            roll: 0.0
            pitch: 0.0
            yaw: -0.8412259543122279
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05750816510040796
            roll: 0.0
            pitch: 0.0
            yaw: -0.7025259900469585
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08757492778577179
            roll: 0.0
            pitch: 0.0
            yaw: -1.008918198593004
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.051680194540707824
            roll: 0.0
            pitch: 0.0
            yaw: 0.47958574770596085
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0012621203831291515
              y: 0.015900454786564187
              z: 0.04066371871866284
              roll: 0.4398702080741264
              pitch: -0.4858570850132749
              yaw: 1.3259701020783632
            roll: 0.4431004090534234
            pitch: -0.4435689899402265
            yaw: 1.3285824517139042
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.22478253990349917
          y: -0.19459131985536637
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.0355103924484671
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.004949439798941923
            roll: 0.0
            pitch: 0.0
            yaw: 0.10457605298151024
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.005917507592788387
            roll: 0.0
            pitch: 0.0
            yaw: -0.10305620120800628
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01782427603038662
            roll: 0.0
            pitch: 0.0
            yaw: 0.0806700011162722
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012782211633849412
            roll: 0.0
            pitch: 0.0
            yaw: -0.0383777455189952
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.013610103422599122
            roll: 0.0
            pitch: 0.0
            yaw: -0.09250576659798508
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.005967079395813708
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.005304497279035238
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.01639335786764018
            roll: 0.0
            pitch: 0.0
            yaw: -0.5514221123340302
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.06981536638729273
            roll: 0.0
            pitch: 0.0
            yaw: 0.6324673220019259
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.035906785541208706
            roll: 0.0
            pitch: 0.0
            yaw: -0.691824491690374
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.038456482203783796
            roll: 0.0
            pitch: 0.0
            yaw: 0.8915306800495415
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06198014265386395
            roll: 0.0
            pitch: 0.0
            yaw: -0.997260915555551
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08218729038448719
            roll: 0.0
            pitch: 0.0
            yaw: 0.7006655132675952
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.00038720669479308913
              y: 0.015177549919957133
              z: 0.040575304557603234
              roll: 0.43631563539028917
              pitch: -0.4446117166744966
              yaw: 1.3589290900330513
            roll: 0.44742198399801064
            pitch: -0.46420673162856513
            yaw: 1.3511513363318384
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
