scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.20809353379310458
          y: -0.10382000289883872
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.0025802190122983237
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.005900925549752916
            roll: 0.0
            pitch: 0.0
            yaw: -0.1350827707930416
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0007596896347829979
            roll: 0.0
            pitch: 0.0
            yaw: 0.04851982000407476
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.004059689018340855
            roll: 0.0
            pitch: 0.0
            yaw: -0.004105947661255632
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013623300660152628
            roll: 0.0
            pitch: 0.0
            yaw: 0.03662554665170489
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0168115310392791
            roll: 0.0
            pitch: 0.0
            yaw: -0.1362668095623629
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.020623132503386023
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03972064162696526
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.01205184986498177
            roll: 0.0
            pitch: 0.0
            yaw: 0.14319170875312492
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.03497932341370488
            roll: 0.0
            pitch: 0.0
            yaw: -0.49039131222486254
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0922481233788531
            roll: 0.0
            pitch: 0.0
            yaw: 0.552891126981272
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04398584776041292
            roll: 0.0
            pitch: 0.0
            yaw: -0.3167605743186356
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07744346144614195
            roll: 0.0
            pitch: 0.0
            yaw: -0.9311237770000698
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.005696653404728247
            roll: 0.0
            pitch: 0.0
            yaw: -0.7778797622393627
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0016512753980597785
              y: 0.01492788876821101
              z: 0.04387562077034836
              roll: 0.4587678813579622
              pitch: -0.47349018232438866
              yaw: 1.3518431804936208
            roll: 0.45791905963604335
            pitch: -0.49417619843132543
            yaw: 1.3241802887728868
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.11751298882244664
          y: -0.13704626183204585
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.0311723977977032
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.017545320463250594
            roll: 0.0
            pitch: 0.0
            yaw: -0.06308577260737663
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010644238382205441
            roll: 0.0
            pitch: 0.0
            yaw: 0.06293913594746106
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.017075269367727578
            roll: 0.0
            pitch: 0.0
            yaw: -0.0438888529736996
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.017893085444537705
            roll: 0.0
            pitch: 0.0
            yaw: 0.049225067324472044
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.005113872842948543
            roll: 0.0
            pitch: 0.0
            yaw: 0.09422387655434888
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.012839448865520124
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.028518545262913267
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08020870845124278
            roll: 0.0
            pitch: 0.0
            yaw: 0.03279208568432046
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.06804407786023256
            roll: 0.0
            pitch: 0.0
            yaw: -0.2654686907537239
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.023980731603462854
            roll: 0.0
            pitch: 0.0
            yaw: -0.07104103245386062
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.027348038506463807
            roll: 0.0
            pitch: 0.0
            yaw: -0.29557925567183607
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.012315414078333309
            roll: 0.0
            pitch: 0.0
            yaw: -0.6698589458991488
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.007008107660609109
            roll: 0.0
            pitch: 0.0
            yaw: 0.38277926250070893
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0018192240760982693
              y: 0.014574545810551436
              z: 0.0441739177237682
              roll: 0.45836152767940613
              pitch: -0.46488153703688734
              yaw: 1.3605300973228345
            roll: 0.4305007062119937
            pitch: -0.46567965988917903
            yaw: 1.3625046289591072
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.222687311001549
          y: -0.297048031792497
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.07343189359128466
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.011895030161970143
            roll: 0.0
            pitch: 0.0
            yaw: -0.11747178087602539
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.00806276450128124
            roll: 0.0
            pitch: 0.0
            yaw: 0.07478079681348138
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.014270211454718372
            roll: 0.0
            pitch: 0.0
            yaw: -0.14541923325406975
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0014478658932580157
            roll: 0.0
            pitch: 0.0
            yaw: -0.0853555171125185
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.018198554915077755
            roll: 0.0
            pitch: 0.0
            yaw: 0.05777376022572439
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.002244684619444978
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04644785202195587
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.027319248699531534
            roll: 0.0
            pitch: 0.0
            yaw: 0.1800273384038651
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07421500475031984
            roll: 0.0
            pitch: 0.0
            yaw: -0.6266979391746644
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03400711080650641
            roll: 0.0
            pitch: 0.0
            yaw: -0.949233250614764
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0058074235650632244
            roll: 0.0
            pitch: 0.0
            yaw: 0.015099012876078177
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06933577688600676
            roll: 0.0
            pitch: 0.0
            yaw: -0.6349094089710678
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.015817850548000195
            roll: 0.0
            pitch: 0.0
            yaw: -0.8636857945533087
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0014649709441554712
              y: 0.016764566904204355
              z: 0.04259171681793868
              roll: 0.46590770040447943
              pitch: -0.47610570968322075
              yaw: 1.3325967450140528
            roll: 0.46557528618749955
            pitch: -0.4674006153147764
            yaw: 1.3397402233451343
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
