scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.20156140088278723
          y: -0.23925533423938794
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.07490491747662598
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01780606791951308
            roll: 0.0
            pitch: 0.0
            yaw: 0.12489451130876189
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01990031884870532
            roll: 0.0
            pitch: 0.0
            yaw: -0.025618731571633663
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01425452783803368
            roll: 0.0
            pitch: 0.0
            yaw: -0.0002907231537294941
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.007131833557879722
            roll: 0.0
            pitch: 0.0
            yaw: -0.16557787637365437
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.004307333921594384
            roll: 0.0
            pitch: 0.0
            yaw: -0.03236985853469507
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.019605670318943204
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0021218092153515652
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.02723144799845746
            roll: 0.0
            pitch: 0.0
            yaw: -0.33473799133298066
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0510488953328605
            roll: 0.0
            pitch: 0.0
            yaw: -0.6058269755143783
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.055433247082704556
            roll: 0.0
            pitch: 0.0
            yaw: -0.21805138456060802
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07790374067317249
            roll: 0.0
            pitch: 0.0
            yaw: 0.3268232640236737
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0129096534878579
            roll: 0.0
            pitch: 0.0
            yaw: 0.05067004913156703
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04092665501191506
            roll: 0.0
            pitch: 0.0
            yaw: 0.020489059164020107
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0006699790669508717
              y: 0.016070801147225557
              z: 0.04287516077463425
              roll: 0.43615741845185824
              pitch: -0.4912421308493782
              yaw: 1.3623088521601392
            roll: 0.4198237651275334
            pitch: -0.48275839699449924
            yaw: 1.2998201427798834
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.11003815114055193
          y: -0.21077321211568378
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3186154168363844
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.003404348627101726
            roll: 0.0
            pitch: 0.0
            yaw: -0.0555731796386883
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0017694796114328323
            roll: 0.0
            pitch: 0.0
            yaw: -0.03687267708832065
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.009562593145656908
            roll: 0.0
            pitch: 0.0
            yaw: -0.14256598747444935
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.023268030300193213
            roll: 0.0
            pitch: 0.0
            yaw: 0.12228254238744207
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.010464365251657873
            roll: 0.0
            pitch: 0.0
            yaw: -0.1292176404051483
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04892258908066201
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.014512854959889611
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.012341471841406076
            roll: 0.0
            pitch: 0.0
            yaw: 0.6276222332153034
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.051164366017584756
            roll: 0.0
            pitch: 0.0
            yaw: 0.2673925753969453
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0917160573264254
            roll: 0.0
            pitch: 0.0
            yaw: 0.6635436352292257
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06365712428264289
            roll: 0.0
            pitch: 0.0
            yaw: 0.28102148172446983
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08266951649895429
            roll: 0.0
            pitch: 0.0
            yaw: -0.6986556312072367
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05499667509242784
            roll: 0.0
            pitch: 0.0
            yaw: 0.8343054917296291
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0005473911607832569
              y: 0.01372738096816305
              z: 0.04113244877220553
              roll: 0.48292721400394106
              pitch: -0.45318317906517386
              yaw: 1.3346747574521154
            roll: 0.4618853709765336
            pitch: -0.4657253928693817
            yaw: 1.348154864528548
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.12197843504028116
          y: -0.2753342499313083
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.11098313312072727
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.003050109944999404
            roll: 0.0
            pitch: 0.0
            yaw: 0.007535408763492429
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.016777689833466558
            roll: 0.0
            pitch: 0.0
            yaw: -0.15179966793256916
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.013413155609674987
            roll: 0.0
            pitch: 0.0
            yaw: -0.0663111411779251
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.00958351462530988
            roll: 0.0
            pitch: 0.0
            yaw: 0.04972827986403719
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.021979303485932487
            roll: 0.0
            pitch: 0.0
            yaw: 0.16901724573781868
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04958260967587491
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.016576939752799266
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0849775116508053
            roll: 0.0
            pitch: 0.0
            yaw: 0.4642807481206439
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.031121129888622104
            roll: 0.0
            pitch: 0.0
            yaw: -0.48469103768058186
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.016333836497421136
            roll: 0.0
            pitch: 0.0
            yaw: 0.7796972911636648
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.002295865960741189
            roll: 0.0
            pitch: 0.0
            yaw: 0.3322202527808986
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.029827361834492666
            roll: 0.0
            pitch: 0.0
            yaw: 0.6884544284677268
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08233845731125045
            roll: 0.0
            pitch: 0.0
            yaw: -0.8349699268952894
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0004826716430344283
              y: 0.015438318533990796
              z: 0.04074971722073455
              roll: 0.4233585454522518
              pitch: -0.509966770557635
              yaw: 1.3035908532334632
            roll: 0.4568465570047544
            pitch: -0.5065173375341415
            yaw: 1.3318230486477498
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
