scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.23544063015281447
          y: -0.17059317229929666
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.26703029096002207
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.019351086813785796
            roll: 0.0
            pitch: 0.0
            yaw: 0.08084661292791856
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.017269328131141806
            roll: 0.0
            pitch: 0.0
            yaw: -0.13020920777714853
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01703087771239312
            roll: 0.0
            pitch: 0.0
            yaw: 0.08130531046711426
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.003627566115948583
            roll: 0.0
            pitch: 0.0
            yaw: 0.0972265285934591
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0032738915657061288
            roll: 0.0
            pitch: 0.0
            yaw: -0.07124284826807364
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.00940099092776131
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04844363701288769
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.018676900570958277
            roll: 0.0
            pitch: 0.0
            yaw: -0.6858521401941992
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08151727483913394
            roll: 0.0
            pitch: 0.0
            yaw: -0.19743101095460813
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04758103129457067
            roll: 0.0
            pitch: 0.0
            yaw: -0.8776832075091254
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.012134962838999327
            roll: 0.0
            pitch: 0.0
            yaw: -0.5697441342411078
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0633675838819904
            roll: 0.0
            pitch: 0.0
            yaw: -0.6377193342244382
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.057427689614015474
            roll: 0.0
            pitch: 0.0
            yaw: 1.032861251563203
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0019617531105563064
              y: 0.015981068123883977
              z: 0.04151564929317799
              roll: 0.47966355635198743
              pitch: -0.44948908421079536
              yaw: 1.3589624628640684
            roll: 0.47203096703539704
            pitch: -0.4443258688459424
            yaw: 1.3682790857112859
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2796059584949392
          y: -0.2672036814020045
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.3995690632067994
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01330345259443046
            roll: 0.0
            pitch: 0.0
            yaw: 0.00808654586792501
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.016727456290637974
            roll: 0.0
            pitch: 0.0
            yaw: -0.04903262069877157
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.00572377069721634
            roll: 0.0
            pitch: 0.0
            yaw: -0.006886333612386775
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0030726253634391527
            roll: 0.0
            pitch: 0.0
            yaw: -0.13735347462893563
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01178749280481112
            roll: 0.0
            pitch: 0.0
            yaw: -0.12240471261319523
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05025842881770101
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05043157814526976
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0036742171258883627
            roll: 0.0
            pitch: 0.0
            yaw: 0.3173485171703101
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0022708423932151223
            roll: 0.0
            pitch: 0.0
            yaw: 0.09938682429621215
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06889566055623639
            roll: 0.0
            pitch: 0.0
            yaw: -0.8524863458517216
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.026650403635426798
            roll: 0.0
            pitch: 0.0
            yaw: 0.54214039396559
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.04642290767459894
            roll: 0.0
            pitch: 0.0
            yaw: 0.3148039268039682
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09233152362306375
            roll: 0.0
            pitch: 0.0
            yaw: 0.3754850913366947
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.001303974450488851
              y: 0.01472035904035279
              z: 0.044365196944592386
              roll: 0.4449943797994146
              pitch: -0.444234932415674
              yaw: 1.3602900064589438
            roll: 0.4257720064048487
            pitch: -0.5012406521737255
            yaw: 1.3002527333350102
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.20685498021953552
          y: -0.18430486318512918
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.3436870288231666
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.020514870531622185
            roll: 0.0
            pitch: 0.0
            yaw: 0.1579804522470442
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.005719194491081693
            roll: 0.0
            pitch: 0.0
            yaw: 0.11421305012687599
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.003071075511622102
            roll: 0.0
            pitch: 0.0
            yaw: 0.13467298942058992
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.003167200006112668
            roll: 0.0
            pitch: 0.0
            yaw: 0.09030040333989486
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.008287957749956623
            roll: 0.0
            pitch: 0.0
            yaw: 0.13920762314570972
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.023524595254765038
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03178347502562909
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0015952522987142531
            roll: 0.0
            pitch: 0.0
            yaw: 0.13761848267333443
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.06968603280995866
            roll: 0.0
            pitch: 0.0
            yaw: -0.35093710492436436
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07521350863130473
            roll: 0.0
            pitch: 0.0
            yaw: 0.44023397222748484
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0854149046600857
            roll: 0.0
            pitch: 0.0
            yaw: -0.5917726758829833
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.022654204432531536
            roll: 0.0
            pitch: 0.0
            yaw: -0.9221104601662015
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07729236192596305
            roll: 0.0
            pitch: 0.0
            yaw: -0.39559746628409576
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 1.2021777206188376e-05
              y: 0.014570935442269372
              z: 0.043211592811345303
              roll: 0.4435945626666474
              pitch: -0.49185123948902126
              yaw: 1.3184664448978536
            roll: 0.46612886011504234
            pitch: -0.4941909951199587
            yaw: 1.3000148479793803
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
