scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.11729652059350154
          y: -0.24908895501939984
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.05693259333587064
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.010152615547225926
            roll: 0.0
            pitch: 0.0
            yaw: 0.10483816545074637
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.019609699055876582
            roll: 0.0
            pitch: 0.0
            yaw: -0.03212957601788172
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.009491439392788781
            roll: 0.0
            pitch: 0.0
            yaw: 0.1153081659362743
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.014043189161554583
            roll: 0.0
            pitch: 0.0
            yaw: 0.13099455361873635
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.019632777032919414
            roll: 0.0
            pitch: 0.0
            yaw: -0.12118897183588004
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.010397976391349949
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.02150676029843089
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07498036436319669
            roll: 0.0
            pitch: 0.0
            yaw: 0.2916168450842951
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.01289479299386842
            roll: 0.0
            pitch: 0.0
            yaw: -0.5961447068163734
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.054106162207478714
            roll: 0.0
            pitch: 0.0
            yaw: 0.09307645372638218
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.023002855029620004
            roll: 0.0
            pitch: 0.0
            yaw: -0.2503587351532486
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.006468083340641292
            roll: 0.0
            pitch: 0.0
            yaw: 0.8331084107790248
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.09005622991870646
            roll: 0.0
            pitch: 0.0
            yaw: 0.7576826780555226
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0012315476555091404
              y: 0.016076656914737624
              z: 0.04149928003841908
              roll: 0.40557137326879683
              pitch: -0.47728771304437395
              yaw: 1.3686262308262382
            roll: 0.4171355375069676
            pitch: -0.4430083435129253
            yaw: 1.332289085938613
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.16082137622788958
          y: -0.23155368507502538
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.22144927070631404
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.010223717556858395
            roll: 0.0
            pitch: 0.0
            yaw: -0.14915778611765812
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.015159128095395484
            roll: 0.0
            pitch: 0.0
            yaw: 0.07228136234850213
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.016614759080961675
            roll: 0.0
            pitch: 0.0
            yaw: 0.11541357875824254
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.018711050634710708
            roll: 0.0
            pitch: 0.0
            yaw: -0.13420042459387865
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.019670869427265147
            roll: 0.0
            pitch: 0.0
            yaw: -0.1594994406687696
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.006612869687304512
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.023892621769729755
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.04094424411158051
            roll: 0.0
            pitch: 0.0
            yaw: 0.4418367380875614
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07419695689959092
            roll: 0.0
            pitch: 0.0
            yaw: 0.8084887840221868
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.038559811367942856
            roll: 0.0
            pitch: 0.0
            yaw: -0.602956301198396
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08436707228685211
            roll: 0.0
            pitch: 0.0
            yaw: -0.10712620723792121
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.04676444684977635
            roll: 0.0
            pitch: 0.0
            yaw: 0.07487096438429752
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03931041201062413
            roll: 0.0
            pitch: 0.0
            yaw: 0.31041003150101165
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0008738539352006417
              y: 0.014981452514957472
              z: 0.04057149478785067
              roll: 0.4323310373887007
              pitch: -0.4751221670146324
              yaw: 1.3121553720004895
            roll: 0.4283674849275912
            pitch: -0.47761326214495725
            yaw: 1.3612942928178624
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.19492088840550803
          y: -0.1362772877315599
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.18204314798863064
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.007236859881566077
            roll: 0.0
            pitch: 0.0
            yaw: 0.1237849836596221
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.017983214869502728
            roll: 0.0
            pitch: 0.0
            yaw: -0.07165691477078842
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0027797157280271996
            roll: 0.0
            pitch: 0.0
            yaw: -0.042127010565725376
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.006616361742889012
            roll: 0.0
            pitch: 0.0
            yaw: 0.16285969170443793
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.003608696828340769
            roll: 0.0
            pitch: 0.0
            yaw: 0.006973633741125501
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.024918181444493773
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05331272906441893
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07135844316648315
            roll: 0.0
            pitch: 0.0
            yaw: -0.07290110793039817
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.03501472759782913
            roll: 0.0
            pitch: 0.0
            yaw: -0.05932794693124055
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.011192437259287286
            roll: 0.0
            pitch: 0.0
            yaw: -0.888815382500144
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.007266957620413544
            roll: 0.0
            pitch: 0.0
            yaw: -0.5395444865165195
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08784165660565071
            roll: 0.0
            pitch: 0.0
            yaw: -0.6522654523025982
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03080657138474882
            roll: 0.0
            pitch: 0.0
            yaw: 0.1273001891794585
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.001221289999685811
              y: 0.014616903128895214
              z: 0.04380746344699903
              roll: 0.4582958112610641
              pitch: -0.4458168387210383
              yaw: 1.341105504456743
            roll: 0.4093416503252514
            pitch: -0.4895833291424608
            yaw: 1.2949135023747684
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
