scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2098306685827444
          y: -0.24731327330099417
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.13529587460842873
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.011604825513764301
            roll: 0.0
            pitch: 0.0
            yaw: 0.060268338920517306
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0016897655920265556
            roll: 0.0
            pitch: 0.0
            yaw: -0.03093316178513769
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.021511467052382917
            roll: 0.0
            pitch: 0.0
            yaw: -0.054452356411074515
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0056499092679269045
            roll: 0.0
            pitch: 0.0
            yaw: 0.16449410299065598
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.004526160673214055
            roll: 0.0
            pitch: 0.0
            yaw: 0.012906327807435308
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04576947814782659
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.014874025903826235
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.09426543649963903
            roll: 0.0
            pitch: 0.0
            yaw: 0.412368903027329
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07755814806887831
            roll: 0.0
            pitch: 0.0
            yaw: 0.7713265643493936
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07685595505985715
            roll: 0.0
            pitch: 0.0
            yaw: 0.32774041697735057
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09338555618242764
            roll: 0.0
            pitch: 0.0
            yaw: -0.029790194535223025
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.09213555840542897
            roll: 0.0
            pitch: 0.0
            yaw: 0.5733404350467135
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05835807680854173
            roll: 0.0
            pitch: 0.0
            yaw: 0.19900457037994235
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -8.130145403471368e-05
              y: 0.015380271410200333
              z: 0.0405651331013714
              roll: 0.43127886648736663
              pitch: -0.49765416832475834
              yaw: 1.3583759209815656
            roll: 0.4362951122471809
            pitch: -0.5034569192101506
            yaw: 1.3146894447434647
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.21379122470990816
          y: -0.2052704864941849
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.06566857880014276
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.02240157333744274
            roll: 0.0
            pitch: 0.0
            yaw: -0.17369722341292573
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.015813793595203404
            roll: 0.0
            pitch: 0.0
            yaw: -0.03962294092077623
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.015238322006804535
            roll: 0.0
            pitch: 0.0
            yaw: -0.00231683428667101
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.009859127962515375
            roll: 0.0
            pitch: 0.0
            yaw: 0.04149979119948241
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01514716869580132
            roll: 0.0
            pitch: 0.0
            yaw: 0.054264805674742844
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.047279697422545536
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.048298355564242015
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06509891350011955
            roll: 0.0
            pitch: 0.0
            yaw: -0.9166462162850383
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.053575154429620214
            roll: 0.0
            pitch: 0.0
            yaw: -0.055523196833056176
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08519102046816156
            roll: 0.0
            pitch: 0.0
            yaw: -0.6103543210465086
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0029380552618807343
            roll: 0.0
            pitch: 0.0
            yaw: -0.7273709613064414
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08550914839211006
            roll: 0.0
            pitch: 0.0
            yaw: -0.24184546095575155
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07591489231262027
            roll: 0.0
            pitch: 0.0
            yaw: 0.7478493279741092
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0019249684615823442
              y: 0.017282605088701955
              z: 0.04267832630886377
              roll: 0.42039068076968433
              pitch: -0.4851437385719295
              yaw: 1.3311178131470573
            roll: 0.4556102467299502
            pitch: -0.45599103405136543
            yaw: 1.3311004856891988
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2901687101885572
          y: -0.2545498546809619
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.13635893669563626
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.020248807680603824
            roll: 0.0
            pitch: 0.0
            yaw: 0.0020195367037696976
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.009058040996790435
            roll: 0.0
            pitch: 0.0
            yaw: 0.14245359329175222
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0058203436966147645
            roll: 0.0
            pitch: 0.0
            yaw: 0.0050957706644239875
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.005098236257591867
            roll: 0.0
            pitch: 0.0
            yaw: 0.1101749441118608
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0002464999094925757
            roll: 0.0
            pitch: 0.0
            yaw: 0.08719821107798703
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.053346640465428564
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.015901538079897748
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.048836126187611024
            roll: 0.0
            pitch: 0.0
            yaw: 0.3412865725854206
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05690977565728498
            roll: 0.0
            pitch: 0.0
            yaw: -0.7465161307824983
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05126469301404793
            roll: 0.0
            pitch: 0.0
            yaw: -0.4184814702458083
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.054788948322776025
            roll: 0.0
            pitch: 0.0
            yaw: -0.06471321706459032
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.037030030241823275
            roll: 0.0
            pitch: 0.0
            yaw: -0.8045590330399037
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.02641687838125767
            roll: 0.0
            pitch: 0.0
            yaw: -0.354678604213863
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0010532912307935054
              y: 0.017299307577714737
              z: 0.04089554256390349
              roll: 0.43719907182393947
              pitch: -0.4438847533690857
              yaw: 1.3576412968555933
            roll: 0.4413423985525113
            pitch: -0.47395138129069003
            yaw: 1.3012370129182265
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
