scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2518271523118395
          y: -0.12589585206387852
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.31529257951810674
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0007434485679262033
            roll: 0.0
            pitch: 0.0
            yaw: 0.15911898060820018
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.014055723513185774
            roll: 0.0
            pitch: 0.0
            yaw: -0.11168872714317686
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01828697363215277
            roll: 0.0
            pitch: 0.0
            yaw: -0.15606719080164286
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0006930164949396078
            roll: 0.0
            pitch: 0.0
            yaw: -0.08424987162791969
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0033617151070113975
            roll: 0.0
            pitch: 0.0
            yaw: -0.008588904808266073
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.018906444933865188
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0059634580150161945
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.03113808189156156
            roll: 0.0
            pitch: 0.0
            yaw: -0.44116417542298003
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0480214316127025
            roll: 0.0
            pitch: 0.0
            yaw: -1.0252622775218005
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07189440420330119
            roll: 0.0
            pitch: 0.0
            yaw: -0.15100614846178861
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.02062223144961843
            roll: 0.0
            pitch: 0.0
            yaw: -0.3756685885710703
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.006496445823477262
            roll: 0.0
            pitch: 0.0
            yaw: 0.5189364744314222
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.008468748341753013
            roll: 0.0
            pitch: 0.0
            yaw: -0.4772373495711152
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0011387469017091765
              y: 0.01729293891769112
              z: 0.043173367497954133
              roll: 0.40366026914662023
              pitch: -0.4873484546281348
              yaw: 1.313825673688241
            roll: 0.437420479506769
            pitch: -0.47445129571753364
            yaw: 1.294539929207406
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2928630001736236
          y: -0.13176310421376017
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.18690087829038182
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.008423635586349655
            roll: 0.0
            pitch: 0.0
            yaw: 0.08200266682060559
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01775716943131511
            roll: 0.0
            pitch: 0.0
            yaw: 0.12707740012220764
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01174837698118645
            roll: 0.0
            pitch: 0.0
            yaw: -0.02298819192262408
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0020975944228171298
            roll: 0.0
            pitch: 0.0
            yaw: -0.17298001932739163
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01307705012553989
            roll: 0.0
            pitch: 0.0
            yaw: 0.06788480464757829
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.009815727201611862
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0026291164872392636
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.09237016079139915
            roll: 0.0
            pitch: 0.0
            yaw: 0.07465373644866391
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.047652767227987225
            roll: 0.0
            pitch: 0.0
            yaw: -0.7251237492348737
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05757731033825006
            roll: 0.0
            pitch: 0.0
            yaw: 0.7155815046047813
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.022435423049204498
            roll: 0.0
            pitch: 0.0
            yaw: -0.15199282900017086
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.02618114893220308
            roll: 0.0
            pitch: 0.0
            yaw: -0.6529177602352597
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.041265910658511734
            roll: 0.0
            pitch: 0.0
            yaw: 0.8299611656638273
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.000677747212460902
              y: 0.013818403213199363
              z: 0.0424948018201246
              roll: 0.4499017024434539
              pitch: -0.5034132149482773
              yaw: 1.3312493607227025
            roll: 0.44225265453909524
            pitch: -0.5190274738887607
            yaw: 1.3566967659552636
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.13097497865398908
          y: -0.2615976535909274
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.07362667741602713
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01703261569750647
            roll: 0.0
            pitch: 0.0
            yaw: -0.01886964533123084
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01746558731004462
            roll: 0.0
            pitch: 0.0
            yaw: 0.12345346857150952
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.013731969634250878
            roll: 0.0
            pitch: 0.0
            yaw: -0.040927009530964426
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02014338449632376
            roll: 0.0
            pitch: 0.0
            yaw: 0.0030449216824468273
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01188087496120932
            roll: 0.0
            pitch: 0.0
            yaw: 0.06694620427056461
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.007386411259501388
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03147492819629727
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.004944911814652911
            roll: 0.0
            pitch: 0.0
            yaw: -0.033895861254665594
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.017313379235597434
            roll: 0.0
            pitch: 0.0
            yaw: 0.967102999769806
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0008585068023381354
            roll: 0.0
            pitch: 0.0
            yaw: 0.012241845748110158
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07256086795594172
            roll: 0.0
            pitch: 0.0
            yaw: -0.6540370458948388
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.09368825733680197
            roll: 0.0
            pitch: 0.0
            yaw: -1.0115918184742687
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.043464534059831535
            roll: 0.0
            pitch: 0.0
            yaw: 0.544327012188401
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0005255367761892575
              y: 0.017254450967312672
              z: 0.04305342868632861
              roll: 0.42743646694820187
              pitch: -0.47413654761646234
              yaw: 1.3278442695230253
            roll: 0.4100326381835845
            pitch: -0.4784404676785988
            yaw: 1.3349995461160982
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
