scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.12622835295121113
          y: -0.16154326195383933
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.18964208068259925
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.008008567762730654
            roll: 0.0
            pitch: 0.0
            yaw: 0.026375320030976313
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.020851222826482725
            roll: 0.0
            pitch: 0.0
            yaw: -0.06466785474741805
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.023287947123335102
            roll: 0.0
            pitch: 0.0
            yaw: 0.14594741718702892
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.015009933187029409
            roll: 0.0
            pitch: 0.0
            yaw: 0.007623521031264763
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.013289212839371269
            roll: 0.0
            pitch: 0.0
            yaw: 0.1628204717803582
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.008398772294208642
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.010950247011685982
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08734775101063354
            roll: 0.0
            pitch: 0.0
            yaw: 0.9024347937761712
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.006713416311799447
            roll: 0.0
            pitch: 0.0
            yaw: 0.48276276092454884
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07288464356899191
            roll: 0.0
            pitch: 0.0
            yaw: 0.30439474644246056
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05603220018857169
            roll: 0.0
            pitch: 0.0
            yaw: 0.8602545712363583
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08252385870523732
            roll: 0.0
            pitch: 0.0
            yaw: 0.24144871009069613
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.023076275071690744
            roll: 0.0
            pitch: 0.0
            yaw: 0.9839084113776775
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0005900556382039761
              y: 0.015348683105259716
              z: 0.04252814643535506
              roll: 0.43722346567857734
              pitch: -0.4769003087208529
              yaw: 1.3187068041139425
            roll: 0.4675618985381333
            pitch: -0.5175392579181637
            yaw: 1.3607772347745737
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.24661964406154493
          y: -0.15591911784472184
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.29540500298966255
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.007743438141217324
            roll: 0.0
            pitch: 0.0
            yaw: 0.003122722114508536
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.011198627445341877
            roll: 0.0
            pitch: 0.0
            yaw: -0.0892815618961362
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.023268574915714053
            roll: 0.0
            pitch: 0.0
            yaw: 0.025133830277601937
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0011834512598487938
            roll: 0.0
            pitch: 0.0
            yaw: -0.17285888236847013
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.004281294300093379
            roll: 0.0
            pitch: 0.0
            yaw: 0.04971604622700118
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.048439669007267434
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04257038729993719
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05594992465848532
            roll: 0.0
            pitch: 0.0
            yaw: 0.027488780955274184
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.025535387800786236
            roll: 0.0
            pitch: 0.0
            yaw: 0.20064128528300018
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.042903530847483426
            roll: 0.0
            pitch: 0.0
            yaw: -0.6949110293893948
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09172974906586864
            roll: 0.0
            pitch: 0.0
            yaw: -0.17977574534882879
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.006987762242438703
            roll: 0.0
            pitch: 0.0
            yaw: -0.43455429875122265
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03927647577257457
            roll: 0.0
            pitch: 0.0
            yaw: -0.3449566242215891
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001199802487482139
              y: 0.013805660055601857
              z: 0.04144902453192043
              roll: 0.4423940702924316
              pitch: -0.4860113584414494
              yaw: 1.3416400214637592
            roll: 0.44561645809744144
            pitch: -0.46732031631774973
            yaw: 1.2952728467532157
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.1151272972212105
          y: -0.24862207624613375
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.47805719016352366
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0171872479877202
            roll: 0.0
            pitch: 0.0
            yaw: 0.04884188798678518
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.005652795991575754
            roll: 0.0
            pitch: 0.0
            yaw: 0.10371028145818267
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0004967878422138111
            roll: 0.0
            pitch: 0.0
            yaw: -0.018188141657055318
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.00782779517317704
            roll: 0.0
            pitch: 0.0
            yaw: -0.026367728249936717
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01963780288685617
            roll: 0.0
            pitch: 0.0
            yaw: 0.03000860555904941
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.030634370591870085
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.006761985295827805
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.09066339919365046
            roll: 0.0
            pitch: 0.0
            yaw: -1.0333435349585949
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08725896666898633
            roll: 0.0
            pitch: 0.0
            yaw: 0.184309541002724
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.09310179972868687
            roll: 0.0
            pitch: 0.0
            yaw: 0.8704315972109242
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0028650541792279716
            roll: 0.0
            pitch: 0.0
            yaw: -0.033196375182384275
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.03103135539272177
            roll: 0.0
            pitch: 0.0
            yaw: -0.6718494214238211
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04127795866417844
            roll: 0.0
            pitch: 0.0
            yaw: 0.06797403616585251
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0010462025946912212
              y: 0.015547252079138318
              z: 0.04158484090421714
              roll: 0.4357343690923463
              pitch: -0.4511011795653152
              yaw: 1.3035206027294803
            roll: 0.4768826273237555
            pitch: -0.5061530668900611
            yaw: 1.3609864138093841
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
