scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.18978755488837473
          y: -0.12445395050228839
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.28258305477424606
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.00400786578438939
            roll: 0.0
            pitch: 0.0
            yaw: -0.0409531184365127
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.02002085812427907
            roll: 0.0
            pitch: 0.0
            yaw: -0.1627444945926507
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.008779726827792614
            roll: 0.0
            pitch: 0.0
            yaw: 0.1642307762515261
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.015297287163518879
            roll: 0.0
            pitch: 0.0
            yaw: -0.017659013946807134
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.007510795008137016
            roll: 0.0
            pitch: 0.0
            yaw: 0.0754912897728357
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.021061456863358093
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05119600445137294
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.008893866468748582
            roll: 0.0
            pitch: 0.0
            yaw: 0.7408384306497029
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07998465169200261
            roll: 0.0
            pitch: 0.0
            yaw: -0.919295368227078
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04403090938690543
            roll: 0.0
            pitch: 0.0
            yaw: 0.30451796130627207
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07058981951067286
            roll: 0.0
            pitch: 0.0
            yaw: -0.4473625506929201
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.015402731291542807
            roll: 0.0
            pitch: 0.0
            yaw: 0.21028723228795476
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.014275992375378493
            roll: 0.0
            pitch: 0.0
            yaw: 0.41239680159377956
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0016949422567425834
              y: 0.015594499050358611
              z: 0.04062423984764412
              roll: 0.4185858697264431
              pitch: -0.4929748761993111
              yaw: 1.337286673698175
            roll: 0.43931324515347453
            pitch: -0.4839623107828287
            yaw: 1.2921185528734704
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.13120511035559437
          y: -0.10491673723116784
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.49946537946572434
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.00982725708097014
            roll: 0.0
            pitch: 0.0
            yaw: 0.14167534898605882
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.014583347096649026
            roll: 0.0
            pitch: 0.0
            yaw: -0.09767826089361387
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.00794572902147322
            roll: 0.0
            pitch: 0.0
            yaw: -0.08841059863677908
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.010882212419589253
            roll: 0.0
            pitch: 0.0
            yaw: -0.0761926742150723
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.008230541972974948
            roll: 0.0
            pitch: 0.0
            yaw: 0.0632551297372993
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03309008101336035
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03720635294796856
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.009821812734546853
            roll: 0.0
            pitch: 0.0
            yaw: 0.9545599043115314
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08298676027035504
            roll: 0.0
            pitch: 0.0
            yaw: -0.9110165732104734
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04501990736234328
            roll: 0.0
            pitch: 0.0
            yaw: 0.6758019894379883
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.008336761462232029
            roll: 0.0
            pitch: 0.0
            yaw: -0.08420115850137522
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.04970664658247152
            roll: 0.0
            pitch: 0.0
            yaw: 0.36421148907772416
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08308978649622736
            roll: 0.0
            pitch: 0.0
            yaw: 0.9668402464778187
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00048273221190722857
              y: 0.013631453289456207
              z: 0.04203013035062253
              roll: 0.4561776606897219
              pitch: -0.4911370499278503
              yaw: 1.3216977650189283
            roll: 0.40769753963008687
            pitch: -0.5174667779652233
            yaw: 1.3324564925677815
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.15118569054008063
          y: -0.18127059691038122
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.052808954803468255
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.011439721921633136
            roll: 0.0
            pitch: 0.0
            yaw: 0.035169382834604634
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0005778637019327529
            roll: 0.0
            pitch: 0.0
            yaw: 0.16720744743536514
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01252571761986234
            roll: 0.0
            pitch: 0.0
            yaw: -0.028302701399413155
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.00991138351645727
            roll: 0.0
            pitch: 0.0
            yaw: -0.1655230841317799
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.00447471327424534
            roll: 0.0
            pitch: 0.0
            yaw: -0.06166733278530827
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0026069601882135335
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0004083966250189863
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.026359473953424487
            roll: 0.0
            pitch: 0.0
            yaw: -0.47155466278173563
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.012167365292869575
            roll: 0.0
            pitch: 0.0
            yaw: -0.5092465843722014
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08649439736353512
            roll: 0.0
            pitch: 0.0
            yaw: 0.2960864307075255
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06450515031803015
            roll: 0.0
            pitch: 0.0
            yaw: -0.41699187729548537
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.09547324074787727
            roll: 0.0
            pitch: 0.0
            yaw: -0.7558099573610009
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05435267630311345
            roll: 0.0
            pitch: 0.0
            yaw: 0.7335205063565964
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0017214812174279049
              y: 0.016148009961777177
              z: 0.043814519808117965
              roll: 0.4739926384667926
              pitch: -0.5098125547759689
              yaw: 1.3055576409284844
            roll: 0.4125662294723704
            pitch: -0.46194911099583746
            yaw: 1.313756423476787
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
