scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.10166474264023846
          y: -0.18102357614488424
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.2919248724489133
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.00785859736443743
            roll: 0.0
            pitch: 0.0
            yaw: -0.041262124855578425
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.00960547509984297
            roll: 0.0
            pitch: 0.0
            yaw: -0.15339447978290235
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0006319177784341046
            roll: 0.0
            pitch: 0.0
            yaw: -0.021057186098507097
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.006785915585775685
            roll: 0.0
            pitch: 0.0
            yaw: 0.07346079833927802
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.011792128210003631
            roll: 0.0
            pitch: 0.0
            yaw: -0.11834420231620535
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03915787359568767
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03888923689829823
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.04332186478000408
            roll: 0.0
            pitch: 0.0
            yaw: 0.535109296797593
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08938541894498031
            roll: 0.0
            pitch: 0.0
            yaw: -0.5683364467159596
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04304757722660085
            roll: 0.0
            pitch: 0.0
            yaw: -0.622489343515348
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06471744437824004
            roll: 0.0
            pitch: 0.0
            yaw: 0.047925447530866805
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.04122622080610651
            roll: 0.0
            pitch: 0.0
            yaw: 0.6595112539207204
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.005846814973776204
            roll: 0.0
            pitch: 0.0
            yaw: 0.6819161609190427
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0006665693795355619
              y: 0.016440268881805
              z: 0.043547230082598934
              roll: 0.4460047329750847
              pitch: -0.5219483694271694
              yaw: 1.3452566220016642
            roll: 0.4673379219420377
            pitch: -0.4968676769729755
            yaw: 1.3630813709912049
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.29086793525526916
          y: -0.18155796968110208
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.05459253079777149
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.016323261105269646
            roll: 0.0
            pitch: 0.0
            yaw: -0.05361451749180744
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0008244234886716217
            roll: 0.0
            pitch: 0.0
            yaw: 0.17146616679216786
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 4.153756020561228e-05
            roll: 0.0
            pitch: 0.0
            yaw: 0.120849236514536
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.005028683380356388
            roll: 0.0
            pitch: 0.0
            yaw: -0.07187609083029839
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02142516063505008
            roll: 0.0
            pitch: 0.0
            yaw: 0.02263160745341064
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.004380406739133667
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.022479021982022306
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.05018984142370242
            roll: 0.0
            pitch: 0.0
            yaw: 0.6877416380720052
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09401668883088225
            roll: 0.0
            pitch: 0.0
            yaw: 0.9261958236765024
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09049417892745693
            roll: 0.0
            pitch: 0.0
            yaw: -0.7935770895693669
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05873342248848937
            roll: 0.0
            pitch: 0.0
            yaw: -0.2928864134259638
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08915805984106201
            roll: 0.0
            pitch: 0.0
            yaw: 0.3367781252631441
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08979479631164022
            roll: 0.0
            pitch: 0.0
            yaw: -0.47892340811165623
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0016622318370132652
              y: 0.016706785500008984
              z: 0.044094550165277024
              roll: 0.4797869266815613
              pitch: -0.4648393223377887
              yaw: 1.3297862286635733
            roll: 0.46646411116946984
            pitch: -0.45072362001951766
            yaw: 1.3532122257489279
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.29596897213823026
          y: -0.15990326697588353
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.08534515079201399
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.00857669412312726
            roll: 0.0
            pitch: 0.0
            yaw: 0.10011488871489421
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01474087913853877
            roll: 0.0
            pitch: 0.0
            yaw: 0.09053114477379093
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0014370305465476463
            roll: 0.0
            pitch: 0.0
            yaw: 0.15036474089714347
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.005528737093487952
            roll: 0.0
            pitch: 0.0
            yaw: 0.049939971298026326
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.010262227219847604
            roll: 0.0
            pitch: 0.0
            yaw: -0.15755706447635118
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04600931719451456
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.00049417827968333
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.09230359893715598
            roll: 0.0
            pitch: 0.0
            yaw: 0.5878926776895879
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.06296218990465927
            roll: 0.0
            pitch: 0.0
            yaw: -0.7288536741665368
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04763633651757118
            roll: 0.0
            pitch: 0.0
            yaw: 0.14424956745019224
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08243647205975456
            roll: 0.0
            pitch: 0.0
            yaw: -0.6105013856166696
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08834338501832265
            roll: 0.0
            pitch: 0.0
            yaw: -0.1907926474172651
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.01901594152090544
            roll: 0.0
            pitch: 0.0
            yaw: 0.042053562736749095
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0016757703923436255
              y: 0.01630523453695021
              z: 0.04195661334322337
              roll: 0.48030709921991915
              pitch: -0.5069944007543988
              yaw: 1.34039074098089
            roll: 0.4717791801414555
            pitch: -0.4780935729529187
            yaw: 1.3691843793992835
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
