scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.22449098170692483
          y: -0.13493159708665375
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.23036301890352728
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.006820605098652267
            roll: 0.0
            pitch: 0.0
            yaw: -0.053406988033160296
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.003185922550510624
            roll: 0.0
            pitch: 0.0
            yaw: 0.13305628446411577
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0018407120512397498
            roll: 0.0
            pitch: 0.0
            yaw: -0.07582977341436328
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012522771493596485
            roll: 0.0
            pitch: 0.0
            yaw: 0.15460633327860357
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.004461995959772622
            roll: 0.0
            pitch: 0.0
            yaw: -0.11624158342247136
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02837161858476718
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04733910550508872
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.05155384747784755
            roll: 0.0
            pitch: 0.0
            yaw: 0.3231525217526685
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07316022305922322
            roll: 0.0
            pitch: 0.0
            yaw: 0.6876387103195041
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08836219556321775
            roll: 0.0
            pitch: 0.0
            yaw: 0.4377127964626677
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04963755915898185
            roll: 0.0
            pitch: 0.0
            yaw: 0.9702295178204834
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.03707154862465663
            roll: 0.0
            pitch: 0.0
            yaw: 0.7148051690793946
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05292414600400894
            roll: 0.0
            pitch: 0.0
            yaw: 0.6135857938579099
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.000815323499329883
              y: 0.013662099150584242
              z: 0.04240478190715826
              roll: 0.4775700824777155
              pitch: -0.4481816980729263
              yaw: 1.3363138971046429
            roll: 0.40892424438181424
            pitch: -0.46370664481146756
            yaw: 1.3599987812297751
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2554210191586979
          y: -0.23012253986498749
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.43019670227466356
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0006619985499081299
            roll: 0.0
            pitch: 0.0
            yaw: 0.14054505906477333
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01767746983089241
            roll: 0.0
            pitch: 0.0
            yaw: -0.1422618263325333
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0043789597383403454
            roll: 0.0
            pitch: 0.0
            yaw: -0.12682409020411428
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0019682848837386767
            roll: 0.0
            pitch: 0.0
            yaw: 0.10696991587164745
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.017698659136908847
            roll: 0.0
            pitch: 0.0
            yaw: -0.00045853131284037674
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.048013815879167816
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.024118567212178497
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.06099664481474967
            roll: 0.0
            pitch: 0.0
            yaw: 0.7229812356038745
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04534672293864278
            roll: 0.0
            pitch: 0.0
            yaw: -0.7591753043339153
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08336700620180433
            roll: 0.0
            pitch: 0.0
            yaw: -1.025008676160335
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.06483042336211828
            roll: 0.0
            pitch: 0.0
            yaw: -0.37566701283890036
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.006590150345187881
            roll: 0.0
            pitch: 0.0
            yaw: 0.5879887129618593
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.01708436596379166
            roll: 0.0
            pitch: 0.0
            yaw: -0.9476931291647679
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 5.634500100663593e-05
              y: 0.015485638547489404
              z: 0.04207943489377596
              roll: 0.4375556247580962
              pitch: -0.4818467582263872
              yaw: 1.3442240960110006
            roll: 0.4168783876601678
            pitch: -0.5059073306548315
            yaw: 1.3607526069868516
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2995599434549467
          y: -0.20343764634037265
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.09527878376234244
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.012996252864160564
            roll: 0.0
            pitch: 0.0
            yaw: 0.05781414990961353
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007321672681118604
            roll: 0.0
            pitch: 0.0
            yaw: -0.11176331810656522
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.012818684982753755
            roll: 0.0
            pitch: 0.0
            yaw: 0.06322786236093256
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.019872152031655287
            roll: 0.0
            pitch: 0.0
            yaw: -0.03757123117143535
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.018420659545305286
            roll: 0.0
            pitch: 0.0
            yaw: -0.1708544793950699
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.015082779226453472
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.010334836681346847
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08241455909870654
            roll: 0.0
            pitch: 0.0
            yaw: 0.23759508105354965
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.027412813146043144
            roll: 0.0
            pitch: 0.0
            yaw: 0.407259601424401
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.059541286314310854
            roll: 0.0
            pitch: 0.0
            yaw: 0.3684369079476528
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.054588235829919535
            roll: 0.0
            pitch: 0.0
            yaw: 0.5263146618620214
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05731640167282148
            roll: 0.0
            pitch: 0.0
            yaw: 1.017130777397256
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.004277431640361956
            roll: 0.0
            pitch: 0.0
            yaw: -0.5769411979981893
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0006213361559726668
              y: 0.014696312260100394
              z: 0.04356555631590528
              roll: 0.47438622595408264
              pitch: -0.5232203996152318
              yaw: 1.3451180774263518
            roll: 0.45281715873128353
            pitch: -0.508868196176814
            yaw: 1.308528373066875
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
