scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2867950101464102
          y: -0.23853844133871688
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.004179916139834483
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01631689197600472
            roll: 0.0
            pitch: 0.0
            yaw: -0.02511775634509747
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007812951860261819
            roll: 0.0
            pitch: 0.0
            yaw: -0.04764546690163804
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.013932283947546642
            roll: 0.0
            pitch: 0.0
            yaw: -0.06441591206793505
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.007613782798469592
            roll: 0.0
            pitch: 0.0
            yaw: -0.09017275080157819
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.010888456916906084
            roll: 0.0
            pitch: 0.0
            yaw: -0.04533802793134506
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05698909818221824
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.044889529433953204
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.04714585468243948
            roll: 0.0
            pitch: 0.0
            yaw: -0.48330580415129465
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0797269622649637
            roll: 0.0
            pitch: 0.0
            yaw: 0.9840532771486903
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.039980987229380205
            roll: 0.0
            pitch: 0.0
            yaw: 0.20371808329356056
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.011617959237900613
            roll: 0.0
            pitch: 0.0
            yaw: 0.05832105958450695
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.04306255654343796
            roll: 0.0
            pitch: 0.0
            yaw: -0.15458704138813661
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03606115021250589
            roll: 0.0
            pitch: 0.0
            yaw: -0.2625656771897169
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0010385673745509035
              y: 0.01425808351519573
              z: 0.041338424116983755
              roll: 0.4104097275431518
              pitch: -0.46346121204496665
              yaw: 1.3168568982390343
            roll: 0.4196724571246888
            pitch: -0.4841660101059909
            yaw: 1.359585830876451
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2143679266946292
          y: -0.2835808613145974
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.439059247474901
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.008857630185910592
            roll: 0.0
            pitch: 0.0
            yaw: -0.14954343169243847
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.004909200049709534
            roll: 0.0
            pitch: 0.0
            yaw: -0.055580511080896136
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.019254302866962003
            roll: 0.0
            pitch: 0.0
            yaw: -0.14971741385934606
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01809657663210676
            roll: 0.0
            pitch: 0.0
            yaw: -0.04354531085603225
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.012409113980014631
            roll: 0.0
            pitch: 0.0
            yaw: 0.1088523220939493
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02444119117666413
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.015814631618817
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07579203332821605
            roll: 0.0
            pitch: 0.0
            yaw: -0.6287557968212525
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04706651078797505
            roll: 0.0
            pitch: 0.0
            yaw: -0.3416587985206818
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.039273614252758125
            roll: 0.0
            pitch: 0.0
            yaw: 0.91705845976495
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07553941235710013
            roll: 0.0
            pitch: 0.0
            yaw: 0.8106096353166121
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.002434619744252048
            roll: 0.0
            pitch: 0.0
            yaw: -0.7218209871270928
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.01454533097386683
            roll: 0.0
            pitch: 0.0
            yaw: -0.3077083161802029
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00013650653727982978
              y: 0.01729301270336582
              z: 0.041294655379555636
              roll: 0.45026402592503456
              pitch: -0.5149512080301487
              yaw: 1.3055457454245503
            roll: 0.4090765667422411
            pitch: -0.5126767791010383
            yaw: 1.3195930923130215
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.19572441245237757
          y: -0.18062417475974898
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.1808390642580222
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.005942684075139974
            roll: 0.0
            pitch: 0.0
            yaw: -0.005347072678739295
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.011734654730598863
            roll: 0.0
            pitch: 0.0
            yaw: -0.1286326394181502
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.005612460430116067
            roll: 0.0
            pitch: 0.0
            yaw: 0.11374160189380178
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.019533782189972752
            roll: 0.0
            pitch: 0.0
            yaw: -0.14797974296942434
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01102684763140565
            roll: 0.0
            pitch: 0.0
            yaw: 0.08550960719015088
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04828762583890847
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0016304815983889248
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04299357465804666
            roll: 0.0
            pitch: 0.0
            yaw: 0.143321404871662
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05969248764828027
            roll: 0.0
            pitch: 0.0
            yaw: -0.6595332410179839
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08558577802399081
            roll: 0.0
            pitch: 0.0
            yaw: 0.26218056882787955
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03187541203100189
            roll: 0.0
            pitch: 0.0
            yaw: 0.5243445288191417
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05156192312270683
            roll: 0.0
            pitch: 0.0
            yaw: -0.6367257305853833
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.039511634194124054
            roll: 0.0
            pitch: 0.0
            yaw: -0.4832485918391026
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.000905709593021784
              y: 0.01662797315785848
              z: 0.04342322523273077
              roll: 0.42133763411130476
              pitch: -0.4838623899926889
              yaw: 1.3069210013298815
            roll: 0.41661735887424406
            pitch: -0.4749610503904839
            yaw: 1.307611521992002
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
