scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.19121670228045615
          y: -0.2909500269901419
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.349174056794887
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.011035433889576701
            roll: 0.0
            pitch: 0.0
            yaw: 0.04073052841606267
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006062947402130368
            roll: 0.0
            pitch: 0.0
            yaw: -0.05015190025638111
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0051462084767807635
            roll: 0.0
            pitch: 0.0
            yaw: -0.020048923323855106
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01417545526973818
            roll: 0.0
            pitch: 0.0
            yaw: -0.10616024235701242
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.014853659207196508
            roll: 0.0
            pitch: 0.0
            yaw: 0.004219893897130594
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03276042270374098
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0514928606471671
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06444204593293451
            roll: 0.0
            pitch: 0.0
            yaw: 0.8372163380517381
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09153987440460416
            roll: 0.0
            pitch: 0.0
            yaw: -0.9279499370415758
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0552234599395001
            roll: 0.0
            pitch: 0.0
            yaw: -0.14729960885348814
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.09039326249253511
            roll: 0.0
            pitch: 0.0
            yaw: 0.7195958375095739
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.021871502058150735
            roll: 0.0
            pitch: 0.0
            yaw: 0.3508352306665814
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03164455796995741
            roll: 0.0
            pitch: 0.0
            yaw: 0.5281000895011452
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 7.324933862744038e-05
              y: 0.01373115438176815
              z: 0.042285540798755857
              roll: 0.4472293855465548
              pitch: -0.4639545674198704
              yaw: 1.3185375828607897
            roll: 0.47471381645866495
            pitch: -0.478109992990122
            yaw: 1.3451836168889906
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.12667863342668068
          y: -0.26427145079703895
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.3265601508416057
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01502716616611257
            roll: 0.0
            pitch: 0.0
            yaw: 0.07435877385594272
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006516572311819161
            roll: 0.0
            pitch: 0.0
            yaw: -0.054763571180492854
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.007507926735909831
            roll: 0.0
            pitch: 0.0
            yaw: -0.12461629480200953
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0035202590542409533
            roll: 0.0
            pitch: 0.0
            yaw: 0.12743879244136103
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.015746947486874482
            roll: 0.0
            pitch: 0.0
            yaw: -0.0916470582327232
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02660080267828857
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.022110363994900892
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.017311445801931405
            roll: 0.0
            pitch: 0.0
            yaw: -0.10556579719607617
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.024402029832216066
            roll: 0.0
            pitch: 0.0
            yaw: -0.2818075385004931
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04466491144706611
            roll: 0.0
            pitch: 0.0
            yaw: 0.37092451524629566
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04795631535816941
            roll: 0.0
            pitch: 0.0
            yaw: 1.0377356581210317
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05864927347865134
            roll: 0.0
            pitch: 0.0
            yaw: 0.4849082663517681
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04984397561786644
            roll: 0.0
            pitch: 0.0
            yaw: 0.6287099618617946
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0006055708804617991
              y: 0.013971242319367954
              z: 0.0441975148103832
              roll: 0.44351728396875423
              pitch: -0.45581425868195036
              yaw: 1.3226456262547626
            roll: 0.4383330497144226
            pitch: -0.5161414514508845
            yaw: 1.33555844298971
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.18352919004504348
          y: -0.28531143575936085
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.07340382029209414
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0026459817557870705
            roll: 0.0
            pitch: 0.0
            yaw: -0.15673011256288252
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.012383422905642944
            roll: 0.0
            pitch: 0.0
            yaw: 0.08889170605686669
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01646123964862313
            roll: 0.0
            pitch: 0.0
            yaw: 0.11122515468083782
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.016239047199604877
            roll: 0.0
            pitch: 0.0
            yaw: 0.11023535614812457
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.008248809682047801
            roll: 0.0
            pitch: 0.0
            yaw: 0.05064096684768385
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04688823986779597
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04046618277245248
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.06080905598611075
            roll: 0.0
            pitch: 0.0
            yaw: -0.6511584797874959
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09553614671155156
            roll: 0.0
            pitch: 0.0
            yaw: 0.04051156881711093
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08517027458799264
            roll: 0.0
            pitch: 0.0
            yaw: -0.8775451604865004
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.045164659678876534
            roll: 0.0
            pitch: 0.0
            yaw: -0.4189573853538351
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07190517632609625
            roll: 0.0
            pitch: 0.0
            yaw: 0.544046066025957
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07963151815253426
            roll: 0.0
            pitch: 0.0
            yaw: 0.3496616003596609
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0010633596623765788
              y: 0.013942553331186866
              z: 0.044335402264827115
              roll: 0.4063512487382485
              pitch: -0.4920461529254413
              yaw: 1.2961042943096226
            roll: 0.4604684141983314
            pitch: -0.48249495815749716
            yaw: 1.3494281429932011
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
