scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.18796075325594935
          y: -0.20324773226960643
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.37237408063963795
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.010202274510664458
            roll: 0.0
            pitch: 0.0
            yaw: 0.11580623719126865
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.017472676982329686
            roll: 0.0
            pitch: 0.0
            yaw: 0.08250287624626323
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.019720226309273566
            roll: 0.0
            pitch: 0.0
            yaw: -0.02513885482886974
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0011813577094036687
            roll: 0.0
            pitch: 0.0
            yaw: -0.00595414912383474
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.020178778256482628
            roll: 0.0
            pitch: 0.0
            yaw: -0.03200384173704335
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.035138004665860756
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.01915620241084294
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.05055214885859727
            roll: 0.0
            pitch: 0.0
            yaw: 0.9802642888477637
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.057699164751670556
            roll: 0.0
            pitch: 0.0
            yaw: -0.47640913763670867
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.046106572199733076
            roll: 0.0
            pitch: 0.0
            yaw: 0.7271995255999775
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08626760026201308
            roll: 0.0
            pitch: 0.0
            yaw: -0.565283517036774
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08607879711034436
            roll: 0.0
            pitch: 0.0
            yaw: -0.5561292965676976
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.026466232972768552
            roll: 0.0
            pitch: 0.0
            yaw: -0.5657056096493702
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0008976630522224784
              y: 0.014299572275279749
              z: 0.043098782844442185
              roll: 0.4380969472158536
              pitch: -0.49726886892722544
              yaw: 1.368877598672337
            roll: 0.4124350560772204
            pitch: -0.47082013141108386
            yaw: 1.3278739418999148
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.23514807021101364
          y: -0.2830465638878158
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.08765914922253026
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.02224266967287067
            roll: 0.0
            pitch: 0.0
            yaw: -0.03758333189187721
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01963151654154924
            roll: 0.0
            pitch: 0.0
            yaw: 0.021181219880208685
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.010470359617220332
            roll: 0.0
            pitch: 0.0
            yaw: 0.07037906034783545
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.009766870724503425
            roll: 0.0
            pitch: 0.0
            yaw: -0.05662482904291116
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.021237703811839075
            roll: 0.0
            pitch: 0.0
            yaw: 0.0023115569757110044
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.018805742882693724
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05228821178679112
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.06733080566215244
            roll: 0.0
            pitch: 0.0
            yaw: -1.0265193379294733
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.054316358605396964
            roll: 0.0
            pitch: 0.0
            yaw: -0.2345687432631689
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.005856012389291287
            roll: 0.0
            pitch: 0.0
            yaw: 0.5881995655155676
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.025544066099112528
            roll: 0.0
            pitch: 0.0
            yaw: 0.3513072728801614
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.02534267128548169
            roll: 0.0
            pitch: 0.0
            yaw: 0.6010306614353105
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05029910044353442
            roll: 0.0
            pitch: 0.0
            yaw: -0.2819683216229417
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0008138937458147227
              y: 0.01632975120949093
              z: 0.04174747731064306
              roll: 0.4514695774059392
              pitch: -0.472587282236213
              yaw: 1.3041223878897754
            roll: 0.458996513326957
            pitch: -0.4701693628706979
            yaw: 1.293357146114925
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.13040083590879897
          y: -0.2610604558679525
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.07138146231513198
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0023796527973938483
            roll: 0.0
            pitch: 0.0
            yaw: 0.07586867234804379
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.02087795077446994
            roll: 0.0
            pitch: 0.0
            yaw: -0.015238731828836838
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.018774262671343384
            roll: 0.0
            pitch: 0.0
            yaw: -0.16075777673738903
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.005302887935788696
            roll: 0.0
            pitch: 0.0
            yaw: -0.03640206484218733
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.007152374629333031
            roll: 0.0
            pitch: 0.0
            yaw: 0.08757072654659859
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.026702473818235727
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.025777830282598148
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0027529030579788866
            roll: 0.0
            pitch: 0.0
            yaw: 0.1758907547897013
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05099303233415529
            roll: 0.0
            pitch: 0.0
            yaw: -0.9703666473608415
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07996688153141879
            roll: 0.0
            pitch: 0.0
            yaw: 0.20756634424677012
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.024764570091183838
            roll: 0.0
            pitch: 0.0
            yaw: 0.21312659892425323
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.046736959324906235
            roll: 0.0
            pitch: 0.0
            yaw: -0.07032633044030279
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06912177824426133
            roll: 0.0
            pitch: 0.0
            yaw: -0.9963799248484755
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0012865216032519476
              y: 0.017094360001686654
              z: 0.0441952497533706
              roll: 0.4219994292371146
              pitch: -0.5153528460976052
              yaw: 1.3246838063583002
            roll: 0.4557095575543808
            pitch: -0.5029355120626194
            yaw: 1.3303933255494471
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
