scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.11924796156798985
          y: -0.23635761222087592
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.30793536007502076
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.007316850608348642
            roll: 0.0
            pitch: 0.0
            yaw: -0.053412102822683244
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.014849559223561189
            roll: 0.0
            pitch: 0.0
            yaw: -0.036981028565600316
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01573791865584801
            roll: 0.0
            pitch: 0.0
            yaw: 0.15217306893524052
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.017520746928453238
            roll: 0.0
            pitch: 0.0
            yaw: 0.13550435144433737
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.019296261490108668
            roll: 0.0
            pitch: 0.0
            yaw: 0.04366461042736183
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.048631461519698965
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04252728070445988
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.014369633857132857
            roll: 0.0
            pitch: 0.0
            yaw: 0.056630235215070934
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08229307047543472
            roll: 0.0
            pitch: 0.0
            yaw: -0.8287554906247381
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.008472017711007154
            roll: 0.0
            pitch: 0.0
            yaw: -0.36081862301444156
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.006238754297051563
            roll: 0.0
            pitch: 0.0
            yaw: 0.26045181638721004
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.044391616345644314
            roll: 0.0
            pitch: 0.0
            yaw: 0.2908080524666512
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.022774345484094224
            roll: 0.0
            pitch: 0.0
            yaw: -1.0443736114499764
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0008989283652550517
              y: 0.017002266517499462
              z: 0.04363809233770663
              roll: 0.4048836115479329
              pitch: -0.5021674611098008
              yaw: 1.3151700506072566
            roll: 0.408323556559536
            pitch: -0.4765777879564557
            yaw: 1.367803800512856
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.24524326544026934
          y: -0.11962321953039001
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4980071768184725
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.009733905463046595
            roll: 0.0
            pitch: 0.0
            yaw: -0.08574700024075949
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008023773944779279
            roll: 0.0
            pitch: 0.0
            yaw: 0.050924884199788495
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.010440807693521367
            roll: 0.0
            pitch: 0.0
            yaw: -0.0039816363062775695
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013559183180626063
            roll: 0.0
            pitch: 0.0
            yaw: -0.0659848346823539
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.006891328710935531
            roll: 0.0
            pitch: 0.0
            yaw: -0.009046969644408154
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.004439999200642808
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.020479541069768147
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.027394902924073775
            roll: 0.0
            pitch: 0.0
            yaw: 0.8212532658148639
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07151573296420427
            roll: 0.0
            pitch: 0.0
            yaw: -0.5804786651170649
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04445692493352757
            roll: 0.0
            pitch: 0.0
            yaw: -0.7225385979696919
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.012182381577681062
            roll: 0.0
            pitch: 0.0
            yaw: 0.3718506283769365
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.03152035423375098
            roll: 0.0
            pitch: 0.0
            yaw: -1.0302088452072748
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0795804977877203
            roll: 0.0
            pitch: 0.0
            yaw: -0.6283657677030219
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00048697860580229103
              y: 0.014553194859934497
              z: 0.043204516616160045
              roll: 0.42194755168997955
              pitch: -0.4741376421320696
              yaw: 1.321663571464964
            roll: 0.4134626154319651
            pitch: -0.48037799552461086
            yaw: 1.2991742613222932
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.16708352015749076
          y: -0.15710955704439297
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.014187851822661579
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.016544331806164107
            roll: 0.0
            pitch: 0.0
            yaw: -0.028114444678416783
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.010858312130643899
            roll: 0.0
            pitch: 0.0
            yaw: 0.08168256997352907
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.010795432138207915
            roll: 0.0
            pitch: 0.0
            yaw: 0.13484574357645052
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.002233526178086802
            roll: 0.0
            pitch: 0.0
            yaw: 0.08841563627768201
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01699637013274593
            roll: 0.0
            pitch: 0.0
            yaw: -0.06730213436976147
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.029642263585540948
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03360536115895832
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.01976616841580907
            roll: 0.0
            pitch: 0.0
            yaw: 1.031196284828168
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09012640623137094
            roll: 0.0
            pitch: 0.0
            yaw: 0.5643086606043273
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06260509574275573
            roll: 0.0
            pitch: 0.0
            yaw: -0.5740091197605665
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08186566291918382
            roll: 0.0
            pitch: 0.0
            yaw: 0.48763500349153976
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07735797033357585
            roll: 0.0
            pitch: 0.0
            yaw: 0.6433919625267672
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07620557402719405
            roll: 0.0
            pitch: 0.0
            yaw: -0.13651170077232566
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0010632615002870126
              y: 0.01651122587449837
              z: 0.04372936960174677
              roll: 0.41751679438625056
              pitch: -0.5182487051421437
              yaw: 1.3418881007343144
            roll: 0.41536184580935137
            pitch: -0.4991527043110385
            yaw: 1.3328882152859824
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
