scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.23974706506425772
          y: -0.22495774732459567
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.49110071504133623
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0030580908258947513
            roll: 0.0
            pitch: 0.0
            yaw: -0.09859287659510722
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.00593371195059586
            roll: 0.0
            pitch: 0.0
            yaw: -0.13039690350526323
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.02046693439656915
            roll: 0.0
            pitch: 0.0
            yaw: 0.07737412456163029
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.020517250159709767
            roll: 0.0
            pitch: 0.0
            yaw: 0.11622884429162733
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.019574705485077407
            roll: 0.0
            pitch: 0.0
            yaw: -0.0988930626655701
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05737980185204374
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.025620877139018193
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.025562963814529036
            roll: 0.0
            pitch: 0.0
            yaw: -0.22633055668390245
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07485411268881145
            roll: 0.0
            pitch: 0.0
            yaw: 0.8064911439816478
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02112894327544297
            roll: 0.0
            pitch: 0.0
            yaw: 0.3397554763508974
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0029487418358741246
            roll: 0.0
            pitch: 0.0
            yaw: -0.7898432300847856
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.022287275059266948
            roll: 0.0
            pitch: 0.0
            yaw: 0.39986817077705283
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04396923470869997
            roll: 0.0
            pitch: 0.0
            yaw: -0.15987672659738583
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00036480544800213035
              y: 0.015830020800652503
              z: 0.04329389095504925
              roll: 0.43199907951342453
              pitch: -0.4443099184425228
              yaw: 1.3412351528283757
            roll: 0.408559446817179
            pitch: -0.49918870879219834
            yaw: 1.3001789163610848
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.125841344383556
          y: -0.2480655809153619
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.2850936930501977
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.017152729830150808
            roll: 0.0
            pitch: 0.0
            yaw: -0.05699055168901743
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.018974660907199865
            roll: 0.0
            pitch: 0.0
            yaw: 0.12959142874680396
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.00026444383910136787
            roll: 0.0
            pitch: 0.0
            yaw: 0.08476743200424186
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01906844612006929
            roll: 0.0
            pitch: 0.0
            yaw: 0.12681528620867594
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.019370413739860058
            roll: 0.0
            pitch: 0.0
            yaw: 0.14386232251662462
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.024978197664426972
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05017253556417379
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.03738286330328883
            roll: 0.0
            pitch: 0.0
            yaw: -0.9376508030919228
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.046360034914177645
            roll: 0.0
            pitch: 0.0
            yaw: 0.8032229517080969
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04554673684077126
            roll: 0.0
            pitch: 0.0
            yaw: 0.18832574699557414
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07718651879163241
            roll: 0.0
            pitch: 0.0
            yaw: 0.9500472934051369
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06843914085722828
            roll: 0.0
            pitch: 0.0
            yaw: 0.036513863655786016
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03270521786809827
            roll: 0.0
            pitch: 0.0
            yaw: -0.4352620359342243
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00017573809535324563
              y: 0.013792290573638268
              z: 0.042809832567317484
              roll: 0.46284941417297626
              pitch: -0.44755475278883816
              yaw: 1.3232824184408678
            roll: 0.4071009960892513
            pitch: -0.471750625750771
            yaw: 1.3226287689712812
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.10300836716880563
          y: -0.2605717642537162
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.36712454859599886
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.007806205786765351
            roll: 0.0
            pitch: 0.0
            yaw: 0.1236551514065155
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.00732270077116947
            roll: 0.0
            pitch: 0.0
            yaw: -0.15070408834937798
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.012024739507077914
            roll: 0.0
            pitch: 0.0
            yaw: 0.13190262263802582
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02123521212315311
            roll: 0.0
            pitch: 0.0
            yaw: -0.04967568427404259
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0005112874777209037
            roll: 0.0
            pitch: 0.0
            yaw: -0.11811322088053725
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.01804594243296679
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04291419802560102
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06608736256458951
            roll: 0.0
            pitch: 0.0
            yaw: 0.4221240394309276
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.018129524248440443
            roll: 0.0
            pitch: 0.0
            yaw: 0.8056329280157084
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07452446930808834
            roll: 0.0
            pitch: 0.0
            yaw: -0.25605171401855553
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0005874563008514272
            roll: 0.0
            pitch: 0.0
            yaw: 0.29328460670413703
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.043478609427550816
            roll: 0.0
            pitch: 0.0
            yaw: 0.5650457381248271
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.030794204794689264
            roll: 0.0
            pitch: 0.0
            yaw: -0.19558823963511007
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0011025251625333293
              y: 0.016739603325099228
              z: 0.04339193422906105
              roll: 0.4473319974115704
              pitch: -0.46340306901366235
              yaw: 1.2907852030103275
            roll: 0.47429924182793337
            pitch: -0.4446359756487047
            yaw: 1.342231717282927
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
