scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.10115013131730122
          y: -0.1994416499044644
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.19565479244119421
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.011061273154389109
            roll: 0.0
            pitch: 0.0
            yaw: 0.10878987398523482
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.00611853959502992
            roll: 0.0
            pitch: 0.0
            yaw: 0.11680000256861095
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.007698394691564175
            roll: 0.0
            pitch: 0.0
            yaw: 0.10158141801640808
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.003433952260426098
            roll: 0.0
            pitch: 0.0
            yaw: 0.1354558829117382
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.007676629721370714
            roll: 0.0
            pitch: 0.0
            yaw: 0.14528793438582643
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.008297426592775714
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04102216048380061
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.03929555126372349
            roll: 0.0
            pitch: 0.0
            yaw: -0.6927993895167968
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.023634866589763187
            roll: 0.0
            pitch: 0.0
            yaw: -0.15239719154866072
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.01957905097472591
            roll: 0.0
            pitch: 0.0
            yaw: -0.019783964871922466
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.025756059867781567
            roll: 0.0
            pitch: 0.0
            yaw: 0.7026080925674607
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.062401353062970955
            roll: 0.0
            pitch: 0.0
            yaw: 0.956135058670043
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07258466865648014
            roll: 0.0
            pitch: 0.0
            yaw: -0.9616040695407027
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0002284436089538917
              y: 0.015732997286794552
              z: 0.041569784433944365
              roll: 0.41731820972177386
              pitch: -0.5161001970228857
              yaw: 1.2993642760745685
            roll: 0.42581749222766596
            pitch: -0.4432568333576852
            yaw: 1.3560460261221303
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.18088514748000148
          y: -0.16783254050433488
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.20450946582912477
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.019738961845220455
            roll: 0.0
            pitch: 0.0
            yaw: -0.14107494827646044
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.007165358384242374
            roll: 0.0
            pitch: 0.0
            yaw: 0.023022037612968088
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01855590182360932
            roll: 0.0
            pitch: 0.0
            yaw: 0.01769341366954752
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.00649956043786051
            roll: 0.0
            pitch: 0.0
            yaw: 0.012755323602742896
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.021669409995762084
            roll: 0.0
            pitch: 0.0
            yaw: 0.08027909879428752
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.051440756280270755
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.002576081715616574
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0250692767114237
            roll: 0.0
            pitch: 0.0
            yaw: -0.1637367132990042
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.06688464938783487
            roll: 0.0
            pitch: 0.0
            yaw: 0.2418106718505535
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.018522880372588618
            roll: 0.0
            pitch: 0.0
            yaw: 1.0416976787964554
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.011247277933249172
            roll: 0.0
            pitch: 0.0
            yaw: 0.550781531797438
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07156041683433545
            roll: 0.0
            pitch: 0.0
            yaw: 0.2785156932982469
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0547168318148922
            roll: 0.0
            pitch: 0.0
            yaw: 0.6220914806754629
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0014012979086596277
              y: 0.013771248843337193
              z: 0.04054896504835764
              roll: 0.46559662098578636
              pitch: -0.47307362274293074
              yaw: 1.3251653652413018
            roll: 0.4156099224309671
            pitch: -0.46901111737075923
            yaw: 1.299672139727177
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2889460795435649
          y: -0.24943210864801557
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.11841100547970007
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01766519583430972
            roll: 0.0
            pitch: 0.0
            yaw: -0.12198854307625459
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.020239205414279836
            roll: 0.0
            pitch: 0.0
            yaw: -0.16374615171159063
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.018063735851569552
            roll: 0.0
            pitch: 0.0
            yaw: 0.09573731439181193
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0017010133453734394
            roll: 0.0
            pitch: 0.0
            yaw: -0.1725959112475168
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.004384472959804792
            roll: 0.0
            pitch: 0.0
            yaw: -0.16870326571921962
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.011732548937429407
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.004086726628616338
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07246341586858583
            roll: 0.0
            pitch: 0.0
            yaw: -0.11177255837998878
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07746775660683133
            roll: 0.0
            pitch: 0.0
            yaw: -0.053406713230677805
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05664458625395311
            roll: 0.0
            pitch: 0.0
            yaw: 0.8036537339802987
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09196833090078857
            roll: 0.0
            pitch: 0.0
            yaw: 0.2836834026159627
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.020956086479221828
            roll: 0.0
            pitch: 0.0
            yaw: 0.48489778429953123
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.043935173795068366
            roll: 0.0
            pitch: 0.0
            yaw: 0.6831666876209592
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0016652811854073399
              y: 0.01679700477145318
              z: 0.042364087903971004
              roll: 0.4277387158809561
              pitch: -0.49628879281984495
              yaw: 1.310294562789096
            roll: 0.42530416401537485
            pitch: -0.5163307084822685
            yaw: 1.3077412231093306
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
