scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.17839532294118113
          y: -0.25985352447345134
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.2689152758055938
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.003755425304323927
            roll: 0.0
            pitch: 0.0
            yaw: 0.15668257802273822
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0010555886324166916
            roll: 0.0
            pitch: 0.0
            yaw: -0.021583088131600675
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0038500098396203053
            roll: 0.0
            pitch: 0.0
            yaw: -0.1552886767592656
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.020603920485973898
            roll: 0.0
            pitch: 0.0
            yaw: -0.10313158606040182
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.015083099230533512
            roll: 0.0
            pitch: 0.0
            yaw: 0.01685645885939724
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.045346197518034065
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.009496224938982147
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.03166125339018107
            roll: 0.0
            pitch: 0.0
            yaw: 0.8250955805696556
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.038443161686249956
            roll: 0.0
            pitch: 0.0
            yaw: -1.012105843411809
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0633948353952053
            roll: 0.0
            pitch: 0.0
            yaw: -0.990757201618943
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03859009623162145
            roll: 0.0
            pitch: 0.0
            yaw: 0.5464100659073601
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.01351727225873238
            roll: 0.0
            pitch: 0.0
            yaw: -0.09156703383662856
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04951379162639202
            roll: 0.0
            pitch: 0.0
            yaw: 0.81522688479991
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0003832097302331552
              y: 0.01438374044381793
              z: 0.04183589992844579
              roll: 0.4133794575757147
              pitch: -0.4665036893333546
              yaw: 1.307978948596857
            roll: 0.4666089071660059
            pitch: -0.5050476409040422
            yaw: 1.3571745198537555
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.29960933002951917
          y: -0.14441083960707932
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.028368921488625243
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01950208133640227
            roll: 0.0
            pitch: 0.0
            yaw: -0.028199854752097353
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.007886954723964218
            roll: 0.0
            pitch: 0.0
            yaw: -0.016716623410567566
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.009232664412584222
            roll: 0.0
            pitch: 0.0
            yaw: -0.10159411501736498
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01899372387639458
            roll: 0.0
            pitch: 0.0
            yaw: -0.05073855978062379
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.009770456678226921
            roll: 0.0
            pitch: 0.0
            yaw: 0.03326063877183899
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.042127340108568875
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03292668277809419
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.03161027112566017
            roll: 0.0
            pitch: 0.0
            yaw: 0.18195111902826788
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05217142188626316
            roll: 0.0
            pitch: 0.0
            yaw: 0.6827665077839626
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07237011642670438
            roll: 0.0
            pitch: 0.0
            yaw: 0.03049283020748028
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09190578660973867
            roll: 0.0
            pitch: 0.0
            yaw: -0.6430190512046832
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.053063728545172606
            roll: 0.0
            pitch: 0.0
            yaw: -0.5340391445067272
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.056997062455060366
            roll: 0.0
            pitch: 0.0
            yaw: -0.06874378111470059
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0017222721247173705
              y: 0.016280395708267472
              z: 0.04053564899413011
              roll: 0.4576192307957093
              pitch: -0.44659092420927426
              yaw: 1.3372047648517034
            roll: 0.4297032777727527
            pitch: -0.45956707553826104
            yaw: 1.3176865480370838
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.1491091416609502
          y: -0.19301918590749878
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.1546470499054018
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01576447271143449
            roll: 0.0
            pitch: 0.0
            yaw: 0.008086916986026066
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.013756022380914211
            roll: 0.0
            pitch: 0.0
            yaw: -0.03512579649624861
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.019380002456158583
            roll: 0.0
            pitch: 0.0
            yaw: 0.14697404805531056
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.008124584732608204
            roll: 0.0
            pitch: 0.0
            yaw: 0.17254005951125295
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.016073412256897845
            roll: 0.0
            pitch: 0.0
            yaw: -0.04724410864418707
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.051559305364423026
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.013525024149388581
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04869126092974949
            roll: 0.0
            pitch: 0.0
            yaw: -0.9364059297748895
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.022620193610064995
            roll: 0.0
            pitch: 0.0
            yaw: -0.3946901132159506
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.060842828241110584
            roll: 0.0
            pitch: 0.0
            yaw: -1.0326277475399217
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07648959954812623
            roll: 0.0
            pitch: 0.0
            yaw: -0.7894838541863369
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.007419925901245655
            roll: 0.0
            pitch: 0.0
            yaw: -0.31707153966494483
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.019762811826659676
            roll: 0.0
            pitch: 0.0
            yaw: -0.9825870176714009
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0015332510034687659
              y: 0.01483454826565418
              z: 0.04053202764945782
              roll: 0.48251515723643523
              pitch: -0.48601546842275145
              yaw: 1.3435201927451936
            roll: 0.46052894658099675
            pitch: -0.4621393322447005
            yaw: 1.3634148218300055
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
