scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.27255533682541666
          y: -0.15310334308461085
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.051327130345705796
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.00884578324455049
            roll: 0.0
            pitch: 0.0
            yaw: 0.045977913521884795
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01893840881549314
            roll: 0.0
            pitch: 0.0
            yaw: 0.05584765620075527
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.011779949590294242
            roll: 0.0
            pitch: 0.0
            yaw: -0.10691418750884893
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0010999203766799796
            roll: 0.0
            pitch: 0.0
            yaw: -0.11033731053924883
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.022731847090349526
            roll: 0.0
            pitch: 0.0
            yaw: -0.1028067825257512
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.01901272207877914
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.024524550911637466
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08509949773339283
            roll: 0.0
            pitch: 0.0
            yaw: 0.30369999147807536
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.02826911734594298
            roll: 0.0
            pitch: 0.0
            yaw: 0.09479942762157756
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06310741232528119
            roll: 0.0
            pitch: 0.0
            yaw: -0.11818010425242775
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06522871587606267
            roll: 0.0
            pitch: 0.0
            yaw: 0.846817984175158
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0845477421326922
            roll: 0.0
            pitch: 0.0
            yaw: 0.9002294739753687
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08533363259672738
            roll: 0.0
            pitch: 0.0
            yaw: 0.27415000066248085
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00028104574914945466
              y: 0.015510197447316338
              z: 0.04111950343259533
              roll: 0.4560955508538556
              pitch: -0.4900005703222396
              yaw: 1.368715511092352
            roll: 0.4606540723199089
            pitch: -0.4401722019001006
            yaw: 1.3400233902068315
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1556550929044046
          y: -0.16066879533683948
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3322755443034686
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.010911605747461488
            roll: 0.0
            pitch: 0.0
            yaw: 0.04814301351893141
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.019734711187816154
            roll: 0.0
            pitch: 0.0
            yaw: -0.12778950682320508
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0022412492782930976
            roll: 0.0
            pitch: 0.0
            yaw: 0.03962969806121644
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01940682656950323
            roll: 0.0
            pitch: 0.0
            yaw: 0.04519076243960912
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.020457372289206764
            roll: 0.0
            pitch: 0.0
            yaw: -0.010870960054746415
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05777385871812376
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.027843770850882632
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05689972646652277
            roll: 0.0
            pitch: 0.0
            yaw: -0.03531285703580389
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0548002849563437
            roll: 0.0
            pitch: 0.0
            yaw: 0.9828651981731464
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.017340681426752214
            roll: 0.0
            pitch: 0.0
            yaw: -0.14097210092990853
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04780531281788797
            roll: 0.0
            pitch: 0.0
            yaw: -0.9596542507303004
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.09456436053504805
            roll: 0.0
            pitch: 0.0
            yaw: -0.0790014105634913
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06594001637188296
            roll: 0.0
            pitch: 0.0
            yaw: 0.5208037307499234
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0013006095067106915
              y: 0.016387257390556548
              z: 0.04147191508140979
              roll: 0.41614832941575436
              pitch: -0.44422877078498957
              yaw: 1.3588413571878915
            roll: 0.46213247065958896
            pitch: -0.45718697820321963
            yaw: 1.3472663121999795
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.137627938080382
          y: -0.24292765360798976
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.2581422139650241
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.013055423117096593
            roll: 0.0
            pitch: 0.0
            yaw: 0.17049683100090135
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.016768282217112317
            roll: 0.0
            pitch: 0.0
            yaw: 0.009954379483395226
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.019042786810918023
            roll: 0.0
            pitch: 0.0
            yaw: -0.0008894225328997252
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.008433197039996603
            roll: 0.0
            pitch: 0.0
            yaw: -0.05829696934764199
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.011373646466827439
            roll: 0.0
            pitch: 0.0
            yaw: -0.050540785622296566
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04291323730960872
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0021441773546047108
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07416597797694588
            roll: 0.0
            pitch: 0.0
            yaw: 0.11388418951099366
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07879040373697724
            roll: 0.0
            pitch: 0.0
            yaw: 0.8463804399334762
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08544828519058753
            roll: 0.0
            pitch: 0.0
            yaw: -0.9670899333263473
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08675713741086202
            roll: 0.0
            pitch: 0.0
            yaw: -0.8567660592103744
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.019588778615222693
            roll: 0.0
            pitch: 0.0
            yaw: -0.18354048433330838
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08050929753267227
            roll: 0.0
            pitch: 0.0
            yaw: 0.9233592610106258
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0007022351020235921
              y: 0.016056828879685243
              z: 0.04221725626782937
              roll: 0.4253253162803507
              pitch: -0.47594827714139437
              yaw: 1.3320432653230851
            roll: 0.472854991103465
            pitch: -0.47016938935085284
            yaw: 1.2910655342280912
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
