scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.17062349385382333
          y: -0.29583506605999565
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.0006469887157078968
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.006359793137727311
            roll: 0.0
            pitch: 0.0
            yaw: -0.06379723313835875
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008376523884266662
            roll: 0.0
            pitch: 0.0
            yaw: 0.15678326476267906
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01992232033335009
            roll: 0.0
            pitch: 0.0
            yaw: 0.1338805957017531
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0151871036436221
            roll: 0.0
            pitch: 0.0
            yaw: -0.055722522923628004
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.006853332937090546
            roll: 0.0
            pitch: 0.0
            yaw: 0.12174750092477704
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02539379353137934
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.029059903810368166
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.061878347300909686
            roll: 0.0
            pitch: 0.0
            yaw: 0.9415362775827671
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07312347922265314
            roll: 0.0
            pitch: 0.0
            yaw: 0.03498604407874195
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08593407530129292
            roll: 0.0
            pitch: 0.0
            yaw: 0.31083024708180074
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.014897859795429791
            roll: 0.0
            pitch: 0.0
            yaw: -0.43436175351580275
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.022980868616309325
            roll: 0.0
            pitch: 0.0
            yaw: 0.21056485849664952
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09607653036598128
            roll: 0.0
            pitch: 0.0
            yaw: -0.10760105651096741
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0002297301568305371
              y: 0.014701704989522866
              z: 0.043791445826289806
              roll: 0.45600819130655873
              pitch: -0.5005707252948445
              yaw: 1.3637128333585982
            roll: 0.42162744340942143
            pitch: -0.48152157282240926
            yaw: 1.3499026913971472
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2806077210162063
          y: -0.2517380940403149
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.29398004849049164
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.015023139668129543
            roll: 0.0
            pitch: 0.0
            yaw: -0.07097652499222516
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0055226380366923955
            roll: 0.0
            pitch: 0.0
            yaw: -0.13552164555052038
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.015810910935275507
            roll: 0.0
            pitch: 0.0
            yaw: 0.13253203497125315
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.002942142789286329
            roll: 0.0
            pitch: 0.0
            yaw: -0.0710547653917871
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0026763914901731627
            roll: 0.0
            pitch: 0.0
            yaw: 0.08903434741747918
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.053523306129206485
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05124691377855628
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07336433239748205
            roll: 0.0
            pitch: 0.0
            yaw: -0.7713352134552054
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08746951925969385
            roll: 0.0
            pitch: 0.0
            yaw: -0.3737833015877796
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.09146492750979665
            roll: 0.0
            pitch: 0.0
            yaw: 0.37443733826949743
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08128066084862445
            roll: 0.0
            pitch: 0.0
            yaw: 0.7077303000167978
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.004978017406563562
            roll: 0.0
            pitch: 0.0
            yaw: -0.8824041699030013
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.024564480829368948
            roll: 0.0
            pitch: 0.0
            yaw: 0.01677848697476736
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0014449227921340957
              y: 0.01647490914966489
              z: 0.0439436541261164
              roll: 0.42235136946620033
              pitch: -0.5096559991632811
              yaw: 1.302040607958906
            roll: 0.4706448632169784
            pitch: -0.44076272800594873
            yaw: 1.3331354430759959
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2891262366545895
          y: -0.1582037997562471
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.3182691405128313
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01605899629199148
            roll: 0.0
            pitch: 0.0
            yaw: -0.1572975762072954
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.019178053534209538
            roll: 0.0
            pitch: 0.0
            yaw: 0.09050735031489898
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.009373470741167166
            roll: 0.0
            pitch: 0.0
            yaw: -0.08750456024532795
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.009160217444019129
            roll: 0.0
            pitch: 0.0
            yaw: -0.05567839782776447
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01826329573172515
            roll: 0.0
            pitch: 0.0
            yaw: -0.10416359727233838
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04601849892374667
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04308083078687246
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.012604354030827172
            roll: 0.0
            pitch: 0.0
            yaw: 0.22038139811934965
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09255867618073577
            roll: 0.0
            pitch: 0.0
            yaw: 0.8577607505564355
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04330781888027397
            roll: 0.0
            pitch: 0.0
            yaw: 0.9983257700374095
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.006576437856487538
            roll: 0.0
            pitch: 0.0
            yaw: -0.07504032128607518
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.021219833133986052
            roll: 0.0
            pitch: 0.0
            yaw: -0.8081379261809338
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.042059183152012194
            roll: 0.0
            pitch: 0.0
            yaw: 0.026459473403139144
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.00016544990671248398
              y: 0.01578957946084418
              z: 0.042615173262205965
              roll: 0.42944967590294253
              pitch: -0.45903233385791864
              yaw: 1.2970834891053964
            roll: 0.432633572747932
            pitch: -0.4875420246254589
            yaw: 1.347123637749256
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
