scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.23333445637929276
          y: -0.19990327032605437
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.49012289886783433
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0038502299182422775
            roll: 0.0
            pitch: 0.0
            yaw: -0.12610721089863208
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007992280359385075
            roll: 0.0
            pitch: 0.0
            yaw: -0.027300331232431224
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.017930406070952025
            roll: 0.0
            pitch: 0.0
            yaw: 0.03855100973589737
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.020750516933067856
            roll: 0.0
            pitch: 0.0
            yaw: 0.03542078409819116
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.020795024844351605
            roll: 0.0
            pitch: 0.0
            yaw: -0.1434514069989619
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0015480571928829026
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.053524657621529186
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.011363491047743493
            roll: 0.0
            pitch: 0.0
            yaw: 0.22100377663055748
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07877661923449714
            roll: 0.0
            pitch: 0.0
            yaw: -0.44374256073257956
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0048737244539806684
            roll: 0.0
            pitch: 0.0
            yaw: -0.44932718644895264
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.013914236593218388
            roll: 0.0
            pitch: 0.0
            yaw: 0.9816135116730698
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07799229031170823
            roll: 0.0
            pitch: 0.0
            yaw: 1.0215248412242064
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08120860796896023
            roll: 0.0
            pitch: 0.0
            yaw: 0.07894884997638596
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0007417896846489409
              y: 0.014392393002385833
              z: 0.0424674083080517
              roll: 0.4246494020794945
              pitch: -0.4716561274064534
              yaw: 1.3626528318109097
            roll: 0.4461683008145799
            pitch: -0.4553177300067085
            yaw: 1.3510059867702489
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.22493587586204478
          y: -0.16997001386075009
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.42659249641243935
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01695086426575177
            roll: 0.0
            pitch: 0.0
            yaw: 0.16283488260360124
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0016398409949432702
            roll: 0.0
            pitch: 0.0
            yaw: -0.0679191327828411
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.002221894222573663
            roll: 0.0
            pitch: 0.0
            yaw: 0.04690779170365178
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01670230948590862
            roll: 0.0
            pitch: 0.0
            yaw: 0.09511926117317032
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.005025306543824808
            roll: 0.0
            pitch: 0.0
            yaw: 0.09771173857626059
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04185979516227201
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.046224421321202996
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0727618968991267
            roll: 0.0
            pitch: 0.0
            yaw: -0.5389444500058919
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08341586919358257
            roll: 0.0
            pitch: 0.0
            yaw: 0.8450170342984065
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.025738464537017572
            roll: 0.0
            pitch: 0.0
            yaw: -0.5893496618046203
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05121959213207186
            roll: 0.0
            pitch: 0.0
            yaw: -0.7554851951897285
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.021310866750517563
            roll: 0.0
            pitch: 0.0
            yaw: 0.4821804183703029
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.056599704936910314
            roll: 0.0
            pitch: 0.0
            yaw: 0.8137825864961408
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.000600333657087793
              y: 0.017325556049871214
              z: 0.0427471542600504
              roll: 0.4748805066610326
              pitch: -0.4797635057235494
              yaw: 1.3497039513418019
            roll: 0.46852507897010437
            pitch: -0.5109442561441351
            yaw: 1.3381583486619217
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.1596278311392459
          y: -0.1973049228085817
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.26805044904250896
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0204690410584965
            roll: 0.0
            pitch: 0.0
            yaw: -0.10367436701879415
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0010318838337051855
            roll: 0.0
            pitch: 0.0
            yaw: 0.1389231310363533
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.020144278166848602
            roll: 0.0
            pitch: 0.0
            yaw: -0.15786970962954422
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.004105493203804236
            roll: 0.0
            pitch: 0.0
            yaw: 0.1628895738851689
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.020001379713060194
            roll: 0.0
            pitch: 0.0
            yaw: 0.05810809223749058
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.023156673622875365
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.015002001250218673
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04786867781780463
            roll: 0.0
            pitch: 0.0
            yaw: -0.06987936416633278
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.03788854799133794
            roll: 0.0
            pitch: 0.0
            yaw: -0.9976536944017538
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04389421545135938
            roll: 0.0
            pitch: 0.0
            yaw: -0.7402289772897542
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0042976908177567025
            roll: 0.0
            pitch: 0.0
            yaw: 0.8061392410481423
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06002196619940836
            roll: 0.0
            pitch: 0.0
            yaw: -0.08763687912925444
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06014805362149632
            roll: 0.0
            pitch: 0.0
            yaw: 0.8960657524914379
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0019655658621267414
              y: 0.014098741778530037
              z: 0.042496330250709966
              roll: 0.46459072499359855
              pitch: -0.46927885584194795
              yaw: 1.3354934842633583
            roll: 0.43503338360086435
            pitch: -0.49176445274584923
            yaw: 1.3568490920537855
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
