scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.16040464119649128
          y: -0.29301505152931673
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.2115702131018734
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.004866685503905885
            roll: 0.0
            pitch: 0.0
            yaw: 0.09573329890048604
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01530169260467956
            roll: 0.0
            pitch: 0.0
            yaw: -0.012068458635002888
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0004397071772114375
            roll: 0.0
            pitch: 0.0
            yaw: -0.14658640441374318
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0020958064029997503
            roll: 0.0
            pitch: 0.0
            yaw: -0.17402673129738291
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.00972710189225907
            roll: 0.0
            pitch: 0.0
            yaw: -0.1608641875768888
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.024403059764223217
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.012947412859819186
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.035180654406803
            roll: 0.0
            pitch: 0.0
            yaw: -0.9742789429962347
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.02591835887464336
            roll: 0.0
            pitch: 0.0
            yaw: 0.7438184157563079
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0054550273197923604
            roll: 0.0
            pitch: 0.0
            yaw: 0.8263291403581734
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.02573535556883426
            roll: 0.0
            pitch: 0.0
            yaw: 0.0659833417301483
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.007206540872039785
            roll: 0.0
            pitch: 0.0
            yaw: 0.0472342751107695
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06463284119641466
            roll: 0.0
            pitch: 0.0
            yaw: -0.9456871534090452
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00036038783107767217
              y: 0.015863210147015694
              z: 0.043606004079571284
              roll: 0.41024551043209506
              pitch: -0.4578900001080547
              yaw: 1.325624158616995
            roll: 0.439925530497318
            pitch: -0.480193031902124
            yaw: 1.3076191609819448
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.25219343416753964
          y: -0.16872774692048137
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.008059504632547343
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01478099966406898
            roll: 0.0
            pitch: 0.0
            yaw: -0.14560502842641893
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.02133438020741455
            roll: 0.0
            pitch: 0.0
            yaw: -0.05255800033894811
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.003638434574394219
            roll: 0.0
            pitch: 0.0
            yaw: 0.12309692731061062
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0007295999234948232
            roll: 0.0
            pitch: 0.0
            yaw: 0.02639060889115677
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01558074157344852
            roll: 0.0
            pitch: 0.0
            yaw: -0.09536143870673168
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04702966553454338
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 6.187184929560413e-05
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.019925105341050756
            roll: 0.0
            pitch: 0.0
            yaw: 1.0244812121622313
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0188916886829701
            roll: 0.0
            pitch: 0.0
            yaw: 0.5094195207838257
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.09546854533105782
            roll: 0.0
            pitch: 0.0
            yaw: 0.610197803972673
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.00033876627609821797
            roll: 0.0
            pitch: 0.0
            yaw: -0.2280322677315343
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.035070036150304795
            roll: 0.0
            pitch: 0.0
            yaw: -0.49020724388815795
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.003523523686214669
            roll: 0.0
            pitch: 0.0
            yaw: 0.45116552249697683
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0013106247158015752
              y: 0.015846895364477614
              z: 0.04223806013094896
              roll: 0.4647934027002732
              pitch: -0.4884430359639637
              yaw: 1.3310995402892352
            roll: 0.4386069114869561
            pitch: -0.4823623227730461
            yaw: 1.3688775285034434
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2928106897362466
          y: -0.2960508477597862
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.09611912646706011
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.00529493264458112
            roll: 0.0
            pitch: 0.0
            yaw: -0.08358880066788807
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.016847452537682096
            roll: 0.0
            pitch: 0.0
            yaw: -0.03403861976324682
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.005065794361033247
            roll: 0.0
            pitch: 0.0
            yaw: -0.04033826125065887
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.023050479088841218
            roll: 0.0
            pitch: 0.0
            yaw: -0.04136077423626397
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0036576719807024267
            roll: 0.0
            pitch: 0.0
            yaw: -0.16639241290008436
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04731088935068488
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05108935591732468
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.061861127960385134
            roll: 0.0
            pitch: 0.0
            yaw: -0.7141291382707255
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.009646683077440515
            roll: 0.0
            pitch: 0.0
            yaw: -0.1502943457792979
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0626165377974339
            roll: 0.0
            pitch: 0.0
            yaw: -0.7285247228555036
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06064092466190409
            roll: 0.0
            pitch: 0.0
            yaw: -0.9360059059875069
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06469551259916251
            roll: 0.0
            pitch: 0.0
            yaw: 0.7871329753695753
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.026731305881012773
            roll: 0.0
            pitch: 0.0
            yaw: 0.1563797054136371
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0011669988361326447
              y: 0.016224799134426336
              z: 0.0424883594322435
              roll: 0.43877860589902995
              pitch: -0.5066616312322818
              yaw: 1.3282103713701376
            roll: 0.4751149494574633
            pitch: -0.491805586619588
            yaw: 1.3004216794976475
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
