scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.12494753898394878
          y: -0.1745427327764027
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.10361077657861761
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0015643321156079068
            roll: 0.0
            pitch: 0.0
            yaw: 0.08964849393894986
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.020391792634380245
            roll: 0.0
            pitch: 0.0
            yaw: 0.09278777636335933
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01096558513868122
            roll: 0.0
            pitch: 0.0
            yaw: -0.14349839213293009
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012847806185244077
            roll: 0.0
            pitch: 0.0
            yaw: -0.001312578091677119
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.020260983617787547
            roll: 0.0
            pitch: 0.0
            yaw: 0.14044674989474448
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.028623327436636536
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0022207190586973555
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0108406708422632
            roll: 0.0
            pitch: 0.0
            yaw: 0.5185199201776582
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.048239560435392216
            roll: 0.0
            pitch: 0.0
            yaw: -0.31498012327411695
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03894448404168125
            roll: 0.0
            pitch: 0.0
            yaw: 0.276287040068925
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.040172861550155294
            roll: 0.0
            pitch: 0.0
            yaw: 0.5727821635771211
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03869798895825677
            roll: 0.0
            pitch: 0.0
            yaw: -0.5334222400268455
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.011764990056690364
            roll: 0.0
            pitch: 0.0
            yaw: 0.44528648878058497
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -5.625833526415845e-05
              y: 0.015914764150773426
              z: 0.04317888805516019
              roll: 0.4361125790298267
              pitch: -0.5073260108536672
              yaw: 1.3238448588439307
            roll: 0.4443072620381704
            pitch: -0.49167595118630886
            yaw: 1.3596636355854674
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.16819313810439862
          y: -0.28484598080058626
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.019332483853113924
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.014362636904548871
            roll: 0.0
            pitch: 0.0
            yaw: 0.09820030434040039
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01582515310771441
            roll: 0.0
            pitch: 0.0
            yaw: -0.15924259470172192
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.019736154117633506
            roll: 0.0
            pitch: 0.0
            yaw: -0.12706963298587032
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.012826560573713633
            roll: 0.0
            pitch: 0.0
            yaw: 0.0517122845157546
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0049090630697455236
            roll: 0.0
            pitch: 0.0
            yaw: -0.03887626812957026
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05621564487470011
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.048508254377033
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.012910913081017439
            roll: 0.0
            pitch: 0.0
            yaw: -0.15515264938339524
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08621135922294094
            roll: 0.0
            pitch: 0.0
            yaw: 0.2201860013150747
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09266366805706161
            roll: 0.0
            pitch: 0.0
            yaw: -0.5772531895983851
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0056939255469207195
            roll: 0.0
            pitch: 0.0
            yaw: 0.03942970681317148
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.09623229106876063
            roll: 0.0
            pitch: 0.0
            yaw: 0.7621931384058624
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06089330247732683
            roll: 0.0
            pitch: 0.0
            yaw: 0.43322575022365406
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0015760283760002792
              y: 0.01370222765398919
              z: 0.04228745842821435
              roll: 0.44855799178786804
              pitch: -0.48056338840567386
              yaw: 1.350160754812011
            roll: 0.4246103876172327
            pitch: -0.4833125240632684
            yaw: 1.3453017358713493
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.25614446770073396
          y: -0.2041453334249019
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.24694406234571553
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.02012952181847047
            roll: 0.0
            pitch: 0.0
            yaw: 0.16000757196726972
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0074524464681096254
            roll: 0.0
            pitch: 0.0
            yaw: -0.0782110681071439
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.022606542552850148
            roll: 0.0
            pitch: 0.0
            yaw: -0.02481819810785532
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.002423923109740902
            roll: 0.0
            pitch: 0.0
            yaw: 0.11577483486366963
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01288788668412626
            roll: 0.0
            pitch: 0.0
            yaw: 0.03696953600916625
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03669067288452389
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.021769804655735032
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07325254658046379
            roll: 0.0
            pitch: 0.0
            yaw: -0.874645234513282
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08654819513508824
            roll: 0.0
            pitch: 0.0
            yaw: 0.9967914998725631
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08342783701095635
            roll: 0.0
            pitch: 0.0
            yaw: 0.056381362524933865
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05890446367264823
            roll: 0.0
            pitch: 0.0
            yaw: 0.35371750521648027
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06167502259763133
            roll: 0.0
            pitch: 0.0
            yaw: 0.023964867737211515
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.017434956840890622
            roll: 0.0
            pitch: 0.0
            yaw: -0.009945217497917103
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0005196596475268431
              y: 0.013763919134354038
              z: 0.04282566825010716
              roll: 0.46540975975210175
              pitch: -0.4909925485424833
              yaw: 1.3590722105818056
            roll: 0.46077476367596654
            pitch: -0.46399209745432735
            yaw: 1.3349129814155067
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
