scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2392988552092438
          y: -0.2890908778544777
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3364042234059553
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01643666879668872
            roll: 0.0
            pitch: 0.0
            yaw: -0.07941689120835199
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.015224852956539095
            roll: 0.0
            pitch: 0.0
            yaw: -0.04770630748441465
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.010291460070222143
            roll: 0.0
            pitch: 0.0
            yaw: 0.008855567100730932
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.002342937045716982
            roll: 0.0
            pitch: 0.0
            yaw: 0.1143692889209944
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.019092749431141823
            roll: 0.0
            pitch: 0.0
            yaw: 0.12816884553407532
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0408230632492277
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0472361783068878
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.039461545524485414
            roll: 0.0
            pitch: 0.0
            yaw: -0.0418689203785807
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.008431841579326124
            roll: 0.0
            pitch: 0.0
            yaw: -0.314175410417567
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0037992578737393867
            roll: 0.0
            pitch: 0.0
            yaw: -0.3658783455362866
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09517284816312105
            roll: 0.0
            pitch: 0.0
            yaw: -0.7862850140413584
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.054836074521130346
            roll: 0.0
            pitch: 0.0
            yaw: -0.9381161715658574
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.019723081543210064
            roll: 0.0
            pitch: 0.0
            yaw: -0.6159799384942641
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0014966794101819439
              y: 0.013919105681532472
              z: 0.042053931716247696
              roll: 0.40349740156328157
              pitch: -0.5138724851322836
              yaw: 1.3648900320722566
            roll: 0.441201211249321
            pitch: -0.5179636230790956
            yaw: 1.2922023339058208
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2918262809041364
          y: -0.12047260814253077
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.15126693945045788
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.007789118712247658
            roll: 0.0
            pitch: 0.0
            yaw: 0.015341901351621584
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.020815441214435113
            roll: 0.0
            pitch: 0.0
            yaw: -0.1354608189338664
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.011545341306243143
            roll: 0.0
            pitch: 0.0
            yaw: -0.16460335497094133
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.020549188437244736
            roll: 0.0
            pitch: 0.0
            yaw: -0.08379606586280658
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0021147878282280104
            roll: 0.0
            pitch: 0.0
            yaw: 0.14541522199175522
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.029293329369261566
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04514486346290454
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.013304515690673105
            roll: 0.0
            pitch: 0.0
            yaw: 0.10487650683665062
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07507318961432222
            roll: 0.0
            pitch: 0.0
            yaw: 0.655901915608464
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06897158763651676
            roll: 0.0
            pitch: 0.0
            yaw: -0.0337224365444746
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.04505847692557126
            roll: 0.0
            pitch: 0.0
            yaw: 0.5482432811905973
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.09611745475816452
            roll: 0.0
            pitch: 0.0
            yaw: 0.8122358551808102
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08974417760085306
            roll: 0.0
            pitch: 0.0
            yaw: 0.07572984918085912
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0007415835216208191
              y: 0.016238528765245785
              z: 0.04432648731096331
              roll: 0.4695004750582955
              pitch: -0.5154545540099853
              yaw: 1.3231503977667678
            roll: 0.44113094990838386
            pitch: -0.49372358344533873
            yaw: 1.369061956367818
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.16931397247877883
          y: -0.176161712189393
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.1863353873519742
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.014312527144210413
            roll: 0.0
            pitch: 0.0
            yaw: -0.07780479522768903
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01249063332840853
            roll: 0.0
            pitch: 0.0
            yaw: 0.15903356771638172
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.015917255430048953
            roll: 0.0
            pitch: 0.0
            yaw: -0.10044968099728253
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.02004544025570392
            roll: 0.0
            pitch: 0.0
            yaw: -0.09713646901716066
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.014819549990341956
            roll: 0.0
            pitch: 0.0
            yaw: 0.15488088289352558
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05207014186731744
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.020076585323775785
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0681115802672739
            roll: 0.0
            pitch: 0.0
            yaw: 0.0203374673145571
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.06255050132854242
            roll: 0.0
            pitch: 0.0
            yaw: -0.0021320161658580083
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07727060094917654
            roll: 0.0
            pitch: 0.0
            yaw: 0.15059878591931875
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07393124589940694
            roll: 0.0
            pitch: 0.0
            yaw: -0.743464586670854
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05974528006502486
            roll: 0.0
            pitch: 0.0
            yaw: -0.8554698543770184
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.025544959716061813
            roll: 0.0
            pitch: 0.0
            yaw: 0.4178116013651263
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0014136485506200712
              y: 0.01636418920960279
              z: 0.04272753660604111
              roll: 0.4423836711417217
              pitch: -0.4524880046128532
              yaw: 1.3665351526905205
            roll: 0.4302579469266963
            pitch: -0.5167932268274551
            yaw: 1.3179446037752334
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
