scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2512393407950493
          y: -0.2896841422714344
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.20884671278369793
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.018954708269283922
            roll: 0.0
            pitch: 0.0
            yaw: 0.07810040835743176
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01952777213999675
            roll: 0.0
            pitch: 0.0
            yaw: 0.008390682404843919
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.009568588055137064
            roll: 0.0
            pitch: 0.0
            yaw: -0.010525738059188966
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.004161179064704337
            roll: 0.0
            pitch: 0.0
            yaw: -0.15593965903857132
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.017435154019392496
            roll: 0.0
            pitch: 0.0
            yaw: -0.040818008972448555
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05402414570687343
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.015293801101706445
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.029201279802581137
            roll: 0.0
            pitch: 0.0
            yaw: -0.3930042044705331
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.052246719765189825
            roll: 0.0
            pitch: 0.0
            yaw: -0.5218117504760716
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04548058454467299
            roll: 0.0
            pitch: 0.0
            yaw: 0.643734626347578
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.026480736186136264
            roll: 0.0
            pitch: 0.0
            yaw: 0.6785386799629647
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0544298529749431
            roll: 0.0
            pitch: 0.0
            yaw: 0.4996489513103961
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07529747445071448
            roll: 0.0
            pitch: 0.0
            yaw: 0.6242498493673121
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.000860127889432663
              y: 0.013777182767556073
              z: 0.041619721772707986
              roll: 0.45950263008244563
              pitch: -0.4816170243424591
              yaw: 1.3612103499271808
            roll: 0.4258821448474493
            pitch: -0.44177048431774446
            yaw: 1.292514315323313
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.23789452103085748
          y: -0.1975810516912318
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.11804424128902757
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.021090503523486757
            roll: 0.0
            pitch: 0.0
            yaw: 0.15906815270916191
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006402165071455423
            roll: 0.0
            pitch: 0.0
            yaw: -0.08826810482594032
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.008474929766826999
            roll: 0.0
            pitch: 0.0
            yaw: -0.0338603800651589
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.00045815215360687014
            roll: 0.0
            pitch: 0.0
            yaw: -0.08440545100049651
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.017528927755192693
            roll: 0.0
            pitch: 0.0
            yaw: 0.08888237566821611
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.010282136441957065
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04667620777828521
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.027712725681768288
            roll: 0.0
            pitch: 0.0
            yaw: -0.45377860935293757
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.060638279767982944
            roll: 0.0
            pitch: 0.0
            yaw: 0.30410577298816777
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08761492463291481
            roll: 0.0
            pitch: 0.0
            yaw: -0.5197481833577543
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08109698817405796
            roll: 0.0
            pitch: 0.0
            yaw: 1.0457185846750698
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.051699518863521345
            roll: 0.0
            pitch: 0.0
            yaw: 0.8005549501974218
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03760565958011723
            roll: 0.0
            pitch: 0.0
            yaw: 0.03490705053866083
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.001264911546687687
              y: 0.014755168249279426
              z: 0.04434627696596278
              roll: 0.43376685459465514
              pitch: -0.4855153715054702
              yaw: 1.3403194388578148
            roll: 0.46415186211950804
            pitch: -0.45517636215440554
            yaw: 1.2977980970682914
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2248723256519682
          y: -0.2104532652223962
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.22482005397664206
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01819130917335039
            roll: 0.0
            pitch: 0.0
            yaw: 0.16482892237971403
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.015638266117846487
            roll: 0.0
            pitch: 0.0
            yaw: 0.029818525448732647
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.019514973931936748
            roll: 0.0
            pitch: 0.0
            yaw: 0.07234239991614605
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.00760352549060923
            roll: 0.0
            pitch: 0.0
            yaw: 0.08756331919683213
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.015512583273778576
            roll: 0.0
            pitch: 0.0
            yaw: 0.028272815025532222
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04081034329092546
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.005072680366273785
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.03635173480011458
            roll: 0.0
            pitch: 0.0
            yaw: -0.025444772241339342
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.055601809701289
            roll: 0.0
            pitch: 0.0
            yaw: 0.004161233545510568
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0922167584041497
            roll: 0.0
            pitch: 0.0
            yaw: 0.1476293483627622
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.021272293329211697
            roll: 0.0
            pitch: 0.0
            yaw: 0.5925478869297931
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.012721182527968902
            roll: 0.0
            pitch: 0.0
            yaw: -0.06883183508702218
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0322387009203447
            roll: 0.0
            pitch: 0.0
            yaw: -0.18644551575935964
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0012789280577739067
              y: 0.016780088569352564
              z: 0.04325648116035216
              roll: 0.48289895816818035
              pitch: -0.46461598930541254
              yaw: 1.3590483312853976
            roll: 0.48020010764330523
            pitch: -0.5028783604486518
            yaw: 1.36690836557726
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
