scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.10170641110985411
          y: -0.28407415480599213
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.1306296681744178
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0047728196242056535
            roll: 0.0
            pitch: 0.0
            yaw: 0.11599263641123259
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.00840311823713954
            roll: 0.0
            pitch: 0.0
            yaw: 0.11229567244658817
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.007477711321749337
            roll: 0.0
            pitch: 0.0
            yaw: -0.027243921670962984
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.00819267941650114
            roll: 0.0
            pitch: 0.0
            yaw: -0.03969822208537044
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0033929178890897242
            roll: 0.0
            pitch: 0.0
            yaw: -0.12138031912692512
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03203634986647767
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.013863648254947583
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0458325156193778
            roll: 0.0
            pitch: 0.0
            yaw: 0.674576273029813
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07984891389832136
            roll: 0.0
            pitch: 0.0
            yaw: -0.3398185634095299
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08965186908643763
            roll: 0.0
            pitch: 0.0
            yaw: 0.015718027388188505
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.07481098853326901
            roll: 0.0
            pitch: 0.0
            yaw: 0.2833580736633645
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06431794887061887
            roll: 0.0
            pitch: 0.0
            yaw: 0.9061046633833618
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03330699695223818
            roll: 0.0
            pitch: 0.0
            yaw: -0.0776220738338903
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0011516434072697628
              y: 0.013845861168125452
              z: 0.04291244638101553
              roll: 0.4617870636330548
              pitch: -0.44686383217891246
              yaw: 1.3519692352136814
            roll: 0.45862534450565284
            pitch: -0.49725568405753234
            yaw: 1.3473005963836968
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.17664821553976154
          y: -0.14726316704603598
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.28274543973242827
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.012912816529076313
            roll: 0.0
            pitch: 0.0
            yaw: -0.12437839604729366
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.016550623635135292
            roll: 0.0
            pitch: 0.0
            yaw: 0.10504028850684438
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.013089717252137444
            roll: 0.0
            pitch: 0.0
            yaw: 0.1493704652232099
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.017138909713307796
            roll: 0.0
            pitch: 0.0
            yaw: 0.14766528194048267
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01554507074290834
            roll: 0.0
            pitch: 0.0
            yaw: -0.002649449387380487
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.051128850221909536
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03966948724415456
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05835961909837926
            roll: 0.0
            pitch: 0.0
            yaw: -0.34840250744426404
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09398806685342873
            roll: 0.0
            pitch: 0.0
            yaw: -0.11150229042316173
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.048485428705575186
            roll: 0.0
            pitch: 0.0
            yaw: -0.3270498367182082
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05311646801854882
            roll: 0.0
            pitch: 0.0
            yaw: 0.3980562576204114
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.00496334963449277
            roll: 0.0
            pitch: 0.0
            yaw: 1.0209917034668858
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.004722801281199507
            roll: 0.0
            pitch: 0.0
            yaw: -0.7126179867390356
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 4.915601056120584e-05
              y: 0.015003590257985823
              z: 0.04252026889383568
              roll: 0.4585137477149612
              pitch: -0.4533622723187265
              yaw: 1.313689637206003
            roll: 0.43299466540078174
            pitch: -0.496865724559564
            yaw: 1.2986004599641305
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.21104047350229116
          y: -0.13596831889960806
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.125270115539718
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.004989508080883404
            roll: 0.0
            pitch: 0.0
            yaw: -0.021663022375360524
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.018229140649044767
            roll: 0.0
            pitch: 0.0
            yaw: -0.017419981865124334
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.006588947166001408
            roll: 0.0
            pitch: 0.0
            yaw: 0.004031918817701735
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0020791438327321422
            roll: 0.0
            pitch: 0.0
            yaw: -0.053519824041448144
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0017109147429514408
            roll: 0.0
            pitch: 0.0
            yaw: 0.13468989062714198
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05173639223592369
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.013918938979294637
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.02886091053919118
            roll: 0.0
            pitch: 0.0
            yaw: 0.5994458399222535
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.01584729721639147
            roll: 0.0
            pitch: 0.0
            yaw: -0.550295438136114
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05071316350789375
            roll: 0.0
            pitch: 0.0
            yaw: -0.643580547883656
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.055383526346869855
            roll: 0.0
            pitch: 0.0
            yaw: -0.15072072414471016
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.02229137810123266
            roll: 0.0
            pitch: 0.0
            yaw: -0.9348528913532049
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06486911768227976
            roll: 0.0
            pitch: 0.0
            yaw: -0.18502595711675318
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0010181388774315706
              y: 0.017357139814596564
              z: 0.0428839793740059
              roll: 0.42730029102090206
              pitch: -0.4953045947165981
              yaw: 1.3370938134669983
            roll: 0.4267537000201607
            pitch: -0.5196359727560634
            yaw: 1.3070404057585006
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
