scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.17854484702991866
          y: -0.12422286473143646
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.3850684449107894
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.02248242620210958
            roll: 0.0
            pitch: 0.0
            yaw: 0.1133824286335316
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.00047123716111603306
            roll: 0.0
            pitch: 0.0
            yaw: -0.0681455546018325
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0007955418359934137
            roll: 0.0
            pitch: 0.0
            yaw: -0.16947172591711754
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.018768440158633243
            roll: 0.0
            pitch: 0.0
            yaw: 0.14553572911690932
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.009127909065756314
            roll: 0.0
            pitch: 0.0
            yaw: -0.15095288741745636
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04768131068830603
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.054836320716148704
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06761899423095367
            roll: 0.0
            pitch: 0.0
            yaw: 0.303964710293227
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.020149718852200987
            roll: 0.0
            pitch: 0.0
            yaw: 0.25261577338008645
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.09437752306249306
            roll: 0.0
            pitch: 0.0
            yaw: -0.6990393065801908
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.048846344262486435
            roll: 0.0
            pitch: 0.0
            yaw: 0.3655088506012987
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.009281632499622328
            roll: 0.0
            pitch: 0.0
            yaw: 0.27853727458164523
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.062321370744665
            roll: 0.0
            pitch: 0.0
            yaw: 0.2215967023878911
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0011099053495925194
              y: 0.013649279724733945
              z: 0.04298915399669443
              roll: 0.4435929422952877
              pitch: -0.5036126596242079
              yaw: 1.2980854934634338
            roll: 0.44148702366394854
            pitch: -0.5137160729247582
            yaw: 1.2972910840407863
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.23731180909692884
          y: -0.2859561951459082
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.48327671104637504
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01805703271538237
            roll: 0.0
            pitch: 0.0
            yaw: 0.05924007320964819
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.003756503234147241
            roll: 0.0
            pitch: 0.0
            yaw: -0.13222239233061298
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.017036242334711002
            roll: 0.0
            pitch: 0.0
            yaw: 0.11735440352509913
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.009138291626751584
            roll: 0.0
            pitch: 0.0
            yaw: -0.0587016637139184
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.007116255943192823
            roll: 0.0
            pitch: 0.0
            yaw: -0.10255288937134528
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01803613431739165
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04998868597276125
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0458851938984105
            roll: 0.0
            pitch: 0.0
            yaw: 0.43988934529519685
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.024679483119317863
            roll: 0.0
            pitch: 0.0
            yaw: 0.6267247965059861
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.00976302764858332
            roll: 0.0
            pitch: 0.0
            yaw: -0.15378334155188622
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09266150958793451
            roll: 0.0
            pitch: 0.0
            yaw: -0.42360559325956704
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07002380943974601
            roll: 0.0
            pitch: 0.0
            yaw: 0.7564590373010855
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06607791592869197
            roll: 0.0
            pitch: 0.0
            yaw: -0.7018269804427362
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00011990612931748936
              y: 0.017338264036650185
              z: 0.04399986099673993
              roll: 0.4824556790106713
              pitch: -0.5179832149943253
              yaw: 1.3557648801187128
            roll: 0.40438953800516575
            pitch: -0.4903006410422748
            yaw: 1.3555472965570188
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.10225296629843579
          y: -0.10518656002561594
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.16492986959644307
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.014260153071528142
            roll: 0.0
            pitch: 0.0
            yaw: -0.059079779014958256
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.015847791811086375
            roll: 0.0
            pitch: 0.0
            yaw: -0.13306808582265864
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0014861349937750554
            roll: 0.0
            pitch: 0.0
            yaw: -0.04798880518838192
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.004611200820596569
            roll: 0.0
            pitch: 0.0
            yaw: -0.12496385433295043
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.021396813673579373
            roll: 0.0
            pitch: 0.0
            yaw: -0.0075481032907497025
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.025138630351749652
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04276688349001438
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0702501829273974
            roll: 0.0
            pitch: 0.0
            yaw: 0.4072950650467386
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04416598606543021
            roll: 0.0
            pitch: 0.0
            yaw: -0.7625566655894578
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.013113406999957375
            roll: 0.0
            pitch: 0.0
            yaw: 0.7204714209039151
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08411651458614285
            roll: 0.0
            pitch: 0.0
            yaw: 0.2438856038452888
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.09015227708807513
            roll: 0.0
            pitch: 0.0
            yaw: -0.8648850346719684
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.007708312057866679
            roll: 0.0
            pitch: 0.0
            yaw: -0.09973012139937465
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0019261279224070643
              y: 0.013453377583625916
              z: 0.0432362736927365
              roll: 0.47557109091772143
              pitch: -0.5221916332714597
              yaw: 1.3038025678990093
            roll: 0.4218351317315989
            pitch: -0.5053609593504403
            yaw: 1.294656612804475
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
