scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.14368551568044444
          y: -0.2603508927799117
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.19712559785164296
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.007781328309610851
            roll: 0.0
            pitch: 0.0
            yaw: 0.14581017704972404
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.021274167370548255
            roll: 0.0
            pitch: 0.0
            yaw: -0.07213350840052973
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.010961914670522953
            roll: 0.0
            pitch: 0.0
            yaw: -0.1392928725619675
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01232225507022057
            roll: 0.0
            pitch: 0.0
            yaw: -0.02238289255710388
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.00987932263085655
            roll: 0.0
            pitch: 0.0
            yaw: -0.07847832736332801
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02053702838232703
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.027054135335384692
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.041322701691986236
            roll: 0.0
            pitch: 0.0
            yaw: 0.4373862305865377
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04737344291577673
            roll: 0.0
            pitch: 0.0
            yaw: -0.21702578179970666
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0761555564327579
            roll: 0.0
            pitch: 0.0
            yaw: -0.6532963766808054
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05203521208558998
            roll: 0.0
            pitch: 0.0
            yaw: 0.2564493271841286
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05635492572731408
            roll: 0.0
            pitch: 0.0
            yaw: 0.056123370351611745
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09563575013194474
            roll: 0.0
            pitch: 0.0
            yaw: 0.44182054275280414
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0005756290629899898
              y: 0.01661833343873612
              z: 0.0432086227108584
              roll: 0.4625326244140543
              pitch: -0.4921913669244869
              yaw: 1.3615812604225013
            roll: 0.4302073684725023
            pitch: -0.4851778876933711
            yaw: 1.3421763143588
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.21570996615257038
          y: -0.25343515541258355
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.25774782926382056
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.008715627947952323
            roll: 0.0
            pitch: 0.0
            yaw: 0.02795046653406913
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.001786530411101571
            roll: 0.0
            pitch: 0.0
            yaw: -0.08523101501966826
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.017323312868771375
            roll: 0.0
            pitch: 0.0
            yaw: 0.07477357085163208
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0014147378901789125
            roll: 0.0
            pitch: 0.0
            yaw: -0.16094113237553997
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0034760416841809957
            roll: 0.0
            pitch: 0.0
            yaw: -0.17076581505242022
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04615310990424063
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.027129741523194167
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.042653801496852384
            roll: 0.0
            pitch: 0.0
            yaw: 0.905910422392908
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.015917313601155322
            roll: 0.0
            pitch: 0.0
            yaw: 0.4823150921740995
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.027528881000328048
            roll: 0.0
            pitch: 0.0
            yaw: 0.8084617157793637
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.008660913545444793
            roll: 0.0
            pitch: 0.0
            yaw: 0.40039657123619365
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.005897695643092962
            roll: 0.0
            pitch: 0.0
            yaw: -0.8205605792464914
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08333243385095172
            roll: 0.0
            pitch: 0.0
            yaw: 0.35309470708574664
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0014055758369057045
              y: 0.014045448361742709
              z: 0.040696148500237436
              roll: 0.43742420016684097
              pitch: -0.47602037794901547
              yaw: 1.3184607745406676
            roll: 0.4818532831334401
            pitch: -0.5129340956838023
            yaw: 1.3210501209906307
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.28387045826613955
          y: -0.2696858841838963
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3686763389326979
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.014878354678489487
            roll: 0.0
            pitch: 0.0
            yaw: -0.04177265257901827
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0131646823553951
            roll: 0.0
            pitch: 0.0
            yaw: 0.11079145416505998
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.004552172895952569
            roll: 0.0
            pitch: 0.0
            yaw: 0.02895186409134934
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.00814916737445728
            roll: 0.0
            pitch: 0.0
            yaw: -0.008654624994057086
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0066603468047188585
            roll: 0.0
            pitch: 0.0
            yaw: 0.09949116392088841
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05711389713237801
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.055067182027663406
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07886853009814188
            roll: 0.0
            pitch: 0.0
            yaw: -0.36079600370463527
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08964782562621049
            roll: 0.0
            pitch: 0.0
            yaw: 1.0197706125406538
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.016323765988097982
            roll: 0.0
            pitch: 0.0
            yaw: 0.6862088349475011
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.02046008428280799
            roll: 0.0
            pitch: 0.0
            yaw: -0.7732295226311439
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07808273145921847
            roll: 0.0
            pitch: 0.0
            yaw: 0.5128852392409613
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0894321808456236
            roll: 0.0
            pitch: 0.0
            yaw: 0.14061245044718684
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0007891429168480762
              y: 0.014297915847032473
              z: 0.04134506748715043
              roll: 0.42960457730842644
              pitch: -0.46765702391039426
              yaw: 1.2999015948219055
            roll: 0.4749869688510374
            pitch: -0.5048169312543216
            yaw: 1.3102662833819123
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
