scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1652647515175401
          y: -0.19015698514906015
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.19967317785647276
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0036286926342020444
            roll: 0.0
            pitch: 0.0
            yaw: 0.05892385773236242
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0047284224775979815
            roll: 0.0
            pitch: 0.0
            yaw: 0.00670232829676784
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.015500626263113495
            roll: 0.0
            pitch: 0.0
            yaw: -0.02764744785892584
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.018175630016452924
            roll: 0.0
            pitch: 0.0
            yaw: 0.13076656860338226
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.002691107060596283
            roll: 0.0
            pitch: 0.0
            yaw: -0.02614089246987672
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03823795627577104
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0004620822424588819
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0820538386369955
            roll: 0.0
            pitch: 0.0
            yaw: -0.9731291550131433
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05979579728027176
            roll: 0.0
            pitch: 0.0
            yaw: 1.0364388154832211
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0764092596991221
            roll: 0.0
            pitch: 0.0
            yaw: 0.8204090432033466
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.002107391392058927
            roll: 0.0
            pitch: 0.0
            yaw: 0.78036601766556
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.022243716154711823
            roll: 0.0
            pitch: 0.0
            yaw: -0.8620544404020711
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06693311893927648
            roll: 0.0
            pitch: 0.0
            yaw: 0.4051653694053039
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0010282795713525811
              y: 0.01612241394803531
              z: 0.04184641832714578
              roll: 0.4246457442273993
              pitch: -0.45862589443941226
              yaw: 1.3678823256233015
            roll: 0.4043871324624878
            pitch: -0.5073762654640115
            yaw: 1.3544085012241498
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.27051800239931356
          y: -0.13710544200478197
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.2586453328514373
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.018936541636153815
            roll: 0.0
            pitch: 0.0
            yaw: 0.03939896818218877
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.014888999028889856
            roll: 0.0
            pitch: 0.0
            yaw: -0.020781713478620317
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.004024291624972982
            roll: 0.0
            pitch: 0.0
            yaw: 0.10699639368995784
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.011837596910751827
            roll: 0.0
            pitch: 0.0
            yaw: -0.09556680740715451
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.005248807125543018
            roll: 0.0
            pitch: 0.0
            yaw: -0.14226435005820878
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.01563643361659285
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0396830908815988
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.01243423288706029
            roll: 0.0
            pitch: 0.0
            yaw: -0.6170537438873591
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08129981013620437
            roll: 0.0
            pitch: 0.0
            yaw: 0.9788501358102824
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.013130826932374731
            roll: 0.0
            pitch: 0.0
            yaw: 0.20889462625722954
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03453507264317934
            roll: 0.0
            pitch: 0.0
            yaw: 0.09013125328584648
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08147844478242551
            roll: 0.0
            pitch: 0.0
            yaw: -0.030209146499942108
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05513241879150591
            roll: 0.0
            pitch: 0.0
            yaw: -0.7018144556640251
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.001196175447896342
              y: 0.016414496509596994
              z: 0.04277833285833401
              roll: 0.4530807307373803
              pitch: -0.4914850181655267
              yaw: 1.3089789215489034
            roll: 0.43344362086417454
            pitch: -0.45223029288437777
            yaw: 1.305270867515514
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.22935817205448042
          y: -0.10493507613787817
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.432848332532771
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.02207369200920329
            roll: 0.0
            pitch: 0.0
            yaw: -0.1531033018953641
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01572775496779749
            roll: 0.0
            pitch: 0.0
            yaw: -0.09099659087282
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.010884047974016431
            roll: 0.0
            pitch: 0.0
            yaw: 0.09247254353164835
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012248084950235176
            roll: 0.0
            pitch: 0.0
            yaw: -0.038480186369242664
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0076484298561641465
            roll: 0.0
            pitch: 0.0
            yaw: 0.040307189918853764
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04679352288631983
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.019656294377847147
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07064746613339948
            roll: 0.0
            pitch: 0.0
            yaw: -0.3937624812178723
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.023077739323217675
            roll: 0.0
            pitch: 0.0
            yaw: -0.9484414274724882
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09483294811296364
            roll: 0.0
            pitch: 0.0
            yaw: 0.6698911567133952
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.06604427410400768
            roll: 0.0
            pitch: 0.0
            yaw: -0.11150774169403344
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.057157598367453835
            roll: 0.0
            pitch: 0.0
            yaw: -0.9703520549022866
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.019857907270325756
            roll: 0.0
            pitch: 0.0
            yaw: 0.35753758751503395
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 5.78036276363764e-06
              y: 0.013420059350418446
              z: 0.041876725578649715
              roll: 0.45878605933305244
              pitch: -0.49392298119660083
              yaw: 1.302823265183955
            roll: 0.46287082016186853
            pitch: -0.45986375071365776
            yaw: 1.2976340335525574
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
