scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.17269684125434306
          y: -0.11755670183064079
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.45963373033964416
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0218967081753565
            roll: 0.0
            pitch: 0.0
            yaw: 0.061456980973306236
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.020359522498006176
            roll: 0.0
            pitch: 0.0
            yaw: -0.16037709822797633
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.007934830775290145
            roll: 0.0
            pitch: 0.0
            yaw: -0.10267787029355756
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02160032420278113
            roll: 0.0
            pitch: 0.0
            yaw: -0.012719098277877927
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.016645168571397924
            roll: 0.0
            pitch: 0.0
            yaw: 0.13771349551127554
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.003274644499971238
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.059196922930806646
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.09529855280203461
            roll: 0.0
            pitch: 0.0
            yaw: 0.7732002409651684
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0004638964135581375
            roll: 0.0
            pitch: 0.0
            yaw: -0.954789864156595
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0798280133883146
            roll: 0.0
            pitch: 0.0
            yaw: -0.6369521060126165
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07319508799186006
            roll: 0.0
            pitch: 0.0
            yaw: -0.8069302728591512
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.04465347147794309
            roll: 0.0
            pitch: 0.0
            yaw: 0.8096957834914622
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09316373107081458
            roll: 0.0
            pitch: 0.0
            yaw: 0.8463279494057896
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0014103445692560453
              y: 0.014711415822047548
              z: 0.04236590845582298
              roll: 0.41061375467673766
              pitch: -0.46579122987325616
              yaw: 1.2970475414909015
            roll: 0.4635608438518666
            pitch: -0.5166042290191143
            yaw: 1.3544039038471065
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1412974121578966
          y: -0.24390870115971997
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.2418393956229331
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.00763794716207726
            roll: 0.0
            pitch: 0.0
            yaw: -0.05261468383597481
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.019566547287343194
            roll: 0.0
            pitch: 0.0
            yaw: 0.04536341424475537
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01784743713719983
            roll: 0.0
            pitch: 0.0
            yaw: -0.0346726759566989
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.014069372130887204
            roll: 0.0
            pitch: 0.0
            yaw: 0.13013230877949555
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0053742332835860045
            roll: 0.0
            pitch: 0.0
            yaw: -0.0410253349822467
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.025475405601591852
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05325734709398486
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.009572585318063431
            roll: 0.0
            pitch: 0.0
            yaw: 0.4070447992684456
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.072469959150997
            roll: 0.0
            pitch: 0.0
            yaw: 0.9929241354921581
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0576945581007483
            roll: 0.0
            pitch: 0.0
            yaw: -0.9016207512267372
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.09095215640514724
            roll: 0.0
            pitch: 0.0
            yaw: 0.8329549139335091
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.028057501542310223
            roll: 0.0
            pitch: 0.0
            yaw: -0.09494655667920537
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.004543811582050611
            roll: 0.0
            pitch: 0.0
            yaw: -0.795330444205492
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001006294534262471
              y: 0.015791241353769407
              z: 0.04444134131364175
              roll: 0.43317445352848377
              pitch: -0.46386227599318636
              yaw: 1.3217106063232722
            roll: 0.4337316950439232
            pitch: -0.49994287442296725
            yaw: 1.332389972255623
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.22985164374947586
          y: -0.2826894261071428
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.38848997847892264
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.012900416583611156
            roll: 0.0
            pitch: 0.0
            yaw: 0.1294914533767561
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.013386134978822463
            roll: 0.0
            pitch: 0.0
            yaw: -0.09108441849148066
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.007842905597018229
            roll: 0.0
            pitch: 0.0
            yaw: 0.0739995170406221
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.017114078688757233
            roll: 0.0
            pitch: 0.0
            yaw: -0.15772510364145279
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02044945540364327
            roll: 0.0
            pitch: 0.0
            yaw: -0.1180223670530628
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04597134578868224
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.021350034654288114
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.017197589080529527
            roll: 0.0
            pitch: 0.0
            yaw: -0.7386964845383617
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0428874329259022
            roll: 0.0
            pitch: 0.0
            yaw: -0.15306880218867547
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07782207010552289
            roll: 0.0
            pitch: 0.0
            yaw: 0.8855048021019052
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09588381086744094
            roll: 0.0
            pitch: 0.0
            yaw: 0.7561449824464248
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05292002975497773
            roll: 0.0
            pitch: 0.0
            yaw: -1.0353777913453992
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.039602645486937586
            roll: 0.0
            pitch: 0.0
            yaw: 0.22597258936588172
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0008533055686170184
              y: 0.01632306291895888
              z: 0.042090682753346306
              roll: 0.42729404506514795
              pitch: -0.5038382791186147
              yaw: 1.3066582820508048
            roll: 0.43220962746847646
            pitch: -0.4424442874474926
            yaw: 1.3502002753563105
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
