scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.16908913405501613
          y: -0.28549105026741695
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.06388351334779652
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01831443146583094
            roll: 0.0
            pitch: 0.0
            yaw: -0.13653513744643095
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.009870328599467612
            roll: 0.0
            pitch: 0.0
            yaw: 0.06496288924589672
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.02044496063153881
            roll: 0.0
            pitch: 0.0
            yaw: -0.04829006376646344
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01689659490269583
            roll: 0.0
            pitch: 0.0
            yaw: -0.027106298670738715
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.015129693513219106
            roll: 0.0
            pitch: 0.0
            yaw: -0.02245257336541648
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.01818401892810692
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.027941698431739423
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.056910754660236144
            roll: 0.0
            pitch: 0.0
            yaw: 0.8387567752721254
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.06236987540973428
            roll: 0.0
            pitch: 0.0
            yaw: -0.8216859195312384
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07693226596118447
            roll: 0.0
            pitch: 0.0
            yaw: -0.2744517624744637
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07855585729127684
            roll: 0.0
            pitch: 0.0
            yaw: -0.79995460709849
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0006156806460428099
            roll: 0.0
            pitch: 0.0
            yaw: 0.0014300640054567548
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.011597474682995046
            roll: 0.0
            pitch: 0.0
            yaw: -0.09994618121204801
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0011684057065435107
              y: 0.01677625006848036
              z: 0.04181349728169116
              roll: 0.48137962376273263
              pitch: -0.48077235811581004
              yaw: 1.3491537332937273
            roll: 0.42922975156777754
            pitch: -0.5158948794513979
            yaw: 1.3488511849860907
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1215887810225626
          y: -0.27353601942551586
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.17862704226280257
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0013946308846805242
            roll: 0.0
            pitch: 0.0
            yaw: -0.1519762272941966
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.010896180924094208
            roll: 0.0
            pitch: 0.0
            yaw: 0.15505099058649946
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0017232013713008483
            roll: 0.0
            pitch: 0.0
            yaw: 0.022043911275924227
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.007778338702862748
            roll: 0.0
            pitch: 0.0
            yaw: -0.12520547947020425
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.003347668928425855
            roll: 0.0
            pitch: 0.0
            yaw: 0.006953844519981406
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0455625546571431
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0013042242309426674
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.02717542338086522
            roll: 0.0
            pitch: 0.0
            yaw: -0.09202569321778609
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08626313201223501
            roll: 0.0
            pitch: 0.0
            yaw: 0.037473901381737784
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0596699447433024
            roll: 0.0
            pitch: 0.0
            yaw: 0.599613540003985
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04564487952481913
            roll: 0.0
            pitch: 0.0
            yaw: -0.7315128607919041
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.02837498995492717
            roll: 0.0
            pitch: 0.0
            yaw: -1.0238805519518923
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.01027852652020425
            roll: 0.0
            pitch: 0.0
            yaw: 0.14125640046922272
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0014476089098963431
              y: 0.014897973360493776
              z: 0.04407157066481386
              roll: 0.40918861258139927
              pitch: -0.4664450502503422
              yaw: 1.337295867986534
            roll: 0.4401884192014931
            pitch: -0.45921714058460594
            yaw: 1.3471025216457606
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.1268938818614858
          y: -0.21837981263516132
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.28533175428522284
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.021418238410238023
            roll: 0.0
            pitch: 0.0
            yaw: 0.12092252676502646
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006816835661392585
            roll: 0.0
            pitch: 0.0
            yaw: -0.05585611289158965
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0025415160777155915
            roll: 0.0
            pitch: 0.0
            yaw: -0.004490062673150025
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.019819306969295694
            roll: 0.0
            pitch: 0.0
            yaw: -0.06368850613772982
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0165786362676729
            roll: 0.0
            pitch: 0.0
            yaw: 0.062225147317124085
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0326059581367877
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04858881288529092
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08460658332372137
            roll: 0.0
            pitch: 0.0
            yaw: -0.6343634745979537
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08091660243531759
            roll: 0.0
            pitch: 0.0
            yaw: 0.3998109414314044
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0502046184641784
            roll: 0.0
            pitch: 0.0
            yaw: -1.0182611868952969
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.005873906464730336
            roll: 0.0
            pitch: 0.0
            yaw: -0.35620743067148253
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.025852989683236807
            roll: 0.0
            pitch: 0.0
            yaw: 0.7436813776819522
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08468624220560646
            roll: 0.0
            pitch: 0.0
            yaw: 0.45492800983042225
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0013023527145975535
              y: 0.014372177124776448
              z: 0.042515817178932165
              roll: 0.47347605063827286
              pitch: -0.4647695682953698
              yaw: 1.357071505330726
            roll: 0.44289976371726886
            pitch: -0.4585851277069639
            yaw: 1.3663130496540146
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
