scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1923017714384332
          y: -0.26762665088121423
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.37677007505041515
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015522001194589258
            roll: 0.0
            pitch: 0.0
            yaw: 0.018497637255261268
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.004261046185103274
            roll: 0.0
            pitch: 0.0
            yaw: 0.05859213863277837
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.022712626578653305
            roll: 0.0
            pitch: 0.0
            yaw: 0.1328916402402014
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.007201914900342483
            roll: 0.0
            pitch: 0.0
            yaw: 0.03324342950311496
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.015609951208698597
            roll: 0.0
            pitch: 0.0
            yaw: 0.14457004747111946
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.019077300048377405
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.010884845524225396
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.05474896347673924
            roll: 0.0
            pitch: 0.0
            yaw: -0.270844936773873
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.06925870526824861
            roll: 0.0
            pitch: 0.0
            yaw: -0.44834021142558333
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.028655144591042195
            roll: 0.0
            pitch: 0.0
            yaw: 1.0389183719828947
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.020321139560640203
            roll: 0.0
            pitch: 0.0
            yaw: 0.16082370314249128
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0015804384498431245
            roll: 0.0
            pitch: 0.0
            yaw: 0.695837814620957
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04300107232557948
            roll: 0.0
            pitch: 0.0
            yaw: -0.5874773297332704
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0011522946278742638
              y: 0.016732589153888724
              z: 0.04082450316768013
              roll: 0.41529262109797005
              pitch: -0.49661088731632197
              yaw: 1.3561418770433509
            roll: 0.4828061330825924
            pitch: -0.4769463510645893
            yaw: 1.3284858182016321
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1233969737225113
          y: -0.23344434455077828
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.21152502496051628
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015012231481784186
            roll: 0.0
            pitch: 0.0
            yaw: -0.13442081550341473
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006356405936006237
            roll: 0.0
            pitch: 0.0
            yaw: 0.11963219946573356
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.012016434482819941
            roll: 0.0
            pitch: 0.0
            yaw: 0.06078007193596807
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.007583730060938392
            roll: 0.0
            pitch: 0.0
            yaw: 0.13107648450766002
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.00425314204605411
            roll: 0.0
            pitch: 0.0
            yaw: -0.15998738882415334
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.005104490683946042
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04161595883293137
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0070955004551696566
            roll: 0.0
            pitch: 0.0
            yaw: 0.7336072301793484
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08250715284723617
            roll: 0.0
            pitch: 0.0
            yaw: -0.1374138721812943
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07964651293448863
            roll: 0.0
            pitch: 0.0
            yaw: 0.13677158265879052
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.002646106285084604
            roll: 0.0
            pitch: 0.0
            yaw: 0.23196831275748453
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.009013986361740098
            roll: 0.0
            pitch: 0.0
            yaw: -0.48291396652272955
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04012595848854515
            roll: 0.0
            pitch: 0.0
            yaw: 0.02689585175966558
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0006576974510738298
              y: 0.014653010886280522
              z: 0.040824224239093536
              roll: 0.43824834668649093
              pitch: -0.5117943450638063
              yaw: 1.3041168268142986
            roll: 0.4696245883245249
            pitch: -0.47717913256597694
            yaw: 1.3697059069632818
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.13303442330175955
          y: -0.1798325952947634
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.40397881729411234
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.008171697228254197
            roll: 0.0
            pitch: 0.0
            yaw: -0.03086535724273723
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007965733089259432
            roll: 0.0
            pitch: 0.0
            yaw: 0.005578994206207721
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.010664097918328515
            roll: 0.0
            pitch: 0.0
            yaw: -0.013653241403971644
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.006280849547740946
            roll: 0.0
            pitch: 0.0
            yaw: -0.04174891069113626
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.019713483833863232
            roll: 0.0
            pitch: 0.0
            yaw: -0.0005594246205759823
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.016551567727338762
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0025398733727594464
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04798375059854764
            roll: 0.0
            pitch: 0.0
            yaw: -0.3292155146356436
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.06817651082881798
            roll: 0.0
            pitch: 0.0
            yaw: 0.3828772711273023
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0416533533111084
            roll: 0.0
            pitch: 0.0
            yaw: 0.7201955651748968
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.013386580045884666
            roll: 0.0
            pitch: 0.0
            yaw: 0.8021741596951624
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06294806351716714
            roll: 0.0
            pitch: 0.0
            yaw: 0.8377976524011095
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04527327191198206
            roll: 0.0
            pitch: 0.0
            yaw: 0.7161060867688835
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0017289613531950656
              y: 0.017182124753203944
              z: 0.043058560420665484
              roll: 0.410333049902296
              pitch: -0.5103041712926768
              yaw: 1.350487432295737
            roll: 0.4760995929759428
            pitch: -0.4993128494292077
            yaw: 1.3094368384385648
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
