scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2066188665463112
          y: -0.12865671113725127
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.10064600949573121
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.010525227565940876
            roll: 0.0
            pitch: 0.0
            yaw: 0.06147054436936719
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.013547943015850836
            roll: 0.0
            pitch: 0.0
            yaw: -0.15349371687115926
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.016945014738733232
            roll: 0.0
            pitch: 0.0
            yaw: 0.14918706319478048
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.010688373527715858
            roll: 0.0
            pitch: 0.0
            yaw: 0.010359915347864151
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.013066743922956266
            roll: 0.0
            pitch: 0.0
            yaw: 0.10434632988831521
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.013558708953129675
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02263767914126895
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.013421382587061381
            roll: 0.0
            pitch: 0.0
            yaw: -0.9958976203612575
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.026392680703530333
            roll: 0.0
            pitch: 0.0
            yaw: 0.7292931417270041
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09149858813940559
            roll: 0.0
            pitch: 0.0
            yaw: -0.544199830989411
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.053254299886633175
            roll: 0.0
            pitch: 0.0
            yaw: -0.5959053639488981
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0019045608398461644
            roll: 0.0
            pitch: 0.0
            yaw: 0.923749054333777
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07621227132178543
            roll: 0.0
            pitch: 0.0
            yaw: -0.734592458929848
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00018074665153566425
              y: 0.014884934279003267
              z: 0.04431540302687747
              roll: 0.4257787750966139
              pitch: -0.5216245192296828
              yaw: 1.3140115364431513
            roll: 0.4521259146097682
            pitch: -0.4956310847374549
            yaw: 1.3067637475446972
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2985016987255278
          y: -0.20829190877236287
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.1110882354036874
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.009725345373679015
            roll: 0.0
            pitch: 0.0
            yaw: -0.03276592902930631
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008477674830617078
            roll: 0.0
            pitch: 0.0
            yaw: -0.0936591303635341
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0005195822397298273
            roll: 0.0
            pitch: 0.0
            yaw: -0.0077503578436017295
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.007263975134193202
            roll: 0.0
            pitch: 0.0
            yaw: -0.006103815861102174
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.018045034923475534
            roll: 0.0
            pitch: 0.0
            yaw: 0.057539657912772296
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02033551073368732
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.003576904917705598
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.020039670147840305
            roll: 0.0
            pitch: 0.0
            yaw: 0.3598095647495363
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0014247660308548682
            roll: 0.0
            pitch: 0.0
            yaw: 1.0299579021743586
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0069332996676468445
            roll: 0.0
            pitch: 0.0
            yaw: -0.9786025913085405
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.061623934134252295
            roll: 0.0
            pitch: 0.0
            yaw: 0.14855548120866957
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07364154459210745
            roll: 0.0
            pitch: 0.0
            yaw: 0.7138095555698252
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03328573110015412
            roll: 0.0
            pitch: 0.0
            yaw: 0.8569664315707852
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0015928574409252326
              y: 0.016426247600524177
              z: 0.04300601879334746
              roll: 0.469833611475606
              pitch: -0.5059382124120804
              yaw: 1.3391977238556378
            roll: 0.4149187690714461
            pitch: -0.4816347222664991
            yaw: 1.299822864720345
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.10479737549944242
          y: -0.2449628887022154
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.39465641303021404
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.011702101890340162
            roll: 0.0
            pitch: 0.0
            yaw: -0.0013953599482608714
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01711850998413897
            roll: 0.0
            pitch: 0.0
            yaw: 0.15697237240598239
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0006311242550822924
            roll: 0.0
            pitch: 0.0
            yaw: 0.03472246709567792
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.004577838280987356
            roll: 0.0
            pitch: 0.0
            yaw: -0.0028283748349399174
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.004277272479340958
            roll: 0.0
            pitch: 0.0
            yaw: -0.07286903269789013
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.052647958963711036
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.020440622039571837
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.03676458154459461
            roll: 0.0
            pitch: 0.0
            yaw: -0.9735242619598102
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07010070670023213
            roll: 0.0
            pitch: 0.0
            yaw: -0.3567559310109688
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04512834849176064
            roll: 0.0
            pitch: 0.0
            yaw: 0.1984354769283856
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.002182276108377623
            roll: 0.0
            pitch: 0.0
            yaw: 1.000222237657394
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.011773337511859563
            roll: 0.0
            pitch: 0.0
            yaw: -1.0002094265707155
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09272115790677603
            roll: 0.0
            pitch: 0.0
            yaw: 0.6780991337579212
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0014404342708250577
              y: 0.017114533585032073
              z: 0.04243950255976704
              roll: 0.4334631122622514
              pitch: -0.482816383667156
              yaw: 1.3061181114394569
            roll: 0.4123630193379117
            pitch: -0.46596911543217645
            yaw: 1.293754092217607
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
