scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.14336521702816635
          y: -0.1019852073316761
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.013638737222065322
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01985062270146115
            roll: 0.0
            pitch: 0.0
            yaw: 0.16157518793594933
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0015089957308835923
            roll: 0.0
            pitch: 0.0
            yaw: 0.08938180056982542
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.015035713129942702
            roll: 0.0
            pitch: 0.0
            yaw: 0.038432438011325704
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01591344248160466
            roll: 0.0
            pitch: 0.0
            yaw: -0.07197138770091935
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.008753043531771275
            roll: 0.0
            pitch: 0.0
            yaw: 0.14418359722809465
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05440931559929127
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.053360749582243766
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06899363138696882
            roll: 0.0
            pitch: 0.0
            yaw: -0.5414888028684933
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.003903481222320232
            roll: 0.0
            pitch: 0.0
            yaw: 0.2926145285486812
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.005664356510026197
            roll: 0.0
            pitch: 0.0
            yaw: 0.680947271458177
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.060243099143165696
            roll: 0.0
            pitch: 0.0
            yaw: -0.8737666851486345
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0065862230147871875
            roll: 0.0
            pitch: 0.0
            yaw: 0.962853947456271
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.032959868696262606
            roll: 0.0
            pitch: 0.0
            yaw: -0.4258325124634451
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0007913603644696132
              y: 0.016464538349321944
              z: 0.04418586069113798
              roll: 0.47041770434539376
              pitch: -0.5205636124979955
              yaw: 1.3518887421462988
            roll: 0.4351721419479899
            pitch: -0.4410554159108223
            yaw: 1.3301055127680654
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2823133645854651
          y: -0.2310931514757062
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.07183991921011768
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.016776624701705725
            roll: 0.0
            pitch: 0.0
            yaw: -0.03681067122406739
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.016158622624118386
            roll: 0.0
            pitch: 0.0
            yaw: -0.1727785842241911
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.004891107345987598
            roll: 0.0
            pitch: 0.0
            yaw: 0.045451217867693405
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.002032422619745837
            roll: 0.0
            pitch: 0.0
            yaw: -0.16852768459218292
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.020678410642536935
            roll: 0.0
            pitch: 0.0
            yaw: -0.16377288442600874
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04365040974219882
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.014963105301387267
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07481136588478862
            roll: 0.0
            pitch: 0.0
            yaw: 0.16011632748145432
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09271024963039491
            roll: 0.0
            pitch: 0.0
            yaw: 0.7589147638533815
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.057287501866732114
            roll: 0.0
            pitch: 0.0
            yaw: 0.964364693960196
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04188770793390911
            roll: 0.0
            pitch: 0.0
            yaw: 0.6889396504054939
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03548422789925168
            roll: 0.0
            pitch: 0.0
            yaw: 0.41129730270833464
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03979217145086741
            roll: 0.0
            pitch: 0.0
            yaw: 0.7760610638127325
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0002864371312519421
              y: 0.015337331707352991
              z: 0.04292802027195628
              roll: 0.41498927326306095
              pitch: -0.4815999192297302
              yaw: 1.3243414595967853
            roll: 0.43875807788800847
            pitch: -0.46643648427586054
            yaw: 1.3369434786134151
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.24136751570726692
          y: -0.25431713075293993
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.28541514354501474
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.012356563257457966
            roll: 0.0
            pitch: 0.0
            yaw: -0.019869039368572622
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.004838511153254458
            roll: 0.0
            pitch: 0.0
            yaw: -0.021725185942220948
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.005711230712990196
            roll: 0.0
            pitch: 0.0
            yaw: 0.09607185439146193
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.002276426494692861
            roll: 0.0
            pitch: 0.0
            yaw: 0.007125566361195906
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.014620730203958536
            roll: 0.0
            pitch: 0.0
            yaw: 0.08309919374107844
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.055908295398364505
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.015558027106093684
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07249086261455313
            roll: 0.0
            pitch: 0.0
            yaw: -0.5184752613721636
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.018382092900582334
            roll: 0.0
            pitch: 0.0
            yaw: 0.8020380619637579
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06778981480384919
            roll: 0.0
            pitch: 0.0
            yaw: 0.9662132813719124
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07804258359888866
            roll: 0.0
            pitch: 0.0
            yaw: -0.955632598298231
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.03585617478445785
            roll: 0.0
            pitch: 0.0
            yaw: -0.6772594628997437
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07276523693524359
            roll: 0.0
            pitch: 0.0
            yaw: -0.161942883912628
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0017923708496751516
              y: 0.017192314366144736
              z: 0.04213781978450823
              roll: 0.4685216525357707
              pitch: -0.5188922064338405
              yaw: 1.2926607932917213
            roll: 0.48117641642172626
            pitch: -0.46949443462143825
            yaw: 1.3281794004348801
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
