scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.11736209740766274
          y: -0.11328619359912798
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.15095242052513402
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.017407831391382553
            roll: 0.0
            pitch: 0.0
            yaw: -0.017189510914194128
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.015265603400943245
            roll: 0.0
            pitch: 0.0
            yaw: 0.09782590701635474
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.008189374688090553
            roll: 0.0
            pitch: 0.0
            yaw: 0.14130408129672667
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0018014990654672512
            roll: 0.0
            pitch: 0.0
            yaw: 0.06397688955644015
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01594556918676319
            roll: 0.0
            pitch: 0.0
            yaw: 0.08056728890887654
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.046781115365376144
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0378015980589559
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06605872492533804
            roll: 0.0
            pitch: 0.0
            yaw: -1.006747935605281
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.004699170540330894
            roll: 0.0
            pitch: 0.0
            yaw: 0.9508085308283329
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03221052624556134
            roll: 0.0
            pitch: 0.0
            yaw: -0.7802396740329922
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.031055205656199014
            roll: 0.0
            pitch: 0.0
            yaw: 0.9443380320516432
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.005440881128524089
            roll: 0.0
            pitch: 0.0
            yaw: -0.27041810979906866
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0008719336951960449
            roll: 0.0
            pitch: 0.0
            yaw: 0.20522986823085354
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0016448276059773887
              y: 0.013405283170307382
              z: 0.04142697996479919
              roll: 0.44657433569044885
              pitch: -0.48127509342982516
              yaw: 1.3630037551587086
            roll: 0.4781749413919647
            pitch: -0.5041878793400643
            yaw: 1.3001954804912879
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.10253048625819655
          y: -0.19568766881325836
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3774753280043488
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.022617021546780643
            roll: 0.0
            pitch: 0.0
            yaw: -0.020426401490853785
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.016071773022302952
            roll: 0.0
            pitch: 0.0
            yaw: 0.13721761535339277
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0013680158475940472
            roll: 0.0
            pitch: 0.0
            yaw: -0.03333887811827854
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0016908359766164248
            roll: 0.0
            pitch: 0.0
            yaw: -0.1041154944012711
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.005993676132447327
            roll: 0.0
            pitch: 0.0
            yaw: -0.02622576793579684
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0029485034660547277
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.010635651329699562
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04320767833938865
            roll: 0.0
            pitch: 0.0
            yaw: 0.540670487867341
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0837207622508577
            roll: 0.0
            pitch: 0.0
            yaw: 0.41738441556234207
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.002475237938105654
            roll: 0.0
            pitch: 0.0
            yaw: -0.14713443264294512
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03648900905797108
            roll: 0.0
            pitch: 0.0
            yaw: 0.906922964171776
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08516257028492272
            roll: 0.0
            pitch: 0.0
            yaw: 0.5430188238949889
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.016754146532400926
            roll: 0.0
            pitch: 0.0
            yaw: -0.902143015161511
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0010821519817526765
              y: 0.014832866114713026
              z: 0.040838052775903244
              roll: 0.42695977160981624
              pitch: -0.4909088746816965
              yaw: 1.2934456775941807
            roll: 0.462997615249504
            pitch: -0.44054156138321043
            yaw: 1.3199793846547605
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.22177245683452845
          y: -0.16861469471772625
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.25707203366769893
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.018964958731325417
            roll: 0.0
            pitch: 0.0
            yaw: -0.07924126160179003
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008931727090493039
            roll: 0.0
            pitch: 0.0
            yaw: -0.12924311116576287
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.00023986625950696283
            roll: 0.0
            pitch: 0.0
            yaw: -0.03027412051622408
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.017182403479859967
            roll: 0.0
            pitch: 0.0
            yaw: -0.046156423077475556
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.006327132664885812
            roll: 0.0
            pitch: 0.0
            yaw: -0.12247558322745955
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02595119257457376
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0042598015024528715
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.02646685656739496
            roll: 0.0
            pitch: 0.0
            yaw: -0.36429897275029977
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08484245820455388
            roll: 0.0
            pitch: 0.0
            yaw: 0.16746854482544649
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02946936569728309
            roll: 0.0
            pitch: 0.0
            yaw: 0.5990153059110617
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07682352462408876
            roll: 0.0
            pitch: 0.0
            yaw: -0.47150551354436054
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.09074471409266285
            roll: 0.0
            pitch: 0.0
            yaw: -0.31410930134725445
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.008952012115186925
            roll: 0.0
            pitch: 0.0
            yaw: 1.0079684295988904
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.001184272055093432
              y: 0.01546800841437699
              z: 0.04142358002803449
              roll: 0.4448260130379722
              pitch: -0.4485079833058146
              yaw: 1.3680555178479645
            roll: 0.40675835732861076
            pitch: -0.48438640120846044
            yaw: 1.341440845230804
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
