scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.13469535440090308
          y: -0.29428411111680725
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.16356925908729558
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.009660270309217695
            roll: 0.0
            pitch: 0.0
            yaw: 0.13162572396503347
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0054951139312496705
            roll: 0.0
            pitch: 0.0
            yaw: -0.12269601033225058
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.010432001410820037
            roll: 0.0
            pitch: 0.0
            yaw: 0.028906499371741695
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.015000067641536698
            roll: 0.0
            pitch: 0.0
            yaw: -0.06719830672009344
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.008258211878468615
            roll: 0.0
            pitch: 0.0
            yaw: 0.1557090787920163
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.020649962622025987
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.00916589565524173
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.00734792096497916
            roll: 0.0
            pitch: 0.0
            yaw: -0.7430501868304951
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.03551403327471675
            roll: 0.0
            pitch: 0.0
            yaw: 0.9084381220063684
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.026696254024247912
            roll: 0.0
            pitch: 0.0
            yaw: 0.8421723905692597
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07047727092790393
            roll: 0.0
            pitch: 0.0
            yaw: -0.4137187473852255
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07494148646255164
            roll: 0.0
            pitch: 0.0
            yaw: 0.947859547660999
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08140987490273238
            roll: 0.0
            pitch: 0.0
            yaw: -0.59648114180127
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0009296506340859105
              y: 0.01637791689626344
              z: 0.04197415133812204
              roll: 0.42928848847024825
              pitch: -0.4621004417140581
              yaw: 1.3588718161331328
            roll: 0.4200335021662957
            pitch: -0.44255892358910764
            yaw: 1.3101536402077776
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1689769759408012
          y: -0.10060055484133221
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.297037977379922
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.004073906668797613
            roll: 0.0
            pitch: 0.0
            yaw: -0.0728199060907878
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.009898931179984447
            roll: 0.0
            pitch: 0.0
            yaw: 0.07490725815149485
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.019762250245743518
            roll: 0.0
            pitch: 0.0
            yaw: 0.042235049163088595
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.020902488071074046
            roll: 0.0
            pitch: 0.0
            yaw: 0.10285897608063116
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.002361925057586648
            roll: 0.0
            pitch: 0.0
            yaw: 0.0792249426367948
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.009049882415108235
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.015198601973995807
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.050123604053849906
            roll: 0.0
            pitch: 0.0
            yaw: -0.23512152554482968
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05347351680011628
            roll: 0.0
            pitch: 0.0
            yaw: 0.7553770350300133
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0599741851445189
            roll: 0.0
            pitch: 0.0
            yaw: -0.3551201381486624
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.024463599343695977
            roll: 0.0
            pitch: 0.0
            yaw: 0.8428880898356281
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0038602086907307126
            roll: 0.0
            pitch: 0.0
            yaw: -0.4111578763929302
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0006105069806625618
            roll: 0.0
            pitch: 0.0
            yaw: 0.3673825820047203
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0014457314443344729
              y: 0.014529565050721727
              z: 0.04200933869667859
              roll: 0.47690083033964265
              pitch: -0.522850942272392
              yaw: 1.3157821565916783
            roll: 0.4256351534034828
            pitch: -0.4899655899900342
            yaw: 1.3006908538961302
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2849235978445711
          y: -0.10110097761455691
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.3834035337794992
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.006286750470402131
            roll: 0.0
            pitch: 0.0
            yaw: -0.04566113661455351
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.001717097450796897
            roll: 0.0
            pitch: 0.0
            yaw: 0.16173510915568806
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.014472432625980747
            roll: 0.0
            pitch: 0.0
            yaw: -0.0994320314022869
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.00975669588967092
            roll: 0.0
            pitch: 0.0
            yaw: 0.0628158686044877
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.010614189608039212
            roll: 0.0
            pitch: 0.0
            yaw: 0.056427102805792634
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.006596115080844803
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.025946178403650322
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0075106735511556305
            roll: 0.0
            pitch: 0.0
            yaw: 0.18832928919268377
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.01223618955928095
            roll: 0.0
            pitch: 0.0
            yaw: 0.008285284333788612
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02153008087011772
            roll: 0.0
            pitch: 0.0
            yaw: -0.7210292499565162
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.02852933100937738
            roll: 0.0
            pitch: 0.0
            yaw: -0.37076680193376377
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08495774265588046
            roll: 0.0
            pitch: 0.0
            yaw: 0.5588787729794946
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.054230374971574624
            roll: 0.0
            pitch: 0.0
            yaw: 0.43880416130556377
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0010547346608531035
              y: 0.01366896630921862
              z: 0.04291416951531551
              roll: 0.4071775116816477
              pitch: -0.4476338075195761
              yaw: 1.2914042683258535
            roll: 0.46557311846700566
            pitch: -0.45674480250328336
            yaw: 1.3444719201365645
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
