scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2531268733467278
          y: -0.10045056915191544
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.17733127086906275
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.006995267252769954
            roll: 0.0
            pitch: 0.0
            yaw: -0.10039168937815045
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.02069864521239937
            roll: 0.0
            pitch: 0.0
            yaw: 0.1558220480976003
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.005800998160150169
            roll: 0.0
            pitch: 0.0
            yaw: -0.10561562300465066
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012906119153359687
            roll: 0.0
            pitch: 0.0
            yaw: 0.13870273350627005
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.010958162547119269
            roll: 0.0
            pitch: 0.0
            yaw: 0.12335678800071542
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.020299658056992936
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.051824725837802954
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05055798487641822
            roll: 0.0
            pitch: 0.0
            yaw: -0.5179990840835834
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08314441179929152
            roll: 0.0
            pitch: 0.0
            yaw: -0.7817665280489735
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08582942923247988
            roll: 0.0
            pitch: 0.0
            yaw: 0.6604967421746133
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.013178018856328078
            roll: 0.0
            pitch: 0.0
            yaw: 0.046967728362361516
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.09005776754737105
            roll: 0.0
            pitch: 0.0
            yaw: -0.9843169838986532
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.017009578799269412
            roll: 0.0
            pitch: 0.0
            yaw: -0.41745390108176905
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0001371802814564625
              y: 0.015774267610520223
              z: 0.04272139432492946
              roll: 0.45020124911144965
              pitch: -0.4539662007021368
              yaw: 1.3609648096733042
            roll: 0.41824670365726735
            pitch: -0.5120007548426313
            yaw: 1.317132611894779
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.10145154648369761
          y: -0.10216083668105455
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4969617968697958
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0028625752044252155
            roll: 0.0
            pitch: 0.0
            yaw: 0.15541437865375185
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.02018606634226592
            roll: 0.0
            pitch: 0.0
            yaw: -0.14848115184999405
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.009684115295683124
            roll: 0.0
            pitch: 0.0
            yaw: 0.10064502224536342
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.017537155979652337
            roll: 0.0
            pitch: 0.0
            yaw: -0.15494767635174578
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.014500167094144497
            roll: 0.0
            pitch: 0.0
            yaw: -0.14643290587939573
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01944251844554651
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.006926636398994365
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07281409222045226
            roll: 0.0
            pitch: 0.0
            yaw: 0.42722100794577567
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04894578809104702
            roll: 0.0
            pitch: 0.0
            yaw: -0.2872281608804792
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02676661535665474
            roll: 0.0
            pitch: 0.0
            yaw: -1.0078731169722819
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08082707576540768
            roll: 0.0
            pitch: 0.0
            yaw: 0.043508360115469324
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0065110777584188595
            roll: 0.0
            pitch: 0.0
            yaw: 0.2136325047313994
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07807433646536929
            roll: 0.0
            pitch: 0.0
            yaw: 1.0016475890104741
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0007554227760110609
              y: 0.01515036627930417
              z: 0.04163995290008903
              roll: 0.42701484422067393
              pitch: -0.5035847920114852
              yaw: 1.31024626882155
            roll: 0.46026734573167793
            pitch: -0.504351027779724
            yaw: 1.3009403430607858
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.19588252911035073
          y: -0.15296811948703656
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.14646098257452422
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.006483674746557902
            roll: 0.0
            pitch: 0.0
            yaw: -0.05557964963481454
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 1.3274772605584295e-05
            roll: 0.0
            pitch: 0.0
            yaw: 0.13960866632934826
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0045558901904456765
            roll: 0.0
            pitch: 0.0
            yaw: -0.14550559399698273
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013167911916365535
            roll: 0.0
            pitch: 0.0
            yaw: 0.12536062773164547
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.002528471169975538
            roll: 0.0
            pitch: 0.0
            yaw: 0.0760959793891734
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.005349100785450929
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05477646309409659
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.022973475686180134
            roll: 0.0
            pitch: 0.0
            yaw: 0.24903604206432073
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07954450790922707
            roll: 0.0
            pitch: 0.0
            yaw: 0.1490093517903297
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.045620915583277834
            roll: 0.0
            pitch: 0.0
            yaw: 0.7829356015487958
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.033348397871516944
            roll: 0.0
            pitch: 0.0
            yaw: -0.557708129056821
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05440917288304542
            roll: 0.0
            pitch: 0.0
            yaw: -0.6725853390791718
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08358499439729342
            roll: 0.0
            pitch: 0.0
            yaw: -0.8190944733157031
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0006259657027150216
              y: 0.014382960217429328
              z: 0.04426471994234653
              roll: 0.45163601334811654
              pitch: -0.4986877324985396
              yaw: 1.3117181868653154
            roll: 0.43146306516459576
            pitch: -0.4935547866259563
            yaw: 1.3017762843762157
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
