scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1478246630599619
          y: -0.15682145107971085
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.03178818559304364
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0049982513539175814
            roll: 0.0
            pitch: 0.0
            yaw: -0.12411095018971854
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007400496411602769
            roll: 0.0
            pitch: 0.0
            yaw: -0.16604977436687884
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.022406307866958734
            roll: 0.0
            pitch: 0.0
            yaw: 0.036764054080953484
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.011565921692894554
            roll: 0.0
            pitch: 0.0
            yaw: 0.06157810547032194
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -4.783727421156167e-05
            roll: 0.0
            pitch: 0.0
            yaw: -0.08927455264200576
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0408971175307354
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.048479346418493885
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.09444659201928142
            roll: 0.0
            pitch: 0.0
            yaw: 0.6641155629378512
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.014529770001249123
            roll: 0.0
            pitch: 0.0
            yaw: -0.05634998391427992
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06416461146576721
            roll: 0.0
            pitch: 0.0
            yaw: -0.4952090507374134
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09387040134105637
            roll: 0.0
            pitch: 0.0
            yaw: -0.3862311980409816
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06951033326422784
            roll: 0.0
            pitch: 0.0
            yaw: -0.4845187479150913
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0554453240291631
            roll: 0.0
            pitch: 0.0
            yaw: -1.0275665294289844
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0009055849634289062
              y: 0.015468057834594994
              z: 0.042619228960081114
              roll: 0.44195025966849527
              pitch: -0.505609991229961
              yaw: 1.3626819895030688
            roll: 0.44004417033182075
            pitch: -0.5059889016875714
            yaw: 1.3512193009552236
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.16896036290620767
          y: -0.21342167274128737
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.1114155780987589
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01800460535562734
            roll: 0.0
            pitch: 0.0
            yaw: -0.09605829470638622
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.012870029852719483
            roll: 0.0
            pitch: 0.0
            yaw: 0.1418626267299658
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0013391445477119734
            roll: 0.0
            pitch: 0.0
            yaw: 0.14976649571934142
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.017363724232645233
            roll: 0.0
            pitch: 0.0
            yaw: -0.06566281806776174
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.00744297669339326
            roll: 0.0
            pitch: 0.0
            yaw: 0.13923185717172648
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.030663479540634916
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.053275711348304555
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08101066415131256
            roll: 0.0
            pitch: 0.0
            yaw: 0.7451643265242551
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.055279505752220987
            roll: 0.0
            pitch: 0.0
            yaw: -0.3437939901997219
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04603465022602493
            roll: 0.0
            pitch: 0.0
            yaw: -0.03260684268661196
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03704683990060853
            roll: 0.0
            pitch: 0.0
            yaw: -1.0387255737050987
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.002662073402514023
            roll: 0.0
            pitch: 0.0
            yaw: -0.43737055561754423
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.005661000336475139
            roll: 0.0
            pitch: 0.0
            yaw: -0.9786322514850146
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0013694566591491743
              y: 0.016680473749519142
              z: 0.04400207020589608
              roll: 0.47471019920392377
              pitch: -0.4924805673482071
              yaw: 1.347130537571057
            roll: 0.43307961940274853
            pitch: -0.46454088618497447
            yaw: 1.3046169030497383
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2307775249696873
          y: -0.20642966001828986
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.38364609718605625
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.00473948631629259
            roll: 0.0
            pitch: 0.0
            yaw: -0.15358025912142168
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 3.364844199807773e-05
            roll: 0.0
            pitch: 0.0
            yaw: -0.0006588267239880929
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0012137031371224384
            roll: 0.0
            pitch: 0.0
            yaw: 0.04351845855220565
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.021553157526698723
            roll: 0.0
            pitch: 0.0
            yaw: -0.051437204058544
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.009759650706925952
            roll: 0.0
            pitch: 0.0
            yaw: 0.04732967894577855
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03979435267562828
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03569122901378961
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.06649208669255455
            roll: 0.0
            pitch: 0.0
            yaw: 0.8516644476928246
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.007738063975381945
            roll: 0.0
            pitch: 0.0
            yaw: -0.2874413606950059
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.014202265118848631
            roll: 0.0
            pitch: 0.0
            yaw: -0.9267322411161625
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03532339092948789
            roll: 0.0
            pitch: 0.0
            yaw: -0.2378940036053233
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06339007176317843
            roll: 0.0
            pitch: 0.0
            yaw: -0.04924142120814723
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.011368543720914948
            roll: 0.0
            pitch: 0.0
            yaw: -0.38265088724579466
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0016259349302832184
              y: 0.015470059228666793
              z: 0.042547387565924244
              roll: 0.472094119629674
              pitch: -0.5022209044571194
              yaw: 1.3479187839848337
            roll: 0.43632960939018517
            pitch: -0.5195399186975487
            yaw: 1.3220313044678988
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
