scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.20788717263393386
          y: -0.23709916980820683
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.01999933097272788
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.007833834436844064
            roll: 0.0
            pitch: 0.0
            yaw: -0.13286639884808862
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.02017340203807049
            roll: 0.0
            pitch: 0.0
            yaw: -0.05953408435335526
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0015455194299454807
            roll: 0.0
            pitch: 0.0
            yaw: -0.13465398734553474
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0011148406359638534
            roll: 0.0
            pitch: 0.0
            yaw: 0.16904567900194295
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.019780568830049725
            roll: 0.0
            pitch: 0.0
            yaw: 0.13053401451062352
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.008559399170863985
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.042030804617588416
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08226847127762259
            roll: 0.0
            pitch: 0.0
            yaw: -0.5424383320790278
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.03871987346593106
            roll: 0.0
            pitch: 0.0
            yaw: -0.11604246467453483
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.055264661428995734
            roll: 0.0
            pitch: 0.0
            yaw: 0.04556041416661838
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0587257750272053
            roll: 0.0
            pitch: 0.0
            yaw: -0.7545744147526501
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07778532675387091
            roll: 0.0
            pitch: 0.0
            yaw: -0.0779162950617569
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.012477221249647896
            roll: 0.0
            pitch: 0.0
            yaw: 0.5029605580975598
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0019486402130740985
              y: 0.014811515231966698
              z: 0.04156371233398268
              roll: 0.43219154449397995
              pitch: -0.4892825619120053
              yaw: 1.3018335445313869
            roll: 0.4273715301633999
            pitch: -0.5007388009493935
            yaw: 1.3534674801651139
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.29362844593993526
          y: -0.2909299588947385
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.38477384774546197
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.018582159517681406
            roll: 0.0
            pitch: 0.0
            yaw: -0.04347760907797532
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.019411958218012497
            roll: 0.0
            pitch: 0.0
            yaw: -0.1351120310523307
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.016741708731264432
            roll: 0.0
            pitch: 0.0
            yaw: -0.15572180786836887
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.009078800273305945
            roll: 0.0
            pitch: 0.0
            yaw: 0.0809663216300276
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.013326390696219062
            roll: 0.0
            pitch: 0.0
            yaw: 0.13858464655267155
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05834845978761845
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.027043723070282147
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0816708760256886
            roll: 0.0
            pitch: 0.0
            yaw: -0.5483094890617219
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09208734737771707
            roll: 0.0
            pitch: 0.0
            yaw: 0.527835918772708
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04781574937437816
            roll: 0.0
            pitch: 0.0
            yaw: -0.3574337864662466
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08927602193229214
            roll: 0.0
            pitch: 0.0
            yaw: -0.1632818328087836
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08476011606551992
            roll: 0.0
            pitch: 0.0
            yaw: -0.8295988622976688
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.008194143651128014
            roll: 0.0
            pitch: 0.0
            yaw: -0.4113391947005617
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0004649747028675666
              y: 0.01657572492493444
              z: 0.041048288593003225
              roll: 0.42350713502395054
              pitch: -0.5177942630213322
              yaw: 1.339818617297346
            roll: 0.42546619347355324
            pitch: -0.506810246924037
            yaw: 1.3575064245012014
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.29937910595530115
          y: -0.141102471041374
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.03865369343290692
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.017429787966313295
            roll: 0.0
            pitch: 0.0
            yaw: 0.0023784084748753043
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006948456127401066
            roll: 0.0
            pitch: 0.0
            yaw: -0.0915440609062469
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.012586912926991031
            roll: 0.0
            pitch: 0.0
            yaw: 0.08696991331613624
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02234661180545886
            roll: 0.0
            pitch: 0.0
            yaw: -0.03357586979970642
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.00839296633409468
            roll: 0.0
            pitch: 0.0
            yaw: 0.04190278976047984
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.029947709521159327
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02161700393914122
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.008384479805551293
            roll: 0.0
            pitch: 0.0
            yaw: 0.7558864053318135
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.03865787194819875
            roll: 0.0
            pitch: 0.0
            yaw: 0.18151079558658223
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05976706041873119
            roll: 0.0
            pitch: 0.0
            yaw: -0.9863569876807792
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08339352476934384
            roll: 0.0
            pitch: 0.0
            yaw: -0.36548565945236755
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08469131975256391
            roll: 0.0
            pitch: 0.0
            yaw: 0.8750072568360778
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03271547353619064
            roll: 0.0
            pitch: 0.0
            yaw: -0.2720171748351973
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0008344024187447907
              y: 0.016078241923447163
              z: 0.04214584648294352
              roll: 0.41122739377774775
              pitch: -0.5185219575126936
              yaw: 1.311118254665725
            roll: 0.41426153430649004
            pitch: -0.4989958376001481
            yaw: 1.3613320273257965
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
