scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.14217147578095377
          y: -0.2693674611174602
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.2635605544645768
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.016788752485344685
            roll: 0.0
            pitch: 0.0
            yaw: 0.05199049132704198
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.011147426076277604
            roll: 0.0
            pitch: 0.0
            yaw: -0.04617890962333926
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.013945205338800403
            roll: 0.0
            pitch: 0.0
            yaw: -0.13804233431312712
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0216856214377157
            roll: 0.0
            pitch: 0.0
            yaw: -0.17458764314164557
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.012292993055360489
            roll: 0.0
            pitch: 0.0
            yaw: -0.16287939230981105
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0436562034666904
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.020606320609856732
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.046953686119075994
            roll: 0.0
            pitch: 0.0
            yaw: -0.5383615431913309
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.040202163905887545
            roll: 0.0
            pitch: 0.0
            yaw: 0.728650876826008
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05114474499417419
            roll: 0.0
            pitch: 0.0
            yaw: -0.5828522811834549
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.02837859491581718
            roll: 0.0
            pitch: 0.0
            yaw: 0.1539212643287644
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07787642387095864
            roll: 0.0
            pitch: 0.0
            yaw: -0.030950206326703755
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02731294048588695
            roll: 0.0
            pitch: 0.0
            yaw: -0.05341931137016476
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0002997089629798175
              y: 0.01714181140303392
              z: 0.0427307196925937
              roll: 0.4405718485858313
              pitch: -0.46463319444654005
              yaw: 1.3235107523458658
            roll: 0.46868598194547795
            pitch: -0.45206494148188503
            yaw: 1.3044742627694939
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1313565047914299
          y: -0.2714120395917809
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.43614849180317083
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.018063194458260885
            roll: 0.0
            pitch: 0.0
            yaw: -0.05918825920455387
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.022122876110151873
            roll: 0.0
            pitch: 0.0
            yaw: -0.12824607159996526
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.017272564511994087
            roll: 0.0
            pitch: 0.0
            yaw: -0.05792935294005647
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.020958382285034327
            roll: 0.0
            pitch: 0.0
            yaw: 0.13866232102011722
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.008530075302372271
            roll: 0.0
            pitch: 0.0
            yaw: 0.13575914293581237
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.051409093507159276
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04029855789022816
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06058623927323349
            roll: 0.0
            pitch: 0.0
            yaw: -0.9252280191191659
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07219595555050018
            roll: 0.0
            pitch: 0.0
            yaw: -0.5618339761610525
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0673979661783707
            roll: 0.0
            pitch: 0.0
            yaw: -0.5860452768841762
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06678590551979165
            roll: 0.0
            pitch: 0.0
            yaw: 0.8541778920302512
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.061111639816693736
            roll: 0.0
            pitch: 0.0
            yaw: -0.8459260964707918
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.01718027104479246
            roll: 0.0
            pitch: 0.0
            yaw: -0.6928806713832043
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0011383155028054778
              y: 0.015291596624803842
              z: 0.041782844370388955
              roll: 0.41499739829074517
              pitch: -0.46013271553724977
              yaw: 1.3030422776907482
            roll: 0.4158037383551032
            pitch: -0.47311183085230335
            yaw: 1.3689792987028082
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.27077438967773837
          y: -0.18209690335038814
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.48167756538809847
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.018747137549827333
            roll: 0.0
            pitch: 0.0
            yaw: 0.05130721969652027
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.017074705010030562
            roll: 0.0
            pitch: 0.0
            yaw: 0.10672466779332473
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.010763528342725794
            roll: 0.0
            pitch: 0.0
            yaw: -0.0955337107163066
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0008848409129100891
            roll: 0.0
            pitch: 0.0
            yaw: -0.064337319896953
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.00016839290340555507
            roll: 0.0
            pitch: 0.0
            yaw: -0.15345865669703693
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03811488245539675
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.012252258270582586
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04090369854598024
            roll: 0.0
            pitch: 0.0
            yaw: 0.12060431867332722
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.054604025513905724
            roll: 0.0
            pitch: 0.0
            yaw: 0.6533138564290821
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07552748780991482
            roll: 0.0
            pitch: 0.0
            yaw: -0.12084640560180027
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.006223471638248254
            roll: 0.0
            pitch: 0.0
            yaw: -0.9105241842835672
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08600127821632632
            roll: 0.0
            pitch: 0.0
            yaw: -0.5785632479235268
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07972967389492489
            roll: 0.0
            pitch: 0.0
            yaw: 0.7436701692381342
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0019799800994568656
              y: 0.014137982605312589
              z: 0.04368980783096623
              roll: 0.47197107304201535
              pitch: -0.4529656320118456
              yaw: 1.3418466474867383
            roll: 0.4529929560330166
            pitch: -0.4903696391085264
            yaw: 1.3365371665160635
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
