scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.24660599810518388
          y: -0.2828525684171572
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.31787133528342926
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.014482144611058928
            roll: 0.0
            pitch: 0.0
            yaw: -0.013139075023784197
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0062449031143226065
            roll: 0.0
            pitch: 0.0
            yaw: -0.13500678988855042
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.011668642936211886
            roll: 0.0
            pitch: 0.0
            yaw: -0.007437997543610769
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.008064375767442008
            roll: 0.0
            pitch: 0.0
            yaw: -0.0172892812690075
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0037958123139828076
            roll: 0.0
            pitch: 0.0
            yaw: 0.06125615821082736
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.010550244603141273
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.028389085889447337
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.005597243919408967
            roll: 0.0
            pitch: 0.0
            yaw: -0.7296307179037196
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08877581760266212
            roll: 0.0
            pitch: 0.0
            yaw: -0.14969460599734785
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.013179798197868173
            roll: 0.0
            pitch: 0.0
            yaw: -0.398070177143078
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.02797905641111631
            roll: 0.0
            pitch: 0.0
            yaw: 0.5687965852096553
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05416126656401548
            roll: 0.0
            pitch: 0.0
            yaw: -0.9794195578751371
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06023214264780763
            roll: 0.0
            pitch: 0.0
            yaw: -0.20670072850668508
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0010913986111056118
              y: 0.013826214586216303
              z: 0.044413143301416304
              roll: 0.47134593462741314
              pitch: -0.4589814999028428
              yaw: 1.308233761154898
            roll: 0.4628040341319524
            pitch: -0.4770562973368227
            yaw: 1.3629350799792554
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.24602991352702733
          y: -0.22113183487736987
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.43701016423087025
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.006254595382021309
            roll: 0.0
            pitch: 0.0
            yaw: -0.17299179484444713
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.018095007766236598
            roll: 0.0
            pitch: 0.0
            yaw: 0.031051085512017018
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.019579723764957112
            roll: 0.0
            pitch: 0.0
            yaw: 0.06880747836129678
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.001216754165347514
            roll: 0.0
            pitch: 0.0
            yaw: 0.15417331329147543
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.019083960112600752
            roll: 0.0
            pitch: 0.0
            yaw: -0.15063761112772636
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05352283023840272
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.015936682450226627
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.01794043863117996
            roll: 0.0
            pitch: 0.0
            yaw: -0.7447487639549639
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04586611577887187
            roll: 0.0
            pitch: 0.0
            yaw: -0.2559041513621573
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07992614448151544
            roll: 0.0
            pitch: 0.0
            yaw: -0.0785913961742899
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07844036127354537
            roll: 0.0
            pitch: 0.0
            yaw: 0.5918245473946153
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.011799976264997833
            roll: 0.0
            pitch: 0.0
            yaw: 0.3920120131165781
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07690805118026321
            roll: 0.0
            pitch: 0.0
            yaw: 1.0290869611604985
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001731148337419136
              y: 0.015335254351271853
              z: 0.04426293863344165
              roll: 0.44136696452372876
              pitch: -0.47706064747315113
              yaw: 1.3697759822029354
            roll: 0.4537784738228557
            pitch: -0.4637638389693396
            yaw: 1.354246356896257
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2092058034638696
          y: -0.21057181784947937
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.18301253912140492
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.009013809123333837
            roll: 0.0
            pitch: 0.0
            yaw: 0.1451288750970841
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.012964219942425696
            roll: 0.0
            pitch: 0.0
            yaw: -0.12138880607419845
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01703093984475696
            roll: 0.0
            pitch: 0.0
            yaw: 0.0033589604540259776
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.017788237091097156
            roll: 0.0
            pitch: 0.0
            yaw: -0.12517938461768918
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.009175231281145488
            roll: 0.0
            pitch: 0.0
            yaw: -0.11217291071329573
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.051061885830872344
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.027653094254187084
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.009019287347718563
            roll: 0.0
            pitch: 0.0
            yaw: -0.4710218284252119
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.008218447050122216
            roll: 0.0
            pitch: 0.0
            yaw: 0.18245563309841772
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07923494432989095
            roll: 0.0
            pitch: 0.0
            yaw: 0.16535884516950783
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03717739077026903
            roll: 0.0
            pitch: 0.0
            yaw: 0.9704673650580349
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07037527664391668
            roll: 0.0
            pitch: 0.0
            yaw: 0.29756282126946054
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.034958515802856804
            roll: 0.0
            pitch: 0.0
            yaw: 0.7945631966952817
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0006688859949026396
              y: 0.014048358228998813
              z: 0.04208503672080298
              roll: 0.42855654226611745
              pitch: -0.4951698388675063
              yaw: 1.2985847054182564
            roll: 0.40946664604681365
            pitch: -0.49626825505008576
            yaw: 1.301845934505098
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
