scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2705357924256699
          y: -0.2470793483781971
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.01224730393259621
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015291213151750142
            roll: 0.0
            pitch: 0.0
            yaw: -0.04282922691177177
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.02105808899391739
            roll: 0.0
            pitch: 0.0
            yaw: 0.05959208198039331
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.018769744064448556
            roll: 0.0
            pitch: 0.0
            yaw: -0.10492298154096763
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02154114361752113
            roll: 0.0
            pitch: 0.0
            yaw: 0.007070513281728252
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.02048109446617064
            roll: 0.0
            pitch: 0.0
            yaw: 0.13994965475195303
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.00048128124126683297
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03260879642427672
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.02995924915296766
            roll: 0.0
            pitch: 0.0
            yaw: 0.11270515549644378
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.022754660755866934
            roll: 0.0
            pitch: 0.0
            yaw: 0.24894247606501185
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.020603478610806053
            roll: 0.0
            pitch: 0.0
            yaw: -0.1473673003493663
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.023233604924920062
            roll: 0.0
            pitch: 0.0
            yaw: 0.06245596820147692
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.04657070891141968
            roll: 0.0
            pitch: 0.0
            yaw: -0.9261207008225703
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.055850076731815114
            roll: 0.0
            pitch: 0.0
            yaw: 0.9557424020650191
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0003630126077690493
              y: 0.014464566791240415
              z: 0.043189649910359056
              roll: 0.4179354138377103
              pitch: -0.4855941762264092
              yaw: 1.2931929781585456
            roll: 0.4724337287395578
            pitch: -0.4789639108543026
            yaw: 1.302042622440765
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2966748829302283
          y: -0.11448883053503925
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.060564688083410534
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01627285845195137
            roll: 0.0
            pitch: 0.0
            yaw: -0.07700499258814487
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010193192107708693
            roll: 0.0
            pitch: 0.0
            yaw: 0.1041590867063138
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.005790785820989523
            roll: 0.0
            pitch: 0.0
            yaw: -0.06529148417234477
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02024212346934167
            roll: 0.0
            pitch: 0.0
            yaw: -0.12217230375979879
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.005953207306697159
            roll: 0.0
            pitch: 0.0
            yaw: 0.15563695537025918
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.018083505870299346
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.048593969166966164
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.008292241789910365
            roll: 0.0
            pitch: 0.0
            yaw: 0.05483043153877287
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.022276751994328325
            roll: 0.0
            pitch: 0.0
            yaw: 0.2883606531199565
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07230658033496348
            roll: 0.0
            pitch: 0.0
            yaw: 0.9562571101525872
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.022082783112036236
            roll: 0.0
            pitch: 0.0
            yaw: 0.5022913534632272
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.09208663879739612
            roll: 0.0
            pitch: 0.0
            yaw: 0.4903955682757355
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.036873741658656145
            roll: 0.0
            pitch: 0.0
            yaw: -0.9020418272618373
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0012538400668250583
              y: 0.014907194025984005
              z: 0.042077016069310885
              roll: 0.42593185931063204
              pitch: -0.4783852496380551
              yaw: 1.3106022125277492
            roll: 0.4555128084893487
            pitch: -0.4778280935807925
            yaw: 1.3474402780027859
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.28810182347997865
          y: -0.1678054755097323
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.12764749184359026
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.012539984619948923
            roll: 0.0
            pitch: 0.0
            yaw: -0.16075558942998883
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.008535526408693709
            roll: 0.0
            pitch: 0.0
            yaw: -0.10628321106049532
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01901915852301296
            roll: 0.0
            pitch: 0.0
            yaw: 0.036089429678124146
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.019878145318005122
            roll: 0.0
            pitch: 0.0
            yaw: -0.09449320344041469
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01426247101521256
            roll: 0.0
            pitch: 0.0
            yaw: -0.10597077481504615
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.025691371941385557
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.038075356397047
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.04476382978394877
            roll: 0.0
            pitch: 0.0
            yaw: 0.27985397796101275
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.01732607657441476
            roll: 0.0
            pitch: 0.0
            yaw: 0.3670752718043322
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05420042705277524
            roll: 0.0
            pitch: 0.0
            yaw: 0.6634684467826508
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.013283744268188014
            roll: 0.0
            pitch: 0.0
            yaw: 0.5512509635575156
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.017887571823677353
            roll: 0.0
            pitch: 0.0
            yaw: 0.33723302157536006
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.048187927057763084
            roll: 0.0
            pitch: 0.0
            yaw: -0.4029276728067771
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.00027159660168582663
              y: 0.01643306049082591
              z: 0.0427551943345479
              roll: 0.4388615869099469
              pitch: -0.5135751425890438
              yaw: 1.3055754736628158
            roll: 0.45235603112661915
            pitch: -0.4943811416343403
            yaw: 1.3321064528004232
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
