scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.22128181441826617
          y: -0.2624359007724042
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.07601116085498572
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.007083446104922078
            roll: 0.0
            pitch: 0.0
            yaw: 0.01914763210501466
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01021394063424056
            roll: 0.0
            pitch: 0.0
            yaw: 0.16909692035700852
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01825420886699166
            roll: 0.0
            pitch: 0.0
            yaw: 0.059170964940637755
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.014960338096517707
            roll: 0.0
            pitch: 0.0
            yaw: -0.1385013139377757
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02111297948088804
            roll: 0.0
            pitch: 0.0
            yaw: -0.1444483964373339
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0005810943405589603
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.008803249645884484
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.042946670483208715
            roll: 0.0
            pitch: 0.0
            yaw: 0.6181119788018892
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.021410628694149475
            roll: 0.0
            pitch: 0.0
            yaw: 0.1837017775177674
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07930237995324436
            roll: 0.0
            pitch: 0.0
            yaw: -0.567858857089115
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06625694437244847
            roll: 0.0
            pitch: 0.0
            yaw: 0.19636450233805824
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08778179051966456
            roll: 0.0
            pitch: 0.0
            yaw: -0.5704294763678873
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.01415381836934941
            roll: 0.0
            pitch: 0.0
            yaw: -0.08452415693554338
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0003933179295089854
              y: 0.01586530496000037
              z: 0.043088277199512935
              roll: 0.45587991726007504
              pitch: -0.49317336523220107
              yaw: 1.298199836444851
            roll: 0.4362933364338359
            pitch: -0.5141105690490386
            yaw: 1.294805902232594
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2300514757368099
          y: -0.13840700617626658
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4870606269938995
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.010082134725610238
            roll: 0.0
            pitch: 0.0
            yaw: 0.01750996226652901
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.021050955231058793
            roll: 0.0
            pitch: 0.0
            yaw: -0.16735400270594702
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.016973846634176747
            roll: 0.0
            pitch: 0.0
            yaw: -0.09739424851592253
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.007492872519878957
            roll: 0.0
            pitch: 0.0
            yaw: -0.12451768229464606
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.008189166563485895
            roll: 0.0
            pitch: 0.0
            yaw: -0.1452072787105656
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.017662123784192726
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.01799728040777717
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.03562555687878231
            roll: 0.0
            pitch: 0.0
            yaw: 0.3190839411938855
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.027430309152857657
            roll: 0.0
            pitch: 0.0
            yaw: 0.7852814700270729
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.013668607704039493
            roll: 0.0
            pitch: 0.0
            yaw: 0.4738864987513216
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.004418357927360034
            roll: 0.0
            pitch: 0.0
            yaw: -0.6136867644218107
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.013839198206997874
            roll: 0.0
            pitch: 0.0
            yaw: 0.4840461434981813
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.001130187050580711
            roll: 0.0
            pitch: 0.0
            yaw: 1.0064027085584486
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00046230460373273977
              y: 0.015806322532301225
              z: 0.041578982191029186
              roll: 0.4348726655385369
              pitch: -0.5024743989691295
              yaw: 1.3185467903132801
            roll: 0.4747041298533482
            pitch: -0.4525273198286438
            yaw: 1.303418111960806
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.26741019038052627
          y: -0.2805900536704765
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4181288699601011
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.012721902750230468
            roll: 0.0
            pitch: 0.0
            yaw: 0.09479555936592943
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0007316387959658797
            roll: 0.0
            pitch: 0.0
            yaw: 0.14055475530068978
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.010194406100163178
            roll: 0.0
            pitch: 0.0
            yaw: 0.16354810950680948
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.018067720234474383
            roll: 0.0
            pitch: 0.0
            yaw: 0.07221782133477936
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.004355748027258601
            roll: 0.0
            pitch: 0.0
            yaw: 0.0038021331671281855
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.024825357340852852
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03511239804851159
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08189879064628483
            roll: 0.0
            pitch: 0.0
            yaw: -0.09936342961668498
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.06074210059158
            roll: 0.0
            pitch: 0.0
            yaw: 0.724957149904911
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0020833981995796724
            roll: 0.0
            pitch: 0.0
            yaw: -0.4294782773736847
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03152213537492779
            roll: 0.0
            pitch: 0.0
            yaw: 0.5687954761598628
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.011908031140230688
            roll: 0.0
            pitch: 0.0
            yaw: 0.92877968610544
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.015503559269380698
            roll: 0.0
            pitch: 0.0
            yaw: -0.8963407297822671
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.000980945149575133
              y: 0.01385569889399333
              z: 0.04164676122331847
              roll: 0.47017269855011656
              pitch: -0.45258540293723093
              yaw: 1.3519440379791168
            roll: 0.4070857709017669
            pitch: -0.482143018645879
            yaw: 1.337603079055605
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
