scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.21575029307841076
          y: -0.27762948676410004
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.021521668077952416
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.005257490320408759
            roll: 0.0
            pitch: 0.0
            yaw: 0.09930797479864456
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.018079879917415775
            roll: 0.0
            pitch: 0.0
            yaw: -0.029940195992089802
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.013991499573248772
            roll: 0.0
            pitch: 0.0
            yaw: 0.025764441026094848
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.020793970646502097
            roll: 0.0
            pitch: 0.0
            yaw: 0.15058314901600767
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0030676014364884423
            roll: 0.0
            pitch: 0.0
            yaw: -0.09045001168049067
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.025937049403326577
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.032890816299886175
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.010839044685841584
            roll: 0.0
            pitch: 0.0
            yaw: 0.8755211872836157
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.029485227921727516
            roll: 0.0
            pitch: 0.0
            yaw: 0.2535241024477868
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05050245840395112
            roll: 0.0
            pitch: 0.0
            yaw: 0.7202340479456264
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.007273720006683956
            roll: 0.0
            pitch: 0.0
            yaw: 0.6227813084156817
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.003576889495131186
            roll: 0.0
            pitch: 0.0
            yaw: -0.5792082812099613
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05173548383849765
            roll: 0.0
            pitch: 0.0
            yaw: 0.9814891845755673
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00035245052488899016
              y: 0.01676773232214846
              z: 0.040912767748567974
              roll: 0.42198345393315345
              pitch: -0.44755701253004754
              yaw: 1.3351215521372928
            roll: 0.4605925523399973
            pitch: -0.503119973368222
            yaw: 1.3698434079698867
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2125802542973329
          y: -0.2827475543042262
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.35087098543048645
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.017967043925721328
            roll: 0.0
            pitch: 0.0
            yaw: 0.005926951121473012
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006069965202035675
            roll: 0.0
            pitch: 0.0
            yaw: 0.012418503726915026
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.013052223105312323
            roll: 0.0
            pitch: 0.0
            yaw: -0.012551642607713492
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.018686015598227537
            roll: 0.0
            pitch: 0.0
            yaw: -0.00026729076875756097
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.02114863273651023
            roll: 0.0
            pitch: 0.0
            yaw: 0.13532250855385886
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05357565004210353
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.014251104413378388
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.06234717942863849
            roll: 0.0
            pitch: 0.0
            yaw: 0.6610167131303668
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09382944611986266
            roll: 0.0
            pitch: 0.0
            yaw: -0.8888572985957036
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.017917750862364884
            roll: 0.0
            pitch: 0.0
            yaw: -0.7212082536426856
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.026725412811834368
            roll: 0.0
            pitch: 0.0
            yaw: -1.0224531368161365
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08999605906972749
            roll: 0.0
            pitch: 0.0
            yaw: -0.7684954553001653
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05177015593096396
            roll: 0.0
            pitch: 0.0
            yaw: 0.2371543671102483
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0009321413383860215
              y: 0.015080957620011864
              z: 0.04123519357974341
              roll: 0.47012375813564133
              pitch: -0.5094710838563496
              yaw: 1.3579212147171646
            roll: 0.44219333629581237
            pitch: -0.4687888001941138
            yaw: 1.3539911316292594
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2413786129613559
          y: -0.22380583737972293
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4145334332090488
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01944961953352014
            roll: 0.0
            pitch: 0.0
            yaw: -0.1477272154461303
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.009886620383786762
            roll: 0.0
            pitch: 0.0
            yaw: 0.0579264975595192
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.007456546848505167
            roll: 0.0
            pitch: 0.0
            yaw: 0.03583749113196574
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.015323463042406775
            roll: 0.0
            pitch: 0.0
            yaw: -0.051184805176906156
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.00215490063681369
            roll: 0.0
            pitch: 0.0
            yaw: -0.13606151106034883
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05041318231734042
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0019578214480933526
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07976654866574132
            roll: 0.0
            pitch: 0.0
            yaw: -0.9571901701171028
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.002535139705994796
            roll: 0.0
            pitch: 0.0
            yaw: 0.9282003457789898
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08742515633076967
            roll: 0.0
            pitch: 0.0
            yaw: -1.019306838647516
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09112946644744158
            roll: 0.0
            pitch: 0.0
            yaw: 0.8630475253034109
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.03578713759178771
            roll: 0.0
            pitch: 0.0
            yaw: -0.03948078487750517
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03030074017079265
            roll: 0.0
            pitch: 0.0
            yaw: 0.931445386555559
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.001420801842422202
              y: 0.015186577798904076
              z: 0.04204435651604792
              roll: 0.44973711813539485
              pitch: -0.47766351817380454
              yaw: 1.3311867715214984
            roll: 0.4095167337178405
            pitch: -0.48815395201503153
            yaw: 1.3120795615319714
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
