scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.13944166733071592
          y: -0.1152280062273564
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.18727513275013252
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0002780714811007681
            roll: 0.0
            pitch: 0.0
            yaw: -0.026493567621119624
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008687991302455742
            roll: 0.0
            pitch: 0.0
            yaw: 0.08571167943687075
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01628437643095923
            roll: 0.0
            pitch: 0.0
            yaw: -0.16131939968017422
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01111807138697983
            roll: 0.0
            pitch: 0.0
            yaw: 0.14447693636728004
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0051106845571510205
            roll: 0.0
            pitch: 0.0
            yaw: 0.11372731597742358
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.00762054051819426
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0009863688045695304
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.009894773847636956
            roll: 0.0
            pitch: 0.0
            yaw: 0.9724824118369464
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.015884854371805632
            roll: 0.0
            pitch: 0.0
            yaw: -0.21530469422801946
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06644880183978757
            roll: 0.0
            pitch: 0.0
            yaw: -0.7913793152865962
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.012117703583468739
            roll: 0.0
            pitch: 0.0
            yaw: 0.7355956065087215
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.01756232648721076
            roll: 0.0
            pitch: 0.0
            yaw: -0.17616579914346941
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.019907642274604648
            roll: 0.0
            pitch: 0.0
            yaw: 0.9253202959405662
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0013917955954032852
              y: 0.014995212646484115
              z: 0.041732565084149506
              roll: 0.43792935659235077
              pitch: -0.4561603696494744
              yaw: 1.292925306907087
            roll: 0.4481978145490018
            pitch: -0.498994585887024
            yaw: 1.3274980251142836
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.13895581188572428
          y: -0.19321089672201835
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.2688116162530798
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0010019195657401218
            roll: 0.0
            pitch: 0.0
            yaw: 0.16246128461933645
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.00870067826364323
            roll: 0.0
            pitch: 0.0
            yaw: 0.04818697194800364
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.015432471088802524
            roll: 0.0
            pitch: 0.0
            yaw: -0.08453049689535817
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.007366944022586605
            roll: 0.0
            pitch: 0.0
            yaw: 0.10227818152797541
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01936708966787132
            roll: 0.0
            pitch: 0.0
            yaw: -0.024130275190742317
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.009171334764641464
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.01569269354781675
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08250484543338878
            roll: 0.0
            pitch: 0.0
            yaw: 0.631430335443663
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.032793629166635724
            roll: 0.0
            pitch: 0.0
            yaw: -0.2565712256366768
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0015746185655909212
            roll: 0.0
            pitch: 0.0
            yaw: 0.5636788069297274
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0035879464124969757
            roll: 0.0
            pitch: 0.0
            yaw: -0.2830019316926671
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.053631927783987066
            roll: 0.0
            pitch: 0.0
            yaw: 1.0092425172360062
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.035777012557277985
            roll: 0.0
            pitch: 0.0
            yaw: 0.9893569283459411
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0010832166115248057
              y: 0.016603998514169858
              z: 0.040948660070112664
              roll: 0.4375293727995615
              pitch: -0.5054641055564711
              yaw: 1.3404305941417305
            roll: 0.4683072737343855
            pitch: -0.47839210248226044
            yaw: 1.3286476035474533
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.11351491948120195
          y: -0.26135849190435856
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.30240880774263323
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.006051904039291213
            roll: 0.0
            pitch: 0.0
            yaw: -0.03430948413204893
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01950983881779824
            roll: 0.0
            pitch: 0.0
            yaw: -0.016423333622983455
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0026572501463544805
            roll: 0.0
            pitch: 0.0
            yaw: 0.018125193920123378
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.009413764819325616
            roll: 0.0
            pitch: 0.0
            yaw: -0.06874146511634867
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.009924069705875123
            roll: 0.0
            pitch: 0.0
            yaw: 0.02104532035026993
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.026579039657412935
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05986542951930101
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.040813487983351465
            roll: 0.0
            pitch: 0.0
            yaw: -0.07342924513962368
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09495434816038614
            roll: 0.0
            pitch: 0.0
            yaw: -0.3584049789820888
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07914213579943313
            roll: 0.0
            pitch: 0.0
            yaw: -0.2671128912406656
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.005741381349132366
            roll: 0.0
            pitch: 0.0
            yaw: 0.7011220023412936
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08552771271819273
            roll: 0.0
            pitch: 0.0
            yaw: 0.2711458639573989
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.057866446272080804
            roll: 0.0
            pitch: 0.0
            yaw: -0.7442164809325174
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0008240231224105434
              y: 0.01518509160490808
              z: 0.044172522869095524
              roll: 0.47261328911167344
              pitch: -0.4520257187558943
              yaw: 1.3261716296945836
            roll: 0.47041013656257014
            pitch: -0.45768640936864835
            yaw: 1.3363105932626853
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
