scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.22891222494154878
          y: -0.2405516215079071
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.14455864946786667
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.023011451873143463
            roll: 0.0
            pitch: 0.0
            yaw: 0.07317934980680174
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.002830552534155994
            roll: 0.0
            pitch: 0.0
            yaw: -0.1464462695375039
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.005615790190180572
            roll: 0.0
            pitch: 0.0
            yaw: 0.08788481438040946
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.006879240889817348
            roll: 0.0
            pitch: 0.0
            yaw: -0.1164862481502268
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0033497518932399627
            roll: 0.0
            pitch: 0.0
            yaw: -0.09017870544387796
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01082935188248628
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04434649458904702
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.03164265459139495
            roll: 0.0
            pitch: 0.0
            yaw: 0.06714367502258933
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.01869310095750737
            roll: 0.0
            pitch: 0.0
            yaw: -0.5416723804152357
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05938562449229988
            roll: 0.0
            pitch: 0.0
            yaw: -0.1826067619942725
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03344033195246318
            roll: 0.0
            pitch: 0.0
            yaw: 0.534236347574873
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.039019522694754866
            roll: 0.0
            pitch: 0.0
            yaw: -0.03497829692239596
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07986168894801558
            roll: 0.0
            pitch: 0.0
            yaw: -0.7828880153551241
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00197750422912776
              y: 0.01668101803326209
              z: 0.042202341589121506
              roll: 0.48299558677851584
              pitch: -0.5201986011779342
              yaw: 1.3484825202434494
            roll: 0.41508399575412597
            pitch: -0.5031450971967193
            yaw: 1.368573403874374
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.29493622611372766
          y: -0.1797886343538063
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.32839378135218944
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01733295681118739
            roll: 0.0
            pitch: 0.0
            yaw: -0.1415073795115261
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.005340842206171762
            roll: 0.0
            pitch: 0.0
            yaw: 0.1154338287745128
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0001384963295302001
            roll: 0.0
            pitch: 0.0
            yaw: 0.019848255086686667
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.004836636536565419
            roll: 0.0
            pitch: 0.0
            yaw: -0.06389435087581297
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.007648036109214353
            roll: 0.0
            pitch: 0.0
            yaw: 0.09932200475358949
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0026982193672220878
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05338217150193674
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.032267060956151394
            roll: 0.0
            pitch: 0.0
            yaw: 0.8994574994814666
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07446496716283288
            roll: 0.0
            pitch: 0.0
            yaw: -0.24520924206398986
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.030076206411582554
            roll: 0.0
            pitch: 0.0
            yaw: -0.026973714852924546
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.055967225001334
            roll: 0.0
            pitch: 0.0
            yaw: -0.5920818954523144
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07984502742472424
            roll: 0.0
            pitch: 0.0
            yaw: 0.9207952648644135
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06048653218005485
            roll: 0.0
            pitch: 0.0
            yaw: 0.46167289587235594
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0006953848175257956
              y: 0.01607005622902939
              z: 0.042220007653155325
              roll: 0.4492754248959635
              pitch: -0.5024685172393636
              yaw: 1.3077986154715537
            roll: 0.4158637568061497
            pitch: -0.5098536059199775
            yaw: 1.3025051796074867
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2770375110103799
          y: -0.2642510920680589
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4902236617650547
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0074045531008661795
            roll: 0.0
            pitch: 0.0
            yaw: 0.07059034161912522
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006849671442459416
            roll: 0.0
            pitch: 0.0
            yaw: -0.05754271204696351
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.019022538417732868
            roll: 0.0
            pitch: 0.0
            yaw: 0.040099701027805856
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012309688152188573
            roll: 0.0
            pitch: 0.0
            yaw: -0.09951818528322538
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.015720148674375378
            roll: 0.0
            pitch: 0.0
            yaw: -0.1438857193359495
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.027913234148815885
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.007662583542053424
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08580102913514215
            roll: 0.0
            pitch: 0.0
            yaw: 0.09829693500933923
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08667327925835475
            roll: 0.0
            pitch: 0.0
            yaw: -0.954551767932066
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08856640445823633
            roll: 0.0
            pitch: 0.0
            yaw: -0.29508879345146144
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04171684964565542
            roll: 0.0
            pitch: 0.0
            yaw: 0.4179237979527768
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.007958883289729185
            roll: 0.0
            pitch: 0.0
            yaw: 0.1610469002801549
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.007331434235386847
            roll: 0.0
            pitch: 0.0
            yaw: -0.4579701247078829
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0013666132720208126
              y: 0.015473876364822567
              z: 0.04218573284283089
              roll: 0.4293167821451046
              pitch: -0.4623914871613904
              yaw: 1.3631383857667831
            roll: 0.4241232803063734
            pitch: -0.4731856191827548
            yaw: 1.298748033698184
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
