scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.25927886861630334
          y: -0.1960851100908831
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.022299022489577047
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.018684115671743284
            roll: 0.0
            pitch: 0.0
            yaw: 0.14700111754984557
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.015383000551122596
            roll: 0.0
            pitch: 0.0
            yaw: -0.08193493139706812
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.018174868491965424
            roll: 0.0
            pitch: 0.0
            yaw: 0.06496051948689413
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.015224712509687523
            roll: 0.0
            pitch: 0.0
            yaw: 0.05908763395995972
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0008602916402443428
            roll: 0.0
            pitch: 0.0
            yaw: -0.14337351820658956
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.01122629838058977
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0260871450517002
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0013114322899504954
            roll: 0.0
            pitch: 0.0
            yaw: -0.5568600969454782
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.083146861598931
            roll: 0.0
            pitch: 0.0
            yaw: 1.0371768956392613
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06500316994883562
            roll: 0.0
            pitch: 0.0
            yaw: -0.46681131442184753
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.016560426291255842
            roll: 0.0
            pitch: 0.0
            yaw: 0.5414160259984651
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06669771448412953
            roll: 0.0
            pitch: 0.0
            yaw: -0.5206437321579461
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.09438694797421043
            roll: 0.0
            pitch: 0.0
            yaw: 0.6184051721789343
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00013756262472902929
              y: 0.014065779491320712
              z: 0.0412664941654557
              roll: 0.46810068375010805
              pitch: -0.4537064836593231
              yaw: 1.3631287198514976
            roll: 0.48101583112325125
            pitch: -0.4849848978505984
            yaw: 1.3246192608763596
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.28583167983165
          y: -0.15767569838071152
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4176212667121634
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0033746705690734617
            roll: 0.0
            pitch: 0.0
            yaw: -0.14533265325641526
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01665001927314868
            roll: 0.0
            pitch: 0.0
            yaw: -0.07330130391208041
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0030772932540278075
            roll: 0.0
            pitch: 0.0
            yaw: 0.09514567048260753
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.006929973445565115
            roll: 0.0
            pitch: 0.0
            yaw: 0.16285730331755133
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.015494234013921554
            roll: 0.0
            pitch: 0.0
            yaw: 0.03320973047771733
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.021154010783135238
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02019108242244999
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.006693461111089011
            roll: 0.0
            pitch: 0.0
            yaw: -0.029958638894682643
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04006052644947314
            roll: 0.0
            pitch: 0.0
            yaw: 0.5190695363386102
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04286703627015758
            roll: 0.0
            pitch: 0.0
            yaw: 0.1954433320151452
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04668256208415417
            roll: 0.0
            pitch: 0.0
            yaw: -0.6694028184522058
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.034140212198744024
            roll: 0.0
            pitch: 0.0
            yaw: 0.6087352108302966
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.008376282144126473
            roll: 0.0
            pitch: 0.0
            yaw: 0.7323211315944813
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0017490073116815763
              y: 0.014769710400803245
              z: 0.04135669045202192
              roll: 0.42964800881548026
              pitch: -0.4940011731868112
              yaw: 1.3402339657331654
            roll: 0.45493234099144453
            pitch: -0.5002205691121765
            yaw: 1.348364956827201
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.17986627614675957
          y: -0.15713021557933127
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.27811121434416297
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.004029357594433364
            roll: 0.0
            pitch: 0.0
            yaw: 0.09499342249049664
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.02049633402687001
            roll: 0.0
            pitch: 0.0
            yaw: -0.04540991698012625
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.012620437213914266
            roll: 0.0
            pitch: 0.0
            yaw: -0.12997491079884363
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.019716761287416895
            roll: 0.0
            pitch: 0.0
            yaw: 0.17163232758269237
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.006835748071032077
            roll: 0.0
            pitch: 0.0
            yaw: -0.03989377547122119
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03759387509292936
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.005047100845997382
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.03906594858056539
            roll: 0.0
            pitch: 0.0
            yaw: 0.38504847270571596
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.028149826043619805
            roll: 0.0
            pitch: 0.0
            yaw: 0.6744891797933568
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05669273752093097
            roll: 0.0
            pitch: 0.0
            yaw: 0.8590909115891863
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07596334336779792
            roll: 0.0
            pitch: 0.0
            yaw: 0.8726172356939359
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07010795054724142
            roll: 0.0
            pitch: 0.0
            yaw: 0.4250863911667011
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03310670427633215
            roll: 0.0
            pitch: 0.0
            yaw: -0.22481362761676105
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0011999457670172752
              y: 0.014529584391872144
              z: 0.043585912106613896
              roll: 0.41360164549019374
              pitch: -0.4992996362291099
              yaw: 1.31231059473939
            roll: 0.434704681932262
            pitch: -0.5182583017850154
            yaw: 1.3420288379042404
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
