scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.27490085315685936
          y: -0.16665972632741471
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.43331934131247973
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.011761811334626351
            roll: 0.0
            pitch: 0.0
            yaw: -0.06752784564707393
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.016056354842886846
            roll: 0.0
            pitch: 0.0
            yaw: -0.1624307961384121
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.006764894205145033
            roll: 0.0
            pitch: 0.0
            yaw: 0.026346560166110117
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013946264124843594
            roll: 0.0
            pitch: 0.0
            yaw: -0.014507661656567389
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02333582555067444
            roll: 0.0
            pitch: 0.0
            yaw: 0.160883676941398
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.039113549260953714
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04821954767700208
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.007565596558505749
            roll: 0.0
            pitch: 0.0
            yaw: 0.438731826823308
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08095525272789203
            roll: 0.0
            pitch: 0.0
            yaw: -0.26035031254367647
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0823863197386359
            roll: 0.0
            pitch: 0.0
            yaw: -0.8792386798191983
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0247266493282514
            roll: 0.0
            pitch: 0.0
            yaw: -0.9448437654187843
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05573180838806552
            roll: 0.0
            pitch: 0.0
            yaw: -0.7192453820035345
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.013217756755601995
            roll: 0.0
            pitch: 0.0
            yaw: -0.6710612586086171
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0003449109157704778
              y: 0.016287400050757163
              z: 0.04198242784652575
              roll: 0.428412124585071
              pitch: -0.48210199304033396
              yaw: 1.2947496625807933
            roll: 0.468302689205399
            pitch: -0.5146885181269444
            yaw: 1.329801185817793
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.10478365992932043
          y: -0.13369082898474066
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.18068561527759153
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.013755299827587622
            roll: 0.0
            pitch: 0.0
            yaw: 0.03622805598930501
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01800898829510241
            roll: 0.0
            pitch: 0.0
            yaw: 0.15263894664405214
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.012307180285269656
            roll: 0.0
            pitch: 0.0
            yaw: -0.048717655813229815
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.022470104621460728
            roll: 0.0
            pitch: 0.0
            yaw: 0.07039699062143143
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01512272556396474
            roll: 0.0
            pitch: 0.0
            yaw: -0.031694984074548765
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.003142181891770429
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.007468101686243053
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.037956887076133705
            roll: 0.0
            pitch: 0.0
            yaw: 0.15062847093540377
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04849703656869711
            roll: 0.0
            pitch: 0.0
            yaw: 0.7304117888139301
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05397212971584445
            roll: 0.0
            pitch: 0.0
            yaw: -0.4581040667585029
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04596739633881419
            roll: 0.0
            pitch: 0.0
            yaw: 0.16353581622094238
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08508095539947527
            roll: 0.0
            pitch: 0.0
            yaw: -0.8252833938202176
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06621954535918016
            roll: 0.0
            pitch: 0.0
            yaw: -0.15610585251867903
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0003265541843020521
              y: 0.013387058169044506
              z: 0.043630551995564246
              roll: 0.4551475505737581
              pitch: -0.48491803111541093
              yaw: 1.3625670551019964
            roll: 0.47952023349581196
            pitch: -0.4840086581492397
            yaw: 1.3497599169460148
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.23843875671807488
          y: -0.29776484564004824
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4259298336018924
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.012915331981193913
            roll: 0.0
            pitch: 0.0
            yaw: 0.024641489969432745
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.014157422567469699
            roll: 0.0
            pitch: 0.0
            yaw: 0.012818919069388507
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0009129774208895929
            roll: 0.0
            pitch: 0.0
            yaw: 0.02817916782902835
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.012563102835478873
            roll: 0.0
            pitch: 0.0
            yaw: 0.12429589839835964
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.007893189663944136
            roll: 0.0
            pitch: 0.0
            yaw: -0.072813511868145
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0369107150622576
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05325806279441374
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.027116873065993655
            roll: 0.0
            pitch: 0.0
            yaw: 0.8465437781176244
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05705256026593647
            roll: 0.0
            pitch: 0.0
            yaw: 0.5806438226010113
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0014764981879547001
            roll: 0.0
            pitch: 0.0
            yaw: 0.9461404559103814
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03658015209151378
            roll: 0.0
            pitch: 0.0
            yaw: 0.4985129124157732
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.01032071036255186
            roll: 0.0
            pitch: 0.0
            yaw: 0.6433734417281616
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04550431861093096
            roll: 0.0
            pitch: 0.0
            yaw: -0.26234472993663716
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.001978213095426632
              y: 0.016544899065184686
              z: 0.04277258283228403
              roll: 0.4535243148741448
              pitch: -0.45187182963980677
              yaw: 1.3409698493085633
            roll: 0.46564855638531405
            pitch: -0.4982972553739226
            yaw: 1.31991986467372
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
