scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.10786140985757418
          y: -0.2772449763994191
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.47377928698544247
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.009890807451346323
            roll: 0.0
            pitch: 0.0
            yaw: -0.03987909738471879
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.003744295898069308
            roll: 0.0
            pitch: 0.0
            yaw: 0.12941863452029095
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.020771982728808445
            roll: 0.0
            pitch: 0.0
            yaw: 0.043094579180439324
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01763197057262822
            roll: 0.0
            pitch: 0.0
            yaw: 0.15303795977318296
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.018080760675876606
            roll: 0.0
            pitch: 0.0
            yaw: 0.032652517812445936
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.023858798937511916
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.023419880933531992
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05410096576983779
            roll: 0.0
            pitch: 0.0
            yaw: 0.03825943175344615
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09093774903453572
            roll: 0.0
            pitch: 0.0
            yaw: 0.550224009666761
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04854903925205581
            roll: 0.0
            pitch: 0.0
            yaw: 0.3192388713887473
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.07973682140596378
            roll: 0.0
            pitch: 0.0
            yaw: -0.24393357087548873
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07543917330809918
            roll: 0.0
            pitch: 0.0
            yaw: 0.2909197227141065
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06520297129656052
            roll: 0.0
            pitch: 0.0
            yaw: -0.8846197023461089
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0004308758802475201
              y: 0.016441417852875118
              z: 0.042952276132245094
              roll: 0.4455812115914318
              pitch: -0.4863764064226047
              yaw: 1.3644784985951541
            roll: 0.4329020196200478
            pitch: -0.4995254598020617
            yaw: 1.355217888741527
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.22235332574284372
          y: -0.10627309916604788
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.05627695119189935
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.006703545740516514
            roll: 0.0
            pitch: 0.0
            yaw: 0.0819102643787688
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.019861177844964828
            roll: 0.0
            pitch: 0.0
            yaw: -0.08632257452632125
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.004505830255368607
            roll: 0.0
            pitch: 0.0
            yaw: -0.17447254318721836
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01395135448067468
            roll: 0.0
            pitch: 0.0
            yaw: 0.05296388085254533
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01182596972182212
            roll: 0.0
            pitch: 0.0
            yaw: -0.01756310474682876
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01772561940839068
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.007041600266939563
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.005489873819078159
            roll: 0.0
            pitch: 0.0
            yaw: -0.2533180302737197
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.012657372926849875
            roll: 0.0
            pitch: 0.0
            yaw: -0.35193233302270266
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09394975883744636
            roll: 0.0
            pitch: 0.0
            yaw: 0.7944635121939179
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.021370970411817874
            roll: 0.0
            pitch: 0.0
            yaw: 0.024025498952485735
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0920990808616008
            roll: 0.0
            pitch: 0.0
            yaw: 0.8070162541859838
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.003404699520037399
            roll: 0.0
            pitch: 0.0
            yaw: -0.45109957091459585
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00013495569885579092
              y: 0.016357219937550578
              z: 0.043832710954574486
              roll: 0.45275056484539883
              pitch: -0.512668887308599
              yaw: 1.3075347095407435
            roll: 0.4613075087659103
            pitch: -0.48288286809961584
            yaw: 1.3107826535534461
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.17034930307586743
          y: -0.13716555901363592
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.19142223464848618
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.015565728582349052
            roll: 0.0
            pitch: 0.0
            yaw: 0.13129842666576103
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.002076988403145536
            roll: 0.0
            pitch: 0.0
            yaw: 0.06146187037995604
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.017041643867082217
            roll: 0.0
            pitch: 0.0
            yaw: -0.054324225024040426
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01732209434777414
            roll: 0.0
            pitch: 0.0
            yaw: 0.017036241429131016
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.013315243823721845
            roll: 0.0
            pitch: 0.0
            yaw: -0.07070003435782538
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0019312310909454303
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.01656219125029154
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.02697240133721783
            roll: 0.0
            pitch: 0.0
            yaw: 0.155957538878724
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.030765615571922172
            roll: 0.0
            pitch: 0.0
            yaw: -0.3698477307282022
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.025089724179592904
            roll: 0.0
            pitch: 0.0
            yaw: 0.7624534900503042
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.042076999831483886
            roll: 0.0
            pitch: 0.0
            yaw: -0.9360052326313136
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0020310245689470624
            roll: 0.0
            pitch: 0.0
            yaw: 0.11659601064806058
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.027649690417566583
            roll: 0.0
            pitch: 0.0
            yaw: -0.20975312332723828
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0004710823408679739
              y: 0.014378983288765659
              z: 0.04301148207029043
              roll: 0.40821159213045916
              pitch: -0.5174643487907611
              yaw: 1.3201055937358805
            roll: 0.46409231634350595
            pitch: -0.47962477133958614
            yaw: 1.322531950515348
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
