scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.12165536420286459
          y: -0.20490788812314206
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4989008463584278
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01845813531410316
            roll: 0.0
            pitch: 0.0
            yaw: -0.06336028322081808
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.013805710271495401
            roll: 0.0
            pitch: 0.0
            yaw: -0.16813743376293194
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.020992982019874033
            roll: 0.0
            pitch: 0.0
            yaw: -0.1566356146097604
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.009900420938547651
            roll: 0.0
            pitch: 0.0
            yaw: 0.06266364373067493
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02011681635730199
            roll: 0.0
            pitch: 0.0
            yaw: -0.10328914089311535
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02385411408364358
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.023837023900188672
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.06777414817461211
            roll: 0.0
            pitch: 0.0
            yaw: 0.8852339485837772
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07989215681872344
            roll: 0.0
            pitch: 0.0
            yaw: 0.7992378500073221
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02964977975563124
            roll: 0.0
            pitch: 0.0
            yaw: -0.5786735087686768
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0716479946137786
            roll: 0.0
            pitch: 0.0
            yaw: 0.567375733955104
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.04638749950187096
            roll: 0.0
            pitch: 0.0
            yaw: -0.19602509065467
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0540403746394961
            roll: 0.0
            pitch: 0.0
            yaw: -0.037770501481880325
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001304662293536733
              y: 0.01403497225359004
              z: 0.04165887540967982
              roll: 0.43866654843225844
              pitch: -0.5150239872832677
              yaw: 1.3415862292585934
            roll: 0.47620251754709825
            pitch: -0.4998818250514611
            yaw: 1.364545634025289
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.1309366213189744
          y: -0.1299299489977089
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.2309671220545889
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.014591033969700204
            roll: 0.0
            pitch: 0.0
            yaw: -0.15807593897431127
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.016019762561379707
            roll: 0.0
            pitch: 0.0
            yaw: 0.0893128648903882
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.007465756973907483
            roll: 0.0
            pitch: 0.0
            yaw: -0.046221554587236535
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.013484304238235115
            roll: 0.0
            pitch: 0.0
            yaw: -0.16825015443244387
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.001595506048651052
            roll: 0.0
            pitch: 0.0
            yaw: -0.06833141446174897
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.018824383118974164
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0119475882733356
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04153789692916036
            roll: 0.0
            pitch: 0.0
            yaw: -0.9416030666226185
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.025227776272107955
            roll: 0.0
            pitch: 0.0
            yaw: -0.8043060583724954
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.035811721587643064
            roll: 0.0
            pitch: 0.0
            yaw: 0.1345177901794632
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07819474149535763
            roll: 0.0
            pitch: 0.0
            yaw: 0.44623987098757256
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07781042211213482
            roll: 0.0
            pitch: 0.0
            yaw: -0.13901702640325142
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06906331031844412
            roll: 0.0
            pitch: 0.0
            yaw: 0.7122143352535399
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 4.271963950328939e-05
              y: 0.016565619239384648
              z: 0.04443150840083203
              roll: 0.4457349364812169
              pitch: -0.45444523687919947
              yaw: 1.3485759744580166
            roll: 0.40755603567773363
            pitch: -0.4736698850520472
            yaw: 1.319001800122894
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.17946242352234582
          y: -0.2698257247971381
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4140507462106362
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.015188133920864731
            roll: 0.0
            pitch: 0.0
            yaw: 0.10420171402780787
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.005455277369291203
            roll: 0.0
            pitch: 0.0
            yaw: -0.17089570466967863
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01680296349730604
            roll: 0.0
            pitch: 0.0
            yaw: -0.16623466683370686
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.010229012209580028
            roll: 0.0
            pitch: 0.0
            yaw: -0.10837100648849984
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.009947143225250537
            roll: 0.0
            pitch: 0.0
            yaw: 0.14255789479978587
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.030732818312155765
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.034378200922940264
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08354550198962414
            roll: 0.0
            pitch: 0.0
            yaw: 0.300267760156967
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0804681346455301
            roll: 0.0
            pitch: 0.0
            yaw: 0.8996888934682234
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09027764543870789
            roll: 0.0
            pitch: 0.0
            yaw: -0.36456041664046845
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07851985646992557
            roll: 0.0
            pitch: 0.0
            yaw: -0.23819385702830942
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.012800106369764669
            roll: 0.0
            pitch: 0.0
            yaw: 0.7696377703365713
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04258190951447707
            roll: 0.0
            pitch: 0.0
            yaw: 0.2837954839034531
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0008464749607982941
              y: 0.016209841737509927
              z: 0.04074273605281503
              roll: 0.42170360752660113
              pitch: -0.455825423291436
              yaw: 1.3263365855201672
            roll: 0.4393486522685658
            pitch: -0.4682996537444138
            yaw: 1.2983448752427484
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
