scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2834029853505757
          y: -0.25558723991372445
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.22090933049999972
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.013757068238837392
            roll: 0.0
            pitch: 0.0
            yaw: -0.1538672479646339
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007562254236608348
            roll: 0.0
            pitch: 0.0
            yaw: -0.13065635009105725
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.015186739840855806
            roll: 0.0
            pitch: 0.0
            yaw: 0.07506731735794364
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.014008528146536976
            roll: 0.0
            pitch: 0.0
            yaw: -0.1499914462242441
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0005425763744802588
            roll: 0.0
            pitch: 0.0
            yaw: -0.15560829223180228
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0465360884162771
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.02146650210327042
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.026241894138501837
            roll: 0.0
            pitch: 0.0
            yaw: 0.6803000439433933
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.03912088259062721
            roll: 0.0
            pitch: 0.0
            yaw: -0.9454228361143382
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.060011659629266745
            roll: 0.0
            pitch: 0.0
            yaw: 0.7649982873369956
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.012710530447148233
            roll: 0.0
            pitch: 0.0
            yaw: -0.38325775268443507
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.001810449139449652
            roll: 0.0
            pitch: 0.0
            yaw: 0.7196579484751773
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05104609017039269
            roll: 0.0
            pitch: 0.0
            yaw: 0.4661344233783009
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001331964517029403
              y: 0.015618828590553854
              z: 0.040569072836882714
              roll: 0.4401007033981402
              pitch: -0.5135822955185262
              yaw: 1.3419440805011729
            roll: 0.4724350544285333
            pitch: -0.4828409737788028
            yaw: 1.3208219926060238
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.25999762668934584
          y: -0.1028767682262807
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.23007963949778165
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.014464811826299509
            roll: 0.0
            pitch: 0.0
            yaw: -0.1745359418636552
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.015182437830890419
            roll: 0.0
            pitch: 0.0
            yaw: 0.15362158363259287
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.008529228796203957
            roll: 0.0
            pitch: 0.0
            yaw: -0.01627114368924998
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012193505750930249
            roll: 0.0
            pitch: 0.0
            yaw: 0.051595382856884
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0033618326366254107
            roll: 0.0
            pitch: 0.0
            yaw: 0.13315626084799403
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03917362750092628
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03948650143026179
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08070276050169126
            roll: 0.0
            pitch: 0.0
            yaw: -0.06599039137887242
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.02051738947515322
            roll: 0.0
            pitch: 0.0
            yaw: 0.7086878091843261
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02231593585490592
            roll: 0.0
            pitch: 0.0
            yaw: 0.292942859892398
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0315681938527122
            roll: 0.0
            pitch: 0.0
            yaw: -0.0992975782997555
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.024658586402732594
            roll: 0.0
            pitch: 0.0
            yaw: 0.05336110456525378
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.010323124800341338
            roll: 0.0
            pitch: 0.0
            yaw: 0.22046107585773567
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0013637090228874184
              y: 0.014105467024909887
              z: 0.04175167470003304
              roll: 0.4365380558614672
              pitch: -0.476905709129043
              yaw: 1.3472148279819591
            roll: 0.4113731011151425
            pitch: -0.45447255045150214
            yaw: 1.3484015369058335
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2326979290974797
          y: -0.21316905075296755
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.41861327218224
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.001583646652130427
            roll: 0.0
            pitch: 0.0
            yaw: 0.0810917390112893
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.00033679877253666585
            roll: 0.0
            pitch: 0.0
            yaw: 0.03442596029391573
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.012784662660042204
            roll: 0.0
            pitch: 0.0
            yaw: -0.16032465188940634
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01936509172671782
            roll: 0.0
            pitch: 0.0
            yaw: 0.12618433288542458
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.020911911361445434
            roll: 0.0
            pitch: 0.0
            yaw: 0.0013381699296778349
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.038708531760478365
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.006946811789340181
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08656727002131001
            roll: 0.0
            pitch: 0.0
            yaw: 0.7784498728917719
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.057988725425108995
            roll: 0.0
            pitch: 0.0
            yaw: -0.6866435355412784
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.053128317617436784
            roll: 0.0
            pitch: 0.0
            yaw: 0.49035824565585795
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05944714269431817
            roll: 0.0
            pitch: 0.0
            yaw: 0.3800923508746503
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.019491517507210912
            roll: 0.0
            pitch: 0.0
            yaw: -0.16769803056139565
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03147264770596084
            roll: 0.0
            pitch: 0.0
            yaw: -0.6042868347905302
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0008025129619116523
              y: 0.015951291292931893
              z: 0.04422744072943363
              roll: 0.4265422422898661
              pitch: -0.4697137514810678
              yaw: 1.3056308981237343
            roll: 0.4483683177453644
            pitch: -0.46247999242526977
            yaw: 1.3303070043624807
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
