scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1649044205333448
          y: -0.1661703665474964
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.20590133872313232
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0006820508383119338
            roll: 0.0
            pitch: 0.0
            yaw: -0.11298321326428726
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010941088082609948
            roll: 0.0
            pitch: 0.0
            yaw: 0.007050297894376056
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.002026839088248397
            roll: 0.0
            pitch: 0.0
            yaw: 0.10610916840324258
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.005683359214306974
            roll: 0.0
            pitch: 0.0
            yaw: 0.011726660974113207
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02321531125920781
            roll: 0.0
            pitch: 0.0
            yaw: -0.10878254847091083
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.015241290181505884
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.012606525495497664
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08167694803562513
            roll: 0.0
            pitch: 0.0
            yaw: 0.9783566192409252
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.002041161746940537
            roll: 0.0
            pitch: 0.0
            yaw: 0.24554613720328344
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05585996959131115
            roll: 0.0
            pitch: 0.0
            yaw: -0.7595574087793744
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.010964213395241854
            roll: 0.0
            pitch: 0.0
            yaw: -0.17482204290332493
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05954309377585585
            roll: 0.0
            pitch: 0.0
            yaw: -0.021707820018002755
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.09095779873728979
            roll: 0.0
            pitch: 0.0
            yaw: 0.7048203180108512
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00022214376024391703
              y: 0.013606598621655587
              z: 0.04060468385405754
              roll: 0.4259910878626664
              pitch: -0.4680830020383859
              yaw: 1.363738622263223
            roll: 0.4255261421337411
            pitch: -0.48192429789168845
            yaw: 1.32436842320585
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.29189994614541037
          y: -0.1627390038829941
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.01413944275738932
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0030974075920925277
            roll: 0.0
            pitch: 0.0
            yaw: -0.017916628740739626
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01390125471059244
            roll: 0.0
            pitch: 0.0
            yaw: 0.07988529950808465
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.022454456878364774
            roll: 0.0
            pitch: 0.0
            yaw: 0.09726336053168422
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0033226318173931353
            roll: 0.0
            pitch: 0.0
            yaw: -0.05228168368265558
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.012465956763651198
            roll: 0.0
            pitch: 0.0
            yaw: 0.07268685687996665
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04781126857981012
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.048005351010053474
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0347307351639531
            roll: 0.0
            pitch: 0.0
            yaw: 0.8384419402474708
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.06540425687195847
            roll: 0.0
            pitch: 0.0
            yaw: -0.024876688217569498
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.002262154104774247
            roll: 0.0
            pitch: 0.0
            yaw: 0.7315983593134885
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.047784586437336615
            roll: 0.0
            pitch: 0.0
            yaw: -0.13625002214807513
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.056313582224989445
            roll: 0.0
            pitch: 0.0
            yaw: -0.0032302240876038724
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.044112011450975167
            roll: 0.0
            pitch: 0.0
            yaw: -0.4090707994459213
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0017083166773256813
              y: 0.014930465265285955
              z: 0.04235765371318916
              roll: 0.44283457078738153
              pitch: -0.4523095314446207
              yaw: 1.3106191649666463
            roll: 0.4799851600481916
            pitch: -0.5061223230762766
            yaw: 1.3098521913027406
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.1484883442627803
          y: -0.24368588751959017
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.108149494473606
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.005720436802683051
            roll: 0.0
            pitch: 0.0
            yaw: 0.10382641574866752
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.02093971496261581
            roll: 0.0
            pitch: 0.0
            yaw: -0.060652316713284624
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01227189764776863
            roll: 0.0
            pitch: 0.0
            yaw: 0.04594174704740875
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0015006953876790415
            roll: 0.0
            pitch: 0.0
            yaw: -0.1543581479742851
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.015413392473178359
            roll: 0.0
            pitch: 0.0
            yaw: 0.03303301012514828
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02753862890218145
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05062840992061139
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08375528464868556
            roll: 0.0
            pitch: 0.0
            yaw: 0.5563341351328845
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09304605620387724
            roll: 0.0
            pitch: 0.0
            yaw: -0.27156571541147223
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.010352111068812064
            roll: 0.0
            pitch: 0.0
            yaw: -0.8368839432766365
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.043326734477741116
            roll: 0.0
            pitch: 0.0
            yaw: 0.5660570159798022
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07308384412401683
            roll: 0.0
            pitch: 0.0
            yaw: -0.08756754380428955
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.009423917506207316
            roll: 0.0
            pitch: 0.0
            yaw: -0.7994323124593187
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.001195141993741444
              y: 0.015496100362074557
              z: 0.04292297394210073
              roll: 0.4401541553586295
              pitch: -0.4600443475974802
              yaw: 1.291168902943039
            roll: 0.40908744421158527
            pitch: -0.45350997431623297
            yaw: 1.363153517791086
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
