scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.278054521445253
          y: -0.24195717629360078
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.19104494857520804
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.014625486873798409
            roll: 0.0
            pitch: 0.0
            yaw: -0.017498897532863045
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.013991547333302976
            roll: 0.0
            pitch: 0.0
            yaw: -0.0963760815589655
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0094772778917706
            roll: 0.0
            pitch: 0.0
            yaw: 0.033446782801443004
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02200000595854934
            roll: 0.0
            pitch: 0.0
            yaw: 0.08625795916409557
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.008508330045759124
            roll: 0.0
            pitch: 0.0
            yaw: -0.07120126420466949
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.00410535993813807
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04304552749699188
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0851019102662526
            roll: 0.0
            pitch: 0.0
            yaw: 0.9330169781785571
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08330023447777857
            roll: 0.0
            pitch: 0.0
            yaw: -0.43996281917563895
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08599687443391305
            roll: 0.0
            pitch: 0.0
            yaw: -0.7734740994672592
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0657609919205614
            roll: 0.0
            pitch: 0.0
            yaw: -0.9416520542321744
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03556778894271298
            roll: 0.0
            pitch: 0.0
            yaw: -0.5818685174358755
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08018148818677243
            roll: 0.0
            pitch: 0.0
            yaw: -0.2831608063043183
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0009065526259589393
              y: 0.015550141596711583
              z: 0.041528802106858
              roll: 0.46737591118106225
              pitch: -0.4897280696662783
              yaw: 1.3044373993799954
            roll: 0.4292658772071625
            pitch: -0.4658499439683986
            yaw: 1.3241141408734887
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.29281940229311254
          y: -0.26084644134967755
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.37624694767675526
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.006962398623749689
            roll: 0.0
            pitch: 0.0
            yaw: -0.060214573526010964
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0136486843284237
            roll: 0.0
            pitch: 0.0
            yaw: 0.07023500882119849
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01999654668134395
            roll: 0.0
            pitch: 0.0
            yaw: 0.026667733467414023
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.005258421955837964
            roll: 0.0
            pitch: 0.0
            yaw: -0.06897229108024201
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.022086471123069343
            roll: 0.0
            pitch: 0.0
            yaw: 0.08336555537209445
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03899382373997404
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.008738853213212945
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.026379899419887165
            roll: 0.0
            pitch: 0.0
            yaw: 0.07765553573857065
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.02086831442957872
            roll: 0.0
            pitch: 0.0
            yaw: -0.17402766465869002
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.000903159908106077
            roll: 0.0
            pitch: 0.0
            yaw: 0.34365890744348504
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03474213633389586
            roll: 0.0
            pitch: 0.0
            yaw: -0.8605841210085612
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08758752003749677
            roll: 0.0
            pitch: 0.0
            yaw: -0.07750959125278079
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06199254543771059
            roll: 0.0
            pitch: 0.0
            yaw: -0.96704569791164
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0019244147257113714
              y: 0.01560101292659164
              z: 0.044276484586603486
              roll: 0.4329065272972107
              pitch: -0.4930012567657125
              yaw: 1.3289719772882624
            roll: 0.4208137647880383
            pitch: -0.4787815788232512
            yaw: 1.3650948681554247
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.20095327597983836
          y: -0.27162283690041517
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.06917110393105119
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.022009388002022845
            roll: 0.0
            pitch: 0.0
            yaw: -0.12945636096099178
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.017902757721433557
            roll: 0.0
            pitch: 0.0
            yaw: 0.12168891810859617
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.020237532267719162
            roll: 0.0
            pitch: 0.0
            yaw: -0.13814999981045223
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.011869560326693708
            roll: 0.0
            pitch: 0.0
            yaw: 0.04641906075311475
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.009220201181876192
            roll: 0.0
            pitch: 0.0
            yaw: 0.05727608428959782
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.006141968076598003
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.004544517039785888
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.013629825775836601
            roll: 0.0
            pitch: 0.0
            yaw: 0.20972901725235316
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.008257083701197376
            roll: 0.0
            pitch: 0.0
            yaw: -0.698122575411591
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04699028957121812
            roll: 0.0
            pitch: 0.0
            yaw: 0.010799780519039626
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0252122035555693
            roll: 0.0
            pitch: 0.0
            yaw: 0.9814499032168766
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.014812441736499732
            roll: 0.0
            pitch: 0.0
            yaw: 0.8503744574527765
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05115474845850135
            roll: 0.0
            pitch: 0.0
            yaw: -0.37658857243018884
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0012355291081651057
              y: 0.015565733755462668
              z: 0.04099605730126986
              roll: 0.47015749583488653
              pitch: -0.5171051574086839
              yaw: 1.3565176724714192
            roll: 0.4129299338734466
            pitch: -0.5121452136350304
            yaw: 1.3673611760648037
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
