scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.28407811332585564
          y: 0.29623286601464766
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.1416032315064317
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.002922712244747081
            roll: 0.0
            pitch: 0.0
            yaw: -0.03878257350229586
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.014655250494845645
            roll: 0.0
            pitch: 0.0
            yaw: 0.14153495675068406
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.020033652552448863
            roll: 0.0
            pitch: 0.0
            yaw: -0.12451022435248707
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.015656669737815487
            roll: 0.0
            pitch: 0.0
            yaw: -0.13264652619061162
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02259297121255458
            roll: 0.0
            pitch: 0.0
            yaw: 0.16071220244851386
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0454419323465991
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.013661035055970903
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.007934418204666005
            roll: 0.0
            pitch: 0.0
            yaw: 0.705498224197243
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04206844725529266
            roll: 0.0
            pitch: 0.0
            yaw: -0.09265122007944104
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08300534159497847
            roll: 0.0
            pitch: 0.0
            yaw: -0.541771735074697
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05019547338115851
            roll: 0.0
            pitch: 0.0
            yaw: 0.24033682707857618
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.005191250799994565
            roll: 0.0
            pitch: 0.0
            yaw: 0.6500654734180622
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.012944943039461143
            roll: 0.0
            pitch: 0.0
            yaw: -0.7297590489923558
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0019845086856489025
              y: 0.016499859442472602
              z: 0.0424255092198035
              roll: 0.45026239105506416
              pitch: -0.46272242000324615
              yaw: 1.3602219883037443
            roll: 0.4464346849994324
            pitch: -0.47801791012262085
            yaw: 1.3673060112730901
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2894081971200428
          y: -0.29138341140349716
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.0601480974749955
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.020034837310720865
            roll: 0.0
            pitch: 0.0
            yaw: -0.16829362777968973
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007382397994281899
            roll: 0.0
            pitch: 0.0
            yaw: 0.0837427196572823
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.005861644183469399
            roll: 0.0
            pitch: 0.0
            yaw: -0.04701715405621715
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.020987154966275606
            roll: 0.0
            pitch: 0.0
            yaw: -0.10639797213060609
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0010372394385330837
            roll: 0.0
            pitch: 0.0
            yaw: 0.09165485183545785
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04082465638663452
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.029167056655481832
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06906207754162483
            roll: 0.0
            pitch: 0.0
            yaw: -0.9798753833039678
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09567963760769845
            roll: 0.0
            pitch: 0.0
            yaw: -0.9692629796853178
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01828335515118712
            roll: 0.0
            pitch: 0.0
            yaw: -0.4535600349636425
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0011804605132017948
            roll: 0.0
            pitch: 0.0
            yaw: -0.9591055633206644
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.02968745930063918
            roll: 0.0
            pitch: 0.0
            yaw: 0.8229008912641935
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03734117225913064
            roll: 0.0
            pitch: 0.0
            yaw: 0.2894849043490313
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0012085159128553849
              y: 0.015843322750952536
              z: 0.04441060617727789
              roll: 0.41743138345094205
              pitch: -0.4931496109734284
              yaw: 1.300491067470556
            roll: 0.4490590351043353
            pitch: -0.44607547917520424
            yaw: 1.3194129191268018
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.29987768892748007
          y: 0.2584593004074555
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.5455958096765148
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.019868111579171947
            roll: 0.0
            pitch: 0.0
            yaw: 0.1435298256276018
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.016443801969188612
            roll: 0.0
            pitch: 0.0
            yaw: 0.09721140695395719
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.006416890178557816
            roll: 0.0
            pitch: 0.0
            yaw: -0.08267376150073123
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0027466472443768465
            roll: 0.0
            pitch: 0.0
            yaw: -0.1320120552429614
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01961351741492931
            roll: 0.0
            pitch: 0.0
            yaw: -0.13728537545071312
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.034447845134280425
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.014829505799302908
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04088567702138883
            roll: 0.0
            pitch: 0.0
            yaw: -0.0882826715156616
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09102569827589897
            roll: 0.0
            pitch: 0.0
            yaw: 0.6020848107166588
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04393782872853821
            roll: 0.0
            pitch: 0.0
            yaw: -0.3287100348803488
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.07982817082457312
            roll: 0.0
            pitch: 0.0
            yaw: 0.6094432481911163
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05292360561915038
            roll: 0.0
            pitch: 0.0
            yaw: 0.8014630639515083
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.017315713604931934
            roll: 0.0
            pitch: 0.0
            yaw: 0.3455034531147019
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0004834758317542563
              y: 0.015968361029896707
              z: 0.04360091529026715
              roll: 0.4161878401507106
              pitch: -0.4452468739921559
              yaw: 1.3241895226522458
            roll: 0.4643016046539229
            pitch: -0.49527253550757305
            yaw: 1.341815948936984
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
