scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.16021814544804086
          y: 0.27465652736008345
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.0514134037959337
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01639592380274278
            roll: 0.0
            pitch: 0.0
            yaw: -0.06415722056204742
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.015799559657798043
            roll: 0.0
            pitch: 0.0
            yaw: 0.06317175139399
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.012323581437049147
            roll: 0.0
            pitch: 0.0
            yaw: -0.029124194475441484
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012635163672775654
            roll: 0.0
            pitch: 0.0
            yaw: 0.018550120475550602
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0006058195662668638
            roll: 0.0
            pitch: 0.0
            yaw: -0.0530952463519392
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01172009360398793
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.011474645525661416
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.02970743047900562
            roll: 0.0
            pitch: 0.0
            yaw: 0.5924926178028507
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07971025882966845
            roll: 0.0
            pitch: 0.0
            yaw: -0.758944042269926
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02620192981381861
            roll: 0.0
            pitch: 0.0
            yaw: -0.6132981023307176
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08985884977086317
            roll: 0.0
            pitch: 0.0
            yaw: 0.7062782000067602
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08454402241760502
            roll: 0.0
            pitch: 0.0
            yaw: -0.8540235887438782
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.02621890675334196
            roll: 0.0
            pitch: 0.0
            yaw: -0.7942895435092168
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0003363198569785882
              y: 0.015591373619793703
              z: 0.04151877161902919
              roll: 0.4424636728316608
              pitch: -0.4672663915142352
              yaw: 1.3330626797653968
            roll: 0.4464813465258653
            pitch: -0.46085892371658643
            yaw: 1.3519717487901697
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.25847182551409403
          y: -0.2707923592667795
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -1.1477323340989443
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.021591918912985196
            roll: 0.0
            pitch: 0.0
            yaw: 0.10893013516726646
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0016447915881951276
            roll: 0.0
            pitch: 0.0
            yaw: -0.16817590547478717
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.008603858463003326
            roll: 0.0
            pitch: 0.0
            yaw: 0.052645271638065844
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01409897414467911
            roll: 0.0
            pitch: 0.0
            yaw: -0.1003349700351502
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.011814661922534525
            roll: 0.0
            pitch: 0.0
            yaw: 0.13678903303787016
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.029396614142599697
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.023338697233435214
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05100377843953582
            roll: 0.0
            pitch: 0.0
            yaw: -0.29849665772045475
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04306459940617874
            roll: 0.0
            pitch: 0.0
            yaw: -0.37272624979152735
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05427107414266302
            roll: 0.0
            pitch: 0.0
            yaw: -0.6305920899900628
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.050974293616578015
            roll: 0.0
            pitch: 0.0
            yaw: 0.3811184245284187
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0268721446387008
            roll: 0.0
            pitch: 0.0
            yaw: 0.4605537218858924
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.007979665282239812
            roll: 0.0
            pitch: 0.0
            yaw: -0.8132584212217228
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0017287493086719464
              y: 0.017128786954486108
              z: 0.0421593200633382
              roll: 0.4654027581411776
              pitch: -0.4698032532552458
              yaw: 1.321073294793164
            roll: 0.42018390623491175
            pitch: -0.5027052571444388
            yaw: 1.3519633543131595
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2385844740413682
          y: 0.23956649453750495
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.1699073006795846
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.00374404988492261
            roll: 0.0
            pitch: 0.0
            yaw: -0.17070360764291892
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01967493679641763
            roll: 0.0
            pitch: 0.0
            yaw: 0.018907404289307123
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.009969342797240944
            roll: 0.0
            pitch: 0.0
            yaw: -0.01977617198073839
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.015627734788507007
            roll: 0.0
            pitch: 0.0
            yaw: 0.11132555036793307
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.019518360046908517
            roll: 0.0
            pitch: 0.0
            yaw: -0.1310469756492859
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0064053332587497985
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.007815386553169046
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.020801114766082707
            roll: 0.0
            pitch: 0.0
            yaw: 0.4965936409629683
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08219803333494702
            roll: 0.0
            pitch: 0.0
            yaw: 0.9497900552934873
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06671698942669185
            roll: 0.0
            pitch: 0.0
            yaw: -0.0384380967615896
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.01724938115874386
            roll: 0.0
            pitch: 0.0
            yaw: -0.7763431284295764
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.002855344192845735
            roll: 0.0
            pitch: 0.0
            yaw: 0.0986558528338437
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.015581820720362322
            roll: 0.0
            pitch: 0.0
            yaw: -0.5534551533670902
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0007279643509890688
              y: 0.016138694225233376
              z: 0.04339252713623362
              roll: 0.4058906321587695
              pitch: -0.44441253629059596
              yaw: 1.3644173435227387
            roll: 0.4126647763877125
            pitch: -0.4611914624218859
            yaw: 1.3327822590384384
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
