scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.25526584353615794
          y: -0.2875381051648395
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.35319817150290245
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 6.914299047200423e-05
            roll: 0.0
            pitch: 0.0
            yaw: 0.07304632525165314
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.00747198698045334
            roll: 0.0
            pitch: 0.0
            yaw: -0.14360510219366293
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.011358059078710535
            roll: 0.0
            pitch: 0.0
            yaw: 0.11022522939852891
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01860605844275116
            roll: 0.0
            pitch: 0.0
            yaw: 0.10570612021032494
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.013626097662164258
            roll: 0.0
            pitch: 0.0
            yaw: 0.14176404601556508
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02122994772594672
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.023215002325744735
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.03386304849394493
            roll: 0.0
            pitch: 0.0
            yaw: -0.15579082404501676
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.048421711531327793
            roll: 0.0
            pitch: 0.0
            yaw: -0.707519612126054
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.018517435357314663
            roll: 0.0
            pitch: 0.0
            yaw: 0.3245040308191507
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.036250218091022135
            roll: 0.0
            pitch: 0.0
            yaw: -0.3681518754024794
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0030277199432615365
            roll: 0.0
            pitch: 0.0
            yaw: -1.0082961275957483
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.025007896183601136
            roll: 0.0
            pitch: 0.0
            yaw: 0.6795794852865347
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0018824771373871726
              y: 0.014051525239709175
              z: 0.04263308560130804
              roll: 0.40462051890474643
              pitch: -0.5226199269213664
              yaw: 1.3103464462297636
            roll: 0.4767557874740067
            pitch: -0.45642125681218604
            yaw: 1.355121433492184
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.23726224244259764
          y: -0.2934312177183657
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -1.0691367669630814
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.021655529617362855
            roll: 0.0
            pitch: 0.0
            yaw: 0.16578003873245162
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.00025516739898215693
            roll: 0.0
            pitch: 0.0
            yaw: -0.1597871872839538
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.017614468076176105
            roll: 0.0
            pitch: 0.0
            yaw: -0.09407571615292257
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.020804831179608456
            roll: 0.0
            pitch: 0.0
            yaw: -0.11186882840107408
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02236902658034947
            roll: 0.0
            pitch: 0.0
            yaw: -0.16632660240576008
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0010426148671799015
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04432403817235011
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07260809484383388
            roll: 0.0
            pitch: 0.0
            yaw: 0.5631496889330772
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07439280516462499
            roll: 0.0
            pitch: 0.0
            yaw: 0.8398359832334163
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07537908557216094
            roll: 0.0
            pitch: 0.0
            yaw: -0.9287675598794409
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.014526300774407544
            roll: 0.0
            pitch: 0.0
            yaw: -0.7281362091174179
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.029197895198768947
            roll: 0.0
            pitch: 0.0
            yaw: 0.1225743603087579
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08486413913819205
            roll: 0.0
            pitch: 0.0
            yaw: 0.0432286658083707
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0012404026670490191
              y: 0.016790241593574923
              z: 0.04074644149271649
              roll: 0.41582817102793507
              pitch: -0.5108131273272981
              yaw: 1.3399755813149572
            roll: 0.4061210061108029
            pitch: -0.5199192843287526
            yaw: 1.3203218591722448
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.26641160665843444
          y: -0.1896553672702896
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.519080071186921
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0032551147145074844
            roll: 0.0
            pitch: 0.0
            yaw: 0.15947795887563954
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.016267380573455656
            roll: 0.0
            pitch: 0.0
            yaw: -0.12038898257337334
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.003247998849722388
            roll: 0.0
            pitch: 0.0
            yaw: 0.060535519129476606
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.005180655731381271
            roll: 0.0
            pitch: 0.0
            yaw: -0.09939050402590871
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.02018617645558109
            roll: 0.0
            pitch: 0.0
            yaw: -0.0441754960238564
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04867916715265844
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.020118674334503067
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07226833897232471
            roll: 0.0
            pitch: 0.0
            yaw: 0.12584350079343243
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.013226952120672292
            roll: 0.0
            pitch: 0.0
            yaw: -0.69637763205194
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.003241913025861312
            roll: 0.0
            pitch: 0.0
            yaw: -1.0070303928448778
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04793800110821403
            roll: 0.0
            pitch: 0.0
            yaw: -0.7385920917114712
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.016622502386248073
            roll: 0.0
            pitch: 0.0
            yaw: 0.13663496607700854
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03935715823151452
            roll: 0.0
            pitch: 0.0
            yaw: -0.7073661445970805
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0009267728649942084
              y: 0.013988680529977858
              z: 0.04277827447191257
              roll: 0.45787371616717626
              pitch: -0.5115961915716278
              yaw: 1.3053001586377337
            roll: 0.46970071861266643
            pitch: -0.47654519961045144
            yaw: 1.3043704541101648
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
