scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2047635012016087
          y: 0.2867113362037888
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.052883395239796
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.002297826933453321
            roll: 0.0
            pitch: 0.0
            yaw: 0.07701568087597038
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.011799572549342573
            roll: 0.0
            pitch: 0.0
            yaw: 0.13407446457861655
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.015100858647603368
            roll: 0.0
            pitch: 0.0
            yaw: 0.16966105192277492
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.00388083177667143
            roll: 0.0
            pitch: 0.0
            yaw: -0.13338578961600814
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.023053168669194664
            roll: 0.0
            pitch: 0.0
            yaw: -0.13289055930652569
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05181454878658966
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.046823286873334716
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.03680358955864485
            roll: 0.0
            pitch: 0.0
            yaw: 0.6799899779007739
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.014952678502722874
            roll: 0.0
            pitch: 0.0
            yaw: 0.2794369876697016
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.022423534300525905
            roll: 0.0
            pitch: 0.0
            yaw: -0.7391347847141791
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.04211144832059544
            roll: 0.0
            pitch: 0.0
            yaw: 0.18118415213016492
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0896586657876811
            roll: 0.0
            pitch: 0.0
            yaw: 0.12690910544273337
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.016230841562221807
            roll: 0.0
            pitch: 0.0
            yaw: 0.6764782693848266
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.001155991782679779
              y: 0.014702429945507293
              z: 0.044022971948149685
              roll: 0.43697318807897495
              pitch: -0.4860350796014262
              yaw: 1.3015742874412022
            roll: 0.44390705593558855
            pitch: -0.45898655680544376
            yaw: 1.3000237334663411
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.21086892557730466
          y: 0.2631303546584299
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.1940831639066278
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.008892299551294156
            roll: 0.0
            pitch: 0.0
            yaw: 0.06872514412844535
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.020873193100852547
            roll: 0.0
            pitch: 0.0
            yaw: 0.08024059180801457
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0021850585460372295
            roll: 0.0
            pitch: 0.0
            yaw: 0.03716361233984264
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.021594569724379196
            roll: 0.0
            pitch: 0.0
            yaw: 0.11786468615703
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.022087206696316586
            roll: 0.0
            pitch: 0.0
            yaw: 0.16265478766425107
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0003810278405317613
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.010741527620414443
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.010662906076948322
            roll: 0.0
            pitch: 0.0
            yaw: -0.28598347810458236
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04289980473342077
            roll: 0.0
            pitch: 0.0
            yaw: -0.6706856238618053
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03551872686975555
            roll: 0.0
            pitch: 0.0
            yaw: -0.3844465335963304
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0642918414545147
            roll: 0.0
            pitch: 0.0
            yaw: 0.06638254183178605
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05423072554078285
            roll: 0.0
            pitch: 0.0
            yaw: 0.5362564262117426
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.005389111395516136
            roll: 0.0
            pitch: 0.0
            yaw: -0.7452875314297258
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0005355838889709533
              y: 0.017323387321089734
              z: 0.041132223402484
              roll: 0.4504678833305507
              pitch: -0.4801764232640207
              yaw: 1.3166937052981418
            roll: 0.4804159929804158
            pitch: -0.5075530146191877
            yaw: 1.3178333147795518
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.22587004856825305
          y: 0.22337420582527473
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.3536957081509944
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.013004691694268747
            roll: 0.0
            pitch: 0.0
            yaw: 0.10510257758066227
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.018159198202105042
            roll: 0.0
            pitch: 0.0
            yaw: 0.0030948724589942578
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.003870593589985854
            roll: 0.0
            pitch: 0.0
            yaw: 0.09483089952995077
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.014047113584987274
            roll: 0.0
            pitch: 0.0
            yaw: 0.13861665800805434
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0019668512050863007
            roll: 0.0
            pitch: 0.0
            yaw: 0.00871506399761146
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.047534623513032614
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.015395472349893205
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07877503465815058
            roll: 0.0
            pitch: 0.0
            yaw: 0.2456542762175946
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09318628013936092
            roll: 0.0
            pitch: 0.0
            yaw: 0.35913543796483727
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.050566145982843536
            roll: 0.0
            pitch: 0.0
            yaw: -0.38882744633626076
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.06751170651809371
            roll: 0.0
            pitch: 0.0
            yaw: -0.2707264636413902
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0008863598493652897
            roll: 0.0
            pitch: 0.0
            yaw: 1.0104423908429652
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.018179530027013543
            roll: 0.0
            pitch: 0.0
            yaw: 0.1411881076684014
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0009486338381184526
              y: 0.01495683789789419
              z: 0.041898397323226255
              roll: 0.4153853504560767
              pitch: -0.45141960312726903
              yaw: 1.2993256537801052
            roll: 0.4699660762282341
            pitch: -0.4632231475743076
            yaw: 1.3062968327230016
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
