scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.22808202782662726
          y: 0.2938181758636533
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.1477193865170117
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01212800322861998
            roll: 0.0
            pitch: 0.0
            yaw: 0.001875816531227259
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.010681846108145017
            roll: 0.0
            pitch: 0.0
            yaw: -0.12064989508752497
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.006422914456574421
            roll: 0.0
            pitch: 0.0
            yaw: -0.06283969665376074
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.009101867427035495
            roll: 0.0
            pitch: 0.0
            yaw: -0.12821666585251595
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.012552229112573712
            roll: 0.0
            pitch: 0.0
            yaw: 0.05740393072138164
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01622753927666727
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.015011037068425881
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06905199617511058
            roll: 0.0
            pitch: 0.0
            yaw: 0.9690572308580212
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07607467482559188
            roll: 0.0
            pitch: 0.0
            yaw: 0.9249709120328766
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04306805832047009
            roll: 0.0
            pitch: 0.0
            yaw: 0.05811546337262463
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04974614810821942
            roll: 0.0
            pitch: 0.0
            yaw: 0.7705424401716099
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03046241435480082
            roll: 0.0
            pitch: 0.0
            yaw: -1.0445223861933408
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.028497517333043343
            roll: 0.0
            pitch: 0.0
            yaw: 0.7723025160604529
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0017401302776657197
              y: 0.015525058843185393
              z: 0.04370108203507153
              roll: 0.47105797466476196
              pitch: -0.5204546292346746
              yaw: 1.3519494284424418
            roll: 0.4572203416393828
            pitch: -0.44647088657334394
            yaw: 1.2906009860471759
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2587681713016506
          y: -0.23623911367429135
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.5691113256448146
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.009406642625524625
            roll: 0.0
            pitch: 0.0
            yaw: -0.17245747889430746
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01781703575096128
            roll: 0.0
            pitch: 0.0
            yaw: -0.010147111799529124
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.010720292705817872
            roll: 0.0
            pitch: 0.0
            yaw: 0.0115062832409987
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.017785911797346732
            roll: 0.0
            pitch: 0.0
            yaw: -0.08548501571439533
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.004707331710220784
            roll: 0.0
            pitch: 0.0
            yaw: 0.0629520321056593
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.007074883578104665
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0377109957778303
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.010406666207267698
            roll: 0.0
            pitch: 0.0
            yaw: 0.6915260255651534
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.030687069513434764
            roll: 0.0
            pitch: 0.0
            yaw: 0.3162480567608146
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.061181801625693095
            roll: 0.0
            pitch: 0.0
            yaw: -0.2627777770012725
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0347060439890009
            roll: 0.0
            pitch: 0.0
            yaw: -0.9576650243391124
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.019558959524861294
            roll: 0.0
            pitch: 0.0
            yaw: -0.1722875625525212
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08713846884066588
            roll: 0.0
            pitch: 0.0
            yaw: 0.20012778044364787
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0019136241096592635
              y: 0.016002853631935227
              z: 0.044330325112965425
              roll: 0.46449192413326984
              pitch: -0.48597831291515675
              yaw: 1.3648327346722642
            roll: 0.427176170648982
            pitch: -0.5106774568841467
            yaw: 1.307535937574914
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.29139116820899735
          y: -0.27891818287682657
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.1459011858507653
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0020352452356842445
            roll: 0.0
            pitch: 0.0
            yaw: -0.04791711469196905
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01690638338428169
            roll: 0.0
            pitch: 0.0
            yaw: 0.14076767290857523
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.017986022344732996
            roll: 0.0
            pitch: 0.0
            yaw: -0.037603446982864525
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02059930209584307
            roll: 0.0
            pitch: 0.0
            yaw: 0.1369110259592502
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0013276704451291484
            roll: 0.0
            pitch: 0.0
            yaw: -0.11012617113787952
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05189172481085154
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0052059357975111145
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07723002508114031
            roll: 0.0
            pitch: 0.0
            yaw: -0.19160279521276347
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.015532223844710383
            roll: 0.0
            pitch: 0.0
            yaw: 0.12586360909915273
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.01404565934091491
            roll: 0.0
            pitch: 0.0
            yaw: 0.6101626366803523
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.005639577224210782
            roll: 0.0
            pitch: 0.0
            yaw: -0.47985255734291066
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.04811856588432541
            roll: 0.0
            pitch: 0.0
            yaw: 0.7570613190173838
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.00030827411456717246
            roll: 0.0
            pitch: 0.0
            yaw: -0.7389304529588697
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0014073722597168384
              y: 0.013923697692145345
              z: 0.0432440599532325
              roll: 0.4756905897235757
              pitch: -0.503028479497046
              yaw: 1.3696287302036552
            roll: 0.41711492418138785
            pitch: -0.5117187439500822
            yaw: 1.3116640340760073
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
