scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2732220559582438
          y: -0.2526921490547956
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.3264236785601335
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01620278238331934
            roll: 0.0
            pitch: 0.0
            yaw: -0.16664256622308743
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.011608492562448747
            roll: 0.0
            pitch: 0.0
            yaw: -0.13460120676692816
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01534843394060236
            roll: 0.0
            pitch: 0.0
            yaw: 0.02047068637909416
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.020663370158562913
            roll: 0.0
            pitch: 0.0
            yaw: -0.07041569502426898
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.010548430682547863
            roll: 0.0
            pitch: 0.0
            yaw: -0.11467798006888985
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05165751130676873
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.010927183805529844
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.09522806393577371
            roll: 0.0
            pitch: 0.0
            yaw: -0.06568305685169884
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07919661583823345
            roll: 0.0
            pitch: 0.0
            yaw: 0.44286068106035303
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.005595193287994793
            roll: 0.0
            pitch: 0.0
            yaw: -0.3739007095819442
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0031336491146966017
            roll: 0.0
            pitch: 0.0
            yaw: 0.32397150821300835
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.01357219290943179
            roll: 0.0
            pitch: 0.0
            yaw: -0.1546317030662624
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.018977407275341238
            roll: 0.0
            pitch: 0.0
            yaw: 0.12817447321555342
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.000543638636428177
              y: 0.016409047977822906
              z: 0.04273649167116918
              roll: 0.45141001363926575
              pitch: -0.47462605568606914
              yaw: 1.3238519262186523
            roll: 0.42244019441480896
            pitch: -0.4964253809909725
            yaw: 1.3543494476998514
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2421488920135186
          y: 0.2542255294490658
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.5176512838259826
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.014785948855115624
            roll: 0.0
            pitch: 0.0
            yaw: 0.16278192160107696
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.004265888635953119
            roll: 0.0
            pitch: 0.0
            yaw: 0.14267806756780954
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.018162712649504798
            roll: 0.0
            pitch: 0.0
            yaw: 0.018901368202121738
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0036888473941015035
            roll: 0.0
            pitch: 0.0
            yaw: -0.1690451834035507
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.006536446269252701
            roll: 0.0
            pitch: 0.0
            yaw: -0.07279919284552719
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.053311793542643926
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.012033772052298608
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.03123907380840088
            roll: 0.0
            pitch: 0.0
            yaw: 0.038294777741999075
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04062937631110916
            roll: 0.0
            pitch: 0.0
            yaw: -0.6709555887791314
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.019180516424216032
            roll: 0.0
            pitch: 0.0
            yaw: 0.16667759598122722
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.013979706531067185
            roll: 0.0
            pitch: 0.0
            yaw: -0.3587382211700789
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06721049996488862
            roll: 0.0
            pitch: 0.0
            yaw: -0.4745040568654164
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03058487807828794
            roll: 0.0
            pitch: 0.0
            yaw: 0.3854643854742441
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00111518045568218
              y: 0.014926470607414078
              z: 0.044266013801845715
              roll: 0.4751347039616324
              pitch: -0.5184871267931936
              yaw: 1.3653486154284677
            roll: 0.444868807846688
            pitch: -0.46406938245289214
            yaw: 1.294723544532397
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.17292875352701617
          y: -0.2838580329509354
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -1.1340548567494961
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.013299174896411274
            roll: 0.0
            pitch: 0.0
            yaw: -0.06569219573308409
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01915160046290526
            roll: 0.0
            pitch: 0.0
            yaw: -0.02279157618879782
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01833588843304389
            roll: 0.0
            pitch: 0.0
            yaw: 0.16908081875264586
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.009565960500312977
            roll: 0.0
            pitch: 0.0
            yaw: 0.1372761374041982
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.021752032659230293
            roll: 0.0
            pitch: 0.0
            yaw: 0.07976666147268818
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03854582519538535
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.004963622388752302
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.054828429357006346
            roll: 0.0
            pitch: 0.0
            yaw: 0.9528295297710838
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07112676372994997
            roll: 0.0
            pitch: 0.0
            yaw: -0.20757846710193328
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07392050800529029
            roll: 0.0
            pitch: 0.0
            yaw: 0.21481872505623767
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.054929286139204156
            roll: 0.0
            pitch: 0.0
            yaw: 0.8528418194257881
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0063023004928797755
            roll: 0.0
            pitch: 0.0
            yaw: 0.44790021960342274
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.006708066751653405
            roll: 0.0
            pitch: 0.0
            yaw: 0.7470682781282392
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -6.0614622128344134e-05
              y: 0.0135339990878306
              z: 0.042199772295788716
              roll: 0.46855329016434705
              pitch: -0.4664085429086132
              yaw: 1.2911953382487888
            roll: 0.4685055642492556
            pitch: -0.45979847568882215
            yaw: 1.2933232311766985
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
