scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1835288862618758
          y: 0.2661090677604658
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.341936145262371
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.005095416527173307
            roll: 0.0
            pitch: 0.0
            yaw: -0.12242815120122161
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.02067525816285366
            roll: 0.0
            pitch: 0.0
            yaw: -0.17425311205970703
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.009330151884332373
            roll: 0.0
            pitch: 0.0
            yaw: -0.018285626175762376
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.015005010460209738
            roll: 0.0
            pitch: 0.0
            yaw: 0.10487617672020566
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.019016283360718256
            roll: 0.0
            pitch: 0.0
            yaw: 0.07416423601276595
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0025558342612340273
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0014306709432688747
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.013757724090486714
            roll: 0.0
            pitch: 0.0
            yaw: 0.09125979285143004
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07629692426843482
            roll: 0.0
            pitch: 0.0
            yaw: -0.8728603344767892
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0035244415456599926
            roll: 0.0
            pitch: 0.0
            yaw: 0.7056026608454731
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.013725636330488442
            roll: 0.0
            pitch: 0.0
            yaw: 0.40708805875277543
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03799827032576544
            roll: 0.0
            pitch: 0.0
            yaw: -0.08542294693394292
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05114209880889151
            roll: 0.0
            pitch: 0.0
            yaw: 0.45596374481062996
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001119743842700797
              y: 0.016423909681227467
              z: 0.042929516711867066
              roll: 0.42609634118784184
              pitch: -0.4829424325638193
              yaw: 1.3274990339734851
            roll: 0.4505535827697313
            pitch: -0.4789019060397929
            yaw: 1.3554419428219808
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.24745584967177559
          y: -0.19549591246183357
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.412067660769422
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.009486296641548098
            roll: 0.0
            pitch: 0.0
            yaw: 0.08815821575421051
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.020814495896432663
            roll: 0.0
            pitch: 0.0
            yaw: -0.030257910461763488
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0010655448997247685
            roll: 0.0
            pitch: 0.0
            yaw: -0.1310982445085906
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.013952054363212917
            roll: 0.0
            pitch: 0.0
            yaw: 0.06572948515411015
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.018737830620377188
            roll: 0.0
            pitch: 0.0
            yaw: 0.09561404130945378
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.028202213462770347
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.051303562618482276
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.02048213767663211
            roll: 0.0
            pitch: 0.0
            yaw: -0.04514138780006194
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08563654623071196
            roll: 0.0
            pitch: 0.0
            yaw: 0.5012223635139772
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.013298511625212825
            roll: 0.0
            pitch: 0.0
            yaw: 0.13984947207110698
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03766747221046772
            roll: 0.0
            pitch: 0.0
            yaw: 0.5010660459232064
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.083188628361853
            roll: 0.0
            pitch: 0.0
            yaw: -0.21006065250634864
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05958700769478848
            roll: 0.0
            pitch: 0.0
            yaw: 0.31798621048939224
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0009494993802538335
              y: 0.01526295068743995
              z: 0.04414493534948347
              roll: 0.40608711820041327
              pitch: -0.5056412532845037
              yaw: 1.3551620275759841
            roll: 0.45022981999729333
            pitch: -0.5157111009207553
            yaw: 1.3687249927964782
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2560671051829898
          y: -0.23225278187880638
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.8187425864736402
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.001939457452633457
            roll: 0.0
            pitch: 0.0
            yaw: 0.055076000760784005
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008648637998181725
            roll: 0.0
            pitch: 0.0
            yaw: -0.02932805275014766
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.019421663726460467
            roll: 0.0
            pitch: 0.0
            yaw: 0.1303846955555671
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02265401804591017
            roll: 0.0
            pitch: 0.0
            yaw: 0.08858285894409978
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.014020562624632629
            roll: 0.0
            pitch: 0.0
            yaw: -0.006345256538703409
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.015502524476970661
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.018398068951857742
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07839941861756382
            roll: 0.0
            pitch: 0.0
            yaw: -1.0236012872381934
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.03284995206057825
            roll: 0.0
            pitch: 0.0
            yaw: -0.2663490732841487
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.010335324518860989
            roll: 0.0
            pitch: 0.0
            yaw: -0.6074224976898013
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.015310138524209552
            roll: 0.0
            pitch: 0.0
            yaw: -0.041196132308357836
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06180266621702215
            roll: 0.0
            pitch: 0.0
            yaw: 0.6689006691721486
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.017278570126767645
            roll: 0.0
            pitch: 0.0
            yaw: -0.24564576772016788
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.001424857439386872
              y: 0.014787639092966109
              z: 0.042623575565398295
              roll: 0.4363166060024175
              pitch: -0.47916635588616624
              yaw: 1.333816958523659
            roll: 0.4804696938311743
            pitch: -0.4599143922498322
            yaw: 1.3648778963701045
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
