scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2599803980509715
          y: -0.18412095166467377
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.590934574480026
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0207061677145984
            roll: 0.0
            pitch: 0.0
            yaw: 0.09801343473243007
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01719457433657071
            roll: 0.0
            pitch: 0.0
            yaw: -0.11403502850730693
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.013176004144383253
            roll: 0.0
            pitch: 0.0
            yaw: 0.15149110066994015
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.019019321137883224
            roll: 0.0
            pitch: 0.0
            yaw: -0.16689737347986033
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0040743501264411605
            roll: 0.0
            pitch: 0.0
            yaw: 0.005248914353241152
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05410623524109897
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.020281487886638222
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08267189913903877
            roll: 0.0
            pitch: 0.0
            yaw: -0.2134314572690843
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09104489639313659
            roll: 0.0
            pitch: 0.0
            yaw: 0.7959773722976136
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.005219089786563227
            roll: 0.0
            pitch: 0.0
            yaw: -0.5055439595866953
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0027373645000730584
            roll: 0.0
            pitch: 0.0
            yaw: 0.890015106580651
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06586404596744361
            roll: 0.0
            pitch: 0.0
            yaw: 1.0176896319561617
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.081386812617991
            roll: 0.0
            pitch: 0.0
            yaw: -0.9816596615984702
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0007826266347207196
              y: 0.014497635471483975
              z: 0.040716962487830126
              roll: 0.4262951846991032
              pitch: -0.4745278091550821
              yaw: 1.325245617386568
            roll: 0.4411090861029543
            pitch: -0.4704652505571321
            yaw: 1.316906317425634
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2763006394104707
          y: 0.22643543222283896
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.7479624793691277
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.02079300471312538
            roll: 0.0
            pitch: 0.0
            yaw: -0.11056464667442409
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007718529867149458
            roll: 0.0
            pitch: 0.0
            yaw: -0.10150286449821957
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.003069243842032443
            roll: 0.0
            pitch: 0.0
            yaw: -0.04693429656540157
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.008805355926210942
            roll: 0.0
            pitch: 0.0
            yaw: -0.11714599236499208
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.006320488329876712
            roll: 0.0
            pitch: 0.0
            yaw: -0.06448090241396412
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.003545802383137786
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.003479428154692772
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08076163199394132
            roll: 0.0
            pitch: 0.0
            yaw: 0.2923985799213171
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.034952661448251765
            roll: 0.0
            pitch: 0.0
            yaw: 1.0295202579860214
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03645075498963471
            roll: 0.0
            pitch: 0.0
            yaw: -0.08720743750596671
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06131694589180617
            roll: 0.0
            pitch: 0.0
            yaw: -0.4492235817872241
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05411465570390886
            roll: 0.0
            pitch: 0.0
            yaw: -0.9106909287523953
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.09034763391033607
            roll: 0.0
            pitch: 0.0
            yaw: 0.09564240963782655
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0009474083886977769
              y: 0.016353675391769587
              z: 0.0423967947184145
              roll: 0.46191873329526617
              pitch: -0.45639254244757793
              yaw: 1.2904088698886684
            roll: 0.44789147550247094
            pitch: -0.4581183487830127
            yaw: 1.363204756835788
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.19433332127893685
          y: -0.2937691841248887
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -1.129982649263388
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.013426443197251878
            roll: 0.0
            pitch: 0.0
            yaw: 0.09259255167304159
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01941165003377603
            roll: 0.0
            pitch: 0.0
            yaw: -0.10295929684691109
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.014625290898199333
            roll: 0.0
            pitch: 0.0
            yaw: 0.16864002079052814
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.018819719016611385
            roll: 0.0
            pitch: 0.0
            yaw: -0.1285073630557227
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0215399132505604
            roll: 0.0
            pitch: 0.0
            yaw: -0.07651362628947429
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04199644750458684
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.029945924399756286
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.04423860042838576
            roll: 0.0
            pitch: 0.0
            yaw: 0.34372213656629635
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.03923648843000188
            roll: 0.0
            pitch: 0.0
            yaw: 0.04446266930140008
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06414511216209674
            roll: 0.0
            pitch: 0.0
            yaw: 0.10046756531836198
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.051367690193643775
            roll: 0.0
            pitch: 0.0
            yaw: 0.9428417442784924
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05058370955388214
            roll: 0.0
            pitch: 0.0
            yaw: 0.06549967126930367
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06212498681599964
            roll: 0.0
            pitch: 0.0
            yaw: -0.6245655275570372
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0017590842739496596
              y: 0.016941216311175546
              z: 0.04359692641156869
              roll: 0.43298442083684663
              pitch: -0.48893687231703864
              yaw: 1.2913767507641627
            roll: 0.45611180204964596
            pitch: -0.5097492917356377
            yaw: 1.3453617329819978
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
