scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2379216814064573
          y: -0.2602843984141544
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.167037077693892
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01510430946568106
            roll: 0.0
            pitch: 0.0
            yaw: -0.1259804006371236
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.02130627496613137
            roll: 0.0
            pitch: 0.0
            yaw: 0.07021711922045581
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.006005859993391524
            roll: 0.0
            pitch: 0.0
            yaw: 0.1448097155393674
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012307151347792788
            roll: 0.0
            pitch: 0.0
            yaw: -0.08105822579654329
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.008938915300470498
            roll: 0.0
            pitch: 0.0
            yaw: -0.15490842607326466
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03517320624142495
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.026018553613824928
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08220843853214782
            roll: 0.0
            pitch: 0.0
            yaw: -0.06666696470465361
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05428884931785449
            roll: 0.0
            pitch: 0.0
            yaw: -0.5253027854462358
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08265485021459604
            roll: 0.0
            pitch: 0.0
            yaw: -0.7120839941093107
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09146867254178132
            roll: 0.0
            pitch: 0.0
            yaw: 0.4246306518090426
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05432341575521918
            roll: 0.0
            pitch: 0.0
            yaw: 0.3677308002046069
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.09406291138113457
            roll: 0.0
            pitch: 0.0
            yaw: -0.5910637975691343
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0019111029712591647
              y: 0.014308456261724452
              z: 0.044014884799017925
              roll: 0.4124367207987507
              pitch: -0.4783399086762001
              yaw: 1.2977558991281886
            roll: 0.45057459843693315
            pitch: -0.5192291663344317
            yaw: 1.3381419434270483
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.12534847642298882
          y: 0.2922171191682346
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.1971070819022014
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.010408972989898055
            roll: 0.0
            pitch: 0.0
            yaw: -0.05617844521814065
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.02077312075241379
            roll: 0.0
            pitch: 0.0
            yaw: 0.17432841980754893
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.012483172350670264
            roll: 0.0
            pitch: 0.0
            yaw: -0.03272223765490623
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.013053829651600866
            roll: 0.0
            pitch: 0.0
            yaw: 0.16736554684629312
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.009028698890076278
            roll: 0.0
            pitch: 0.0
            yaw: -0.11446043068702941
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04809427026733963
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.019734343808614364
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.009078800257393979
            roll: 0.0
            pitch: 0.0
            yaw: 0.9910708806220507
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.044496599171027294
            roll: 0.0
            pitch: 0.0
            yaw: -0.24715929742703358
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0019747558536304527
            roll: 0.0
            pitch: 0.0
            yaw: -0.9469462265492229
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06150082621761622
            roll: 0.0
            pitch: 0.0
            yaw: 0.7088554960448608
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.02130385247974781
            roll: 0.0
            pitch: 0.0
            yaw: -0.055220672660661
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0615585268990091
            roll: 0.0
            pitch: 0.0
            yaw: -0.9666824467591013
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0008897487862462041
              y: 0.014508371982758134
              z: 0.04396931650079509
              roll: 0.4121378877272195
              pitch: -0.48382754633877445
              yaw: 1.3118040113638494
            roll: 0.40382491091000433
            pitch: -0.5050581751580215
            yaw: 1.3194338980380733
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2135193153460126
          y: 0.29144693781669745
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.527134044063078
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.016851215113958467
            roll: 0.0
            pitch: 0.0
            yaw: -0.015901832521258485
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.014057004942363026
            roll: 0.0
            pitch: 0.0
            yaw: -0.08948466074769908
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.020332163629934973
            roll: 0.0
            pitch: 0.0
            yaw: 0.07623154478501831
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.010393402817270105
            roll: 0.0
            pitch: 0.0
            yaw: -0.14797317349897027
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.018374493140110762
            roll: 0.0
            pitch: 0.0
            yaw: -0.10984075346832849
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.043307004856719136
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03139775853836988
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.01950200421744895
            roll: 0.0
            pitch: 0.0
            yaw: 0.4270664609695738
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.036905578531299804
            roll: 0.0
            pitch: 0.0
            yaw: 0.08179802318865081
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06648386222737075
            roll: 0.0
            pitch: 0.0
            yaw: 0.8682279897250964
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08585068294595644
            roll: 0.0
            pitch: 0.0
            yaw: -0.9275941074106577
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06699759933495701
            roll: 0.0
            pitch: 0.0
            yaw: -1.0149896929891407
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07419173188564533
            roll: 0.0
            pitch: 0.0
            yaw: -0.0775461956188852
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0016962883052903431
              y: 0.014125199092949587
              z: 0.041357746256120397
              roll: 0.4806359519647755
              pitch: -0.5189538735750249
              yaw: 1.3327026713063825
            roll: 0.4405186074519535
            pitch: -0.4435023512411965
            yaw: 1.2935822204134058
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
