scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.23983829034035584
          y: 0.2661972390972644
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.267615886614541
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0038632090696845284
            roll: 0.0
            pitch: 0.0
            yaw: -0.10031821226452162
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.00675120644988742
            roll: 0.0
            pitch: 0.0
            yaw: 0.057343024019444605
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.011181968702296681
            roll: 0.0
            pitch: 0.0
            yaw: 0.017871768981890496
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.00597704487016313
            roll: 0.0
            pitch: 0.0
            yaw: 0.04546942160328271
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01928629849865168
            roll: 0.0
            pitch: 0.0
            yaw: -0.04510461466709126
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.037332162063657325
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.048153753017194836
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.06161680135061512
            roll: 0.0
            pitch: 0.0
            yaw: 0.6734565983816696
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07654462214756035
            roll: 0.0
            pitch: 0.0
            yaw: 0.7588406770403295
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09451787900586603
            roll: 0.0
            pitch: 0.0
            yaw: 0.37032522545297897
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09429458300230481
            roll: 0.0
            pitch: 0.0
            yaw: 0.2701141365867268
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.03351408910604951
            roll: 0.0
            pitch: 0.0
            yaw: 0.527792469503439
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08954898413636159
            roll: 0.0
            pitch: 0.0
            yaw: -0.11144050676353057
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0004130894419656049
              y: 0.015554594107538662
              z: 0.040710629032074154
              roll: 0.43889303693468507
              pitch: -0.5032172364060469
              yaw: 1.3655800832536253
            roll: 0.43792587426698787
            pitch: -0.4695446764970934
            yaw: 1.3335346011783826
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.22125685210842114
          y: 0.24689156476563417
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.4945542101815734
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01614578684564396
            roll: 0.0
            pitch: 0.0
            yaw: 0.1656696288993288
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.021151287906868894
            roll: 0.0
            pitch: 0.0
            yaw: -0.11475227367617824
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.007099494608761775
            roll: 0.0
            pitch: 0.0
            yaw: -0.10002998262701408
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.016904826000986355
            roll: 0.0
            pitch: 0.0
            yaw: -0.10623207773335183
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.006726752666869305
            roll: 0.0
            pitch: 0.0
            yaw: 0.1136857968520728
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.002488359930199413
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0004755363025204587
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07655402389399121
            roll: 0.0
            pitch: 0.0
            yaw: -0.27162631470766163
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04241059830514161
            roll: 0.0
            pitch: 0.0
            yaw: -0.3447475568554338
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03893973181833535
            roll: 0.0
            pitch: 0.0
            yaw: -0.30803103158987244
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.056320605053145505
            roll: 0.0
            pitch: 0.0
            yaw: -0.5326475232579203
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06856759172030252
            roll: 0.0
            pitch: 0.0
            yaw: 0.4883014856699126
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08812603764125981
            roll: 0.0
            pitch: 0.0
            yaw: -0.6473970238771242
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00022719947632849008
              y: 0.013955493130484359
              z: 0.04392064641442425
              roll: 0.4747260982320646
              pitch: -0.48008099097074336
              yaw: 1.2905824069639262
            roll: 0.41445305951876255
            pitch: -0.4909717605439743
            yaw: 1.340434669363066
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.22027476843830313
          y: -0.28693869111656817
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.2284814596755105
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.005878957270944634
            roll: 0.0
            pitch: 0.0
            yaw: 0.005544746221815222
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0019658261688919945
            roll: 0.0
            pitch: 0.0
            yaw: 0.11892248197030836
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.011052740751168775
            roll: 0.0
            pitch: 0.0
            yaw: -0.020986475270162702
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.016721561327457377
            roll: 0.0
            pitch: 0.0
            yaw: 0.07376635502315523
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01653951861116771
            roll: 0.0
            pitch: 0.0
            yaw: 0.0563438746074065
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.004659231379572824
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03512264110432864
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07587000423723883
            roll: 0.0
            pitch: 0.0
            yaw: 0.04493025546920082
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09297692246773087
            roll: 0.0
            pitch: 0.0
            yaw: -0.5714586614925075
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06198747142527969
            roll: 0.0
            pitch: 0.0
            yaw: 0.23892044747571362
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03644790634992595
            roll: 0.0
            pitch: 0.0
            yaw: -1.0342218267614827
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07478339475934069
            roll: 0.0
            pitch: 0.0
            yaw: 0.8726060663519519
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06787233767305531
            roll: 0.0
            pitch: 0.0
            yaw: -0.1330413537509032
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0008467207257913682
              y: 0.016683223947526006
              z: 0.04086882578447411
              roll: 0.4445481823985503
              pitch: -0.45491802937670045
              yaw: 1.303920837632272
            roll: 0.4071827491421806
            pitch: -0.4696948823234811
            yaw: 1.340079275107785
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
