scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2689658805847442
          y: 0.2669661715776053
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.6860332270241987
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.009028522335075187
            roll: 0.0
            pitch: 0.0
            yaw: 0.058482976057683295
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.021669557702726785
            roll: 0.0
            pitch: 0.0
            yaw: 0.018228892049418827
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.012452873035419594
            roll: 0.0
            pitch: 0.0
            yaw: -0.012411075817679196
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.021187970394949775
            roll: 0.0
            pitch: 0.0
            yaw: 0.10557172000165038
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.010061228356941926
            roll: 0.0
            pitch: 0.0
            yaw: 0.1656670275776982
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.026639271264175063
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04144719811644794
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.01425264640238981
            roll: 0.0
            pitch: 0.0
            yaw: -0.07963824169946065
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.004283494184417619
            roll: 0.0
            pitch: 0.0
            yaw: -0.5255502865967879
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04477909395030871
            roll: 0.0
            pitch: 0.0
            yaw: 0.22832756750002758
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.027124123650108925
            roll: 0.0
            pitch: 0.0
            yaw: 0.2811717277238859
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.051124067132713814
            roll: 0.0
            pitch: 0.0
            yaw: 0.2673683919807557
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.004142452290586546
            roll: 0.0
            pitch: 0.0
            yaw: -0.07435659889785462
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001996296514373011
              y: 0.016032002689021083
              z: 0.04208770794710515
              roll: 0.44540344024057715
              pitch: -0.4889152667613949
              yaw: 1.301899874480005
            roll: 0.4553132035991947
            pitch: -0.4556505571515611
            yaw: 1.312739472502298
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.29217784198184665
          y: 0.16822938966830614
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.8759017232630355
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.008361898939551957
            roll: 0.0
            pitch: 0.0
            yaw: -0.09597159659657878
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.00521008826420204
            roll: 0.0
            pitch: 0.0
            yaw: -0.06299986932247348
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.010684884025005049
            roll: 0.0
            pitch: 0.0
            yaw: 0.1305720773019065
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01525644787910485
            roll: 0.0
            pitch: 0.0
            yaw: -0.15839613335706737
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.013616190024468351
            roll: 0.0
            pitch: 0.0
            yaw: -0.07370594046769469
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0577076718881142
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.01126691148224758
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08232293309300377
            roll: 0.0
            pitch: 0.0
            yaw: 0.5759345046580395
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08147155052766078
            roll: 0.0
            pitch: 0.0
            yaw: 0.3799858692320164
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06912507528185671
            roll: 0.0
            pitch: 0.0
            yaw: 0.8868684554544577
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.010089507545825466
            roll: 0.0
            pitch: 0.0
            yaw: -0.827660046622879
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08915630338064434
            roll: 0.0
            pitch: 0.0
            yaw: -0.8126833252590654
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.042742186288616035
            roll: 0.0
            pitch: 0.0
            yaw: -0.14838314109772388
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.000798655716646236
              y: 0.01668557203103111
              z: 0.04119362931027406
              roll: 0.42981448163418645
              pitch: -0.44788523652686296
              yaw: 1.3581803000457773
            roll: 0.4820786640945409
            pitch: -0.4711187707819478
            yaw: 1.3518455268696883
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2978024999803945
          y: 0.2745687858072113
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.942425680688713
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.003512482284711252
            roll: 0.0
            pitch: 0.0
            yaw: -0.028131661662282315
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.00794528942631703
            roll: 0.0
            pitch: 0.0
            yaw: -0.011301659776195322
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0011389653501294485
            roll: 0.0
            pitch: 0.0
            yaw: -0.10289981001151376
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012179731639434673
            roll: 0.0
            pitch: 0.0
            yaw: 0.12181805345597313
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.014880703065181567
            roll: 0.0
            pitch: 0.0
            yaw: -0.1623310622950646
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.016070494610932996
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.00038909997448253325
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04475081020205178
            roll: 0.0
            pitch: 0.0
            yaw: -0.9887339962766384
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.01653891869366267
            roll: 0.0
            pitch: 0.0
            yaw: -0.0918731401132048
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05060449689289166
            roll: 0.0
            pitch: 0.0
            yaw: -1.0008418170296594
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.04041161784752786
            roll: 0.0
            pitch: 0.0
            yaw: 0.31756399309531425
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05656210292404609
            roll: 0.0
            pitch: 0.0
            yaw: 0.2508091080168635
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.025662574140262656
            roll: 0.0
            pitch: 0.0
            yaw: -0.16595365479666824
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0003087649369593586
              y: 0.017232277920256445
              z: 0.04254313586783663
              roll: 0.426487495740728
              pitch: -0.4644865322109162
              yaw: 1.3448366661575732
            roll: 0.41937925265846393
            pitch: -0.5108422366305432
            yaw: 1.3173177901012443
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
