scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2817343863970119
          y: 0.1652562360693124
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3606942032471019
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.005323128764087873
            roll: 0.0
            pitch: 0.0
            yaw: 0.0330983328028977
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008956375598307472
            roll: 0.0
            pitch: 0.0
            yaw: -0.12746785712895065
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.00911580510496232
            roll: 0.0
            pitch: 0.0
            yaw: 0.0007867306439492405
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.003733195060945646
            roll: 0.0
            pitch: 0.0
            yaw: -0.17435170351654758
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.020739846241040805
            roll: 0.0
            pitch: 0.0
            yaw: 0.03705572694438097
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.042663442374172564
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.051841719441537676
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.09063567566725611
            roll: 0.0
            pitch: 0.0
            yaw: 0.1696282739535584
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05891479420854426
            roll: 0.0
            pitch: 0.0
            yaw: -0.3983568425401214
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01647062740393057
            roll: 0.0
            pitch: 0.0
            yaw: -0.42640963950534805
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.04065951811630247
            roll: 0.0
            pitch: 0.0
            yaw: -1.0451008798181125
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06650202328466873
            roll: 0.0
            pitch: 0.0
            yaw: 0.44868680776618963
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0681907143326845
            roll: 0.0
            pitch: 0.0
            yaw: -0.17318147999133449
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0013060327681837808
              y: 0.015219715483198365
              z: 0.04297490741377354
              roll: 0.4817934443620342
              pitch: -0.49340233689488533
              yaw: 1.2952495555630592
            roll: 0.40691026616032827
            pitch: -0.5164073823504747
            yaw: 1.3146102851363781
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2656284665071783
          y: -0.24466345877517542
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.6371630554000047
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0049752121885511535
            roll: 0.0
            pitch: 0.0
            yaw: 0.012405618755013087
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.014096860365368183
            roll: 0.0
            pitch: 0.0
            yaw: -0.044600584108720115
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.021899111231403458
            roll: 0.0
            pitch: 0.0
            yaw: -0.16701283815851053
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.020410310533208763
            roll: 0.0
            pitch: 0.0
            yaw: 0.04284648178851183
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.005187727901767695
            roll: 0.0
            pitch: 0.0
            yaw: -0.12001853311437398
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02922305564408073
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.01077738673601944
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.023890385857954333
            roll: 0.0
            pitch: 0.0
            yaw: 0.05480085425094994
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.025094884588304223
            roll: 0.0
            pitch: 0.0
            yaw: -0.665498771552157
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.029592980286588993
            roll: 0.0
            pitch: 0.0
            yaw: -0.4835838943315671
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08385954709538966
            roll: 0.0
            pitch: 0.0
            yaw: -0.026811453205746627
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0874825608047203
            roll: 0.0
            pitch: 0.0
            yaw: -0.9454430141756466
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.023018691672237593
            roll: 0.0
            pitch: 0.0
            yaw: -0.2894529284356919
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0007360220435649496
              y: 0.014002342412408246
              z: 0.0405279468157032
              roll: 0.420615781530851
              pitch: -0.5106180321499818
              yaw: 1.3214303405587233
            roll: 0.4296286755848187
            pitch: -0.4420117497723788
            yaw: 1.295401679140051
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.22027476843830313
          y: -0.28693869111656817
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.2284814596755105
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.005878957270944634
            roll: 0.0
            pitch: 0.0
            yaw: 0.005544746221815222
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0019658261688919945
            roll: 0.0
            pitch: 0.0
            yaw: 0.11892248197030836
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.011052740751168775
            roll: 0.0
            pitch: 0.0
            yaw: -0.020986475270162702
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.016721561327457377
            roll: 0.0
            pitch: 0.0
            yaw: 0.07376635502315523
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01653951861116771
            roll: 0.0
            pitch: 0.0
            yaw: 0.0563438746074065
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.004659231379572824
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03512264110432864
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07587000423723883
            roll: 0.0
            pitch: 0.0
            yaw: 0.04493025546920082
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09297692246773087
            roll: 0.0
            pitch: 0.0
            yaw: -0.5714586614925075
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06198747142527969
            roll: 0.0
            pitch: 0.0
            yaw: 0.23892044747571362
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03644790634992595
            roll: 0.0
            pitch: 0.0
            yaw: -1.0342218267614827
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07478339475934069
            roll: 0.0
            pitch: 0.0
            yaw: 0.8726060663519519
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06787233767305531
            roll: 0.0
            pitch: 0.0
            yaw: -0.1330413537509032
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.00053546099619568
              y: 0.013467325152558371
              z: 0.04173029241966062
              roll: 0.45773739867024044
              pitch: -0.4600759998219608
              yaw: 1.3115353942421804
            roll: 0.4071827491421806
            pitch: -0.4696948823234811
            yaw: 1.340079275107785
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
