scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2753959937443909
          y: 0.23670252535276476
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.45686829711958366
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.02120401224962487
            roll: 0.0
            pitch: 0.0
            yaw: -0.1360945071138572
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.015420666143392962
            roll: 0.0
            pitch: 0.0
            yaw: 0.034570441943011676
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.011486774312392561
            roll: 0.0
            pitch: 0.0
            yaw: -0.012840696367943855
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.006412509912385608
            roll: 0.0
            pitch: 0.0
            yaw: -0.17087614397359643
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.021689066586473744
            roll: 0.0
            pitch: 0.0
            yaw: 0.027353351339863358
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03816439662892128
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.046758272328090766
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.023173193639687173
            roll: 0.0
            pitch: 0.0
            yaw: -0.3861316856038408
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05596334292456039
            roll: 0.0
            pitch: 0.0
            yaw: -0.15170315000201384
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.007424554679361331
            roll: 0.0
            pitch: 0.0
            yaw: -0.40654973864740884
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.03933419592315604
            roll: 0.0
            pitch: 0.0
            yaw: 0.2717356857397144
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0772585232746495
            roll: 0.0
            pitch: 0.0
            yaw: -0.8078898952267966
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07461300293593254
            roll: 0.0
            pitch: 0.0
            yaw: -0.5816230948545587
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.001759885892329645
              y: 0.016974394020425127
              z: 0.04086122990407195
              roll: 0.4416760944893283
              pitch: -0.451391200798627
              yaw: 1.3664274909572067
            roll: 0.4144831640297616
            pitch: -0.4534160198413081
            yaw: 1.3072340704819612
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.24194167910501668
          y: 0.19450124964475235
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.6874248475146767
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0018883083240322021
            roll: 0.0
            pitch: 0.0
            yaw: 0.10813460783590545
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.017479052551709923
            roll: 0.0
            pitch: 0.0
            yaw: -0.1551400885469799
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0001605074243219741
            roll: 0.0
            pitch: 0.0
            yaw: 0.033651672286588136
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.002384096197387449
            roll: 0.0
            pitch: 0.0
            yaw: 0.07978378478999693
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.018387948327105892
            roll: 0.0
            pitch: 0.0
            yaw: -0.0030261001532834453
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.018888078563787852
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03612782920633868
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.02268755279271656
            roll: 0.0
            pitch: 0.0
            yaw: 0.17035467080613786
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.06823740739820006
            roll: 0.0
            pitch: 0.0
            yaw: -0.6309237599880252
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03738315406698492
            roll: 0.0
            pitch: 0.0
            yaw: -0.3883744366308366
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.026738844949205046
            roll: 0.0
            pitch: 0.0
            yaw: 0.5630537902648773
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.025304887766316925
            roll: 0.0
            pitch: 0.0
            yaw: 0.08674615834943866
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07534175371916771
            roll: 0.0
            pitch: 0.0
            yaw: -0.8601227478147574
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0006067917411930733
              y: 0.017334207037179368
              z: 0.042854665742058984
              roll: 0.40705835941293833
              pitch: -0.4758443503516776
              yaw: 1.3446480672235306
            roll: 0.47967108288283666
            pitch: -0.47222950996998625
            yaw: 1.328069557830308
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.18726090192468903
          y: 0.249339297625305
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.907644636795367
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01700315200705846
            roll: 0.0
            pitch: 0.0
            yaw: -0.08529660332491446
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.011922699816160613
            roll: 0.0
            pitch: 0.0
            yaw: -0.12300189303563835
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01699463982130986
            roll: 0.0
            pitch: 0.0
            yaw: 0.06007523593060618
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.02135802150268672
            roll: 0.0
            pitch: 0.0
            yaw: 0.12414387643071495
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.014542418263273613
            roll: 0.0
            pitch: 0.0
            yaw: -0.037564155341766076
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.034774679422123256
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.027019618389045562
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06837975698916535
            roll: 0.0
            pitch: 0.0
            yaw: -0.8398414857357532
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05805713665421724
            roll: 0.0
            pitch: 0.0
            yaw: 0.16918799951430974
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.004260214340690557
            roll: 0.0
            pitch: 0.0
            yaw: -0.988159394692987
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08505225963672097
            roll: 0.0
            pitch: 0.0
            yaw: -0.5014237691642359
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.021479389328169993
            roll: 0.0
            pitch: 0.0
            yaw: 0.9565566011324258
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.01545972186169052
            roll: 0.0
            pitch: 0.0
            yaw: -0.028554949347530334
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.000523509913977987
              y: 0.01592747799519077
              z: 0.042065133390786026
              roll: 0.4334782260772715
              pitch: -0.47965332066305
              yaw: 1.3414454755262677
            roll: 0.44561395007836335
            pitch: -0.47337703557404304
            yaw: 1.292597435162248
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
