scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2975803836466557
          y: 0.2948814336464098
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 3.076330024106986
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.017381346843699592
            roll: 0.0
            pitch: 0.0
            yaw: 0.09692070907928813
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008869506117727508
            roll: 0.0
            pitch: 0.0
            yaw: 0.09784996208950791
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.006398461812993209
            roll: 0.0
            pitch: 0.0
            yaw: -0.06265478033783833
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.013843120408549667
            roll: 0.0
            pitch: 0.0
            yaw: 0.04467068788823958
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.021108319938736006
            roll: 0.0
            pitch: 0.0
            yaw: 0.11004551388702566
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.019346110201189648
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02518095827953981
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08751627577580924
            roll: 0.0
            pitch: 0.0
            yaw: 1.0422693371387475
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08734286985952108
            roll: 0.0
            pitch: 0.0
            yaw: -0.9935118180903564
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07808763376217576
            roll: 0.0
            pitch: 0.0
            yaw: 0.5458297051326002
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04837921057477493
            roll: 0.0
            pitch: 0.0
            yaw: -0.3393197588353888
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.044839770398183876
            roll: 0.0
            pitch: 0.0
            yaw: 0.9933567996183201
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.018538701188437645
            roll: 0.0
            pitch: 0.0
            yaw: -0.0584613612962992
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0011205733834558087
              y: 0.016122821187838633
              z: 0.040937358206930646
              roll: 0.4355031216459963
              pitch: -0.4690679014637579
              yaw: 1.2943140647754798
            roll: 0.44583385518830343
            pitch: -0.5036409006072686
            yaw: 1.3410692553371155
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.22117535863904592
          y: -0.27335214337981834
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.0792793291951703
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.005366788161934349
            roll: 0.0
            pitch: 0.0
            yaw: 0.1633024869933849
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.012093474534813617
            roll: 0.0
            pitch: 0.0
            yaw: -0.1245073560900384
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.013278008175729562
            roll: 0.0
            pitch: 0.0
            yaw: 0.05037947227387596
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.018987212483953825
            roll: 0.0
            pitch: 0.0
            yaw: 0.09328775505888764
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.003056827888990865
            roll: 0.0
            pitch: 0.0
            yaw: -0.161724064338266
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.018602590577122873
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0562497836656446
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08367272589607314
            roll: 0.0
            pitch: 0.0
            yaw: -0.4276204147533701
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0062567100729382374
            roll: 0.0
            pitch: 0.0
            yaw: 0.27494345070363324
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08506975283245152
            roll: 0.0
            pitch: 0.0
            yaw: -0.7934899038804131
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05226023379249283
            roll: 0.0
            pitch: 0.0
            yaw: -0.4394419851101451
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.015566769802478161
            roll: 0.0
            pitch: 0.0
            yaw: 0.8445502087996706
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03517060467884481
            roll: 0.0
            pitch: 0.0
            yaw: 1.021592030531928
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0007280861941431306
              y: 0.015915365728736558
              z: 0.043231084953891115
              roll: 0.4139776000698214
              pitch: -0.5216087827442618
              yaw: 1.347903274377834
            roll: 0.4262100220600212
            pitch: -0.5163049593516958
            yaw: 1.3066710601008378
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.26641160665843444
          y: -0.1896553672702896
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.519080071186921
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0032551147145074844
            roll: 0.0
            pitch: 0.0
            yaw: 0.15947795887563954
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.016267380573455656
            roll: 0.0
            pitch: 0.0
            yaw: -0.12038898257337334
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.003247998849722388
            roll: 0.0
            pitch: 0.0
            yaw: 0.060535519129476606
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.005180655731381271
            roll: 0.0
            pitch: 0.0
            yaw: -0.09939050402590871
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.02018617645558109
            roll: 0.0
            pitch: 0.0
            yaw: -0.0441754960238564
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04867916715265844
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.020118674334503067
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07226833897232471
            roll: 0.0
            pitch: 0.0
            yaw: 0.12584350079343243
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.013226952120672292
            roll: 0.0
            pitch: 0.0
            yaw: -0.69637763205194
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.003241913025861312
            roll: 0.0
            pitch: 0.0
            yaw: -1.0070303928448778
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04793800110821403
            roll: 0.0
            pitch: 0.0
            yaw: -0.7385920917114712
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.016622502386248073
            roll: 0.0
            pitch: 0.0
            yaw: 0.13663496607700854
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03935715823151452
            roll: 0.0
            pitch: 0.0
            yaw: -0.7073661445970805
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0003153826923888866
              y: 0.013462765261583428
              z: 0.0443672528116595
              roll: 0.4429743390743584
              pitch: -0.522600703655895
              yaw: 1.3401834314718117
            roll: 0.46970071861266643
            pitch: -0.47654519961045144
            yaw: 1.3043704541101648
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
