scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.28936687455270294
          y: 0.24968094332295426
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4853548195130619
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01139505889695287
            roll: 0.0
            pitch: 0.0
            yaw: -0.17096117611033085
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006993761542885134
            roll: 0.0
            pitch: 0.0
            yaw: -0.12028271811410592
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.02055056529015331
            roll: 0.0
            pitch: 0.0
            yaw: 0.11565871243229103
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.009662630974843243
            roll: 0.0
            pitch: 0.0
            yaw: -0.017793399279982552
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.020417305525286762
            roll: 0.0
            pitch: 0.0
            yaw: 0.07053046726521747
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01106896538703929
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05021348261153641
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.09510433112420599
            roll: 0.0
            pitch: 0.0
            yaw: 0.6218683406047645
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04552024168348756
            roll: 0.0
            pitch: 0.0
            yaw: -0.06297124263858
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.042075660841637746
            roll: 0.0
            pitch: 0.0
            yaw: 0.5032889166285617
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.07431260168175427
            roll: 0.0
            pitch: 0.0
            yaw: 0.3908469570697044
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.027978020821734187
            roll: 0.0
            pitch: 0.0
            yaw: 0.10566131570152582
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0693260692453802
            roll: 0.0
            pitch: 0.0
            yaw: 0.8227280506017951
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00011478808928230984
              y: 0.016136362207088008
              z: 0.04274149343903477
              roll: 0.45598249934038226
              pitch: -0.44659308871903214
              yaw: 1.352775196517159
            roll: 0.4828504694452331
            pitch: -0.4400890440191155
            yaw: 1.3401238802229143
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2817343863970119
          y: 0.1652562360693124
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3606942032471019
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.005323128764087873
            roll: 0.0
            pitch: 0.0
            yaw: 0.0330983328028977
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008956375598307472
            roll: 0.0
            pitch: 0.0
            yaw: -0.12746785712895065
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.00911580510496232
            roll: 0.0
            pitch: 0.0
            yaw: 0.0007867306439492405
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.003733195060945646
            roll: 0.0
            pitch: 0.0
            yaw: -0.17435170351654758
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.020739846241040805
            roll: 0.0
            pitch: 0.0
            yaw: 0.03705572694438097
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.042663442374172564
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.051841719441537676
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.09063567566725611
            roll: 0.0
            pitch: 0.0
            yaw: 0.1696282739535584
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.05891479420854426
            roll: 0.0
            pitch: 0.0
            yaw: -0.3983568425401214
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01647062740393057
            roll: 0.0
            pitch: 0.0
            yaw: -0.42640963950534805
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.04065951811630247
            roll: 0.0
            pitch: 0.0
            yaw: -1.0451008798181125
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.06650202328466873
            roll: 0.0
            pitch: 0.0
            yaw: 0.44868680776618963
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0681907143326845
            roll: 0.0
            pitch: 0.0
            yaw: -0.17318147999133449
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00163930695248616
              y: 0.016698849979810585
              z: 0.04199041739412914
              roll: 0.4461029693781305
              pitch: -0.49555968652114474
              yaw: 1.3203937428430685
            roll: 0.40691026616032827
            pitch: -0.5164073823504747
            yaw: 1.3146102851363781
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.29119256063509985
          y: 0.29149333843022224
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.4625866316208276
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.008926587869306057
            roll: 0.0
            pitch: 0.0
            yaw: -0.10186301175265584
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0013137766431792416
            roll: 0.0
            pitch: 0.0
            yaw: 0.03433383821871039
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.006381772434620641
            roll: 0.0
            pitch: 0.0
            yaw: 0.08810569527210593
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.003491486500261737
            roll: 0.0
            pitch: 0.0
            yaw: 0.11844908847370772
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.005645478440834576
            roll: 0.0
            pitch: 0.0
            yaw: 0.15939895336224053
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.004270651710811577
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.023281366723448105
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0034521118962481945
            roll: 0.0
            pitch: 0.0
            yaw: 0.9415781006127535
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.06957616182647602
            roll: 0.0
            pitch: 0.0
            yaw: -0.9733782903291615
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.012308276150484895
            roll: 0.0
            pitch: 0.0
            yaw: 0.8871587233714084
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03900765612945244
            roll: 0.0
            pitch: 0.0
            yaw: -0.3270653811167401
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06348175492259861
            roll: 0.0
            pitch: 0.0
            yaw: 0.07656097263406636
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.009216254081062358
            roll: 0.0
            pitch: 0.0
            yaw: 0.25331524658298843
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0013634223661059632
              y: 0.01617716867474119
              z: 0.04190140369981631
              roll: 0.445716983527582
              pitch: -0.4950021467893957
              yaw: 1.3212185108894705
            roll: 0.428655199723283
            pitch: -0.4863402668300742
            yaw: 1.2974286532955326
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
