scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.21454100856940858
          y: -0.26722040736619074
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.192701035145263
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.014506643664449315
            roll: 0.0
            pitch: 0.0
            yaw: -0.11725137188202603
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.011950426381344088
            roll: 0.0
            pitch: 0.0
            yaw: 3.142526692639924e-05
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.007150274483509408
            roll: 0.0
            pitch: 0.0
            yaw: -0.07254277807503169
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.006385865359076603
            roll: 0.0
            pitch: 0.0
            yaw: -0.06809089141439319
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.022253105328305635
            roll: 0.0
            pitch: 0.0
            yaw: 0.09077402318517208
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0372601836168355
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.004921800857086968
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.09334362767614615
            roll: 0.0
            pitch: 0.0
            yaw: 0.3381163870064985
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07104215249054963
            roll: 0.0
            pitch: 0.0
            yaw: -0.35020349841337606
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03793468739437225
            roll: 0.0
            pitch: 0.0
            yaw: 0.561998746796929
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03194879809758293
            roll: 0.0
            pitch: 0.0
            yaw: -0.8612814788028653
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.043278998643657196
            roll: 0.0
            pitch: 0.0
            yaw: 0.6729538651768567
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.011834179009346815
            roll: 0.0
            pitch: 0.0
            yaw: 1.0243538734488642
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0012825369507649923
              y: 0.01524856086549136
              z: 0.040510704156580306
              roll: 0.4720018738235936
              pitch: -0.5143364140657318
              yaw: 1.3420377082976682
            roll: 0.4646818458965199
            pitch: -0.4582725426416969
            yaw: 1.2927130846661494
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.27403400674245215
          y: -0.27069646238135664
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.6621102595416208
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.009544973052433616
            roll: 0.0
            pitch: 0.0
            yaw: 0.08030334267205574
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01927637816395779
            roll: 0.0
            pitch: 0.0
            yaw: -0.11854097791916089
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.022334522194950523
            roll: 0.0
            pitch: 0.0
            yaw: 0.09321381480196228
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.021287725404140978
            roll: 0.0
            pitch: 0.0
            yaw: 0.1619949519560583
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.010431199163615776
            roll: 0.0
            pitch: 0.0
            yaw: 0.15603775448835627
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.02877099159364545
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03330577098175558
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.04293394450678825
            roll: 0.0
            pitch: 0.0
            yaw: -0.5442781319153144
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.02580414726000249
            roll: 0.0
            pitch: 0.0
            yaw: 0.5590023395911587
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.031681831152507764
            roll: 0.0
            pitch: 0.0
            yaw: -0.8420982845319984
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09475167152945405
            roll: 0.0
            pitch: 0.0
            yaw: 0.3868988792969903
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.03306222295494177
            roll: 0.0
            pitch: 0.0
            yaw: -0.5637522925121699
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03247862676814628
            roll: 0.0
            pitch: 0.0
            yaw: -0.003183444386593015
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0015261261513635773
              y: 0.016641766894367756
              z: 0.0413161620756559
              roll: 0.43778787207578185
              pitch: -0.5120041464214353
              yaw: 1.2929372442821854
            roll: 0.40617440760074125
            pitch: -0.4553008044885775
            yaw: 1.33219343868023
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2353344027938786
          y: -0.24946254070339158
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.067455846650523
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.013704272268494772
            roll: 0.0
            pitch: 0.0
            yaw: -0.1309926309822538
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.013800027807198908
            roll: 0.0
            pitch: 0.0
            yaw: 0.14651753037615922
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0008648040395685917
            roll: 0.0
            pitch: 0.0
            yaw: 0.07158781288312566
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.018100709026668618
            roll: 0.0
            pitch: 0.0
            yaw: -0.07931893228927578
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0003689146178582209
            roll: 0.0
            pitch: 0.0
            yaw: 0.08977862498983763
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.006333141093148614
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0539105434641653
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.010729106804071048
            roll: 0.0
            pitch: 0.0
            yaw: -0.8891052335553099
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05922825859149463
            roll: 0.0
            pitch: 0.0
            yaw: -0.1756052802970317
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.003576684743693076
            roll: 0.0
            pitch: 0.0
            yaw: 0.37926141378720835
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07096816130363762
            roll: 0.0
            pitch: 0.0
            yaw: 0.4631251120188342
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06038826323372645
            roll: 0.0
            pitch: 0.0
            yaw: 0.3541977520015518
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.013383336790304054
            roll: 0.0
            pitch: 0.0
            yaw: -0.3180189490436547
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0005175126207620558
              y: 0.01733654661737879
              z: 0.041948216860052116
              roll: 0.42996322757091765
              pitch: -0.4858743393670342
              yaw: 1.2913262516384612
            roll: 0.4479870556041279
            pitch: -0.4840544376457635
            yaw: 1.302831863905707
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
