scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.17443196396015853
          y: 0.2875489290417517
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.7502167963074378
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.009704130112664258
            roll: 0.0
            pitch: 0.0
            yaw: -0.14193642125987432
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.009031118770576541
            roll: 0.0
            pitch: 0.0
            yaw: 0.04351555978504548
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.007862812084071812
            roll: 0.0
            pitch: 0.0
            yaw: -0.06633414447556382
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012958595014624916
            roll: 0.0
            pitch: 0.0
            yaw: 0.016921737159222988
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01180562928564626
            roll: 0.0
            pitch: 0.0
            yaw: 0.12344204932779496
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.007094958750494859
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03965358959813482
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.09222244560592284
            roll: 0.0
            pitch: 0.0
            yaw: 0.1351785754830146
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04160005959341293
            roll: 0.0
            pitch: 0.0
            yaw: 0.5055526933054808
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01114134865370936
            roll: 0.0
            pitch: 0.0
            yaw: 1.001641735686473
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.02779942557060426
            roll: 0.0
            pitch: 0.0
            yaw: -0.7809137920093612
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.028267302679902573
            roll: 0.0
            pitch: 0.0
            yaw: 0.7085218542544109
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06682647471153128
            roll: 0.0
            pitch: 0.0
            yaw: 1.040082870158488
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.001492646938647598
              y: 0.017095793204512023
              z: 0.04106841168441086
              roll: 0.4283892417646852
              pitch: -0.4481374499619048
              yaw: 1.368338959432577
            roll: 0.4117564202621219
            pitch: -0.46151529956678355
            yaw: 1.3135300478515284
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2894081971200428
          y: -0.29138341140349716
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.0601480974749955
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.020034837310720865
            roll: 0.0
            pitch: 0.0
            yaw: -0.16829362777968973
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007382397994281899
            roll: 0.0
            pitch: 0.0
            yaw: 0.0837427196572823
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.005861644183469399
            roll: 0.0
            pitch: 0.0
            yaw: -0.04701715405621715
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.020987154966275606
            roll: 0.0
            pitch: 0.0
            yaw: -0.10639797213060609
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0010372394385330837
            roll: 0.0
            pitch: 0.0
            yaw: 0.09165485183545785
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04082465638663452
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.029167056655481832
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06906207754162483
            roll: 0.0
            pitch: 0.0
            yaw: -0.9798753833039678
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09567963760769845
            roll: 0.0
            pitch: 0.0
            yaw: -0.9692629796853178
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01828335515118712
            roll: 0.0
            pitch: 0.0
            yaw: -0.4535600349636425
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0011804605132017948
            roll: 0.0
            pitch: 0.0
            yaw: -0.9591055633206644
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.02968745930063918
            roll: 0.0
            pitch: 0.0
            yaw: 0.8229008912641935
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03734117225913064
            roll: 0.0
            pitch: 0.0
            yaw: 0.2894849043490313
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.001965940828587116
              y: 0.01660693654908368
              z: 0.04115375571496848
              roll: 0.4138661755422871
              pitch: -0.489710419164044
              yaw: 1.3503659873650855
            roll: 0.4490590351043353
            pitch: -0.44607547917520424
            yaw: 1.3194129191268018
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.24762726162197918
          y: 0.27124251115177805
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -1.907333154740988
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.020826981596150422
            roll: 0.0
            pitch: 0.0
            yaw: -0.030301449273464343
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.014267854376795785
            roll: 0.0
            pitch: 0.0
            yaw: 0.058938246599702676
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.011036434806865425
            roll: 0.0
            pitch: 0.0
            yaw: 0.045919169757781375
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.001885767516973686
            roll: 0.0
            pitch: 0.0
            yaw: -0.05850014488038305
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.016310692012934974
            roll: 0.0
            pitch: 0.0
            yaw: 0.10159917592550766
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05085936809861351
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.048957299897641436
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.05706381434019664
            roll: 0.0
            pitch: 0.0
            yaw: -0.18332074790902142
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.06879772023239605
            roll: 0.0
            pitch: 0.0
            yaw: 0.7201539147117919
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.046767349235522476
            roll: 0.0
            pitch: 0.0
            yaw: 0.11327079697507814
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08870499540151233
            roll: 0.0
            pitch: 0.0
            yaw: 0.6265151877981521
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.033001005738763634
            roll: 0.0
            pitch: 0.0
            yaw: 0.25314427287700636
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03259126838808746
            roll: 0.0
            pitch: 0.0
            yaw: -0.3352505644094753
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0009000056605584282
              y: 0.01600815776711894
              z: 0.0437986196725873
              roll: 0.4721881139314694
              pitch: -0.481748931677296
              yaw: 1.295953292949213
            roll: 0.43841444183370654
            pitch: -0.44094265095579155
            yaw: 1.3702913442114648
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
