scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.27340404307107097
          y: 0.2981922516175158
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.064977694251266
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0008289428187397661
            roll: 0.0
            pitch: 0.0
            yaw: 0.1366062582547588
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.00023033259494213698
            roll: 0.0
            pitch: 0.0
            yaw: -0.15038014791473828
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0018740055280845672
            roll: 0.0
            pitch: 0.0
            yaw: -0.022550747317135716
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01436656290348293
            roll: 0.0
            pitch: 0.0
            yaw: 0.07328907176419283
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01634474058615277
            roll: 0.0
            pitch: 0.0
            yaw: -0.15722386580399453
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02428459375514236
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.041416875874283304
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.021396998362856523
            roll: 0.0
            pitch: 0.0
            yaw: 0.6210458436768391
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.052303514058750666
            roll: 0.0
            pitch: 0.0
            yaw: -0.2696987945429099
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0848162923175165
            roll: 0.0
            pitch: 0.0
            yaw: -0.2168931290828674
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.015059754555848473
            roll: 0.0
            pitch: 0.0
            yaw: -0.8274674426370956
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06451214795237258
            roll: 0.0
            pitch: 0.0
            yaw: -0.03992556394939095
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0237450129754902
            roll: 0.0
            pitch: 0.0
            yaw: -0.9055649503650354
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0005253691630119604
              y: 0.016892772463590094
              z: 0.044371957958074935
              roll: 0.4751375094314522
              pitch: -0.47268045682421805
              yaw: 1.322537857756486
            roll: 0.4716991403059592
            pitch: -0.4608334326865119
            yaw: 1.3174115505344302
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.251529362865686
          y: -0.24508453290310744
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -1.0157295097817114
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0038909633298383
            roll: 0.0
            pitch: 0.0
            yaw: 0.003709060922756663
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.015858356679101612
            roll: 0.0
            pitch: 0.0
            yaw: -0.1654610350346254
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.010429132298935823
            roll: 0.0
            pitch: 0.0
            yaw: 0.01850571922640354
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.00038769371752210915
            roll: 0.0
            pitch: 0.0
            yaw: 0.03967151181965403
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.016061317906200023
            roll: 0.0
            pitch: 0.0
            yaw: 0.005929197909149253
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.019642118368048085
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03389617411518876
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.09584411946318659
            roll: 0.0
            pitch: 0.0
            yaw: 0.08733676425815595
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07416218621470629
            roll: 0.0
            pitch: 0.0
            yaw: -0.757511030016562
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03515428941057666
            roll: 0.0
            pitch: 0.0
            yaw: 0.18062823249891347
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08826382951862749
            roll: 0.0
            pitch: 0.0
            yaw: 0.7929346319063775
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.02774079231653659
            roll: 0.0
            pitch: 0.0
            yaw: 0.7497338437665289
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.012356999231189478
            roll: 0.0
            pitch: 0.0
            yaw: 1.043555690224314
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0013531265304924304
              y: 0.015168999966731182
              z: 0.04315778067067556
              roll: 0.47223213624503885
              pitch: -0.49269596353721695
              yaw: 1.3045746800614655
            roll: 0.4347570555264077
            pitch: -0.49804648391994594
            yaw: 1.30464773926816
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.23241966790035729
          y: -0.20956227864980667
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.391256468257562
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0044119538915771035
            roll: 0.0
            pitch: 0.0
            yaw: -0.08197053103444346
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.014679809445792377
            roll: 0.0
            pitch: 0.0
            yaw: -0.03196790391656862
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.00025885195996880675
            roll: 0.0
            pitch: 0.0
            yaw: 0.1328659490257033
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.021225119447576483
            roll: 0.0
            pitch: 0.0
            yaw: 0.013647050497639562
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.008804642087367
            roll: 0.0
            pitch: 0.0
            yaw: -0.05485072076212168
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02187953810275091
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.030547611475201252
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.02462165186310511
            roll: 0.0
            pitch: 0.0
            yaw: 0.6982441757525353
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.019760709023199707
            roll: 0.0
            pitch: 0.0
            yaw: -0.5960650783073582
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.035332638530923416
            roll: 0.0
            pitch: 0.0
            yaw: 0.013387181284362004
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.014737244252271284
            roll: 0.0
            pitch: 0.0
            yaw: 0.6824003326855026
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.00883049330434571
            roll: 0.0
            pitch: 0.0
            yaw: -0.3509011570438545
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.035921679447659616
            roll: 0.0
            pitch: 0.0
            yaw: 0.7027226671543798
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0019409471388492632
              y: 0.016372268642100098
              z: 0.042783887897857587
              roll: 0.4437325178693134
              pitch: -0.45864559026621776
              yaw: 1.3075481833319014
            roll: 0.41872379557642453
            pitch: -0.4797931260379081
            yaw: 1.3665603710624845
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
