scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.266529382472829
          y: -0.2704703529755634
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.745576691352059
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.009184356147069897
            roll: 0.0
            pitch: 0.0
            yaw: 0.12925729713179007
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.002171150433540568
            roll: 0.0
            pitch: 0.0
            yaw: 0.08964920581297625
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01573116566299164
            roll: 0.0
            pitch: 0.0
            yaw: 0.08080477907054479
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0071754151620743965
            roll: 0.0
            pitch: 0.0
            yaw: 0.06684445098329869
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01006013501153754
            roll: 0.0
            pitch: 0.0
            yaw: -0.03528337341313628
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.008680661681712332
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02504672657695048
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06619916928300741
            roll: 0.0
            pitch: 0.0
            yaw: -0.13204190120685522
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.006206646822905587
            roll: 0.0
            pitch: 0.0
            yaw: 0.01571995310043728
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06630216542128561
            roll: 0.0
            pitch: 0.0
            yaw: 0.7709035357498022
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0016264518035828401
            roll: 0.0
            pitch: 0.0
            yaw: -0.6121922373440201
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07847703346778714
            roll: 0.0
            pitch: 0.0
            yaw: -0.6451696456213202
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02395098985617576
            roll: 0.0
            pitch: 0.0
            yaw: -0.38852599199566473
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0002915705057854692
              y: 0.014606629670072098
              z: 0.04093545363843536
              roll: 0.4408554313911209
              pitch: -0.48526566043335007
              yaw: 1.358139328301312
            roll: 0.4265002199497008
            pitch: -0.513251895218795
            yaw: 1.3078257882729554
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2756535514241928
          y: 0.18859748713128327
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.6264745339468893
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.010725699340083182
            roll: 0.0
            pitch: 0.0
            yaw: 0.06950666720671245
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.014005525974563185
            roll: 0.0
            pitch: 0.0
            yaw: 0.003172336911834772
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.014569021079026113
            roll: 0.0
            pitch: 0.0
            yaw: -0.13054299660085816
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.022534641293834326
            roll: 0.0
            pitch: 0.0
            yaw: 0.15177855571177762
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.006141708282082627
            roll: 0.0
            pitch: 0.0
            yaw: 0.16182733666672722
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.008905109823545365
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03602006757419553
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.038116425809471444
            roll: 0.0
            pitch: 0.0
            yaw: -0.17667993369255386
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09503339393275007
            roll: 0.0
            pitch: 0.0
            yaw: 0.7783339983622979
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.025670475034012985
            roll: 0.0
            pitch: 0.0
            yaw: -0.7789555474099515
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05066903900758587
            roll: 0.0
            pitch: 0.0
            yaw: 0.7486074787472461
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.010584942781160775
            roll: 0.0
            pitch: 0.0
            yaw: -0.6083263824977398
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07192731889289528
            roll: 0.0
            pitch: 0.0
            yaw: -0.48286332114740316
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0018350235712702011
              y: 0.014813741221968896
              z: 0.043359346061801037
              roll: 0.43932156631970853
              pitch: -0.5069283294580091
              yaw: 1.302663602740917
            roll: 0.4219778325951098
            pitch: -0.4924742159363197
            yaw: 1.2988099536685067
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.27663387792565847
          y: -0.24995896213782504
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.3259935029429357
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.014181750263919483
            roll: 0.0
            pitch: 0.0
            yaw: 0.09264601919933646
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.009447471082118786
            roll: 0.0
            pitch: 0.0
            yaw: 0.14628013336409418
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.002965745289959177
            roll: 0.0
            pitch: 0.0
            yaw: 0.012933016813669956
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0070224609114103494
            roll: 0.0
            pitch: 0.0
            yaw: -0.1379816863477733
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.00040603098503760524
            roll: 0.0
            pitch: 0.0
            yaw: -0.04881003556781577
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0302806884416514
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.009312603047040055
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.057661307048471264
            roll: 0.0
            pitch: 0.0
            yaw: -0.07528045040415265
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.02695017104732203
            roll: 0.0
            pitch: 0.0
            yaw: -0.9910968716499642
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03978609239228561
            roll: 0.0
            pitch: 0.0
            yaw: 0.7688517863294131
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.030437134827579898
            roll: 0.0
            pitch: 0.0
            yaw: -0.8746996146205243
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07013498484377766
            roll: 0.0
            pitch: 0.0
            yaw: 0.24017654453710868
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05352268022595727
            roll: 0.0
            pitch: 0.0
            yaw: 0.030771914780556298
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0018004956794500037
              y: 0.014419811926906811
              z: 0.04057449676316509
              roll: 0.4537422153042007
              pitch: -0.47812239754500785
              yaw: 1.341665069026914
            roll: 0.4563923238654397
            pitch: -0.5028832652917072
            yaw: 1.3262259404084227
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
