scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2533529624745193
          y: -0.2802384590134577
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.888039041422494
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015661569178867064
            roll: 0.0
            pitch: 0.0
            yaw: -0.009218721968834942
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.009067494244619397
            roll: 0.0
            pitch: 0.0
            yaw: -0.09265793458582867
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.004823115535921619
            roll: 0.0
            pitch: 0.0
            yaw: -0.033477988688241506
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.013011124730173372
            roll: 0.0
            pitch: 0.0
            yaw: -0.021280633103940516
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.018928959126419856
            roll: 0.0
            pitch: 0.0
            yaw: -0.13608553905876014
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.045600075725154045
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.024892337724022814
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06526091417768011
            roll: 0.0
            pitch: 0.0
            yaw: 0.9320435435384908
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0059965746527122915
            roll: 0.0
            pitch: 0.0
            yaw: -0.4962537720606218
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01468712322672179
            roll: 0.0
            pitch: 0.0
            yaw: -0.33474809539481065
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.09165058363674829
            roll: 0.0
            pitch: 0.0
            yaw: 0.5501487864742216
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.03743152056347123
            roll: 0.0
            pitch: 0.0
            yaw: -1.0282351369479883
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.08358418521982894
            roll: 0.0
            pitch: 0.0
            yaw: 0.20224684271669435
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0017032428957700092
              y: 0.013618818245825714
              z: 0.04244375441937315
              roll: 0.47927028723939724
              pitch: -0.4806239731877759
              yaw: 1.356967442787042
            roll: 0.4089013922950104
            pitch: -0.5164706066079233
            yaw: 1.3480008496617533
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.20995598051114242
          y: 0.2870566254842161
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.530909803708125
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01541169512351957
            roll: 0.0
            pitch: 0.0
            yaw: 0.15991973615330612
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.003322467737072045
            roll: 0.0
            pitch: 0.0
            yaw: -0.05323442060613055
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.013587220476611452
            roll: 0.0
            pitch: 0.0
            yaw: 0.16137199311741357
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.00406384249189266
            roll: 0.0
            pitch: 0.0
            yaw: 0.11273124266802892
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.002574319727479204
            roll: 0.0
            pitch: 0.0
            yaw: -0.16372411394946162
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04592205072896797
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03685459431691611
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.04190655850243651
            roll: 0.0
            pitch: 0.0
            yaw: -0.9786453715419643
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.020241802342350138
            roll: 0.0
            pitch: 0.0
            yaw: -0.03396770467499488
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01670385126839566
            roll: 0.0
            pitch: 0.0
            yaw: 0.0418612747007816
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06216850938193008
            roll: 0.0
            pitch: 0.0
            yaw: 0.9335220043054313
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06620288084740031
            roll: 0.0
            pitch: 0.0
            yaw: -0.1440459646056763
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06820735192242794
            roll: 0.0
            pitch: 0.0
            yaw: 0.03664536991448952
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0012928583304952146
              y: 0.017183265369266496
              z: 0.04188533173047173
              roll: 0.4087118418613341
              pitch: -0.47145653537414234
              yaw: 1.3248503629966712
            roll: 0.42054607164035884
            pitch: -0.46032367662348406
            yaw: 1.293383138503652
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.29567719480903154
          y: 0.10902009425572295
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.4482096954607
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.017856945882696193
            roll: 0.0
            pitch: 0.0
            yaw: -0.0885673894336999
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.021044103726281377
            roll: 0.0
            pitch: 0.0
            yaw: 0.08580884249546539
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.010022597103728317
            roll: 0.0
            pitch: 0.0
            yaw: 0.08282031806892048
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02120267455083489
            roll: 0.0
            pitch: 0.0
            yaw: 0.14308099512606337
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0062546861869278575
            roll: 0.0
            pitch: 0.0
            yaw: -0.12294135125471117
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03816650417024499
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05420556266452073
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.020497182885380258
            roll: 0.0
            pitch: 0.0
            yaw: -0.7873493437929022
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.03452725463642659
            roll: 0.0
            pitch: 0.0
            yaw: -0.8008385743260256
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.032146654489726326
            roll: 0.0
            pitch: 0.0
            yaw: -0.7360115014478388
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.02194268784544212
            roll: 0.0
            pitch: 0.0
            yaw: -0.5213281680923594
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.04934497359313242
            roll: 0.0
            pitch: 0.0
            yaw: 0.23842903493560264
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.01182685254977689
            roll: 0.0
            pitch: 0.0
            yaw: 0.39549385540856674
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0007818143539590858
              y: 0.015565877239834689
              z: 0.04213243984097846
              roll: 0.4615015840667134
              pitch: -0.5036072569167318
              yaw: 1.3278697494706075
            roll: 0.42347790445677586
            pitch: -0.4657538000992549
            yaw: 1.354926623949601
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
