scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2913497469453191
          y: 0.15898181671129386
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.561210554729819
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.016783379950743943
            roll: 0.0
            pitch: 0.0
            yaw: -0.15345687474459435
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006978549667846383
            roll: 0.0
            pitch: 0.0
            yaw: 0.15128651605731191
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.017428718759829136
            roll: 0.0
            pitch: 0.0
            yaw: -0.05241263579635598
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01986851091649699
            roll: 0.0
            pitch: 0.0
            yaw: 0.012787556317351373
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.007609285121950773
            roll: 0.0
            pitch: 0.0
            yaw: -0.07784036217911985
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.014576274676765422
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.036360753021277274
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07659901026786102
            roll: 0.0
            pitch: 0.0
            yaw: -0.5906289885433937
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.053976899173998165
            roll: 0.0
            pitch: 0.0
            yaw: 0.7765481754076125
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04242318929272615
            roll: 0.0
            pitch: 0.0
            yaw: -0.4174186390840303
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04953406056579923
            roll: 0.0
            pitch: 0.0
            yaw: 1.0064702044068905
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0039496076859086016
            roll: 0.0
            pitch: 0.0
            yaw: -0.0005339024288455452
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.011649485464338347
            roll: 0.0
            pitch: 0.0
            yaw: 0.17153488794433147
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.00045082582461605965
              y: 0.014091992060652345
              z: 0.04242503353317993
              roll: 0.4794548135778929
              pitch: -0.478733936027695
              yaw: 1.3121304118512005
            roll: 0.4416943828834572
            pitch: -0.48811457920324197
            yaw: 1.3193509405899093
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2756535514241928
          y: 0.18859748713128327
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.6264745339468893
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.010725699340083182
            roll: 0.0
            pitch: 0.0
            yaw: 0.06950666720671245
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.014005525974563185
            roll: 0.0
            pitch: 0.0
            yaw: 0.003172336911834772
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.014569021079026113
            roll: 0.0
            pitch: 0.0
            yaw: -0.13054299660085816
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.022534641293834326
            roll: 0.0
            pitch: 0.0
            yaw: 0.15177855571177762
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.006141708282082627
            roll: 0.0
            pitch: 0.0
            yaw: 0.16182733666672722
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.008905109823545365
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03602006757419553
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.038116425809471444
            roll: 0.0
            pitch: 0.0
            yaw: -0.17667993369255386
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09503339393275007
            roll: 0.0
            pitch: 0.0
            yaw: 0.7783339983622979
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.025670475034012985
            roll: 0.0
            pitch: 0.0
            yaw: -0.7789555474099515
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05066903900758587
            roll: 0.0
            pitch: 0.0
            yaw: 0.7486074787472461
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.010584942781160775
            roll: 0.0
            pitch: 0.0
            yaw: -0.6083263824977398
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07192731889289528
            roll: 0.0
            pitch: 0.0
            yaw: -0.48286332114740316
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0012162871875322748
              y: 0.01654605517860455
              z: 0.04062908340453785
              roll: 0.4825146674183936
              pitch: -0.466487905357757
              yaw: 1.304071199613328
            roll: 0.4219778325951098
            pitch: -0.4924742159363197
            yaw: 1.2988099536685067
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.29553421794772655
          y: 0.12986060000186567
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.726102855545323
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.006274643226978974
            roll: 0.0
            pitch: 0.0
            yaw: -0.0834399880333195
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.01787310294088922
            roll: 0.0
            pitch: 0.0
            yaw: 0.1645490038576644
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.011838270249705
            roll: 0.0
            pitch: 0.0
            yaw: -0.018393512471786277
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.014792221360079424
            roll: 0.0
            pitch: 0.0
            yaw: 0.09193343911217061
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.016685798428502027
            roll: 0.0
            pitch: 0.0
            yaw: -0.09842582390745011
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03319368785123269
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04557469015578666
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08291119635199543
            roll: 0.0
            pitch: 0.0
            yaw: 0.13864383978514017
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.06401264355953556
            roll: 0.0
            pitch: 0.0
            yaw: 0.030723384966371725
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.014195080217768316
            roll: 0.0
            pitch: 0.0
            yaw: 0.268902566891962
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.05698552746349517
            roll: 0.0
            pitch: 0.0
            yaw: -0.3026336202645492
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08029622799986613
            roll: 0.0
            pitch: 0.0
            yaw: 0.40760892385602987
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.02939845079023709
            roll: 0.0
            pitch: 0.0
            yaw: -0.6963744814542323
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.00038411466014062973
              y: 0.01519306990521623
              z: 0.042884826628956936
              roll: 0.44996847131291573
              pitch: -0.44845212154218056
              yaw: 1.334002533746113
            roll: 0.47649614187505607
            pitch: -0.45494590851204525
            yaw: 1.3307890750185043
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
