scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.27224636871802566
          y: 0.28151128848992274
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.5110827507181503
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.017988664304337917
            roll: 0.0
            pitch: 0.0
            yaw: 0.10698400926606622
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.022368515481540667
            roll: 0.0
            pitch: 0.0
            yaw: 0.06128971101754657
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.005271461011260355
            roll: 0.0
            pitch: 0.0
            yaw: -0.16534024926629481
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.007943735052803026
            roll: 0.0
            pitch: 0.0
            yaw: 0.011761875307905179
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0032322495275444695
            roll: 0.0
            pitch: 0.0
            yaw: -0.13663908322917034
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.002407884600573222
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.010528178878523566
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08592693412070444
            roll: 0.0
            pitch: 0.0
            yaw: 0.8425544914652456
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09566367401335471
            roll: 0.0
            pitch: 0.0
            yaw: 0.3470215499158582
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.004932569167051856
            roll: 0.0
            pitch: 0.0
            yaw: -0.42041278615342925
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.013805673878932709
            roll: 0.0
            pitch: 0.0
            yaw: 0.6832373590182717
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05275652668079281
            roll: 0.0
            pitch: 0.0
            yaw: -0.7059579136878518
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.09058564347043063
            roll: 0.0
            pitch: 0.0
            yaw: -0.8764922064658704
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0010087585695164472
              y: 0.017034625761040655
              z: 0.04251058400888793
              roll: 0.4558397752176601
              pitch: -0.4915734924142735
              yaw: 1.3330038136173707
            roll: 0.4540059719253475
            pitch: -0.5025181404115031
            yaw: 1.2953781100533137
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.29693055585783773
          y: -0.2706885397226365
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.222067943547236
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.004752058143760014
            roll: 0.0
            pitch: 0.0
            yaw: -0.09912053625453957
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007416299614555224
            roll: 0.0
            pitch: 0.0
            yaw: -0.0075604680038362515
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.019986151949760077
            roll: 0.0
            pitch: 0.0
            yaw: 0.10359201692544923
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.0044422912956419945
            roll: 0.0
            pitch: 0.0
            yaw: -0.10654800500669359
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.016603868569418964
            roll: 0.0
            pitch: 0.0
            yaw: 0.14494569651728023
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.015368212449343957
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.005921381914956954
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.024426676361281194
            roll: 0.0
            pitch: 0.0
            yaw: -0.7788437692622558
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08183808977792474
            roll: 0.0
            pitch: 0.0
            yaw: -0.7667096358803438
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0013199995781584678
            roll: 0.0
            pitch: 0.0
            yaw: -0.6485933491173901
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0901480352867387
            roll: 0.0
            pitch: 0.0
            yaw: 0.4112006559921435
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.022206990080818834
            roll: 0.0
            pitch: 0.0
            yaw: 0.20622454084594333
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.004496432393532521
            roll: 0.0
            pitch: 0.0
            yaw: -0.46460789372150224
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0006110185137998979
              y: 0.014074668831750427
              z: 0.04265844716676
              roll: 0.4611648017006778
              pitch: -0.4753330722317078
              yaw: 1.319545428981468
            roll: 0.4178653420525469
            pitch: -0.45367700491878427
            yaw: 1.313021960431322
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2818987920703916
          y: -0.18679871777231472
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.43431610110011665
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01995802420654015
            roll: 0.0
            pitch: 0.0
            yaw: 0.013638872325788393
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.020706550403206736
            roll: 0.0
            pitch: 0.0
            yaw: -0.17357202428982932
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.002796381669051714
            roll: 0.0
            pitch: 0.0
            yaw: 0.14538318836619007
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.006734521636501657
            roll: 0.0
            pitch: 0.0
            yaw: 0.11315830520525005
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.015950740719837233
            roll: 0.0
            pitch: 0.0
            yaw: 0.10701302928329182
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.054980310961433035
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.006826611711788361
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.057940121088001756
            roll: 0.0
            pitch: 0.0
            yaw: -0.6934812444705887
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.008338686260256176
            roll: 0.0
            pitch: 0.0
            yaw: -0.3185652030860152
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.059181728405042516
            roll: 0.0
            pitch: 0.0
            yaw: 0.6225855156897451
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08687463801934388
            roll: 0.0
            pitch: 0.0
            yaw: -0.6308380122716835
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0023363595987411223
            roll: 0.0
            pitch: 0.0
            yaw: 0.9092548216556682
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04784887572503563
            roll: 0.0
            pitch: 0.0
            yaw: 0.2515612511466303
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0012044083328172305
              y: 0.014283653394816456
              z: 0.04396600258064932
              roll: 0.4089847845244422
              pitch: -0.517235740070862
              yaw: 1.3077455258513782
            roll: 0.4332977310305236
            pitch: -0.49454447283188613
            yaw: 1.3476459070169873
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
