scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.29902469390315517
          y: 0.147796422919393
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.40673039444426573
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.013092209765767186
            roll: 0.0
            pitch: 0.0
            yaw: -0.05531515552634954
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.021255324832331043
            roll: 0.0
            pitch: 0.0
            yaw: 0.13537133011706404
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.009583076708430557
            roll: 0.0
            pitch: 0.0
            yaw: 0.0018009349149355203
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.005044741505728725
            roll: 0.0
            pitch: 0.0
            yaw: 0.148623438149604
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0018138730883143425
            roll: 0.0
            pitch: 0.0
            yaw: -0.11105638389217722
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.047963554085392414
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04418118515171689
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08333117243373919
            roll: 0.0
            pitch: 0.0
            yaw: -0.6990824276195557
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04077539887324421
            roll: 0.0
            pitch: 0.0
            yaw: 0.5961449316411587
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.029716356800736934
            roll: 0.0
            pitch: 0.0
            yaw: -0.021680218908842752
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04571667751001457
            roll: 0.0
            pitch: 0.0
            yaw: -0.8457347450110289
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07526890146368828
            roll: 0.0
            pitch: 0.0
            yaw: -0.38247242511960733
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.028493364843528907
            roll: 0.0
            pitch: 0.0
            yaw: -0.2473668689133559
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00016737919732295794
              y: 0.014966897705925289
              z: 0.043598636583683584
              roll: 0.44648191531724546
              pitch: -0.45213494490679434
              yaw: 1.3020339586020289
            roll: 0.46657578333850835
            pitch: -0.45862906626740063
            yaw: 1.3555802615559873
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.27665719408173217
          y: -0.2610134061237393
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.547978718264277
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.017250397033833235
            roll: 0.0
            pitch: 0.0
            yaw: 0.013055590419801949
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0030641274035459014
            roll: 0.0
            pitch: 0.0
            yaw: -0.07104416032379307
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0008469328478117218
            roll: 0.0
            pitch: 0.0
            yaw: -0.17460629574704223
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.02006811736199679
            roll: 0.0
            pitch: 0.0
            yaw: 0.08959256092825668
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.023210267472108644
            roll: 0.0
            pitch: 0.0
            yaw: 0.034537563224939255
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.029491343694595717
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04536033740614135
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.07168414439515969
            roll: 0.0
            pitch: 0.0
            yaw: -0.18859384628095355
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.09619297110061581
            roll: 0.0
            pitch: 0.0
            yaw: -0.34269130615673926
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.015911684643154386
            roll: 0.0
            pitch: 0.0
            yaw: 0.8275104160886437
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.03155935905760733
            roll: 0.0
            pitch: 0.0
            yaw: -0.7610092308464043
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.04907210771163729
            roll: 0.0
            pitch: 0.0
            yaw: -0.15234520137067586
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.044213026208290596
            roll: 0.0
            pitch: 0.0
            yaw: 0.4361305054874165
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0016092813238807323
              y: 0.013385455266247025
              z: 0.04113286585620237
              roll: 0.4269612750720805
              pitch: -0.517411356747759
              yaw: 1.3662528316850502
            roll: 0.4663416204698116
            pitch: -0.5093814348287552
            yaw: 1.3105556382934869
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2672170002630595
          y: 0.297835576794176
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.1479098456055814
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0027107293870482115
            roll: 0.0
            pitch: 0.0
            yaw: 0.1411099153574793
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007996036693290208
            roll: 0.0
            pitch: 0.0
            yaw: 0.05847733426432067
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01882945149153503
            roll: 0.0
            pitch: 0.0
            yaw: -0.06108875164079847
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.014808190729589235
            roll: 0.0
            pitch: 0.0
            yaw: 0.014954879571404733
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.01086099912107553
            roll: 0.0
            pitch: 0.0
            yaw: -0.10383233059194086
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.006287723766783285
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02468435039059312
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07014225455260575
            roll: 0.0
            pitch: 0.0
            yaw: -0.7199532323022417
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.024958264601851674
            roll: 0.0
            pitch: 0.0
            yaw: 0.9629615023804747
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.013975403227695679
            roll: 0.0
            pitch: 0.0
            yaw: 0.7478431705333872
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.006819862032288196
            roll: 0.0
            pitch: 0.0
            yaw: 0.15001649246686033
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.054029686862039045
            roll: 0.0
            pitch: 0.0
            yaw: 0.49253771286322245
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0053453608347541065
            roll: 0.0
            pitch: 0.0
            yaw: 0.8636793846151376
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0013259665597848138
              y: 0.014969898416074452
              z: 0.041560040766675105
              roll: 0.4807120163973251
              pitch: -0.505455960981743
              yaw: 1.3204908348316367
            roll: 0.41561410422907846
            pitch: -0.47963862093293147
            yaw: 1.319418361386381
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
