scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.1775019520352384
          y: 0.29494538004954013
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.3666961193582532
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0131064981929963
            roll: 0.0
            pitch: 0.0
            yaw: 0.07798935129856832
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.013215629016155639
            roll: 0.0
            pitch: 0.0
            yaw: -0.03673186340639159
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.004889977324794785
            roll: 0.0
            pitch: 0.0
            yaw: -0.06777316987790964
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.007624168458263074
            roll: 0.0
            pitch: 0.0
            yaw: -0.025578377592400503
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.015340980842553484
            roll: 0.0
            pitch: 0.0
            yaw: -0.16464542294249965
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.032785562771420376
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.029543853421389744
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.023993587287598456
            roll: 0.0
            pitch: 0.0
            yaw: -0.1805329079238046
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08463159077627691
            roll: 0.0
            pitch: 0.0
            yaw: -0.41983923827567426
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07760091898372445
            roll: 0.0
            pitch: 0.0
            yaw: -0.7483740430385124
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07464659369729784
            roll: 0.0
            pitch: 0.0
            yaw: 0.3151077471581558
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.05095247554683549
            roll: 0.0
            pitch: 0.0
            yaw: -0.9735290799023889
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0003363884408371931
            roll: 0.0
            pitch: 0.0
            yaw: 0.4773669889833023
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0007682307780380825
              y: 0.015174467597697833
              z: 0.042013942066124826
              roll: 0.48211754791593103
              pitch: -0.47808362871533283
              yaw: 1.3597435822125437
            roll: 0.43472366509447763
            pitch: -0.508859256419694
            yaw: 1.3451996092230416
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2751648341528382
          y: -0.28273504234687447
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.5171534383867331
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.008408054352977801
            roll: 0.0
            pitch: 0.0
            yaw: 0.09678011780909784
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008004612099651504
            roll: 0.0
            pitch: 0.0
            yaw: 0.0069046029530092645
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.008832466408509893
            roll: 0.0
            pitch: 0.0
            yaw: 0.17408777080208998
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.015291256982113074
            roll: 0.0
            pitch: 0.0
            yaw: -0.15597932936110986
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.018598444390463105
            roll: 0.0
            pitch: 0.0
            yaw: 0.10415344731531445
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03739917922555654
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.036945713488579016
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.006428770029324765
            roll: 0.0
            pitch: 0.0
            yaw: 0.35307634730706705
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.06449288414333615
            roll: 0.0
            pitch: 0.0
            yaw: 0.7056903105815937
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.003483097310689104
            roll: 0.0
            pitch: 0.0
            yaw: -0.9417645897079469
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.02804383413307962
            roll: 0.0
            pitch: 0.0
            yaw: -0.8510277352182951
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.015749575670305827
            roll: 0.0
            pitch: 0.0
            yaw: 0.628714319589676
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06990626987222139
            roll: 0.0
            pitch: 0.0
            yaw: 0.24434817427110822
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0008879530491223875
              y: 0.015647949313404505
              z: 0.0410124955580543
              roll: 0.4495867512910029
              pitch: -0.44525854266276943
              yaw: 1.3079225688143372
            roll: 0.4092938281084246
            pitch: -0.5121075827556061
            yaw: 1.3386200250322096
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.22587004856825305
          y: 0.22337420582527473
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.3536957081509944
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.013004691694268747
            roll: 0.0
            pitch: 0.0
            yaw: 0.10510257758066227
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.018159198202105042
            roll: 0.0
            pitch: 0.0
            yaw: 0.0030948724589942578
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.003870593589985854
            roll: 0.0
            pitch: 0.0
            yaw: 0.09483089952995077
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.014047113584987274
            roll: 0.0
            pitch: 0.0
            yaw: 0.13861665800805434
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0019668512050863007
            roll: 0.0
            pitch: 0.0
            yaw: 0.00871506399761146
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.047534623513032614
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.015395472349893205
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07877503465815058
            roll: 0.0
            pitch: 0.0
            yaw: 0.2456542762175946
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09318628013936092
            roll: 0.0
            pitch: 0.0
            yaw: 0.35913543796483727
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.050566145982843536
            roll: 0.0
            pitch: 0.0
            yaw: -0.38882744633626076
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.06751170651809371
            roll: 0.0
            pitch: 0.0
            yaw: -0.2707264636413902
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0008863598493652897
            roll: 0.0
            pitch: 0.0
            yaw: 1.0104423908429652
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.018179530027013543
            roll: 0.0
            pitch: 0.0
            yaw: 0.1411881076684014
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0014483491131919326
              y: 0.014655510602542903
              z: 0.041181702745605696
              roll: 0.40989597580718545
              pitch: -0.4915418934766212
              yaw: 1.3418136472141822
            roll: 0.4699660762282341
            pitch: -0.4632231475743076
            yaw: 1.3062968327230016
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
