scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.24194167910501668
          y: 0.19450124964475235
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.6874248475146767
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0018883083240322021
            roll: 0.0
            pitch: 0.0
            yaw: 0.10813460783590545
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.017479052551709923
            roll: 0.0
            pitch: 0.0
            yaw: -0.1551400885469799
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0001605074243219741
            roll: 0.0
            pitch: 0.0
            yaw: 0.033651672286588136
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.002384096197387449
            roll: 0.0
            pitch: 0.0
            yaw: 0.07978378478999693
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.018387948327105892
            roll: 0.0
            pitch: 0.0
            yaw: -0.0030261001532834453
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.018888078563787852
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03612782920633868
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.02268755279271656
            roll: 0.0
            pitch: 0.0
            yaw: 0.17035467080613786
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.06823740739820006
            roll: 0.0
            pitch: 0.0
            yaw: -0.6309237599880252
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03738315406698492
            roll: 0.0
            pitch: 0.0
            yaw: -0.3883744366308366
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.026738844949205046
            roll: 0.0
            pitch: 0.0
            yaw: 0.5630537902648773
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.025304887766316925
            roll: 0.0
            pitch: 0.0
            yaw: 0.08674615834943866
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07534175371916771
            roll: 0.0
            pitch: 0.0
            yaw: -0.8601227478147574
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0006115949801138135
              y: 0.014196378682119901
              z: 0.041730734138878886
              roll: 0.4055558262570006
              pitch: -0.4576052875230992
              yaw: 1.3160505314015514
            roll: 0.47967108288283666
            pitch: -0.47222950996998625
            yaw: 1.328069557830308
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2975803836466557
          y: 0.2948814336464098
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 3.076330024106986
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.017381346843699592
            roll: 0.0
            pitch: 0.0
            yaw: 0.09692070907928813
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008869506117727508
            roll: 0.0
            pitch: 0.0
            yaw: 0.09784996208950791
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.006398461812993209
            roll: 0.0
            pitch: 0.0
            yaw: -0.06265478033783833
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.013843120408549667
            roll: 0.0
            pitch: 0.0
            yaw: 0.04467068788823958
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.021108319938736006
            roll: 0.0
            pitch: 0.0
            yaw: 0.11004551388702566
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.019346110201189648
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02518095827953981
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08751627577580924
            roll: 0.0
            pitch: 0.0
            yaw: 1.0422693371387475
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.08734286985952108
            roll: 0.0
            pitch: 0.0
            yaw: -0.9935118180903564
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07808763376217576
            roll: 0.0
            pitch: 0.0
            yaw: 0.5458297051326002
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.04837921057477493
            roll: 0.0
            pitch: 0.0
            yaw: -0.3393197588353888
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.044839770398183876
            roll: 0.0
            pitch: 0.0
            yaw: 0.9933567996183201
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.018538701188437645
            roll: 0.0
            pitch: 0.0
            yaw: -0.0584613612962992
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0013007958049272997
              y: 0.015201807209853806
              z: 0.042875411345486794
              roll: 0.4321307785066267
              pitch: -0.5007547943065983
              yaw: 1.339202198453196
            roll: 0.44583385518830343
            pitch: -0.5036409006072686
            yaw: 1.3410692553371155
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.16890967145946567
          y: -0.2835577763151644
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.9939863230322175
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.00394973350526763
            roll: 0.0
            pitch: 0.0
            yaw: 0.12788887817496725
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.008800694725366015
            roll: 0.0
            pitch: 0.0
            yaw: 0.09487796886717598
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.00036598923288682153
            roll: 0.0
            pitch: 0.0
            yaw: -0.1641866687901341
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.003512929198430971
            roll: 0.0
            pitch: 0.0
            yaw: -0.08941641004216572
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.011172314301359185
            roll: 0.0
            pitch: 0.0
            yaw: -0.16658081344471984
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.059112756693845143
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02519745429761064
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.0722721104213285
            roll: 0.0
            pitch: 0.0
            yaw: -0.9810236760613051
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07863828396734536
            roll: 0.0
            pitch: 0.0
            yaw: 0.15521346421137183
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08036719886024277
            roll: 0.0
            pitch: 0.0
            yaw: 0.47935131156653554
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.006617294153001843
            roll: 0.0
            pitch: 0.0
            yaw: -0.6037452382325367
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05311370345869144
            roll: 0.0
            pitch: 0.0
            yaw: 0.2540037758545761
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0078006536744019556
            roll: 0.0
            pitch: 0.0
            yaw: -0.4908693952700409
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0014546893471171413
              y: 0.016706796783685255
              z: 0.04300272207086368
              roll: 0.460311272817304
              pitch: -0.4877321244251404
              yaw: 1.3108327381136065
            roll: 0.44714087304975536
            pitch: -0.45230246102601435
            yaw: 1.3376748735468555
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
