scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2938432878178694
          y: 0.13748850549456643
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.822032479895576
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.02184831866996194
            roll: 0.0
            pitch: 0.0
            yaw: -0.17118117242390735
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.011192998800929485
            roll: 0.0
            pitch: 0.0
            yaw: 0.10511090191158223
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.019965837784385383
            roll: 0.0
            pitch: 0.0
            yaw: 0.010050057303317206
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.015817150041320466
            roll: 0.0
            pitch: 0.0
            yaw: 0.10678889458491475
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.017662355645200016
            roll: 0.0
            pitch: 0.0
            yaw: -0.055428501518255124
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.00029302129052941744
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.017087595754752785
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.052788640233656
            roll: 0.0
            pitch: 0.0
            yaw: -0.9003696633935292
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0898318904747252
            roll: 0.0
            pitch: 0.0
            yaw: 0.8829176500319644
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05588354517622268
            roll: 0.0
            pitch: 0.0
            yaw: 0.911253565038386
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08762699499703519
            roll: 0.0
            pitch: 0.0
            yaw: -0.4731144673520722
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.05666044466516687
            roll: 0.0
            pitch: 0.0
            yaw: 0.6705735679842604
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07609871295452042
            roll: 0.0
            pitch: 0.0
            yaw: -0.758286869545062
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0010383893541859616
              y: 0.014380346088390188
              z: 0.04261317423740944
              roll: 0.4370491038276533
              pitch: -0.44823599706708606
              yaw: 1.3225372033750018
            roll: 0.4481599249431071
            pitch: -0.4846084829135864
            yaw: 1.330391418875811
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.291675297803353
          y: -0.29724265834567454
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.5151887793875352
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0025264668734635495
            roll: 0.0
            pitch: 0.0
            yaw: -0.10782409900801454
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007935406726981478
            roll: 0.0
            pitch: 0.0
            yaw: -0.036303194124851224
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.007561714005760877
            roll: 0.0
            pitch: 0.0
            yaw: -0.09005266208937639
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.021259805174968303
            roll: 0.0
            pitch: 0.0
            yaw: 0.10654682724672943
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.021269763558564955
            roll: 0.0
            pitch: 0.0
            yaw: -0.04133855026207872
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.009365976191608137
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04297025208458652
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.01049333516734248
            roll: 0.0
            pitch: 0.0
            yaw: 0.7760697767835696
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04754401893315538
            roll: 0.0
            pitch: 0.0
            yaw: -0.4105721634331887
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08588471159900546
            roll: 0.0
            pitch: 0.0
            yaw: 0.4421057431763613
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08868993624034871
            roll: 0.0
            pitch: 0.0
            yaw: -0.6129885913643311
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.049277976427050396
            roll: 0.0
            pitch: 0.0
            yaw: -0.619392608940774
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0854200595465811
            roll: 0.0
            pitch: 0.0
            yaw: 0.6611735672254264
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0013900622624837297
              y: 0.014495790528067522
              z: 0.04202431306535923
              roll: 0.44360515886406177
              pitch: -0.5100153693685784
              yaw: 1.3473574640039945
            roll: 0.43962959369822535
            pitch: -0.4974726617272564
            yaw: 1.3089040607749751
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2982788103611276
          y: -0.15393147923853182
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.5750987431801766
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015542400422912609
            roll: 0.0
            pitch: 0.0
            yaw: 0.15759190592361416
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.02072600006628366
            roll: 0.0
            pitch: 0.0
            yaw: 0.1278960284978513
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.0034238363174475574
            roll: 0.0
            pitch: 0.0
            yaw: 0.021631273852129013
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.012912324875199733
            roll: 0.0
            pitch: 0.0
            yaw: -0.14344521188254145
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0160062873825111
            roll: 0.0
            pitch: 0.0
            yaw: -0.082354620235412
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.01618956046913727
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.014811530141178565
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.09426337087094414
            roll: 0.0
            pitch: 0.0
            yaw: 0.8306135309778806
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0019779794086222102
            roll: 0.0
            pitch: 0.0
            yaw: 0.6859904713542289
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.020472500988486075
            roll: 0.0
            pitch: 0.0
            yaw: -0.8821029537907361
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08873356761521473
            roll: 0.0
            pitch: 0.0
            yaw: 0.828004355286668
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0244108945957921
            roll: 0.0
            pitch: 0.0
            yaw: -0.11886183656551597
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.002283994899191691
            roll: 0.0
            pitch: 0.0
            yaw: 0.005418095268264533
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0006158381324112487
              y: 0.016136157045659797
              z: 0.04219282562273311
              roll: 0.4291870677879101
              pitch: -0.4831200874751493
              yaw: 1.321324526773045
            roll: 0.40493482198155134
            pitch: -0.4918783297349149
            yaw: 1.3447343138720045
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
