scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.25847182551409403
          y: -0.2707923592667795
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -1.1477323340989443
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.021591918912985196
            roll: 0.0
            pitch: 0.0
            yaw: 0.10893013516726646
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0016447915881951276
            roll: 0.0
            pitch: 0.0
            yaw: -0.16817590547478717
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.008603858463003326
            roll: 0.0
            pitch: 0.0
            yaw: 0.052645271638065844
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.01409897414467911
            roll: 0.0
            pitch: 0.0
            yaw: -0.1003349700351502
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.011814661922534525
            roll: 0.0
            pitch: 0.0
            yaw: 0.13678903303787016
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.029396614142599697
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.023338697233435214
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05100377843953582
            roll: 0.0
            pitch: 0.0
            yaw: -0.29849665772045475
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04306459940617874
            roll: 0.0
            pitch: 0.0
            yaw: -0.37272624979152735
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05427107414266302
            roll: 0.0
            pitch: 0.0
            yaw: -0.6305920899900628
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.050974293616578015
            roll: 0.0
            pitch: 0.0
            yaw: 0.3811184245284187
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0268721446387008
            roll: 0.0
            pitch: 0.0
            yaw: 0.4605537218858924
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.007979665282239812
            roll: 0.0
            pitch: 0.0
            yaw: -0.8132584212217228
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0018358462903906698
              y: 0.013916797361475424
              z: 0.040572343874639705
              roll: 0.47613806372283685
              pitch: -0.5167709373921774
              yaw: 1.3095809634198419
            roll: 0.42018390623491175
            pitch: -0.5027052571444388
            yaw: 1.3519633543131595
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.20118931182216943
          y: 0.28525181772683456
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.7107629180598964
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.011692628851147038
            roll: 0.0
            pitch: 0.0
            yaw: -0.13727250475751607
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.009302678907249038
            roll: 0.0
            pitch: 0.0
            yaw: 0.09153863940880258
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.005381473173455796
            roll: 0.0
            pitch: 0.0
            yaw: -0.04798493571621623
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.014515593162537217
            roll: 0.0
            pitch: 0.0
            yaw: -0.03552844342136707
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02027826590152358
            roll: 0.0
            pitch: 0.0
            yaw: 0.0886970855841901
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.009733964736200487
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.00538433262917648
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06769784276750769
            roll: 0.0
            pitch: 0.0
            yaw: -0.02190119206936325
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07979698416584372
            roll: 0.0
            pitch: 0.0
            yaw: -0.9420868270589261
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.046670055922448994
            roll: 0.0
            pitch: 0.0
            yaw: -0.313888833234636
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08401917298864402
            roll: 0.0
            pitch: 0.0
            yaw: -0.6999351544383949
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.03181089526921041
            roll: 0.0
            pitch: 0.0
            yaw: -0.6553361334437033
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.022742176420243107
            roll: 0.0
            pitch: 0.0
            yaw: 0.86520084597313
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0004042287056183918
              y: 0.015559234145723824
              z: 0.041732310597336286
              roll: 0.4716259165761978
              pitch: -0.4649762410865219
              yaw: 1.315791782605166
            roll: 0.4667717198779445
            pitch: -0.4543827349323286
            yaw: 1.3083459976651455
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.22783690632698164
          y: -0.26094796334113096
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.7440808099534157
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01062928249865193
            roll: 0.0
            pitch: 0.0
            yaw: 0.005519773662516686
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.019395978657628495
            roll: 0.0
            pitch: 0.0
            yaw: 0.10448412487983638
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.017868402996826918
            roll: 0.0
            pitch: 0.0
            yaw: 0.01895845050008041
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.014791012954313126
            roll: 0.0
            pitch: 0.0
            yaw: 0.1087298961219732
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01800272660504495
            roll: 0.0
            pitch: 0.0
            yaw: -0.03714917018811048
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.033792394247159074
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02855892288032949
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.03330843560664551
            roll: 0.0
            pitch: 0.0
            yaw: -0.9209959031774142
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.003810843689301485
            roll: 0.0
            pitch: 0.0
            yaw: 0.9585792472925625
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06645599689901383
            roll: 0.0
            pitch: 0.0
            yaw: -0.6037985129058894
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.005720135747359106
            roll: 0.0
            pitch: 0.0
            yaw: 0.13705550593206772
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07912792818978573
            roll: 0.0
            pitch: 0.0
            yaw: 0.343582757967821
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03355047082432008
            roll: 0.0
            pitch: 0.0
            yaw: 0.08617307426365217
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0013209113699130697
              y: 0.016300844418840818
              z: 0.040894463303104686
              roll: 0.43992498824128856
              pitch: -0.5207969580439291
              yaw: 1.3244594564207746
            roll: 0.40777305335562514
            pitch: -0.5140448157833302
            yaw: 1.3123350037911825
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
