scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.29962276092575657
          y: -0.2989110889978301
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.7222326551179314
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.009412065483700398
            roll: 0.0
            pitch: 0.0
            yaw: 0.051241548223454
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.006628844256730191
            roll: 0.0
            pitch: 0.0
            yaw: 0.11295729346188749
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.012379437609196317
            roll: 0.0
            pitch: 0.0
            yaw: 0.06229226458102488
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.02167681496291359
            roll: 0.0
            pitch: 0.0
            yaw: 0.16861124626258073
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.019176768861163332
            roll: 0.0
            pitch: 0.0
            yaw: -0.11856870329220125
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.01453863190526343
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03015224609320665
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.09566524644430958
            roll: 0.0
            pitch: 0.0
            yaw: -0.723266029081708
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.0010401813014091488
            roll: 0.0
            pitch: 0.0
            yaw: -0.9270949720323125
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.030138725190104243
            roll: 0.0
            pitch: 0.0
            yaw: -0.23154269806139172
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.043658038460732546
            roll: 0.0
            pitch: 0.0
            yaw: -0.5022901332569069
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.02880286318858169
            roll: 0.0
            pitch: 0.0
            yaw: 0.9290312827028269
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.026446139834586865
            roll: 0.0
            pitch: 0.0
            yaw: -0.38444971882126044
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00041191908791406205
              y: 0.01613314813194712
              z: 0.040915700098438035
              roll: 0.4063823967358579
              pitch: -0.5209245672898936
              yaw: 1.337854837594525
            roll: 0.40612530926993357
            pitch: -0.47355012376509525
            yaw: 1.333406816738937
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2518720859758613
          y: -0.2574088871605256
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.2736197490406678
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.017666532290962697
            roll: 0.0
            pitch: 0.0
            yaw: 0.14560867505239933
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007428371637467294
            roll: 0.0
            pitch: 0.0
            yaw: 0.139918723715368
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.02029553865463658
            roll: 0.0
            pitch: 0.0
            yaw: 0.08513985523525558
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.005614637667546982
            roll: 0.0
            pitch: 0.0
            yaw: 0.1213946734801139
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.012223936550207898
            roll: 0.0
            pitch: 0.0
            yaw: 0.05470904838510632
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.03412842512237418
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0590463376557343
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.005197915546571355
            roll: 0.0
            pitch: 0.0
            yaw: 0.09741892125490415
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05757650202885006
            roll: 0.0
            pitch: 0.0
            yaw: -0.861177616835929
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.039785696613421184
            roll: 0.0
            pitch: 0.0
            yaw: 0.7824295258541718
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08759358920821576
            roll: 0.0
            pitch: 0.0
            yaw: -0.9972272637527296
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08248444700945098
            roll: 0.0
            pitch: 0.0
            yaw: -0.33691485747581273
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.002113722747037597
            roll: 0.0
            pitch: 0.0
            yaw: 0.7101196777803567
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.001918164761673761
              y: 0.01563995624281847
              z: 0.041063379126594766
              roll: 0.46555687565312853
              pitch: -0.46733641342629795
              yaw: 1.3630565113752424
            roll: 0.46645722040050774
            pitch: -0.5018998335560195
            yaw: 1.3422806023543112
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2514128569734044
          y: 0.27462620952941225
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.9999080209247451
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.022982121880019052
            roll: 0.0
            pitch: 0.0
            yaw: 0.0640609090790919
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.02139193928667682
            roll: 0.0
            pitch: 0.0
            yaw: -0.1133985223232482
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.005236088423984937
            roll: 0.0
            pitch: 0.0
            yaw: -0.14112130036799558
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.005851335592820212
            roll: 0.0
            pitch: 0.0
            yaw: -0.14105272176896191
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.000819027701155009
            roll: 0.0
            pitch: 0.0
            yaw: -0.08522883402341794
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05731728037099149
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.011112680105920328
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.08028360396682735
            roll: 0.0
            pitch: 0.0
            yaw: -0.08866918527940093
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.07470928594309045
            roll: 0.0
            pitch: 0.0
            yaw: -0.5718506236581157
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0656641045753875
            roll: 0.0
            pitch: 0.0
            yaw: -0.637610943959859
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08845044649423067
            roll: 0.0
            pitch: 0.0
            yaw: 0.9225557755787142
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.0038803436528821594
            roll: 0.0
            pitch: 0.0
            yaw: 0.7047749042415434
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.029633666359771382
            roll: 0.0
            pitch: 0.0
            yaw: -0.5817211810472831
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0005104105324018899
              y: 0.01679825384734383
              z: 0.04366472365588142
              roll: 0.4312368892268101
              pitch: -0.479906137697494
              yaw: 1.302540110905546
            roll: 0.4781081273141123
            pitch: -0.46274414891040994
            yaw: 1.3013287501005808
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
