scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.266529382472829
          y: -0.2704703529755634
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.745576691352059
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.009184356147069897
            roll: 0.0
            pitch: 0.0
            yaw: 0.12925729713179007
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.002171150433540568
            roll: 0.0
            pitch: 0.0
            yaw: 0.08964920581297625
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01573116566299164
            roll: 0.0
            pitch: 0.0
            yaw: 0.08080477907054479
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0071754151620743965
            roll: 0.0
            pitch: 0.0
            yaw: 0.06684445098329869
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01006013501153754
            roll: 0.0
            pitch: 0.0
            yaw: -0.03528337341313628
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.008680661681712332
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02504672657695048
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06619916928300741
            roll: 0.0
            pitch: 0.0
            yaw: -0.13204190120685522
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.006206646822905587
            roll: 0.0
            pitch: 0.0
            yaw: 0.01571995310043728
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06630216542128561
            roll: 0.0
            pitch: 0.0
            yaw: 0.7709035357498022
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0016264518035828401
            roll: 0.0
            pitch: 0.0
            yaw: -0.6121922373440201
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07847703346778714
            roll: 0.0
            pitch: 0.0
            yaw: -0.6451696456213202
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.02395098985617576
            roll: 0.0
            pitch: 0.0
            yaw: -0.38852599199566473
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0018644646221005372
              y: 0.01425084579238656
              z: 0.04143687986446733
              roll: 0.44344883199901797
              pitch: -0.47878946376161896
              yaw: 1.3284682251272841
            roll: 0.4265002199497008
            pitch: -0.513251895218795
            yaw: 1.3078257882729554
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.27801045452722256
          y: 0.18282856592404134
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.7918274017373825
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.011541420213750674
            roll: 0.0
            pitch: 0.0
            yaw: -0.040388095903537674
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006148058818190846
            roll: 0.0
            pitch: 0.0
            yaw: 0.06133916903098763
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.02298102108832889
            roll: 0.0
            pitch: 0.0
            yaw: 0.1580553252601743
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.023043829369201664
            roll: 0.0
            pitch: 0.0
            yaw: -0.04044139644401873
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02125487478119025
            roll: 0.0
            pitch: 0.0
            yaw: 0.008388757609587044
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0386041850955562
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.018880242194696355
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08273482323694023
            roll: 0.0
            pitch: 0.0
            yaw: 0.2607533014376149
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0701574433543703
            roll: 0.0
            pitch: 0.0
            yaw: -0.6214118396743361
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04751452190489794
            roll: 0.0
            pitch: 0.0
            yaw: -0.221146913765364
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.005791467554779564
            roll: 0.0
            pitch: 0.0
            yaw: -0.31804869819915105
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08185260702739192
            roll: 0.0
            pitch: 0.0
            yaw: 0.3584690672026596
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06236245202247262
            roll: 0.0
            pitch: 0.0
            yaw: 0.08850217093492274
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0003840691644234804
              y: 0.015246855253773417
              z: 0.04069380192113856
              roll: 0.4211219315013749
              pitch: -0.4977034198002028
              yaw: 1.3367011034626401
            roll: 0.42444927883101735
            pitch: -0.4821262005877368
            yaw: 1.3700962663844583
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2701910424918043
          y: 0.21956902963493935
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.3131212007592157
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.021120798151834555
            roll: 0.0
            pitch: 0.0
            yaw: -0.04903064888179254
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.005740344845665039
            roll: 0.0
            pitch: 0.0
            yaw: -0.1256640919107457
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01826920091513397
            roll: 0.0
            pitch: 0.0
            yaw: 0.08817700354827596
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.01574197613352819
            roll: 0.0
            pitch: 0.0
            yaw: 0.06986622043170318
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0023554245282388434
            roll: 0.0
            pitch: 0.0
            yaw: -0.1361991034669341
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0215016967004171
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03835041908787541
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.010668081929977771
            roll: 0.0
            pitch: 0.0
            yaw: -0.18835023682653695
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.010358781511157461
            roll: 0.0
            pitch: 0.0
            yaw: 0.8173061329958866
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.08171105907080232
            roll: 0.0
            pitch: 0.0
            yaw: 0.2616608295517602
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.0788316994442093
            roll: 0.0
            pitch: 0.0
            yaw: -0.2749596607488657
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0331728644827423
            roll: 0.0
            pitch: 0.0
            yaw: -0.8498619515015364
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.0286058243518008
            roll: 0.0
            pitch: 0.0
            yaw: -0.03938370751448472
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -4.476119496854818e-05
              y: 0.015278127097879004
              z: 0.042232972766416535
              roll: 0.4447400085404152
              pitch: -0.45925854529778243
              yaw: 1.2944866429154211
            roll: 0.47924352460675845
            pitch: -0.46379619291926566
            yaw: 1.3592299954119127
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
