scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.29792796016060985
          y: -0.27862442301570456
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -1.4565743765263135
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01907789270489798
            roll: 0.0
            pitch: 0.0
            yaw: 0.06501753505691332
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.002890568801876131
            roll: 0.0
            pitch: 0.0
            yaw: 0.12267873473971885
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.009461088171229792
            roll: 0.0
            pitch: 0.0
            yaw: -0.10321345832350313
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.00014269196341729073
            roll: 0.0
            pitch: 0.0
            yaw: -0.1607929481611551
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01945305905678594
            roll: 0.0
            pitch: 0.0
            yaw: -0.08191408620819231
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0015280919834703421
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.04588741025897593
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.013590314315393023
            roll: 0.0
            pitch: 0.0
            yaw: -0.5675851319778686
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05313604683616338
            roll: 0.0
            pitch: 0.0
            yaw: -0.7254889433698593
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07156751730935768
            roll: 0.0
            pitch: 0.0
            yaw: 0.722573625019006
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.004791677438279976
            roll: 0.0
            pitch: 0.0
            yaw: 0.075011257330174
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07049416639921854
            roll: 0.0
            pitch: 0.0
            yaw: -0.32174362155990244
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04653442469630953
            roll: 0.0
            pitch: 0.0
            yaw: -0.4952624826029991
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0008850793836095482
              y: 0.015795823063538498
              z: 0.04196607753346933
              roll: 0.47475989647805766
              pitch: -0.4569144110410098
              yaw: 1.343032967679957
            roll: 0.46745289440282656
            pitch: -0.5027033171288907
            yaw: 1.3314992409702309
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.27801045452722256
          y: 0.18282856592404134
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.7918274017373825
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.011541420213750674
            roll: 0.0
            pitch: 0.0
            yaw: -0.040388095903537674
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006148058818190846
            roll: 0.0
            pitch: 0.0
            yaw: 0.06133916903098763
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.02298102108832889
            roll: 0.0
            pitch: 0.0
            yaw: 0.1580553252601743
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.023043829369201664
            roll: 0.0
            pitch: 0.0
            yaw: -0.04044139644401873
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02125487478119025
            roll: 0.0
            pitch: 0.0
            yaw: 0.008388757609587044
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0386041850955562
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.018880242194696355
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08273482323694023
            roll: 0.0
            pitch: 0.0
            yaw: 0.2607533014376149
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0701574433543703
            roll: 0.0
            pitch: 0.0
            yaw: -0.6214118396743361
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.04751452190489794
            roll: 0.0
            pitch: 0.0
            yaw: -0.221146913765364
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.005791467554779564
            roll: 0.0
            pitch: 0.0
            yaw: -0.31804869819915105
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08185260702739192
            roll: 0.0
            pitch: 0.0
            yaw: 0.3584690672026596
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.06236245202247262
            roll: 0.0
            pitch: 0.0
            yaw: 0.08850217093492274
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0017520520033543156
              y: 0.01683754716681187
              z: 0.04387872859173596
              roll: 0.4580322755950281
              pitch: -0.4700515773360974
              yaw: 1.3678170429637295
            roll: 0.42444927883101735
            pitch: -0.4821262005877368
            yaw: 1.3700962663844583
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.25203844920137414
          y: 0.23995501761053922
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.338119061420696
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01979578117944705
            roll: 0.0
            pitch: 0.0
            yaw: 0.06447238218830958
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.017628806881170293
            roll: 0.0
            pitch: 0.0
            yaw: 0.06157577779224138
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.005926658384866758
            roll: 0.0
            pitch: 0.0
            yaw: 0.17187969531283215
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.005162101744994214
            roll: 0.0
            pitch: 0.0
            yaw: -0.11063855720381258
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.018843396322081887
            roll: 0.0
            pitch: 0.0
            yaw: -0.05792108298777132
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.000296985975878461
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05451358614744091
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.00048788345896939866
            roll: 0.0
            pitch: 0.0
            yaw: 0.3106972124008973
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08217993232806961
            roll: 0.0
            pitch: 0.0
            yaw: -0.9871222454951524
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02269288378845749
            roll: 0.0
            pitch: 0.0
            yaw: 0.3857654798889847
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.022585605231604577
            roll: 0.0
            pitch: 0.0
            yaw: -0.4469372760083169
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.025886458622348063
            roll: 0.0
            pitch: 0.0
            yaw: 0.9179955179018984
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09219178971205165
            roll: 0.0
            pitch: 0.0
            yaw: -1.0380398716935504
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 0.0016319575757066857
              y: 0.016495148413409683
              z: 0.04067715787937687
              roll: 0.4534961953533761
              pitch: -0.4537267017484439
              yaw: 1.3001531761101688
            roll: 0.45484514877974563
            pitch: -0.44750053938469725
            yaw: 1.3186811099405054
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
