scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2656284665071783
          y: -0.24466345877517542
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.6371630554000047
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0049752121885511535
            roll: 0.0
            pitch: 0.0
            yaw: 0.012405618755013087
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.014096860365368183
            roll: 0.0
            pitch: 0.0
            yaw: -0.044600584108720115
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.021899111231403458
            roll: 0.0
            pitch: 0.0
            yaw: -0.16701283815851053
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.020410310533208763
            roll: 0.0
            pitch: 0.0
            yaw: 0.04284648178851183
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.005187727901767695
            roll: 0.0
            pitch: 0.0
            yaw: -0.12001853311437398
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02922305564408073
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.01077738673601944
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.023890385857954333
            roll: 0.0
            pitch: 0.0
            yaw: 0.05480085425094994
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.025094884588304223
            roll: 0.0
            pitch: 0.0
            yaw: -0.665498771552157
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.029592980286588993
            roll: 0.0
            pitch: 0.0
            yaw: -0.4835838943315671
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.08385954709538966
            roll: 0.0
            pitch: 0.0
            yaw: -0.026811453205746627
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0874825608047203
            roll: 0.0
            pitch: 0.0
            yaw: -0.9454430141756466
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.023018691672237593
            roll: 0.0
            pitch: 0.0
            yaw: -0.2894529284356919
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.0010230410796751915
              y: 0.014576862681397004
              z: 0.04120965129822586
              roll: 0.4794046633906295
              pitch: -0.5114293963658257
              yaw: 1.2944398907001762
            roll: 0.4296286755848187
            pitch: -0.4420117497723788
            yaw: 1.295401679140051
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_2
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2747744205943988
          y: -0.2831425643588881
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.4334163863789766
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.011250055640131998
            roll: 0.0
            pitch: 0.0
            yaw: -0.08142243052407351
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.0162042226588661
            roll: 0.0
            pitch: 0.0
            yaw: 0.04201248359140122
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.01978701664640046
            roll: 0.0
            pitch: 0.0
            yaw: 0.1333320888930387
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.003870879285636182
            roll: 0.0
            pitch: 0.0
            yaw: -0.07827640755141242
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.019876931570329152
            roll: 0.0
            pitch: 0.0
            yaw: -0.021964675144929724
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.003919123399419938
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03620786309431302
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.03016917924466632
            roll: 0.0
            pitch: 0.0
            yaw: -0.200520974238954
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.053375867513382726
            roll: 0.0
            pitch: 0.0
            yaw: -0.8588357407249647
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0264991908445463
            roll: 0.0
            pitch: 0.0
            yaw: 0.8558561870127632
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.0630676704255207
            roll: 0.0
            pitch: 0.0
            yaw: 0.587323963548082
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06804784788022403
            roll: 0.0
            pitch: 0.0
            yaw: 0.5095608355157704
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08302943507953903
            roll: 0.0
            pitch: 0.0
            yaw: -0.6593828581544923
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.000698403730275193
              y: 0.013789836287341001
              z: 0.04045516886616406
              roll: 0.4450126406497224
              pitch: -0.4997794471505189
              yaw: 1.302583195224708
            roll: 0.4121387619954624
            pitch: -0.47555131880198404
            yaw: 1.306566544977136
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.24800113187173858
          y: 0.28371933579618686
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.280782804738144
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.0013931389289617811
            roll: 0.0
            pitch: 0.0
            yaw: -0.10984142854541519
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0007228473397338057
            roll: 0.0
            pitch: 0.0
            yaw: 0.055647107792653194
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.019387149318680408
            roll: 0.0
            pitch: 0.0
            yaw: -0.023272736254528498
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.019904457970309486
            roll: 0.0
            pitch: 0.0
            yaw: 0.07144248795755706
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.018176274176613768
            roll: 0.0
            pitch: 0.0
            yaw: 0.08785433515742103
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.031357103876168406
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03874538255764484
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06966772401453511
            roll: 0.0
            pitch: 0.0
            yaw: -0.687513359934014
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.04312931921661012
            roll: 0.0
            pitch: 0.0
            yaw: 0.525158081669127
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.02099492244479198
            roll: 0.0
            pitch: 0.0
            yaw: 0.2566879790681542
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.05589504836914234
            roll: 0.0
            pitch: 0.0
            yaw: -0.7788432733552413
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.016001056123982144
            roll: 0.0
            pitch: 0.0
            yaw: -0.9397471260332204
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.06180118264532691
            roll: 0.0
            pitch: 0.0
            yaw: -0.6026519853947319
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0008009816076097955
              y: 0.01643509431655424
              z: 0.04066363461978513
              roll: 0.4629300255515212
              pitch: -0.5129001683813882
              yaw: 1.2964889946804083
            roll: 0.414759417180363
            pitch: -0.4677382545728018
            yaw: 1.3572966520648893
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
