scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2589838554501311
          y: -0.21309997669803588
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.7179076288483124
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.023127509016984106
            roll: 0.0
            pitch: 0.0
            yaw: -0.0612986439466781
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.008190470513805713
            roll: 0.0
            pitch: 0.0
            yaw: 0.05126484602716122
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.011430316437664928
            roll: 0.0
            pitch: 0.0
            yaw: 0.043732961287150623
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.009331538332881108
            roll: 0.0
            pitch: 0.0
            yaw: -0.13067729832245872
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.017069559973090967
            roll: 0.0
            pitch: 0.0
            yaw: 0.1128707394154772
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05316272187445219
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.025542059518964835
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.07065394444635933
            roll: 0.0
            pitch: 0.0
            yaw: -0.45091515203834054
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05596808951667464
            roll: 0.0
            pitch: 0.0
            yaw: -0.7592840427769236
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09447992847575021
            roll: 0.0
            pitch: 0.0
            yaw: -0.690969781820996
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.024007295673200632
            roll: 0.0
            pitch: 0.0
            yaw: -0.42078946123859606
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.051985725190127036
            roll: 0.0
            pitch: 0.0
            yaw: -0.15827804168534676
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.043323485970706
            roll: 0.0
            pitch: 0.0
            yaw: -0.9062479586461625
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0007167151429299699
              y: 0.01627033596676116
              z: 0.04256531354222173
              roll: 0.45761057275477146
              pitch: -0.5214715766815416
              yaw: 1.2935741748156748
            roll: 0.44094466599169563
            pitch: -0.48351877459451414
            yaw: 1.3588354741752753
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.21184175408894867
          y: -0.2938856992994702
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 2.3390175753851246
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.007497575206876987
            roll: 0.0
            pitch: 0.0
            yaw: 0.08518207818000578
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.013994673031521746
            roll: 0.0
            pitch: 0.0
            yaw: 0.010361010954528294
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.018167539227512554
            roll: 0.0
            pitch: 0.0
            yaw: 0.12791746648812086
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: -0.008671908128219516
            roll: 0.0
            pitch: 0.0
            yaw: -0.043026122889061186
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.014076403533416753
            roll: 0.0
            pitch: 0.0
            yaw: -0.14143122729245003
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0017059499364529829
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.026097291812225226
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05808596667307298
            roll: 0.0
            pitch: 0.0
            yaw: -1.0410059474778182
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.016021536193132388
            roll: 0.0
            pitch: 0.0
            yaw: 0.8875443111642864
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.09246074964621362
            roll: 0.0
            pitch: 0.0
            yaw: -0.6555210706512002
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.007306520272495426
            roll: 0.0
            pitch: 0.0
            yaw: -0.6829049404774523
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.037547518807739544
            roll: 0.0
            pitch: 0.0
            yaw: 0.5614502990665615
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03669427550547644
            roll: 0.0
            pitch: 0.0
            yaw: 0.8165464118080621
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0006800578486318466
              y: 0.01373591752803765
              z: 0.04393138808814071
              roll: 0.42141847857420006
              pitch: -0.4441693678924564
              yaw: 1.323433934331179
            roll: 0.4732553776090323
            pitch: -0.4846336060328053
            yaw: 1.3396905533458219
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2385844740413682
          y: 0.23956649453750495
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.1699073006795846
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.00374404988492261
            roll: 0.0
            pitch: 0.0
            yaw: -0.17070360764291892
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.01967493679641763
            roll: 0.0
            pitch: 0.0
            yaw: 0.018907404289307123
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.009969342797240944
            roll: 0.0
            pitch: 0.0
            yaw: -0.01977617198073839
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.015627734788507007
            roll: 0.0
            pitch: 0.0
            yaw: 0.11132555036793307
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.019518360046908517
            roll: 0.0
            pitch: 0.0
            yaw: -0.1310469756492859
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0064053332587497985
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.007815386553169046
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.020801114766082707
            roll: 0.0
            pitch: 0.0
            yaw: 0.4965936409629683
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08219803333494702
            roll: 0.0
            pitch: 0.0
            yaw: 0.9497900552934873
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06671698942669185
            roll: 0.0
            pitch: 0.0
            yaw: -0.0384380967615896
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.01724938115874386
            roll: 0.0
            pitch: 0.0
            yaw: -0.7763431284295764
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.002855344192845735
            roll: 0.0
            pitch: 0.0
            yaw: 0.0986558528338437
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.015581820720362322
            roll: 0.0
            pitch: 0.0
            yaw: -0.5534551533670902
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0015536720189555323
              y: 0.01415379624961337
              z: 0.04074214694170791
              roll: 0.4040371518503815
              pitch: -0.4506222952039056
              yaw: 1.3019061708756516
            roll: 0.4126647763877125
            pitch: -0.4611914624218859
            yaw: 1.3327822590384384
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
