scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.27458058618093933
          y: -0.2923717078914561
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.6841873932271931
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01568277643591602
            roll: 0.0
            pitch: 0.0
            yaw: -0.07928359404010094
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.013642018630532549
            roll: 0.0
            pitch: 0.0
            yaw: 0.06930529017448667
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.003533461795471142
            roll: 0.0
            pitch: 0.0
            yaw: -0.06615014774405713
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.014168128971289426
            roll: 0.0
            pitch: 0.0
            yaw: -0.08511286378881973
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.02137081643126886
            roll: 0.0
            pitch: 0.0
            yaw: 0.09581911563646223
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.012583126007539608
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.04594905182634458
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08745714606598522
            roll: 0.0
            pitch: 0.0
            yaw: -0.5337578385307862
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.05249098473549614
            roll: 0.0
            pitch: 0.0
            yaw: 0.5087046770065946
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.049366884617162654
            roll: 0.0
            pitch: 0.0
            yaw: -1.0312962948146567
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08251263772225428
            roll: 0.0
            pitch: 0.0
            yaw: -0.17824181297719255
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.08580988566187697
            roll: 0.0
            pitch: 0.0
            yaw: 0.9254251969391143
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.005483161956222685
            roll: 0.0
            pitch: 0.0
            yaw: -0.05410150562027716
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0009129698604389209
              y: 0.013800765737462885
              z: 0.04253214337133054
              roll: 0.41073664734259197
              pitch: -0.49016680124732775
              yaw: 1.3354613361853824
            roll: 0.4135079295042353
            pitch: -0.44457561369381393
            yaw: 1.3220108251953413
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.24286172630191838
          y: -0.2581762409925486
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 1.9952304958999418
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01932362559577201
            roll: 0.0
            pitch: 0.0
            yaw: -0.11040049300472678
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.019664676189350895
            roll: 0.0
            pitch: 0.0
            yaw: 0.016730543903577588
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.008293107683219468
            roll: 0.0
            pitch: 0.0
            yaw: -0.0026595973250779226
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0022864464172902173
            roll: 0.0
            pitch: 0.0
            yaw: -0.05389837298718361
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01332165369938551
            roll: 0.0
            pitch: 0.0
            yaw: -0.1349536167364652
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05766039841775327
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.00787872913210684
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.06189454819202883
            roll: 0.0
            pitch: 0.0
            yaw: -0.7001314382905572
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.09325079039173625
            roll: 0.0
            pitch: 0.0
            yaw: -0.8945406371960349
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.04445788705023883
            roll: 0.0
            pitch: 0.0
            yaw: -0.09620103367804789
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06417104354263307
            roll: 0.0
            pitch: 0.0
            yaw: 0.06299666745217536
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0747677796782722
            roll: 0.0
            pitch: 0.0
            yaw: -0.6259117977770254
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.09581940458505325
            roll: 0.0
            pitch: 0.0
            yaw: -0.06784788660479502
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0003147009629078225
              y: 0.0143812723074313
              z: 0.0409677261715605
              roll: 0.4254543333836368
              pitch: -0.46999184699820523
              yaw: 1.3487811257463225
            roll: 0.41774581143476297
            pitch: -0.47844845087693105
            yaw: 1.3553414464725468
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2862492827125059
          y: 0.2983815188562657
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.9413020935153789
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.021351010306814897
            roll: 0.0
            pitch: 0.0
            yaw: 0.07154713511156999
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.010369694846867825
            roll: 0.0
            pitch: 0.0
            yaw: -0.019109386304232034
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.009612568135929974
            roll: 0.0
            pitch: 0.0
            yaw: -0.08784971341464728
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.012856724900807318
            roll: 0.0
            pitch: 0.0
            yaw: 0.1731861390454026
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.019895758142571145
            roll: 0.0
            pitch: 0.0
            yaw: 0.17486492651466762
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.027955265228038553
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.026559700218359836
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0619097642970399
            roll: 0.0
            pitch: 0.0
            yaw: 0.2917598996954498
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.03452653959820059
            roll: 0.0
            pitch: 0.0
            yaw: 0.9738595417706735
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.03162903412904289
            roll: 0.0
            pitch: 0.0
            yaw: -0.49659331674588114
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.018080157251866735
            roll: 0.0
            pitch: 0.0
            yaw: 0.5552347176183772
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.07770212243205413
            roll: 0.0
            pitch: 0.0
            yaw: 1.0209992484708843
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.09539008811718078
            roll: 0.0
            pitch: 0.0
            yaw: -0.26748730876746796
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0006839930634945585
              y: 0.016067756053633177
              z: 0.0434717213318032
              roll: 0.48139014127104296
              pitch: -0.4481688505918326
              yaw: 1.3074315551141964
            roll: 0.46905327155961496
            pitch: -0.48185815685062844
            yaw: 1.329383737552803
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
