scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.27136119612321424
          y: 0.2313196406951244
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.5611313307933163
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.012763141343297715
            roll: 0.0
            pitch: 0.0
            yaw: 0.006908608237487596
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.016884133459255296
            roll: 0.0
            pitch: 0.0
            yaw: 0.14062030742813142
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0029541198016024457
            roll: 0.0
            pitch: 0.0
            yaw: 0.16841844254132465
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0035222447615763236
            roll: 0.0
            pitch: 0.0
            yaw: 0.013168810874572418
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.008175093175996734
            roll: 0.0
            pitch: 0.0
            yaw: -0.0987829285832623
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.01567091740295512
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05472772896800962
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.023669306468333
            roll: 0.0
            pitch: 0.0
            yaw: -0.9160596223960908
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.013805981563694877
            roll: 0.0
            pitch: 0.0
            yaw: -0.9971030581103911
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06863039115363129
            roll: 0.0
            pitch: 0.0
            yaw: 0.8237602175030898
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07121791006138123
            roll: 0.0
            pitch: 0.0
            yaw: 0.9477782268551203
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.020612587390157255
            roll: 0.0
            pitch: 0.0
            yaw: 0.6923704062158915
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03202228926268871
            roll: 0.0
            pitch: 0.0
            yaw: 0.6236550209019613
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 4.872880413505894e-05
              y: 0.016474147855268382
              z: 0.043626375295827295
              roll: 0.46488817451647824
              pitch: -0.47992164384674285
              yaw: 1.3253270117992695
            roll: 0.4328610100696673
            pitch: -0.48457900432157575
            yaw: 1.3204749833164504
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.21396129369629477
          y: 0.24535627291280765
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.5284634071035454
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.019147393296884987
            roll: 0.0
            pitch: 0.0
            yaw: 0.14935327496212308
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.002909588389429219
            roll: 0.0
            pitch: 0.0
            yaw: -0.06534411454219309
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.004925316922651517
            roll: 0.0
            pitch: 0.0
            yaw: -0.15012106302284678
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.000700680479081086
            roll: 0.0
            pitch: 0.0
            yaw: -0.16304338593875153
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.010131986679425848
            roll: 0.0
            pitch: 0.0
            yaw: -0.14532254737614886
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.008975150609014541
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05484542902158549
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.06382948230888155
            roll: 0.0
            pitch: 0.0
            yaw: 0.5390173264475862
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.06470227950241475
            roll: 0.0
            pitch: 0.0
            yaw: -0.7612646172038853
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.07624329929540516
            roll: 0.0
            pitch: 0.0
            yaw: -0.1116103353512996
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.014723489565640943
            roll: 0.0
            pitch: 0.0
            yaw: 0.9536827480800196
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.012924791511491354
            roll: 0.0
            pitch: 0.0
            yaw: 1.0000661500197723
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03104627262875788
            roll: 0.0
            pitch: 0.0
            yaw: -0.20806369025877425
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0013601463099571914
              y: 0.01469516219665496
              z: 0.04290760631711262
              roll: 0.4233549329512651
              pitch: -0.47724339869810173
              yaw: 1.3183213046300837
            roll: 0.4344335106959725
            pitch: -0.5038290079166028
            yaw: 1.3217869411861045
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2937471262639309
          y: -0.15048077993666145
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.34149935096427475
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.01630852907116561
            roll: 0.0
            pitch: 0.0
            yaw: -0.06645117504831695
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.007512255190698893
            roll: 0.0
            pitch: 0.0
            yaw: 0.08512177185270603
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.006187344945633246
            roll: 0.0
            pitch: 0.0
            yaw: -0.11371760642274974
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0086484183207042
            roll: 0.0
            pitch: 0.0
            yaw: 0.14830170061754255
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.003454850789498344
            roll: 0.0
            pitch: 0.0
            yaw: -0.0809408805122844
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.01801751064371472
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.020817086970499943
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.08475835676357477
            roll: 0.0
            pitch: 0.0
            yaw: 0.0347215783955559
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.0925888844420373
            roll: 0.0
            pitch: 0.0
            yaw: 0.2879515931436354
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.08834948012990529
            roll: 0.0
            pitch: 0.0
            yaw: 0.035785996415877985
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.030939224493076817
            roll: 0.0
            pitch: 0.0
            yaw: 0.49720548645689155
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.09070340968501012
            roll: 0.0
            pitch: 0.0
            yaw: 0.7190635363986624
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.0733679351615915
            roll: 0.0
            pitch: 0.0
            yaw: -0.3262837682254248
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0004792180023073401
              y: 0.01410888282443414
              z: 0.04287344788427337
              roll: 0.4446127349558493
              pitch: -0.49492761739818214
              yaw: 1.297317443473095
            roll: 0.45599004642599844
            pitch: -0.5145532075963563
            yaw: 1.2992623351878816
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
