scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.2560331000373381
          y: -0.22216726815976415
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.9658598535717631
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.01656322953355948
            roll: 0.0
            pitch: 0.0
            yaw: 0.16010896196540458
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0026053789248845563
            roll: 0.0
            pitch: 0.0
            yaw: 0.0013171518778146707
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: 0.02020484140627933
            roll: 0.0
            pitch: 0.0
            yaw: 0.13598263060953375
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.006454647780548953
            roll: 0.0
            pitch: 0.0
            yaw: -0.17462513029759233
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.010786498347819931
            roll: 0.0
            pitch: 0.0
            yaw: -0.16474891327830227
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05144110610869655
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03471772887412597
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.045394504203402075
            roll: 0.0
            pitch: 0.0
            yaw: 0.7836222852181376
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07611753591752132
            roll: 0.0
            pitch: 0.0
            yaw: -0.3097792768658666
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.07028021436343809
            roll: 0.0
            pitch: 0.0
            yaw: -0.6434080242240918
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.043503499436465254
            roll: 0.0
            pitch: 0.0
            yaw: -0.024849322966223886
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.04329720194446713
            roll: 0.0
            pitch: 0.0
            yaw: -0.654793786081308
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.035106635908330935
            roll: 0.0
            pitch: 0.0
            yaw: 0.36266279994875594
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: 0.001784026381480328
              y: 0.013461422188692562
              z: 0.04061188131837704
              roll: 0.4807919438414292
              pitch: -0.49151520430421763
              yaw: 1.3644670863361024
            roll: 0.4455830019436675
            pitch: -0.5090775614413015
            yaw: 1.3132645218390506
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.29602333469935377
          y: -0.2313241750532135
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.9167221145224924
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.015418655936285204
            roll: 0.0
            pitch: 0.0
            yaw: -0.031234667339150757
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.006997227372718521
            roll: 0.0
            pitch: 0.0
            yaw: -0.08736787642270817
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.012296704357174873
            roll: 0.0
            pitch: 0.0
            yaw: -0.00206712882979726
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.007295914879642549
            roll: 0.0
            pitch: 0.0
            yaw: 0.051315804900275014
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.007098066566690021
            roll: 0.0
            pitch: 0.0
            yaw: -0.06918485894699722
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.0043406832391080855
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.014432103753759494
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05761084080486713
            roll: 0.0
            pitch: 0.0
            yaw: -0.6427239974143417
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.04308984933120737
            roll: 0.0
            pitch: 0.0
            yaw: -0.9817192816635956
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.09098476533514285
            roll: 0.0
            pitch: 0.0
            yaw: 0.4136156586598958
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.04597833006366173
            roll: 0.0
            pitch: 0.0
            yaw: 0.8371986813824444
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: 0.02785397911728936
            roll: 0.0
            pitch: 0.0
            yaw: -0.0031752306183412404
        sc_mount_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07612849571693525
            roll: 0.0
            pitch: 0.0
            yaw: 1.0206586568341465
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0019259214796451976
              y: 0.015303248016890876
              z: 0.04078562087894775
              roll: 0.482648364699064
              pitch: -0.44915131037585115
              yaw: 1.3454512071718396
            roll: 0.46531829851204165
            pitch: -0.5096239615235896
            yaw: 1.3315105989679326
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_4
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2653080325300682
          y: 0.22120570262239098
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.7180429612679506
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: 0.012618233597396146
            roll: 0.0
            pitch: 0.0
            yaw: 0.10699786219282836
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.00375385450081131
            roll: 0.0
            pitch: 0.0
            yaw: -0.044505690571159245
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.0037981285636823625
            roll: 0.0
            pitch: 0.0
            yaw: -0.026239547521193257
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.019662696807034176
            roll: 0.0
            pitch: 0.0
            yaw: -0.051301162820020604
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.01587912174579635
            roll: 0.0
            pitch: 0.0
            yaw: 0.14686302465904622
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.012882734519972579
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.058863736151098946
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.05709471498814725
            roll: 0.0
            pitch: 0.0
            yaw: -0.30409448783907866
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.029422283043087694
            roll: 0.0
            pitch: 0.0
            yaw: 0.83283597595486
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.06738411805496411
            roll: 0.0
            pitch: 0.0
            yaw: -0.22801634988376662
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.046797125653158356
            roll: 0.0
            pitch: 0.0
            yaw: 0.7708728067836785
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.0648934657405264
            roll: 0.0
            pitch: 0.0
            yaw: 0.2759951289404108
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.07783336678582861
            roll: 0.0
            pitch: 0.0
            yaw: 0.8158270812725406
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.0011402813694849686
              y: 0.01456790701598606
              z: 0.041795643538165166
              roll: 0.4773434079163171
              pitch: -0.46570759392040456
              yaw: 1.3087924644675508
            roll: 0.44388744585433526
            pitch: -0.4943315496668505
            yaw: 1.3597497740504225
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_0
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
