scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.21584017654301965
          y: 0.28965652371782497
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.023951048763988
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.020054636606470243
            roll: 0.0
            pitch: 0.0
            yaw: -0.0644612084204998
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: 0.010052797526608918
            roll: 0.0
            pitch: 0.0
            yaw: 0.12878112758716592
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.021428596369020822
            roll: 0.0
            pitch: 0.0
            yaw: -0.16884972923402725
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.018827728739950825
            roll: 0.0
            pitch: 0.0
            yaw: 0.055512398167404414
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: -0.021470039325979105
            roll: 0.0
            pitch: 0.0
            yaw: 0.07397149008092005
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0004887418847213457
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.03336546000003851
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.015740630948131787
            roll: 0.0
            pitch: 0.0
            yaw: 0.5821112569674152
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: -0.054280544935448254
            roll: 0.0
            pitch: 0.0
            yaw: -0.6986869055741124
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.008259945148617581
            roll: 0.0
            pitch: 0.0
            yaw: -0.9468054032989469
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09492844920373861
            roll: 0.0
            pitch: 0.0
            yaw: -0.6647795189873857
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08835745958458778
            roll: 0.0
            pitch: 0.0
            yaw: -0.3840242989526794
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.022858684044722327
            roll: 0.0
            pitch: 0.0
            yaw: -0.2027596598168453
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.001995838983008696
              y: 0.016643752032986167
              z: 0.04181015253403959
              roll: 0.43276075348449583
              pitch: -0.5152172605480587
              yaw: 1.3354023638606762
            roll: 0.4798041933246727
            pitch: -0.5183992478140499
            yaw: 1.3463445701735182
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.29489948134240385
          y: -0.2502510868380116
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.6740481126419766
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.012265764569658673
            roll: 0.0
            pitch: 0.0
            yaw: 0.09434872286218643
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.0033651947334836715
            roll: 0.0
            pitch: 0.0
            yaw: 0.0726236763997247
        nic_rail_2:
          entity_present: True
          entity_name: nic_card_2
          entity_pose:
            translation: -0.012665560175333969
            roll: 0.0
            pitch: 0.0
            yaw: -0.015448620627487808
        nic_rail_3:
          entity_present: True
          entity_name: nic_card_3
          entity_pose:
            translation: 0.017853503971790426
            roll: 0.0
            pitch: 0.0
            yaw: -0.018991613180884437
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0020246902011512614
            roll: 0.0
            pitch: 0.0
            yaw: -0.15549861872935136
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0037224933928016596
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.05357192900218094
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: 0.0442914088962989
            roll: 0.0
            pitch: 0.0
            yaw: 0.26134396940717397
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.025504043831668016
            roll: 0.0
            pitch: 0.0
            yaw: -0.9778869487124539
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.05387659326998728
            roll: 0.0
            pitch: 0.0
            yaw: -0.8006812285802563
        lc_mount_rail_1:
          entity_present: True
          entity_name: lc_mount_1
          entity_pose:
            translation: -0.06197237237132233
            roll: 0.0
            pitch: 0.0
            yaw: -0.12170950720272955
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.01173558061943171
            roll: 0.0
            pitch: 0.0
            yaw: 0.35286903868480457
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.05902677568787425
            roll: 0.0
            pitch: 0.0
            yaw: -0.48013132242420387
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0009297886855998887
              y: 0.014956287949649441
              z: 0.041227052191720494
              roll: 0.43204887978873663
              pitch: -0.48157663603873324
              yaw: 1.3315285642475245
            roll: 0.43434197556457377
            pitch: -0.45518765285345564
            yaw: 1.3078517412788861
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_0
        target_module_name: nic_card_mount_3
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2135193153460126
          y: 0.29144693781669745
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -2.527134044063078
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: -0.016851215113958467
            roll: 0.0
            pitch: 0.0
            yaw: -0.015901832521258485
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.014057004942363026
            roll: 0.0
            pitch: 0.0
            yaw: -0.08948466074769908
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.020332163629934973
            roll: 0.0
            pitch: 0.0
            yaw: 0.07623154478501831
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.010393402817270105
            roll: 0.0
            pitch: 0.0
            yaw: -0.14797317349897027
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.018374493140110762
            roll: 0.0
            pitch: 0.0
            yaw: -0.10984075346832849
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.043307004856719136
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03139775853836988
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.01950200421744895
            roll: 0.0
            pitch: 0.0
            yaw: 0.4270664609695738
        sfp_mount_rail_0:
          entity_present: True
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.036905578531299804
            roll: 0.0
            pitch: 0.0
            yaw: 0.08179802318865081
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.06648386222737075
            roll: 0.0
            pitch: 0.0
            yaw: 0.8682279897250964
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.08585068294595644
            roll: 0.0
            pitch: 0.0
            yaw: -0.9275941074106577
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.06699759933495701
            roll: 0.0
            pitch: 0.0
            yaw: -1.0149896929891407
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.07419173188564533
            roll: 0.0
            pitch: 0.0
            yaw: -0.0775461956188852
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: 2.9366692679980936e-05
              y: 0.015026838921773398
              z: 0.04089210317433706
              roll: 0.4654716471286619
              pitch: -0.5036237942454
              yaw: 1.3236227254942816
            roll: 0.4405186074519535
            pitch: -0.4435023512411965
            yaw: 1.2935822204134058
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
