scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
      latched: True
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  nic_rail:
    min_translation: -0.0215
    max_translation: 0.0234
  sc_rail:
    min_translation: -0.06
    max_translation: 0.055
  mount_rail:
    min_translation: -0.09425
    max_translation: 0.09425
trials:
  trial_1:
    scene:
      task_board:
        pose:
          x: 0.26493767488025544
          y: 0.1689837230135614
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: 0.6184808988588806
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.012877492861361674
            roll: 0.0
            pitch: 0.0
            yaw: -0.09586098132711669
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: 0.011136432179892977
            roll: 0.0
            pitch: 0.0
            yaw: -0.1361210541444119
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: -0.01784205944897782
            roll: 0.0
            pitch: 0.0
            yaw: 0.035240953446319195
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: 0.0021571885805082153
            roll: 0.0
            pitch: 0.0
            yaw: -0.08816783086952316
        nic_rail_4:
          entity_present: True
          entity_name: nic_card_4
          entity_pose:
            translation: 0.0005864882542540688
            roll: 0.0
            pitch: 0.0
            yaw: 0.11354846292619297
        sc_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.05421681672542751
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.007825435790962239
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.09092015964271408
            roll: 0.0
            pitch: 0.0
            yaw: 0.6099671025811311
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.07323579692589705
            roll: 0.0
            pitch: 0.0
            yaw: 0.013764188075463757
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.027058324905427797
            roll: 0.0
            pitch: 0.0
            yaw: -0.12528616041947482
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.09056152849247143
            roll: 0.0
            pitch: 0.0
            yaw: 0.9985728901869348
        sfp_mount_rail_1:
          entity_present: True
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.08801503304935085
            roll: 0.0
            pitch: 0.0
            yaw: 0.911201638896318
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.027790075397657668
            roll: 0.0
            pitch: 0.0
            yaw: -0.7044925081841151
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.0014340834873377236
              y: 0.01666075336034919
              z: 0.0444419286130157
              roll: 0.40615996930428244
              pitch: -0.47455853483685995
              yaw: 1.295456039997866
            roll: 0.41506968150195056
            pitch: -0.4817632065838404
            yaw: 1.2949289056312787
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      task_board:
        pose:
          x: 0.2970040317705129
          y: -0.289064796870306
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -1.5171453192702253
        nic_rail_0:
          entity_present: True
          entity_name: nic_card_0
          entity_pose:
            translation: 0.010368849966956611
            roll: 0.0
            pitch: 0.0
            yaw: -0.08946250004502833
        nic_rail_1:
          entity_present: True
          entity_name: nic_card_1
          entity_pose:
            translation: -0.00729360646437186
            roll: 0.0
            pitch: 0.0
            yaw: -0.06501850015689396
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.021599726057497326
            roll: 0.0
            pitch: 0.0
            yaw: -0.08801705705850019
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.003569672175534583
            roll: 0.0
            pitch: 0.0
            yaw: 0.0598796877501335
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: 0.007382106059228354
            roll: 0.0
            pitch: 0.0
            yaw: 0.030770308982181083
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.026281193851000972
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.004062020537411129
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: False
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.042142045480873865
            roll: 0.0
            pitch: 0.0
            yaw: -0.9530405296698347
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.046959941873765204
            roll: 0.0
            pitch: 0.0
            yaw: -0.2843808938192709
        sc_mount_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.013053681782468615
            roll: 0.0
            pitch: 0.0
            yaw: -0.11893152700163145
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.07243631801250539
            roll: 0.0
            pitch: 0.0
            yaw: -1.003368920581068
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.07382288793222208
            roll: 0.0
            pitch: 0.0
            yaw: -0.12375664850151225
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.09605992798674706
            roll: 0.0
            pitch: 0.0
            yaw: -0.37240712231636053
      cables:
        cable_0:
          pose:
            gripper_offset:
              x: -0.00017785548128420193
              y: 0.014200162613392162
              z: 0.044220755475767176
              roll: 0.44624342875569956
              pitch: -0.46040634810215725
              yaw: 1.361876275650134
            roll: 0.4377744137949723
            pitch: -0.4716714068488538
            yaw: 1.3066167566609825
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_0
        plug_type: sfp
        plug_name: sfp_tip
        port_type: sfp
        port_name: sfp_port_1
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_3:
    scene:
      task_board:
        pose:
          x: 0.2792207595005689
          y: -0.28745091090156283
          z: 1.14
          roll: 0.0
          pitch: 0.0
          yaw: -0.1773092171960826
        nic_rail_0:
          entity_present: False
          entity_name: nic_card_0
          entity_pose:
            translation: -0.0043517843609000365
            roll: 0.0
            pitch: 0.0
            yaw: -0.15156588357941062
        nic_rail_1:
          entity_present: False
          entity_name: nic_card_1
          entity_pose:
            translation: -0.007475854562298398
            roll: 0.0
            pitch: 0.0
            yaw: -0.08697403173257123
        nic_rail_2:
          entity_present: False
          entity_name: nic_card_2
          entity_pose:
            translation: 0.017074775448888614
            roll: 0.0
            pitch: 0.0
            yaw: 0.05593151523926451
        nic_rail_3:
          entity_present: False
          entity_name: nic_card_3
          entity_pose:
            translation: -0.008773453438132309
            roll: 0.0
            pitch: 0.0
            yaw: 0.16441316200617634
        nic_rail_4:
          entity_present: False
          entity_name: nic_card_4
          entity_pose:
            translation: -0.0022814725516692967
            roll: 0.0
            pitch: 0.0
            yaw: -0.15203429404038546
        sc_rail_0:
          entity_present: True
          entity_name: sc_mount_0
          entity_pose:
            translation: -0.01329633590755467
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        sc_rail_1:
          entity_present: True
          entity_name: sc_mount_1
          entity_pose:
            translation: -0.03482715137156754
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
        lc_mount_rail_0:
          entity_present: True
          entity_name: lc_mount_0
          entity_pose:
            translation: -0.045647009944044914
            roll: 0.0
            pitch: 0.0
            yaw: -0.7248464407085249
        sfp_mount_rail_0:
          entity_present: False
          entity_name: sfp_mount_0
          entity_pose:
            translation: 0.08096087839698216
            roll: 0.0
            pitch: 0.0
            yaw: -0.9601510966609849
        sc_mount_rail_0:
          entity_present: False
          entity_name: sc_mount_0
          entity_pose:
            translation: 0.0461732139120086
            roll: 0.0
            pitch: 0.0
            yaw: 0.8569701713818874
        lc_mount_rail_1:
          entity_present: False
          entity_name: lc_mount_1
          entity_pose:
            translation: 0.01419829096127237
            roll: 0.0
            pitch: 0.0
            yaw: -0.515880095957508
        sfp_mount_rail_1:
          entity_present: False
          entity_name: sfp_mount_1
          entity_pose:
            translation: -0.09069813050742563
            roll: 0.0
            pitch: 0.0
            yaw: 0.31590593862810445
        sc_mount_rail_1:
          entity_present: False
          entity_name: sc_mount_1
          entity_pose:
            translation: 0.08073150637660437
            roll: 0.0
            pitch: 0.0
            yaw: -0.7043595326848839
      cables:
        cable_1:
          pose:
            gripper_offset:
              x: -0.001689566721528878
              y: 0.014810394688619263
              z: 0.04386653109131673
              roll: 0.45239993661179756
              pitch: -0.48039561291360094
              yaw: 1.3062393978061033
            roll: 0.4257450519570709
            pitch: -0.5196052079755678
            yaw: 1.3234972094202366
          attach_cable_to_gripper: True
          cable_type: sfp_sc_cable_reversed
    tasks:
      task_1:
        cable_type: sfp_sc
        cable_name: cable_1
        plug_type: sc
        plug_name: sc_tip
        port_type: sc
        port_name: sc_port_base
        target_module_name: sc_port_1
        time_limit: 180
robot:
  home_joint_positions:
    shoulder_pan_joint: -0.1597
    shoulder_lift_joint: -1.3542
    elbow_joint: -1.6648
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
